// Senior-science starter questions: Physics, Chemistry and Biology
// across the three terms. Original content, written for Renance,
// covering the SSS science track topics.

package school

var examBankSeniorScience = []SeedExamQuestion{
	// Physics, First Term
	{SubjectCode: "PHY", Band: "senior", Term: 1,
		Question:    "The SI unit of force is the:",
		Options:     [4]string{"Joule", "Watt", "Newton", "Pascal"},
		AnswerIndex: 2,
		Explanation: "Force is measured in newtons, from F = ma."},
	{SubjectCode: "PHY", Band: "senior", Term: 1,
		Question:    "A body starts from rest and accelerates at 2 m/s squared for 5 s. Its final velocity is:",
		Options:     [4]string{"2.5 m/s", "5 m/s", "10 m/s", "25 m/s"},
		AnswerIndex: 2,
		Explanation: "v = u + at = 0 + 2 x 5 = 10 m/s."},
	{SubjectCode: "PHY", Band: "senior", Term: 1,
		Question:    "Which of these is a scalar quantity?",
		Options:     [4]string{"Velocity", "Displacement", "Speed", "Force"},
		AnswerIndex: 2,
		Explanation: "Speed has magnitude only; the others have direction."},
	{SubjectCode: "PHY", Band: "senior", Term: 1,
		Question:    "Friction between two surfaces moving over each other can be reduced by:",
		Options:     [4]string{"Adding lubricant", "Roughening the surfaces", "Increasing the load", "Pressing harder"},
		AnswerIndex: 0,
		Explanation: "Lubricants separate the surfaces and lower friction."},

	// Physics, Second Term
	{SubjectCode: "PHY", Band: "senior", Term: 2,
		Question:    "The resistance of two 3-ohm resistors connected in parallel is:",
		Options:     [4]string{"6 ohms", "3 ohms", "1.5 ohms", "0.67 ohms"},
		AnswerIndex: 2,
		Explanation: "For parallel resistors: 1/R = 1/3 + 1/3, so R = 1.5 ohms."},
	{SubjectCode: "PHY", Band: "senior", Term: 2,
		Question:    "A machine with mechanical advantage 4 lifts a 600 N load with an effort of:",
		Options:     [4]string{"2400 N", "604 N", "150 N", "240 N"},
		AnswerIndex: 2,
		Explanation: "Effort = load / MA = 600 / 4 = 150 N."},
	{SubjectCode: "PHY", Band: "senior", Term: 2,
		Question:    "The work done when a force of 20 N moves a body 3 m in the direction of the force is:",
		Options:     [4]string{"60 J", "6.7 J", "23 J", "17 J"},
		AnswerIndex: 0,
		Explanation: "Work = force x distance = 20 x 3 = 60 joules."},
	{SubjectCode: "PHY", Band: "senior", Term: 2,
		Question:    "Power is defined as:",
		Options:     [4]string{"Force per unit area", "Work done per unit time", "Energy stored in a body", "Mass times acceleration"},
		AnswerIndex: 1,
		Explanation: "Power measures how fast work is done, in watts."},

	// Physics, Third Term
	{SubjectCode: "PHY", Band: "senior", Term: 3,
		Question:    "An object floats in water when its density is ______ that of water.",
		Options:     [4]string{"Greater than", "Less than", "Equal to", "Double"},
		AnswerIndex: 1,
		Explanation: "A body less dense than the fluid displaces enough fluid to balance its weight."},
	{SubjectCode: "PHY", Band: "senior", Term: 3,
		Question:    "The unit of electric charge is the:",
		Options:     [4]string{"Ampere", "Volt", "Coulomb", "Ohm"},
		AnswerIndex: 2,
		Explanation: "Charge is measured in coulombs."},
	{SubjectCode: "PHY", Band: "senior", Term: 3,
		Question:    "Waves that need a material medium to travel are called:",
		Options:     [4]string{"Electromagnetic waves", "Mechanical waves", "Radio waves", "Light waves"},
		AnswerIndex: 1,
		Explanation: "Sound and water waves are mechanical; they need matter."},
	{SubjectCode: "PHY", Band: "senior", Term: 3,
		Question:    "A concave mirror is used in a torch as a reflector because it:",
		Options:     [4]string{"Scatters light", "Converges light from its focus", "Absorbs light", "Polarises light"},
		AnswerIndex: 1,
		Explanation: "Light from the focus reflects as a parallel beam."},

	// Chemistry, First Term
	{SubjectCode: "CHM", Band: "senior", Term: 1,
		Question:    "The atomic number of an element equals the number of:",
		Options:     [4]string{"Neutrons", "Protons", "Electrons plus neutrons", "Nucleons"},
		AnswerIndex: 1,
		Explanation: "Atomic number counts the protons in the nucleus."},
	{SubjectCode: "CHM", Band: "senior", Term: 1,
		Question:    "Which gas turns limewater milky?",
		Options:     [4]string{"Oxygen", "Hydrogen", "Carbon dioxide", "Nitrogen"},
		AnswerIndex: 2,
		Explanation: "CO2 forms insoluble calcium carbonate with limewater."},
	{SubjectCode: "CHM", Band: "senior", Term: 1,
		Question:    "A mixture of iron filings and sulphur is best described as:",
		Options:     [4]string{"A compound", "An element", "A mixture", "A solution"},
		AnswerIndex: 2,
		Explanation: "The two substances keep their properties and can be separated."},
	{SubjectCode: "CHM", Band: "senior", Term: 1,
		Question:    "Water is formed from hydrogen and oxygen in the ratio by volume:",
		Options:     [4]string{"1:2", "2:1", "1:1", "1:8"},
		AnswerIndex: 1,
		Explanation: "Two volumes of hydrogen combine with one of oxygen."},

	// Chemistry, Second Term
	{SubjectCode: "CHM", Band: "senior", Term: 2,
		Question:    "An acid reacts with a base to give salt and:",
		Options:     [4]string{"Carbon dioxide", "Water only", "Water and hydrogen", "Water only, in neutralisation"},
		AnswerIndex: 3,
		Explanation: "Neutralisation always yields salt and water."},
	{SubjectCode: "CHM", Band: "senior", Term: 2,
		Question:    "The pH of a neutral solution at 25 degrees Celsius is:",
		Options:     [4]string{"0", "7", "10", "14"},
		AnswerIndex: 1,
		Explanation: "pH 7 is neutral; below is acidic, above is alkaline."},
	{SubjectCode: "CHM", Band: "senior", Term: 2,
		Question:    "Which method separates petrol from crude oil?",
		Options:     [4]string{"Filtration", "Fractional distillation", "Decantation", "Evaporation"},
		AnswerIndex: 1,
		Explanation: "Fractions boil at different temperatures and condense apart."},
	{SubjectCode: "CHM", Band: "senior", Term: 2,
		Question:    "The number of moles in 44 g of CO2 (molar mass 44 g/mol) is:",
		Options:     [4]string{"0.5", "1", "2", "44"},
		AnswerIndex: 1,
		Explanation: "Moles = mass / molar mass = 44 / 44 = 1."},

	// Chemistry, Third Term
	{SubjectCode: "CHM", Band: "senior", Term: 3,
		Question:    "Metals conduct electricity because they contain:",
		Options:     [4]string{"Mobile ions", "Free electrons", "Covalent bonds", "Empty shells"},
		AnswerIndex: 1,
		Explanation: "A sea of delocalised electrons carries the current."},
	{SubjectCode: "CHM", Band: "senior", Term: 3,
		Question:    "Rusting of iron requires both oxygen and:",
		Options:     [4]string{"Nitrogen", "Water", "Carbon dioxide", "Argon"},
		AnswerIndex: 1,
		Explanation: "Rust forms fastest in moist air."},
	{SubjectCode: "CHM", Band: "senior", Term: 3,
		Question:    "Ethene is an example of a/an:",
		Options:     [4]string{"Alkane", "Alkene", "Alkyne", "Alkanol"},
		AnswerIndex: 1,
		Explanation: "Ethene has a carbon-carbon double bond, so it is an alkene."},
	{SubjectCode: "CHM", Band: "senior", Term: 3,
		Question:    "Hard water forms scum with soap because it contains dissolved:",
		Options:     [4]string{"Calcium ions", "Sodium ions", "Oxygen", "Chlorine"},
		AnswerIndex: 0,
		Explanation: "Calcium and magnesium ions react with soap to form scum."},

	// Biology, First Term
	{SubjectCode: "BIO", Band: "senior", Term: 1,
		Question:    "The basic unit of life is the:",
		Options:     [4]string{"Tissue", "Organ", "Cell", "System"},
		AnswerIndex: 2,
		Explanation: "All living things are built from cells."},
	{SubjectCode: "BIO", Band: "senior", Term: 1,
		Question:    "Which organelle releases energy in a cell?",
		Options:     [4]string{"Nucleus", "Ribosome", "Mitochondrion", "Chloroplast"},
		AnswerIndex: 2,
		Explanation: "The mitochondrion is the powerhouse of respiration."},
	{SubjectCode: "BIO", Band: "senior", Term: 1,
		Question:    "Organisms that cannot make their own food are called:",
		Options:     [4]string{"Autotrophs", "Heterotrophs", "Producers", "Photosynthetic"},
		AnswerIndex: 1,
		Explanation: "Heterotrophs feed on ready-made organic matter."},
	{SubjectCode: "BIO", Band: "senior", Term: 1,
		Question:    "The cell wall of a plant cell is made mainly of:",
		Options:     [4]string{"Starch", "Cellulose", "Protein", "Lipid"},
		AnswerIndex: 1,
		Explanation: "Cellulose gives the wall its strength."},

	// Biology, Second Term
	{SubjectCode: "BIO", Band: "senior", Term: 2,
		Question:    "The passage of food from the mouth to the oesophagus is helped by the:",
		Options:     [4]string{"Epiglottis", "Tongue only", "Diaphragm", "Lungs"},
		AnswerIndex: 0,
		Explanation: "The epiglottis covers the windpipe during swallowing."},
	{SubjectCode: "BIO", Band: "senior", Term: 2,
		Question:    "Which blood vessels carry blood away from the heart?",
		Options:     [4]string{"Veins", "Arteries", "Capillaries", "Venules"},
		AnswerIndex: 1,
		Explanation: "Arteries carry blood from the heart to the body."},
	{SubjectCode: "BIO", Band: "senior", Term: 2,
		Question:    "Photosynthesis mainly takes place in the leaf's:",
		Options:     [4]string{"Epidermis", "Palisade layer", "Root hairs", "Xylem"},
		AnswerIndex: 1,
		Explanation: "Palisade cells hold the most chloroplasts."},
	{SubjectCode: "BIO", Band: "senior", Term: 2,
		Question:    "The excretory organ that removes urea from the blood is the:",
		Options:     [4]string{"Liver", "Kidney", "Skin", "Lung"},
		AnswerIndex: 1,
		Explanation: "Kidneys filter urea out of the blood as urine."},

	// Biology, Third Term
	{SubjectCode: "BIO", Band: "senior", Term: 3,
		Question:    "In genetics, an organism with two identical alleles for a trait is:",
		Options:     [4]string{"Heterozygous", "Homozygous", "Hybrid", "Polyloid"},
		AnswerIndex: 1,
		Explanation: "Homozygous means both alleles of the pair are the same."},
	{SubjectCode: "BIO", Band: "senior", Term: 3,
		Question:    "A food chain always begins with a:",
		Options:     [4]string{"Consumer", "Producer", "Decomposer", "Predator"},
		AnswerIndex: 1,
		Explanation: "Green plants capture the energy the chain depends on."},
	{SubjectCode: "BIO", Band: "senior", Term: 3,
		Question:    "The vector of the malaria parasite is the:",
		Options:     [4]string{"Housefly", "Female Anopheles mosquito", "Tsetse fly", "Blackfly"},
		AnswerIndex: 1,
		Explanation: "The female Anopheles mosquito transmits Plasmodium."},
	{SubjectCode: "BIO", Band: "senior", Term: 3,
		Question:    "Evolution by natural selection was proposed by:",
		Options:     [4]string{"Gregor Mendel", "Charles Darwin", "Louis Pasteur", "Jean Lamarck"},
		AnswerIndex: 1,
		Explanation: "Darwin set out natural selection in his 1859 work."},
}
