// Primary core starter questions: English Studies, Mathematics and
// Basic Science & Technology (Primary band). Original content written
// for Renance, simple language for younger pupils.

package school

var examBankPrimaryCore = []SeedExamQuestion{
        // English Studies (Primary), all terms
        {SubjectCode: "ENG-P", Band: "primary", Term: 1,
                Question:    "Choose the correct word: The sun ______ in the east.",
                Options:     [4]string{"rises", "rise", "risen", "rising"},
                AnswerIndex: 0,
                Explanation: "The sun is singular, so the verb takes the s ending."},
        {SubjectCode: "ENG-P", Band: "primary", Term: 1,
                Question:    "Which word is a naming word (noun)?",
                Options:     [4]string{"Run", "Yellow", "School", "Quickly"},
                AnswerIndex: 2,
                Explanation: "A noun names a person, place or thing."},
        {SubjectCode: "ENG-P", Band: "primary", Term: 1,
                Question:    "The plural of book is:",
                Options:     [4]string{"bookes", "book", "books", "bookies"},
                AnswerIndex: 2,
                Explanation: "Most nouns simply add s to make the plural."},
        {SubjectCode: "ENG-P", Band: "primary", Term: 2,
                Question:    "Pick the correct sentence:",
                Options:     [4]string{"i am a boy.", "I am a boy.", "i Am a boy.", "am I a boy."},
                AnswerIndex: 1,
                Explanation: "Sentences start with a capital letter."},
        {SubjectCode: "ENG-P", Band: "primary", Term: 2,
                Question:    "Which word rhymes with cat?",
                Options:     [4]string{"dog", "hat", "cup", "pen"},
                AnswerIndex: 1,
                Explanation: "Hat shares the same ending sound as cat."},
        {SubjectCode: "ENG-P", Band: "primary", Term: 2,
                Question:    "The opposite of big is:",
                Options:     [4]string{"tall", "small", "long", "wide"},
                AnswerIndex: 1,
                Explanation: "Small means the opposite size to big."},
        {SubjectCode: "ENG-P", Band: "primary", Term: 3,
                Question:    "Choose the correct question word: ______ is your name?",
                Options:     [4]string{"What", "When", "Where", "Why"},
                AnswerIndex: 0,
                Explanation: "What asks for a name or thing."},
        {SubjectCode: "ENG-P", Band: "primary", Term: 3,
                Question:    "A word that describes an action is a:",
                Options:     [4]string{"verb", "noun", "letter", "number"},
                AnswerIndex: 0,
                Explanation: "Verbs show actions like run, sing and read."},
        {SubjectCode: "ENG-P", Band: "primary", Term: 3,
                Question:    "Which group of words makes a complete sentence?",
                Options:     [4]string{"Runs fast", "The girl runs fast.", "Very fast", "The fast"},
                AnswerIndex: 1,
                Explanation: "A complete sentence needs a subject and a verb."},

        // Mathematics (Primary), all terms
        {SubjectCode: "MTH-P", Band: "primary", Term: 1,
                Question:    "What is 7 + 5?",
                Options:     [4]string{"11", "12", "13", "10"},
                AnswerIndex: 1,
                Explanation: "Count on five from seven to reach twelve."},
        {SubjectCode: "MTH-P", Band: "primary", Term: 1,
                Question:    "What is 9 - 4?",
                Options:     [4]string{"3", "4", "5", "6"},
                AnswerIndex: 2,
                Explanation: "Take four away from nine and five remain."},
        {SubjectCode: "MTH-P", Band: "primary", Term: 1,
                Question:    "Which number comes next: 2, 4, 6, 8, ...?",
                Options:     [4]string{"9", "10", "11", "12"},
                AnswerIndex: 1,
                Explanation: "The pattern adds two each time."},
        {SubjectCode: "MTH-P", Band: "primary", Term: 2,
                Question:    "What is 3 x 4?",
                Options:     [4]string{"7", "10", "12", "14"},
                AnswerIndex: 2,
                Explanation: "Three groups of four make twelve."},
        {SubjectCode: "MTH-P", Band: "primary", Term: 2,
                Question:    "Which fraction shows one half?",
                Options:     [4]string{"1/4", "1/2", "1/3", "2/3"},
                AnswerIndex: 1,
                Explanation: "One half splits a whole into two equal parts."},
        {SubjectCode: "MTH-P", Band: "primary", Term: 2,
                Question:    "A shape with three sides is a:",
                Options:     [4]string{"square", "triangle", "circle", "rectangle"},
                AnswerIndex: 1,
                Explanation: "Tri means three: a triangle has three sides."},
        {SubjectCode: "MTH-P", Band: "primary", Term: 3,
                Question:    "How many tens are in 60?",
                Options:     [4]string{"6", "10", "60", "16"},
                AnswerIndex: 0,
                Explanation: "Six tens make sixty."},
        {SubjectCode: "MTH-P", Band: "primary", Term: 3,
                Question:    "What is the value of the 5 in 258?",
                Options:     [4]string{"5 ones", "5 tens", "5 hundreds", "5 thousands"},
                AnswerIndex: 1,
                Explanation: "The 5 sits in the tens place."},
        {SubjectCode: "MTH-P", Band: "primary", Term: 3,
                Question:    "Naira and kobo are used in Nigeria to measure:",
                Options:     [4]string{"weight", "length", "money", "time"},
                AnswerIndex: 2,
                Explanation: "They are the units of Nigerian money."},

        // Basic Science & Technology (Primary), all terms
        {SubjectCode: "BST-P", Band: "primary", Term: 1,
                Question:    "Which sense organ do we use to see?",
                Options:     [4]string{"Ear", "Eye", "Nose", "Skin"},
                AnswerIndex: 1,
                Explanation: "The eyes are the organs of sight."},
        {SubjectCode: "BST-P", Band: "primary", Term: 1,
                Question:    "Living things need air, water and:",
                Options:     [4]string{"Sweets", "Food", "Toys", "Money"},
                AnswerIndex: 1,
                Explanation: "Food gives living things energy to grow."},
        {SubjectCode: "BST-P", Band: "primary", Term: 1,
                Question:    "Which of these is a non-living thing?",
                Options:     [4]string{"Goat", "Stone", "Mango tree", "Baby"},
                AnswerIndex: 1,
                Explanation: "A stone does not grow, feed or breathe."},
        {SubjectCode: "BST-P", Band: "primary", Term: 2,
                Question:    "The sun gives us light and:",
                Options:     [4]string{"Rain", "Heat", "Wind only", "Sand"},
                AnswerIndex: 1,
                Explanation: "Sunshine supplies both light and warmth."},
        {SubjectCode: "BST-P", Band: "primary", Term: 2,
                Question:    "Water that is heated to boiling turns into:",
                Options:     [4]string{"Ice", "Steam", "Mud", "Rock"},
                AnswerIndex: 1,
                Explanation: "Boiling changes water to steam (a gas)."},
        {SubjectCode: "BST-P", Band: "primary", Term: 2,
                Question:    "Which animal is a farm animal?",
                Options:     [4]string{"Lion", "Goat", "Eagle", "Whale"},
                AnswerIndex: 1,
                Explanation: "Goats are reared on farms for meat and milk."},
        {SubjectCode: "BST-P", Band: "primary", Term: 3,
                Question:    "A magnet attracts objects made of:",
                Options:     [4]string{"Iron", "Plastic", "Wood", "Glass"},
                AnswerIndex: 0,
                Explanation: "Magnets pull magnetic metals such as iron."},
        {SubjectCode: "BST-P", Band: "primary", Term: 3,
                Question:    "The hard part of the body protecting the brain is the:",
                Options:     [4]string{"Skull", "Ribs", "Knee", "Spine"},
                AnswerIndex: 0,
                Explanation: "The skull is the bony helmet of the head."},
        {SubjectCode: "BST-P", Band: "primary", Term: 3,
                Question:    "Which of these floats on water?",
                Options:     [4]string{"Iron nail", "Stone", "Cork", "Coin"},
                AnswerIndex: 2,
                Explanation: "Cork is light and less dense, so it floats."},
}
