// Senior core and commercial starter questions: English Language,
// Mathematics and Economics across the three terms. Original content,
// written for Renance, NERDC topics of the SSS band.

package school

var examBankSeniorCore = []SeedExamQuestion{
	// English Language, First Term
	{SubjectCode: "ENG-S", Band: "senior", Term: 1,
		Question:    "Choose the option nearest in meaning: The chairman's speech was concise.",
		Options:     [4]string{"Lengthy", "Brief", "Loud", "Confusing"},
		AnswerIndex: 1,
		Explanation: "Concise means saying much in few words."},
	{SubjectCode: "ENG-S", Band: "senior", Term: 1,
		Question:    "Choose the correct form: Neither the students nor the teacher ______ present.",
		Options:     [4]string{"were", "was", "are", "have been"},
		AnswerIndex: 1,
		Explanation: "With neither...nor the verb agrees with the nearer subject, the teacher."},
	{SubjectCode: "ENG-S", Band: "senior", Term: 1,
		Question:    "In Many people came, the adjective many modifies the noun:",
		Options:     [4]string{"Many", "people", "came", "none"},
		AnswerIndex: 1,
		Explanation: "Many tells us about the number of people."},
	{SubjectCode: "ENG-S", Band: "senior", Term: 1,
		Question:    "The idiom to bury the hatchet means to:",
		Options:     [4]string{"Hide a weapon", "Make peace", "Start a quarrel", "Bury a treasure"},
		AnswerIndex: 1,
		Explanation: "The expression means ending a quarrel."},

	// English Language, Second Term
	{SubjectCode: "ENG-S", Band: "senior", Term: 2,
		Question:    "Choose the word opposite in meaning to transparent.",
		Options:     [4]string{"Clear", "Opaque", "Bright", "Shiny"},
		AnswerIndex: 1,
		Explanation: "Opaque means light cannot pass through."},
	{SubjectCode: "ENG-S", Band: "senior", Term: 2,
		Question:    "Identify the sentence with the correct pronoun:",
		Options:     [4]string{"It was me at the gate.", "It was I at the gate.", "It was mine at the gate.", "It was myself at the gate."},
		AnswerIndex: 1,
		Explanation: "After the verb to be the subject pronoun I is used."},
	{SubjectCode: "ENG-S", Band: "senior", Term: 2,
		Question:    "A word formed from the initials of a phrase, like WAEC, is a/an:",
		Options:     [4]string{"Acronym", "Antonym", "Synonym", "Homonym"},
		AnswerIndex: 0,
		Explanation: "WAEC stands for the West African Examinations Council."},
	{SubjectCode: "ENG-S", Band: "senior", Term: 2,
		Question:    "The stress pattern of the word photography falls on the syllable:",
		Options:     [4]string{"pho", "tog", "ra", "phy"},
		AnswerIndex: 1,
		Explanation: "Say pho-TOG-ra-phy; the stress lands on the second syllable."},

	// English Language, Third Term
	{SubjectCode: "ENG-S", Band: "senior", Term: 3,
		Question:    "Choose the option that best completes the sentence: Hardly had the bell rung ______ the pupils rushed out.",
		Options:     [4]string{"than", "when", "then", "that"},
		AnswerIndex: 1,
		Explanation: "Hardly pairs with when in this construction."},
	{SubjectCode: "ENG-S", Band: "senior", Term: 3,
		Question:    "A person who writes the life story of another person is a:",
		Options:     [4]string{"Autobiographer", "Biographer", "Cartographer", "Photographer"},
		AnswerIndex: 1,
		Explanation: "A biographer writes another person's life; an autobiographer writes their own."},
	{SubjectCode: "ENG-S", Band: "senior", Term: 3,
		Question:    "In report writing, the language should be:",
		Options:     [4]string{"Emotional", "Formal and factual", "Playful", "Poetic"},
		AnswerIndex: 1,
		Explanation: "Reports demand formal, objective language."},
	{SubjectCode: "ENG-S", Band: "senior", Term: 3,
		Question:    "Choose the correctly punctuated sentence:",
		Options:     [4]string{"Where is my bag.", "Where is my bag?", "Where is my bag!", "Where is my bag,"},
		AnswerIndex: 1,
		Explanation: "A direct question ends with a question mark."},

	// Mathematics, First Term
	{SubjectCode: "MTH-S", Band: "senior", Term: 1,
		Question:    "Simplify: (2 x cubed) cubed.",
		Options:     [4]string{"2 x^6", "8 x^9", "6 x^6", "8 x^6"},
		AnswerIndex: 1,
		Explanation: "Cube the 2 and multiply the powers: 8 x^9."},
	{SubjectCode: "MTH-S", Band: "senior", Term: 1,
		Question:    "If log to base 10 of x = 2, then x is:",
		Options:     [4]string{"20", "100", "200", "0.01"},
		AnswerIndex: 1,
		Explanation: "Log base 10 of 100 is 2, since 10 squared is 100."},
	{SubjectCode: "MTH-S", Band: "senior", Term: 1,
		Question:    "Solve the pair: x + y = 7 and x - y = 3. The value of x is:",
		Options:     [4]string{"2", "4", "5", "10"},
		AnswerIndex: 2,
		Explanation: "Adding both equations gives 2x = 10, so x = 5."},
	{SubjectCode: "MTH-S", Band: "senior", Term: 1,
		Question:    "The discriminant of ax squared + bx + c = 0 is:",
		Options:     [4]string{"b squared - 4ac", "b squared + 4ac", "4ac - b squared", "2a over b"},
		AnswerIndex: 0,
		Explanation: "The discriminant b squared minus 4ac decides the nature of the roots."},

	// Mathematics, Second Term
	{SubjectCode: "MTH-S", Band: "senior", Term: 2,
		Question:    "In a right-angled triangle, the side facing the right angle is the:",
		Options:     [4]string{"Adjacent", "Opposite", "Hypotenuse", "Base"},
		AnswerIndex: 2,
		Explanation: "The hypotenuse is the longest side, facing the right angle."},
	{SubjectCode: "MTH-S", Band: "senior", Term: 2,
		Question:    "The midpoint of the line from (1, 2) to (5, 10) is:",
		Options:     [4]string{"(3, 6)", "(6, 12)", "(2, 5)", "(3, 8)"},
		AnswerIndex: 0,
		Explanation: "Average the coordinates: ((1+5)/2, (2+10)/2) = (3, 6)."},
	{SubjectCode: "MTH-S", Band: "senior", Term: 2,
		Question:    "The sum of the interior angles of a hexagon is:",
		Options:     [4]string{"540 degrees", "720 degrees", "900 degrees", "1080 degrees"},
		AnswerIndex: 1,
		Explanation: "(6 - 2) x 180 = 720 degrees."},
	{SubjectCode: "MTH-S", Band: "senior", Term: 2,
		Question:    "If the probability of rain is 0.3, the probability it will not rain is:",
		Options:     [4]string{"0.3", "0.7", "1.3", "0"},
		AnswerIndex: 1,
		Explanation: "Complementary probabilities sum to 1: 1 - 0.3 = 0.7."},

	// Mathematics, Third Term
	{SubjectCode: "MTH-S", Band: "senior", Term: 3,
		Question:    "The volume of a cylinder of radius 3 cm and height 7 cm (take pi = 22/7) is:",
		Options:     [4]string{"198 cm cubed", "154 cm cubed", "66 cm cubed", "231 cm cubed"},
		AnswerIndex: 0,
		Explanation: "V = pi r squared h = 22/7 x 9 x 7 = 198 cm cubed."},
	{SubjectCode: "MTH-S", Band: "senior", Term: 3,
		Question:    "The mean of 4, 6, 9, 11 and 10 is:",
		Options:     [4]string{"8", "9", "10", "7.5"},
		AnswerIndex: 0,
		Explanation: "Sum 40 over 5 values gives 8."},
	{SubjectCode: "MTH-S", Band: "senior", Term: 3,
		Question:    "The gradient of the line joining (2, 3) and (4, 9) is:",
		Options:     [4]string{"2", "3", "6", "1/3"},
		AnswerIndex: 1,
		Explanation: "Gradient = (9 - 3)/(4 - 2) = 6/2 = 3."},
	{SubjectCode: "MTH-S", Band: "senior", Term: 3,
		Question:    "A sector of a circle with angle 90 degrees is what fraction of the full circle?",
		Options:     [4]string{"1/2", "1/3", "1/4", "1/8"},
		AnswerIndex: 2,
		Explanation: "90 over 360 simplifies to one quarter."},

	// Economics, First Term
	{SubjectCode: "ECO", Band: "senior", Term: 1,
		Question:    "The fundamental economic problem is that resources are ______ relative to wants.",
		Options:     [4]string{"Abundant", "Scarce", "Free", "Infinite"},
		AnswerIndex: 1,
		Explanation: "Scarcity is the gap between limited resources and unlimited wants."},
	{SubjectCode: "ECO", Band: "senior", Term: 1,
		Question:    "The reward for the factor of production called labour is:",
		Options:     [4]string{"Rent", "Interest", "Wages", "Profit"},
		AnswerIndex: 2,
		Explanation: "Labour earns wages; land earns rent, capital interest, enterprise profit."},
	{SubjectCode: "ECO", Band: "senior", Term: 1,
		Question:    "A demand curve normally slopes downwards because as price falls, quantity demanded:",
		Options:     [4]string{"Falls", "Rises", "Stays fixed", "Doubles"},
		AnswerIndex: 1,
		Explanation: "The law of demand links lower prices to higher quantities."},
	{SubjectCode: "ECO", Band: "senior", Term: 1,
		Question:    "Which of these is an opportunity cost of a school building a library?",
		Options:     [4]string{"The books bought", "The labs not built with the same money", "The land used", "The students enrolled"},
		AnswerIndex: 1,
		Explanation: "Opportunity cost is the next best alternative forgone."},

	// Economics, Second Term
	{SubjectCode: "ECO", Band: "senior", Term: 2,
		Question:    "Inflation refers to a sustained rise in the general:",
		Options:     [4]string{"Population", "Price level", "Unemployment rate", "National output"},
		AnswerIndex: 1,
		Explanation: "Inflation is a persistent increase in the general price level."},
	{SubjectCode: "ECO", Band: "senior", Term: 2,
		Question:    "A market with many buyers and sellers trading an identical product is:",
		Options:     [4]string{"A monopoly", "Perfect competition", "An oligopoly", "A duopoly"},
		AnswerIndex: 1,
		Explanation: "Perfect competition assumes price-taking firms and identical goods."},
	{SubjectCode: "ECO", Band: "senior", Term: 2,
		Question:    "The central bank of Nigeria's main tool for controlling money supply is:",
		Options:     [4]string{"Taxation", "Monetary policy", "Price control", "Budget allocation"},
		AnswerIndex: 1,
		Explanation: "The CBN uses monetary policy instruments to manage money."},
	{SubjectCode: "ECO", Band: "senior", Term: 2,
		Question:    "Supply is said to be inelastic when a price change causes a ______ change in quantity supplied.",
		Options:     [4]string{"Larger", "Smaller", "Zero", "Equal"},
		AnswerIndex: 1,
		Explanation: "Inelastic supply responds less than proportionally to price."},

	// Economics, Third Term
	{SubjectCode: "ECO", Band: "senior", Term: 3,
		Question:    "GDP measures the total value of goods and services produced:",
		Options:     [4]string{"By Nigerians abroad", "Within a country in a year", "By the government only", "By one firm"},
		AnswerIndex: 1,
		Explanation: "GDP counts output produced within the nation's borders."},
	{SubjectCode: "ECO", Band: "senior", Term: 3,
		Question:    "A tax whose burden falls more on the rich relative to income is:",
		Options:     [4]string{"Regressive", "Progressive", "Proportional", "Indirect"},
		AnswerIndex: 1,
		Explanation: "Progressive taxes take a higher share as income rises."},
	{SubjectCode: "ECO", Band: "senior", Term: 3,
		Question:    "Nigeria's major export by value is traditionally:",
		Options:     [4]string{"Cocoa", "Petroleum", "Cotton", "Rubber"},
		AnswerIndex: 1,
		Explanation: "Crude petroleum dominates Nigeria's export earnings."},
	{SubjectCode: "ECO", Band: "senior", Term: 3,
		Question:    "Unemployment caused by a fall in demand during a recession is called:",
		Options:     [4]string{"Frictional", "Structural", "Cyclical", "Seasonal"},
		AnswerIndex: 2,
		Explanation: "Cyclical unemployment follows the downturn phase of the business cycle."},
}

// Part two: one more question per subject per term.
var examBankSeniorCoreP2 = []SeedExamQuestion{
        {SubjectCode: "ENG-S", Band: "senior", Term: 1,
                Question:    "Choose the option nearest in meaning: The headmaster was skeptical about the excuse.",
                Options:     [4]string{"Convinced", "Doubtful", "Angry", "Delighted"},
                AnswerIndex: 1,
                Explanation: "Skeptical means withholding belief until proof."},
        {SubjectCode: "ENG-S", Band: "senior", Term: 2,
                Question:    "The passive form of The chef cooked the meal is:",
                Options:     [4]string{"The meal cooked the chef.", "The meal was cooked by the chef.", "The chef was cooking.", "The chef cooks."},
                AnswerIndex: 1,
                Explanation: "The object becomes the subject with was + past participle."},
        {SubjectCode: "ENG-S", Band: "senior", Term: 3,
                Question:    "Which word collocates with heavy in standard English?",
                Options:     [4]string{"Rain", "Taste", "Idea", "Smell of joy"},
                AnswerIndex: 0,
                Explanation: "Heavy rain is a fixed collocation."},
        {SubjectCode: "MTH-S", Band: "senior", Term: 1,
                Question:    "Simplify log to base 10 of 8 + log to base 10 of 125.",
                Options:     [4]string{"2", "3", "4", "1000"},
                AnswerIndex: 1,
                Explanation: "Sum of logs = log of product: 8 x 125 = 1000, log = 3."},
        {SubjectCode: "MTH-S", Band: "senior", Term: 2,
                Question:    "If sin(theta) = 0.5 for an acute angle, then theta is:",
                Options:     [4]string{"30 degrees", "45 degrees", "60 degrees", "90 degrees"},
                AnswerIndex: 0,
                Explanation: "Sine 30 degrees equals one half."},
        {SubjectCode: "MTH-S", Band: "senior", Term: 3,
                Question:    "The range of the data 3, 7, 8, 15 is:",
                Options:     [4]string{"8", "11", "12", "15"},
                AnswerIndex: 2,
                Explanation: "Range = maximum - minimum = 15 - 3 = 12."},
        {SubjectCode: "ECO", Band: "senior", Term: 1,
                Question:    "A graph showing combinations of two goods an economy can produce is the:",
                Options:     [4]string{"Demand curve", "Production possibility curve", "Supply curve", "Indifference curve"},
                AnswerIndex: 1,
                Explanation: "The PPC maps maximum output mixes given resources."},
        {SubjectCode: "ECO", Band: "senior", Term: 2,
                Question:    "A rise in demand caused by rising incomes shifts the demand curve:",
                Options:     [4]string{"Leftwards", "Rightwards", "Downwards only", "Not at all"},
                AnswerIndex: 1,
                Explanation: "Normal goods see demand grow as income rises."},
        {SubjectCode: "ECO", Band: "senior", Term: 3,
                Question:    "Trade between countries without quotas or tariffs is called:",
                Options:     [4]string{"Free trade", "Fair trade", "Barter", "Embargo"},
                AnswerIndex: 0,
                Explanation: "Free trade removes artificial barriers to exchange."},
}
