// Primary wider starter questions: National Values, Pre-vocational
// and Cultural & Creative Arts (Primary band). Original content
// written for Renance.

package school

var examBankPrimaryWider = []SeedExamQuestion{
        // National Values Education (Primary)
        {SubjectCode: "NVE-P", Band: "primary", Term: 1,
                Question:    "Greeting elders shows that a child is:",
                Options:     [4]string{"Rude", "Respectful", "Lazy", "Noisy"},
                AnswerIndex: 1,
                Explanation: "Greetings are a mark of respect in Nigerian culture."},
        {SubjectCode: "NVE-P", Band: "primary", Term: 1,
                Question:    "Returning money you found shows:",
                Options:     [4]string{"Honesty", "Fear", "Anger", "Pride"},
                AnswerIndex: 0,
                Explanation: "Honesty means returning what is not yours."},
        {SubjectCode: "NVE-P", Band: "primary", Term: 1,
                Question:    "A community is a group of people living:",
                Options:     [4]string{"Alone", "Together in one place", "In cars", "In the sky"},
                AnswerIndex: 1,
                Explanation: "Communities share a place and help one another."},
        {SubjectCode: "NVE-P", Band: "primary", Term: 2,
                Question:    "Civic rules are made to keep people:",
                Options:     [4]string{"Sad", "Safe and orderly", "Late", "Hungry"},
                AnswerIndex: 1,
                Explanation: "Rules protect everyone and keep order."},
        {SubjectCode: "NVE-P", Band: "primary", Term: 2,
                Question:    "The national pledge is recited while:",
                Options:     [4]string{"Sitting", "Standing at attention", "Sleeping", "Running"},
                AnswerIndex: 1,
                Explanation: "We stand to honour the nation during the pledge."},
        {SubjectCode: "NVE-P", Band: "primary", Term: 2,
                Question:    "Which of these is a national symbol of Nigeria?",
                Options:     [4]string{"The flag", "A school bag", "A football", "A pencil"},
                AnswerIndex: 0,
                Explanation: "The green-white flag represents the nation."},
        {SubjectCode: "NVE-P", Band: "primary", Term: 3,
                Question:    "Helping a classmate who falls down shows:",
                Options:     [4]string{"Kindness", "Jealousy", "Fear", "Anger"},
                AnswerIndex: 0,
                Explanation: "Kindness is caring for others in need."},
        {SubjectCode: "NVE-P", Band: "primary", Term: 3,
                Question:    "People who keep our streets clean are:",
                Options:     [4]string{"Sanitation workers", "Pilots", "Tailors", "Chefs"},
                AnswerIndex: 0,
                Explanation: "Sanitation workers protect community health."},
        {SubjectCode: "NVE-P", Band: "primary", Term: 3,
                Question:    "Paying school fees on time is the duty of:",
                Options:     [4]string{"Parents and guardians", "Babies", "Visitors", "Strangers"},
                AnswerIndex: 0,
                Explanation: "Guardians sponsor learning; pupils study hard in return."},
}
