// Geography and Technical Drawing starter questions (senior band,
// science track). Original content written for Renance.

package school

var examBankGeography = []SeedExamQuestion{
        // First Term
        {SubjectCode: "GEO", Band: "senior", Term: 1,
                Question:    "The latitude that divides the Earth into two equal halves is the:",
                Options:     [4]string{"Tropic of Cancer", "Equator", "Prime Meridian", "Arctic Circle"},
                AnswerIndex: 1,
                Explanation: "The equator sits at 0 degrees and splits Earth into hemispheres."},
        {SubjectCode: "GEO", Band: "senior", Term: 1,
                Question:    "The movement of the Earth around the sun once a year is its:",
                Options:     [4]string{"Rotation", "Revolution", "Eclipse", "Axis"},
                AnswerIndex: 1,
                Explanation: "Revolution around the sun drives the yearly seasons."},
        {SubjectCode: "GEO", Band: "senior", Term: 1,
                Question:    "Which rock type forms from cooling magma?",
                Options:     [4]string{"Sedimentary", "Igneous", "Metamorphic", "Limestone"},
                AnswerIndex: 1,
                Explanation: "Magma solidifies into igneous rock like granite."},
}

var examBankTechDrawing = []SeedExamQuestion{
        // First Term
        {SubjectCode: "TDR", Band: "senior", Term: 1,
                Question:    "The standard sheet symbol for first-angle projection is identified by the:",
                Options:     [4]string{"Cone", "Truncated cone", "Circle", "Triangle alone"},
                AnswerIndex: 1,
                Explanation: "A truncated cone distinguishes first-angle projection symbols."},
        {SubjectCode: "TDR", Band: "senior", Term: 1,
                Question:    "Lines drawn to show hidden edges of an object are:",
                Options:     [4]string{"Continuous thick", "Dashed (short dashes)", "Chain lines", "Wavy lines"},
                AnswerIndex: 1,
                Explanation: "Short dashes mark edges invisible from the viewing direction."},
        {SubjectCode: "TDR", Band: "senior", Term: 1,
                Question:    "The true length of a line is seen on a view taken:",
                Options:     [4]string{"Parallel to the line", "At an angle", "Perpendicular only", "In section"},
                AnswerIndex: 0,
                Explanation: "A view plane parallel to the line shows it without foreshortening."},
}

        // Second Term
        {SubjectCode: "GEO", Band: "senior", Term: 2,
                Question:    "Weathering that changes the chemical composition of rocks is:",
                Options:     [4]string{"Physical weathering", "Chemical weathering", "Erosion", "Mass movement"},
                AnswerIndex: 1,
                Explanation: "Chemical weathering alters minerals, as in hydrolysis."},
        {SubjectCode: "GEO", Band: "senior", Term: 2,
                Question:    "The local wind that blows from the Sahara towards the Guinea coast is the:",
                Options:     [4]string{"Harmattan", "Monsoon", "Chinook", "Fohn"},
                AnswerIndex: 0,
                Explanation: "The dry, dusty harmattan sweeps southwest each dry season."},
        {SubjectCode: "GEO", Band: "senior", Term: 2,
                Question:    "A river's mouth opening into the sea may form a(n):",
                Options:     [4]string{"Delta", "Gorge", "Waterfall", "Meander"},
                AnswerIndex: 0,
                Explanation: "Deposits at the mouth build the fan of a delta."},

        // Third Term
        {SubjectCode: "GEO", Band: "senior", Term: 3,
                Question:    "Population distribution across a country is best shown on a map by:",
                Options:     [4]string{"Dots or choropleth shading", "Contour lines alone", "Isotherms", "Wind roses"},
                AnswerIndex: 0,
                Explanation: "Dot maps and choropleths communicate density patterns."},
        {SubjectCode: "GEO", Band: "senior", Term: 3,
                Question:    "The main problem of rapid urban growth in Nigerian cities is:",
                Options:     [4]string{"Too few markets only", "Strain on housing and services", "Too much farmland", "Low birth rate"},
                AnswerIndex: 1,
                Explanation: "Housing pressure, traffic and services lag behind city growth."},
        {SubjectCode: "GEO", Band: "senior", Term: 3,
                Question:    "Which economic activity belongs to the tertiary sector?",
                Options:     [4]string{"Farming", "Mining", "Teaching", "Fishing"},
                AnswerIndex: 2,
                Explanation: "Tertiary activities provide services rather than raw goods."},

        // Second Term
        {SubjectCode: "TDR", Band: "senior", Term: 2,
                Question:    "An isometric drawing presents an object with axes at:",
                Options:     [4]string{"30 degrees apart", "60 degrees", "90 degrees only", "120 degrees"},
                AnswerIndex: 3,
                Explanation: "Isometric axes sit 120 degrees apart on the flat sheet."},
        {SubjectCode: "TDR", Band: "senior", Term: 2,
                Question:    "A section view is used to show:",
                Options:     [4]string{"External beauty", "Internal details", "Colour", "Texture only"},
                AnswerIndex: 1,
                Explanation: "Cutting the object reveals hidden internal construction."},
        {SubjectCode: "TDR", Band: "senior", Term: 2,
                Question:    "The scale used to enlarge a tiny watch part is typically:",
                Options:     [4]string{"1:1", "1:10", "10:1", "1:100"},
                AnswerIndex: 2,
                Explanation: "10:1 enlarges the drawing ten times the real size."},
