// Business Studies and Physical & Health Education starter questions
// (junior band). Original content written for Renance.

package school

var examBankBusiness = []SeedExamQuestion{
        // First Term
        {SubjectCode: "BUS", Band: "junior", Term: 1,
                Question:    "A business is an organization that provides goods or services to:",
                Options:     [4]string{"Make a profit", "Lose money", "Hide money", "Give gifts"},
                AnswerIndex: 0,
                Explanation: "Profit motivates business activity alongside service."},
        {SubjectCode: "BUS", Band: "junior", Term: 1,
                Question:    "The two broad types of business activity are industry and:",
                Options:     [4]string{"Commerce", "Agriculture", "Banking", "Travel"},
                AnswerIndex: 0,
                Explanation: "Industry produces; commerce distributes."},
        {SubjectCode: "BUS", Band: "junior", Term: 1,
                Question:    "A sole proprietorship is owned by:",
                Options:     [4]string{"Two people", "One person", "Shareholders", "The government"},
                AnswerIndex: 1,
                Explanation: "One owner carries the risk and the profit alone."},
}

var examBankPHE = []SeedExamQuestion{
        // First Term
        {SubjectCode: "PHE", Band: "junior", Term: 1,
                Question:    "Physical fitness is the ability of the body to:",
                Options:     [4]string{"Sleep well", "Carry out daily work without undue fatigue", "Grow tall", "Read fast"},
                AnswerIndex: 1,
                Explanation: "Fitness means performing daily tasks with energy to spare."},
        {SubjectCode: "PHE", Band: "junior", Term: 1,
                Question:    "The number of players in a football (soccer) team on the pitch is:",
                Options:     [4]string{"9", "10", "11", "12"},
                AnswerIndex: 2,
                Explanation: "Eleven players per side, including the goalkeeper."},
        {SubjectCode: "PHE", Band: "junior", Term: 1,
                Question:    "Warming up before exercise mainly helps to:",
                Options:     [4]string{"Waste time", "Prevent muscle injury", "Increase weight", "Cool the body"},
                AnswerIndex: 1,
                Explanation: "Gradual warm-up raises blood flow and readies muscles."},
}

        // Second Term
        {SubjectCode: "BUS", Band: "junior", Term: 2,
                Question:    "A document showing details of goods sold and their prices is the:",
                Options:     [4]string{"Invoice", "Passport", "Ledger card", "License"},
                AnswerIndex: 0,
                Explanation: "Invoices state quantity, price and terms of a sale."},
        {SubjectCode: "BUS", Band: "junior", Term: 2,
                Question:    "The factor of production that organizes the others is:",
                Options:     [4]string{"Land", "Labour", "Capital", "Entrepreneurship"},
                AnswerIndex: 3,
                Explanation: "The entrepreneur bears risk and coordinates the factors."},
        {SubjectCode: "BUS", Band: "junior", Term: 2,
                Question:    "Honesty in business builds:",
                Options:     [4]string{"Losses", "Trust and goodwill", "Debts", "Complaints"},
                AnswerIndex: 1,
                Explanation: "Reputation compounds: honest traders keep customers."},

        // Third Term
        {SubjectCode: "BUS", Band: "junior", Term: 3,
                Question:    "Saving money regularly teaches a student:",
                Options:     [4]string{"Wasteful habits", "Financial discipline", "Borrowing", "Gambling"},
                AnswerIndex: 1,
                Explanation: "Savings build the discipline that funds future goals."},
        {SubjectCode: "BUS", Band: "junior", Term: 3,
                Question:    "A partnership differs from a sole proprietorship by having:",
                Options:     [4]string{"One owner", "Two or more owners", "No owners", "Only workers"},
                AnswerIndex: 1,
                Explanation: "Partners share ownership, profit and liability."},
        {SubjectCode: "BUS", Band: "junior", Term: 3,
                Question:    "Buying goods with the intention of paying later is buying on:",
                Options:     [4]string{"Cash", "Credit", "Discount", "Hire purchase only"},
                AnswerIndex: 1,
                Explanation: "Credit trade defers payment while delivering the goods."},

        // Second Term
        {SubjectCode: "PHE", Band: "junior", Term: 2,
                Question:    "The sport played on a court with rackets and a shuttlecock is:",
                Options:     [4]string{"Badminton", "Hockey", "Volleyball", "Tennis"},
                AnswerIndex: 0,
                Explanation: "Badminton uses light rackets and a feathered shuttle."},
        {SubjectCode: "PHE", Band: "junior", Term: 2,
                Question:    "First aid given to a bleeding wound starts with:",
                Options:     [4]string{"Applying pressure", "Removing the bandage", "Pouring dust", "Massaging"},
                AnswerIndex: 0,
                Explanation: "Direct pressure controls bleeding before anything else."},
        {SubjectCode: "PHE", Band: "junior", Term: 2,
                Question:    "Malaria is prevented best by:",
                Options:     [4]string{"Sleeping under treated nets", "Eating sweets", "Running daily", "Bathing twice"},
                AnswerIndex: 0,
                Explanation: "Treated nets cut the mosquito bites that spread malaria."},

        // Third Term
        {SubjectCode: "PHE", Band: "junior", Term: 3,
                Question:    "Drinking safe water is important because unsafe water can cause:",
                Options:     [4]string{"Cholera", "Rickets", "Myopia", "Asthma"},
                AnswerIndex: 0,
                Explanation: "Contaminated water transmits cholera and other waterborne diseases."},
        {SubjectCode: "PHE", Band: "junior", Term: 3,
                Question:    "The relay race baton must be passed within the:",
                Options:     [4]string{"Change-over zone", "Starting blocks", "Spectator stand", "Finish line"},
                AnswerIndex: 0,
                Explanation: "Passes outside the zone disqualify the team."},
        {SubjectCode: "PHE", Band: "junior", Term: 3,
                Question:    "Personal hygiene includes all EXCEPT:",
                Options:     [4]string{"Bathing daily", "Brushing teeth", "Washing clothes", "Sharing towels"},
                AnswerIndex: 3,
                Explanation: "Sharing towels spreads skin and eye infections."},
