// Christian Religious Studies and Islamic Religious Studies starter
// questions (both-band subjects tagged junior). Original content
// written for Renance, framed for respectful classroom use.

package school

var examBankCRS = []SeedExamQuestion{
	{SubjectCode: "CRS", Band: "junior", Term: 1,
		Question:    "In the creation account, God rested on the ______ day.",
		Options:     [4]string{"Sixth", "Seventh", "Fifth", "Third"},
		AnswerIndex: 1,
		Explanation: "God blessed and sanctified the seventh day as a day of rest."},
	{SubjectCode: "CRS", Band: "junior", Term: 1,
		Question:    "The first book of the Bible is:",
		Options:     [4]string{"Exodus", "Genesis", "Leviticus", "Psalms"},
		AnswerIndex: 1,
		Explanation: "Genesis opens the Bible with origins and the patriarchs."},
	{SubjectCode: "CRS", Band: "junior", Term: 1,
		Question:    "Joseph was sold by his brothers into:",
		Options:     [4]string{"Slavery in Egypt", "Prison in Babylon", "Exile in Persia", "Service in Nineveh"},
		AnswerIndex: 0,
		Explanation: "Joseph was taken to Egypt, where God raised him later."},
	{SubjectCode: "CRS", Band: "junior", Term: 2,
		Question:    "Moses led the Israelites out of Egypt through the:",
		Options:     [4]string{"Red Sea", "River Jordan", "Dead Sea", "River Nile"},
		AnswerIndex: 0,
		Explanation: "The Exodus crossing happened at the Red Sea."},
	{SubjectCode: "CRS", Band: "junior", Term: 2,
		Question:    "How many commandments were given to Moses on the mountain?",
		Options:     [4]string{"Seven", "Ten", "Twelve", "Forty"},
		AnswerIndex: 1,
		Explanation: "The Ten Commandments form the moral core of the covenant."},
	{SubjectCode: "CRS", Band: "junior", Term: 2,
		Question:    "David defeated Goliath with a:",
		Options:     [4]string{"Spear", "Sling and stone", "Sword", "Bow"},
		AnswerIndex: 1,
		Explanation: "David trusted God and felled Goliath with one stone."},
	{SubjectCode: "CRS", Band: "junior", Term: 3,
		Question:    "Jesus was born in the town of:",
		Options:     [4]string{"Nazareth", "Bethlehem", "Capernaum", "Jericho"},
		AnswerIndex: 1,
		Explanation: "The nativity accounts place the birth in Bethlehem."},
	{SubjectCode: "CRS", Band: "junior", Term: 3,
		Question:    "The parable of the Good Samaritan teaches:",
		Options:     [4]string{"Fasting", "Neighborly love", "Tithing", "Farming"},
		AnswerIndex: 1,
		Explanation: "The story answers the question: who is my neighbor?"},
	{SubjectCode: "CRS", Band: "junior", Term: 3,
		Question:    "The disciples were first called Christians in:",
		Options:     [4]string{"Jerusalem", "Antioch", "Rome", "Corinth"},
		AnswerIndex: 1,
		Explanation: "Acts records that the name Christian began in Antioch."},
}

var examBankIRS = []SeedExamQuestion{
	{SubjectCode: "IRS", Band: "junior", Term: 1,
		Question:    "The holy book of Islam is the:",
		Options:     [4]string{"Bible", "Qur'an", "Talmud", "Hadith"},
		AnswerIndex: 1,
		Explanation: "The Qur'an is the revealed scripture of Islam."},
	{SubjectCode: "IRS", Band: "junior", Term: 1,
		Question:    "How many pillars of Islam are there?",
		Options:     [4]string{"Three", "Four", "Five", "Seven"},
		AnswerIndex: 2,
		Explanation: "The five pillars outline the core practices of the faith."},
	{SubjectCode: "IRS", Band: "junior", Term: 1,
		Question:    "The month of fasting for Muslims is:",
		Options:     [4]string{"Rajab", "Ramadan", "Shawwal", "Muharram"},
		AnswerIndex: 1,
		Explanation: "Fasting in Ramadan is the fourth pillar of Islam."},
	{SubjectCode: "IRS", Band: "junior", Term: 2,
		Question:    "The daily prayers of Islam are called:",
		Options:     [4]string{"Zakat", "Salat", "Hajj", "Sawm"},
		AnswerIndex: 1,
		Explanation: "Salat is the second pillar, observed five times daily."},
	{SubjectCode: "IRS", Band: "junior", Term: 2,
		Question:    "Almsgiving in Islam is known as:",
		Options:     [4]string{"Salat", "Zakat", "Hajj", "Iman"},
		AnswerIndex: 1,
		Explanation: "Zakat purifies wealth and supports the needy."},
	{SubjectCode: "IRS", Band: "junior", Term: 2,
		Question:    "The pilgrimage to Mecca is performed in the month of:",
		Options:     [4]string{"Dhul-Hijjah", "Ramadan", "Rabi' al-Awwal", "Jumada"},
		AnswerIndex: 0,
		Explanation: "Hajj falls in Dhul-Hijjah, the twelfth month."},
	{SubjectCode: "IRS", Band: "junior", Term: 3,
		Question:    "The first pillar of Islam is the:",
		Options:     [4]string{"Shahada", "Hajj", "Zakat", "Sawm"},
		AnswerIndex: 0,
		Explanation: "The Shahada is the declaration of faith."},
	{SubjectCode: "IRS", Band: "junior", Term: 3,
		Question:    "The migration of the Prophet from Mecca to Medina is called:",
		Options:     [4]string{"Hijrah", "Hajj", "Jihad", "Sunnah"},
		AnswerIndex: 0,
		Explanation: "The Hijrah marks the start of the Islamic calendar."},
	{SubjectCode: "IRS", Band: "junior", Term: 3,
		Question:    "The festival that follows the Ramadan fast is:",
		Options:     [4]string{"Eid-ul-Fitr", "Eid-ul-Adha", "Mawlid", "Ashura"},
		AnswerIndex: 0,
		Explanation: "Eid-ul-Fitr breaks the month of fasting."},
}

var examBankFrench = []SeedExamQuestion{
	// French (junior band)
	{SubjectCode: "FRE", Band: "junior", Term: 1,
		Question:    "How do you say Good morning in French?",
		Options:     [4]string{"Bonsoir", "Bonjour", "Bonne nuit", "Salut"},
		AnswerIndex: 1,
		Explanation: "Bonjour greets the morning and the day."},
	{SubjectCode: "FRE", Band: "junior", Term: 1,
		Question:    "The French word for book is:",
		Options:     [4]string{"Cahier", "Livre", "Crayon", "Table"},
		AnswerIndex: 1,
		Explanation: "Un livre is a book; un cahier is an exercise book."},
	{SubjectCode: "FRE", Band: "junior", Term: 1,
		Question:    "Choose the correct article: ______ pomme (the apple).",
		Options:     [4]string{"Le", "La", "Les", "Un"},
		AnswerIndex: 1,
		Explanation: "Pomme is feminine, so the apple is la pomme."},
	{SubjectCode: "FRE", Band: "junior", Term: 2,
		Question:    "The French sentence Je ne comprends pas means:",
		Options:     [4]string{"I understand", "I do not understand", "I am listening", "Repeat please"},
		AnswerIndex: 1,
		Explanation: "Ne...pas wraps the verb to negate it."},
	{SubjectCode: "FRE", Band: "junior", Term: 2,
		Question:    "Which pair of numbers is correct in French?",
		Options:     [4]string{"Un, deux", "Dix, onze... non", "Cinq, sept", "Quatre, deux"},
		AnswerIndex: 0,
		Explanation: "Un and deux are one and two."},
	{SubjectCode: "FRE", Band: "junior", Term: 2,
		Question:    "Comment t'appelles-tu? asks about:",
		Options:     [4]string{"Your age", "Your name", "Your school", "Your house"},
		AnswerIndex: 1,
		Explanation: "It literally asks what you call yourself."},
	{SubjectCode: "FRE", Band: "junior", Term: 3,
		Question:    "The French word for school is:",
		Options:     [4]string{"Marche", "Ecole", "Eglise", "Marche"},
		AnswerIndex: 1,
		Explanation: "L'ecole is the school."},
	{SubjectCode: "FRE", Band: "junior", Term: 3,
		Question:    "Merci beaucoup means:",
		Options:     [4]string{"Goodbye", "Thank you very much", "See you soon", "Excuse me"},
		AnswerIndex: 1,
		Explanation: "Merci is thanks; beaucoup intensifies it."},
	{SubjectCode: "FRE", Band: "junior", Term: 3,
		Question:    "The correct reply to Comment ca va? is:",
		Options:     [4]string{"Ca va bien", "Je m'appelle", "Bonjour", "Au revoir"},
		AnswerIndex: 0,
		Explanation: "Ca va bien answers the health greeting."},
}

// Part two: three more per term per subject.
var examBankCRSP2 = []SeedExamQuestion{
        {SubjectCode: "CRS", Band: "junior", Term: 1,
                Question:    "The shepherd boy anointed to be king of Israel was:",
                Options:     [4]string{"David", "Saul", "Solomon", "Samuel"},
                AnswerIndex: 0,
                Explanation: "Samuel anointed David while Saul still reigned."},
        {SubjectCode: "CRS", Band: "junior", Term: 2,
                Question:    "The wisdom book of the Bible that opens with The fear of the LORD is:",
                Options:     [4]string{"Proverbs", "Ruth", "Esther", "Jonah"},
                AnswerIndex: 0,
                Explanation: "Proverbs anchors wisdom in reverence for God."},
        {SubjectCode: "CRS", Band: "junior", Term: 3,
                Question:    "Jesus fed five thousand with five loaves and:",
                Options:     [4]string{"Two fish", "One lamb", "Seven grapes", "Ten eggs"},
                AnswerIndex: 0,
                Explanation: "The feeding miracle used five loaves and two fish."},
}

var examBankIRSP2 = []SeedExamQuestion{
        {SubjectCode: "IRS", Band: "junior", Term: 1,
                Question:    "The Prophet of Islam was born in the city of:",
                Options:     [4]string{"Mecca", "Medina", "Cairo", "Baghdad"},
                AnswerIndex: 0,
                Explanation: "Muhammad was born in Mecca around 570 CE."},
        {SubjectCode: "IRS", Band: "junior", Term: 2,
                Question:    "The chapters of the Qur'an are called:",
                Options:     [4]string{"Surahs", "Hadiths", "Ayats", "Sunnahs"},
                AnswerIndex: 0,
                Explanation: "Surahs are the chapters; verses are ayats."},
        {SubjectCode: "IRS", Band: "junior", Term: 3,
                Question:    "The command to fast during Ramadan is found in the month's revelation about:",
                Options:     [4]string{"Guidance", "Trade", "War", "Farming"},
                AnswerIndex: 0,
                Explanation: "The fasting verses tie the month to guidance for mankind."},
}

var examBankFrenchP2 = []SeedExamQuestion{
        {SubjectCode: "FRE", Band: "junior", Term: 1,
                Question:    "The French word for thank you is:",
                Options:     [4]string{"Merci", "Bonjour", "Salut", "Non"},
                AnswerIndex: 0,
                Explanation: "Merci is the everyday thank-you."},
        {SubjectCode: "FRE", Band: "junior", Term: 2,
                Question:    "Nous means:",
                Options:     [4]string{"We", "They", "You", "He"},
                AnswerIndex: 0,
                Explanation: "Nous is the first-person plural pronoun."},
        {SubjectCode: "FRE", Band: "junior", Term: 3,
                Question:    "The colour blanc in English is:",
                Options:     [4]string{"White", "Black", "Blue", "Green"},
                AnswerIndex: 0,
                Explanation: "Blanc is white, as on the Nigerian flag's band."},
}
