// Further Mathematics and Computer Science starter questions (senior
// band, science track). Original content written for Renance.

package school

var examBankFurtherMaths = []SeedExamQuestion{
        // First Term
        {SubjectCode: "FMT", Band: "senior", Term: 1,
                Question:    "The derivative of 3x squared with respect to x is:",
                Options:     [4]string{"3x", "6x", "6x squared", "x cubed"},
                AnswerIndex: 1,
                Explanation: "Differentiate 3x^2: multiply by the power and reduce it, giving 6x."},
        {SubjectCode: "FMT", Band: "senior", Term: 1,
                Question:    "If A is a 2 by 2 matrix with determinant 0, then A is:",
                Options:     [4]string{"Invertible", "Singular", "Symmetric", "Orthogonal"},
                AnswerIndex: 1,
                Explanation: "A zero determinant makes the matrix singular and non-invertible."},
        {SubjectCode: "FMT", Band: "senior", Term: 1,
                Question:    "The roots of the quadratic x squared - 5x + 6 = 0 are:",
                Options:     [4]string{"1 and 6", "2 and 3", "3 and 4", "-2 and -3"},
                AnswerIndex: 1,
                Explanation: "Factor as (x-2)(x-3), so the roots are 2 and 3."},
}

var examBankCompSci = []SeedExamQuestion{
        // First Term
        {SubjectCode: "CSC", Band: "senior", Term: 1,
                Question:    "An algorithm is best described as a:",
                Options:     [4]string{"Computer part", "Step-by-step solution procedure", "Programming language", "File format"},
                AnswerIndex: 1,
                Explanation: "Algorithms are ordered steps that solve a defined problem."},
        {SubjectCode: "CSC", Band: "senior", Term: 1,
                Question:    "Which number system uses only 0 and 1?",
                Options:     [4]string{"Decimal", "Binary", "Octal", "Hexadecimal"},
                AnswerIndex: 1,
                Explanation: "Binary is base two, the machine's native language."},
        {SubjectCode: "CSC", Band: "senior", Term: 1,
                Question:    "A flowchart symbol shaped like a diamond represents:",
                Options:     [4]string{"Start", "Input", "Decision", "Output"},
                AnswerIndex: 2,
                Explanation: "Diamonds test a condition and branch on the result."},
}

        // Second Term
        {SubjectCode: "FMT", Band: "senior", Term: 2,
                Question:    "The integral of 2x with respect to x is:",
                Options:     [4]string{"x squared + c", "2 + c", "x cubed + c", "2x squared + c"},
                AnswerIndex: 0,
                Explanation: "Antidifferentiate 2x to get x squared plus the constant."},
        {SubjectCode: "FMT", Band: "senior", Term: 2,
                Question:    "The set (A union B) contains elements that are in:",
                Options:     [4]string{"A only", "B only", "A, B or both", "Neither A nor B"},
                AnswerIndex: 2,
                Explanation: "Union collects every element of both sets without duplication."},
        {SubjectCode: "FMT", Band: "senior", Term: 2,
                Question:    "If P(A) = 0.4 and A and B are independent with P(B) = 0.5, then P(A and B) is:",
                Options:     [4]string{"0.9", "0.2", "0.45", "0.1"},
                AnswerIndex: 1,
                Explanation: "Independent events multiply: 0.4 x 0.5 = 0.2."},

        // Third Term
        {SubjectCode: "FMT", Band: "senior", Term: 3,
                Question:    "The modulus of the complex number 3 + 4i is:",
                Options:     [4]string{"5", "7", "12", "25"},
                AnswerIndex: 0,
                Explanation: "Modulus = square root of (9 + 16) = 5."},
        {SubjectCode: "FMT", Band: "senior", Term: 3,
                Question:    "The maximum value of f(x) = -x squared + 4x occurs at x =:",
                Options:     [4]string{"1", "2", "3", "4"},
                AnswerIndex: 1,
                Explanation: "Set the derivative -2x + 4 to zero: x = 2."},
        {SubjectCode: "FMT", Band: "senior", Term: 3,
                Question:    "In statistics, the standard deviation measures:",
                Options:     [4]string{"Middle value", "Spread about the mean", "Most frequent value", "Total frequency"},
                AnswerIndex: 1,
                Explanation: "Deviation from the mean, squared, averaged, then rooted."},

        // Second Term
        {SubjectCode: "CSC", Band: "senior", Term: 2,
                Question:    "BASIC and Python are examples of:",
                Options:     [4]string{"High-level languages", "Machine code", "Hardware", "Operating systems"},
                AnswerIndex: 0,
                Explanation: "High-level languages read close to human language and compile or interpret."},
        {SubjectCode: "CSC", Band: "senior", Term: 2,
                Question:    "The hexadecimal digit E equals which decimal value?",
                Options:     [4]string{"12", "13", "14", "15"},
                AnswerIndex: 2,
                Explanation: "Hex digits run A=10 to F=15, so E is 14."},
        {SubjectCode: "CSC", Band: "senior", Term: 2,
                Question:    "A database table's unique identifier for each row is the:",
                Options:     [4]string{"Field", "Primary key", "Record", "Query"},
                AnswerIndex: 1,
                Explanation: "The primary key distinguishes every row from the others."},

        // Third Term
        {SubjectCode: "CSC", Band: "senior", Term: 3,
                Question:    "Which of these is a web browser?",
                Options:     [4]string{"Windows", "Firefox", "Python", "Excel"},
                AnswerIndex: 1,
                Explanation: "Browsers like Firefox request and render web pages."},
        {SubjectCode: "CSC", Band: "senior", Term: 3,
                Question:    "A secure password should be:",
                Options:     [4]string{"Short and common", "Long and mixed", "Your name", "One letter"},
                AnswerIndex: 1,
                Explanation: "Length plus a mix of characters resists guessing."},
        {SubjectCode: "CSC", Band: "senior", Term: 3,
                Question:    "Cloud storage means saving files:",
                Options:     [4]string{"On the hard disk only", "On remote servers over the internet", "On paper", "On flash drives only"},
                AnswerIndex: 1,
                Explanation: "Cloud services keep data on remote servers reachable anywhere."},
