// Junior-secondary starter questions: English Studies, Mathematics and
// Basic Science across the three terms. Original content, written for
// Renance, NERDC topics of the JSS band.

package school

var examBankJunior = []SeedExamQuestion{
	// English Studies (JSS), First Term
	{SubjectCode: "ENG-J", Band: "junior", Term: 1,
		Question:    "Choose the correct plural: One child ran home, and the other ______ followed.",
		Options:     [4]string{"childs", "children", "childrens", "child"},
		AnswerIndex: 1,
		Explanation: "Child has the irregular plural children."},
	{SubjectCode: "ENG-J", Band: "junior", Term: 1,
		Question:    "Identify the adverb in this sentence: The girl sang softly to her brother.",
		Options:     [4]string{"girl", "sang", "softly", "brother"},
		AnswerIndex: 2,
		Explanation: "Softly tells how the singing was done, so it is an adverb."},
	{SubjectCode: "ENG-J", Band: "junior", Term: 1,
		Question:    "Which word rhymes with enough?",
		Options:     [4]string{"plough", "though", "rough", "bough"},
		AnswerIndex: 2,
		Explanation: "Rough shares the same vowel and final consonant sound."},
	{SubjectCode: "ENG-J", Band: "junior", Term: 1,
		Question:    "Choose the right form: She has been living in Abuja ______ 2019.",
		Options:     [4]string{"since", "for", "at", "from"},
		AnswerIndex: 0,
		Explanation: "Since introduces a point in time; for introduces a duration."},

	// English Studies (JSS), Second Term
	{SubjectCode: "ENG-J", Band: "junior", Term: 2,
		Question:    "Pick the correct question tag: You completed the assignment, ______?",
		Options:     [4]string{"isn't it", "didn't you", "aren't you", "won't you"},
		AnswerIndex: 1,
		Explanation: "The statement uses the past tense completed, so the tag is didn't you."},
	{SubjectCode: "ENG-J", Band: "junior", Term: 2,
		Question:    "In the sentence The boys were beaten in the match, the passive voice becomes:",
		Options:     [4]string{"The match beat the boys.", "Someone beat the boys.", "The match was beaten by the boys.", "The boys beat the match."},
		AnswerIndex: 2,
		Explanation: "Passive voice makes the receiver of the action the subject."},
	{SubjectCode: "ENG-J", Band: "junior", Term: 2,
		Question:    "Which word is a synonym of generous?",
		Options:     [4]string{"selfish", "kind", "greedy", "careless"},
		AnswerIndex: 1,
		Explanation: "Generous and kind both describe giving willingly."},
	{SubjectCode: "ENG-J", Band: "junior", Term: 2,
		Question:    "Choose the word opposite in meaning to ancient.",
		Options:     [4]string{"old", "historic", "modern", " antique"},
		AnswerIndex: 2,
		Explanation: "Modern is the direct opposite of ancient."},

	// English Studies (JSS), Third Term
	{SubjectCode: "ENG-J", Band: "junior", Term: 3,
		Question:    "Which sentence uses the correct preposition?",
		Options:     [4]string{"The book is different than mine.", "The book is different from mine.", "The book is different off mine.", "The book is different away mine."},
		AnswerIndex: 1,
		Explanation: "Different from is the accepted form."},
	{SubjectCode: "ENG-J", Band: "junior", Term: 3,
		Question:    "A word that joins two clauses is called a ______.",
		Options:     [4]string{"pronoun", "conjunction", "preposition", "interjection"},
		AnswerIndex: 1,
		Explanation: "Conjunctions such as and, but and because join clauses."},
	{SubjectCode: "ENG-J", Band: "junior", Term: 3,
		Question:    "Choose the correctly spelled word.",
		Options:     [4]string{"accomodation", "acommodation", "accommodation", "acomodation"},
		AnswerIndex: 2,
		Explanation: "Accommodation doubles both the c and the m."},
	{SubjectCode: "ENG-J", Band: "junior", Term: 3,
		Question:    "The underlined word in She wept bitterly is an example of a/an ______.",
		Options:     [4]string{"adjective", "adverb", "noun", "verb"},
		AnswerIndex: 1,
		Explanation: "Bitterly describes manner, which makes it an adverb."},

	// Mathematics (JSS), First Term
	{SubjectCode: "MTH-J", Band: "junior", Term: 1,
		Question:    "Simplify: 48 divided by 6 plus 2 x 3.",
		Options:     [4]string{"14", "10", "8", "12"},
		AnswerIndex: 0,
		Explanation: "Division first: 48/6 = 8, then 8 + 6 = 14."},
	{SubjectCode: "MTH-J", Band: "junior", Term: 1,
		Question:    "What is the lowest common multiple of 4 and 6?",
		Options:     [4]string{"24", "12", "18", "8"},
		AnswerIndex: 1,
		Explanation: "Multiples of 4 are 4, 8, 12; multiples of 6 are 6, 12. The first shared one is 12."},
	{SubjectCode: "MTH-J", Band: "junior", Term: 1,
		Question:    "Express 0.45 as a fraction in its lowest terms.",
		Options:     [4]string{"45/100", "9/20", "5/9", "9/10"},
		AnswerIndex: 1,
		Explanation: "45/100 reduces by 5 to 9/20."},
	{SubjectCode: "MTH-J", Band: "junior", Term: 1,
		Question:    "A number divisible by both 2 and 3 must also be divisible by:",
		Options:     [4]string{"5", "6", "8", "9"},
		AnswerIndex: 1,
		Explanation: "The product of the co-prime divisors 2 and 3 is 6."},

	// Mathematics (JSS), Second Term
	{SubjectCode: "MTH-J", Band: "junior", Term: 2,
		Question:    "Solve for x: 3x - 7 = 14.",
		Options:     [4]string{"7", "5", "9", "21"},
		AnswerIndex: 0,
		Explanation: "Add 7 to both sides, then divide by 3: x = 21/3 = 7."},
	{SubjectCode: "MTH-J", Band: "junior", Term: 2,
		Question:    "The sum of the angles of a triangle is:",
		Options:     [4]string{"90 degrees", "180 degrees", "270 degrees", "360 degrees"},
		AnswerIndex: 1,
		Explanation: "Every triangle's interior angles add up to 180 degrees."},
	{SubjectCode: "MTH-J", Band: "junior", Term: 2,
		Question:    "Convert 3/5 to a percentage.",
		Options:     [4]string{"35%", "53%", "60%", "30%"},
		AnswerIndex: 2,
		Explanation: "3/5 x 100 = 60 percent."},
	{SubjectCode: "MTH-J", Band: "junior", Term: 2,
		Question:    "A car travels 180 km in 3 hours. Its average speed is:",
		Options:     [4]string{"50 km/h", "54 km/h", "60 km/h", "90 km/h"},
		AnswerIndex: 2,
		Explanation: "Speed is distance over time: 180/3 = 60 km/h."},

	// Mathematics (JSS), Third Term
	{SubjectCode: "MTH-J", Band: "junior", Term: 3,
		Question:    "The area of a rectangle 8 m long and 5 m wide is:",
		Options:     [4]string{"13 m squared", "26 m squared", "40 m squared", "45 m squared"},
		AnswerIndex: 2,
		Explanation: "Area of a rectangle is length times breadth: 8 x 5 = 40."},
	{SubjectCode: "MTH-J", Band: "junior", Term: 3,
		Question:    "Find the next term of the sequence 2, 5, 10, 17, ...",
		Options:     [4]string{"24", "25", "26", "27"},
		AnswerIndex: 2,
		Explanation: "The gaps are 3, 5, 7, then 9: 17 + 9 = 26."},
	{SubjectCode: "MTH-J", Band: "junior", Term: 3,
		Question:    "Simplify the ratio 45:60 to its lowest form.",
		Options:     [4]string{"9:12", "3:4", "5:6", "15:20"},
		AnswerIndex: 1,
		Explanation: "Divide both sides by 15 to get 3:4."},
	{SubjectCode: "MTH-J", Band: "junior", Term: 3,
		Question:    "A fair die is rolled once. What is the probability of getting a prime number?",
		Options:     [4]string{"1/6", "1/3", "1/2", "2/3"},
		AnswerIndex: 2,
		Explanation: "Primes on a die are 2, 3 and 5, which is 3 out of 6, so one half."},

	// Basic Science, First Term
	{SubjectCode: "BSC", Band: "junior", Term: 1,
		Question:    "Which instrument is used to measure temperature?",
		Options:     [4]string{"Barometer", "Thermometer", "Hygrometer", "Anemometer"},
		AnswerIndex: 1,
		Explanation: "A thermometer measures how hot or cold a body is."},
	{SubjectCode: "BSC", Band: "junior", Term: 1,
		Question:    "Living things that make their own food are called:",
		Options:     [4]string{"Consumers", "Producers", "Decomposers", "Parasites"},
		AnswerIndex: 1,
		Explanation: "Green plants produce their own food by photosynthesis."},
	{SubjectCode: "BSC", Band: "junior", Term: 1,
		Question:    "The change of water from liquid to gas is called:",
		Options:     [4]string{"Condensation", "Evaporation", "Freezing", "Filtration"},
		AnswerIndex: 1,
		Explanation: "Evaporation turns liquid water into water vapour."},
	{SubjectCode: "BSC", Band: "junior", Term: 1,
		Question:    "Which of these is a renewable source of energy?",
		Options:     [4]string{"Petrol", "Diesel", "Sunlight", "Coal"},
		AnswerIndex: 2,
		Explanation: "Sunlight is replaced naturally and never runs out."},

	// Basic Science, Second Term
	{SubjectCode: "BSC", Band: "junior", Term: 2,
		Question:    "The smallest particle of an element that can exist alone is the:",
		Options:     [4]string{"Molecule", "Atom", "Electron", "Compound"},
		AnswerIndex: 1,
		Explanation: "An atom is the smallest unit of an element with its properties."},
	{SubjectCode: "BSC", Band: "junior", Term: 2,
		Question:    "Which blood cells fight infection in the body?",
		Options:     [4]string{"Red blood cells", "White blood cells", "Platelets", "Plasma"},
		AnswerIndex: 1,
		Explanation: "White blood cells defend the body against germs."},
	{SubjectCode: "BSC", Band: "junior", Term: 2,
		Question:    "The process by which green plants make food is called:",
		Options:     [4]string{"Respiration", "Photosynthesis", "Transpiration", "Digestion"},
		AnswerIndex: 1,
		Explanation: "Photosynthesis uses sunlight, water and carbon dioxide."},
	{SubjectCode: "BSC", Band: "junior", Term: 2,
		Question:    "A mixture of sand and water can be separated by:",
		Options:     [4]string{"Filtration", "Distillation", "Magnetism", "Sublimation"},
		AnswerIndex: 0,
		Explanation: "Sand is insoluble, so a filter holds it back while water passes."},

	// Basic Science, Third Term
	{SubjectCode: "BSC", Band: "junior", Term: 3,
		Question:    "The force that pulls objects towards the centre of the Earth is:",
		Options:     [4]string{"Friction", "Gravity", "Magnetism", "Tension"},
		AnswerIndex: 1,
		Explanation: "Gravity acts towards the centre of the Earth."},
	{SubjectCode: "BSC", Band: "junior", Term: 3,
		Question:    "Which of these is a chemical change?",
		Options:     [4]string{"Melting ice", "Rusting iron", "Breaking glass", "Boiling water"},
		AnswerIndex: 1,
		Explanation: "Rusting forms a new substance, iron oxide."},
	{SubjectCode: "BSC", Band: "junior", Term: 3,
		Question:    "The component of air used in burning is:",
		Options:     [4]string{"Nitrogen", "Oxygen", "Carbon dioxide", "Argon"},
		AnswerIndex: 1,
		Explanation: "Oxygen supports combustion."},
	{SubjectCode: "BSC", Band: "junior", Term: 3,
		Question:    "Energy in food is usually measured in:",
		Options:     [4]string{"Newtons", "Joules", "Metres", "Amperes"},
		AnswerIndex: 1,
		Explanation: "The joule measures energy, including food energy."},
}

// Part two: one more question per subject per term.
var examBankJuniorP2 = []SeedExamQuestion{
        {SubjectCode: "ENG-J", Band: "junior", Term: 1,
                Question:    "Choose the correct homophone: The player scored a ______ in the match.",
                Options:     [4]string{"goal", "gaol", "gowl", "goel"},
                AnswerIndex: 0,
                Explanation: "A goal is scored; a gaol is an old spelling of jail."},
        {SubjectCode: "ENG-J", Band: "junior", Term: 2,
                Question:    "The figure of speech in the sea roared angrily is:",
                Options:     [4]string{"Simile", "Personification", "Irony", "Pun"},
                AnswerIndex: 1,
                Explanation: "Human anger given to the sea personifies it."},
        {SubjectCode: "ENG-J", Band: "junior", Term: 3,
                Question:    "Which sentence is in the future tense?",
                Options:     [4]string{"She will travel tomorrow.", "She travels daily.", "She travelled last week.", "She is travelling now."},
                AnswerIndex: 0,
                Explanation: "Will plus the verb points to the future."},
        {SubjectCode: "MTH-J", Band: "junior", Term: 1,
                Question:    "Simplify 2/3 + 1/6.",
                Options:     [4]string{"3/9", "5/6", "1/2", "2/9"},
                AnswerIndex: 1,
                Explanation: "Common denominator 6: 4/6 + 1/6 = 5/6."},
        {SubjectCode: "MTH-J", Band: "junior", Term: 2,
                Question:    "The sum of angles on a straight line is:",
                Options:     [4]string{"90 degrees", "180 degrees", "270 degrees", "360 degrees"},
                AnswerIndex: 1,
                Explanation: "Adjacent angles on a straight line sum to 180 degrees."},
        {SubjectCode: "MTH-J", Band: "junior", Term: 3,
                Question:    "If a shirt costs 800 naira after a 20 percent discount, the original price was:",
                Options:     [4]string{"1000 naira", "960 naira", "900 naira", "820 naira"},
                AnswerIndex: 0,
                Explanation: "80 percent of the price is 800, so the price was 1000."},
        {SubjectCode: "BSC", Band: "junior", Term: 1,
                Question:    "The organ that pumps blood round the body is the:",
                Options:     [4]string{"Heart", "Liver", "Kidney", "Lung"},
                AnswerIndex: 0,
                Explanation: "The heart drives blood through the circulatory system."},
        {SubjectCode: "BSC", Band: "junior", Term: 2,
                Question:    "Sound travels fastest through:",
                Options:     [4]string{"Steel", "Water", "Air", "Vacuum"},
                AnswerIndex: 0,
                Explanation: "Denser solids like steel carry sound fastest; vacuums carry none."},
        {SubjectCode: "BSC", Band: "junior", Term: 3,
                Question:    "A satellite in orbit stays up because its forward motion balances:",
                Options:     [4]string{"Gravity", "Friction", "Magnetism", "Pressure"},
                AnswerIndex: 0,
                Explanation: "Orbit is a continuous free-fall around the Earth."},
}
