// Commerce and Financial Accounting starter questions (senior band,
// commercial track). Original content written for Renance.

package school

var examBankCommerce = []SeedExamQuestion{
	// First Term
	{SubjectCode: "COM", Band: "senior", Term: 1,
		Question:    "Commerce is divided into trade and:",
		Options:     [4]string{"Banking", "Aids to trade", "Insurance", "Advertising"},
		AnswerIndex: 1,
		Explanation: "Aids to trade include banking, insurance, transport and warehousing."},
	{SubjectCode: "COM", Band: "senior", Term: 1,
		Question:    "Buying and selling of goods and services within a country is:",
		Options:     [4]string{"Foreign trade", "Home trade", "Import trade", "Entrepot trade"},
		AnswerIndex: 1,
		Explanation: "Home (internal) trade happens within national borders."},
	{SubjectCode: "COM", Band: "senior", Term: 1,
		Question:    "The middleman that buys in bulk from producers and sells to retailers is the:",
		Options:     [4]string{"Consumer", "Wholesaler", "Broker", "Hawker"},
		AnswerIndex: 1,
		Explanation: "Wholesalers bridge production and retail distribution."},
}
var examBankAccounting = []SeedExamQuestion{
	// First Term
	{SubjectCode: "FAC", Band: "senior", Term: 1,
		Question:    "The accounting equation states that assets equal:",
		Options:     [4]string{"Income minus expenses", "Liabilities plus capital", "Capital minus liabilities", "Sales plus purchases"},
		AnswerIndex: 1,
		Explanation: "Assets = liabilities + owner's equity, the balance sheet backbone."},
	{SubjectCode: "FAC", Band: "senior", Term: 1,
		Question:    "Every accounting transaction affects at least:",
		Options:     [4]string{"One account", "Two accounts", "Three accounts", "Four accounts"},
		AnswerIndex: 1,
		Explanation: "Double entry records a debit and a matching credit."},
	{SubjectCode: "FAC", Band: "senior", Term: 1,
		Question:    "Which book of original entry records credit purchases?",
		Options:     [4]string{"Sales day book", "Purchases day book", "Cash book", "Journal proper"},
		AnswerIndex: 1,
		Explanation: "The purchases day book collects invoices for goods bought on credit."},

	// Second Term
	{SubjectCode: "COM", Band: "senior", Term: 2,
		Question:    "A document inviting the public to buy shares in a company is the:",
		Options:     [4]string{"Invoice", "Prospectus", "Receipt", "Debit note"},
		AnswerIndex: 1,
		Explanation: "The prospectus discloses the business to prospective shareholders."},
	{SubjectCode: "COM", Band: "senior", Term: 2,
		Question:    "Insurance that spreads risk among many policy holders works on the principle of:",
		Options:     [4]string{"Profit", "Pooling risks", "Interest", "Barter"},
		AnswerIndex: 1,
		Explanation: "Premiums from many cover the losses of a few."},
	{SubjectCode: "COM", Band: "senior", Term: 2,
		Question:    "Transport as an aid to trade mainly creates:",
		Options:     [4]string{"Form utility", "Place utility", "Time utility", "Possession utility"},
		AnswerIndex: 1,
		Explanation: "Transport moves goods to where they are wanted."},

	// Third Term
	{SubjectCode: "COM", Band: "senior", Term: 3,
		Question:    "Advertising that targets a wide consumer market is called:",
		Options:     [4]string{"Trade advertising", "Consumer advertising", "Classified only", "Radio only"},
		AnswerIndex: 1,
		Explanation: "Consumer advertising speaks directly to final buyers."},
	{SubjectCode: "COM", Band: "senior", Term: 3,
		Question:    "Warehousing creates utility by storing goods until they are:",
		Options:     [4]string{"Cheaper to destroy", "Needed in the market", "Damaged", "Sold abroad only"},
		AnswerIndex: 1,
		Explanation: "Storage bridges production and demand across time."},
	{SubjectCode: "COM", Band: "senior", Term: 3,
		Question:    "A current account in a bank allows:",
		Options:     [4]string{"Interest earnings only", "Cheque withdrawals", "Fixed deposits", "No withdrawals"},
		AnswerIndex: 1,
		Explanation: "Current accounts serve business payments through cheques."},

	// Second Term
	{SubjectCode: "FAC", Band: "senior", Term: 2,
		Question:    "The trading account of a business computes:",
		Options:     [4]string{"Gross profit", "Net profit", "Cash balance", "Capital"},
		AnswerIndex: 0,
		Explanation: "Trading account matches sales against cost of goods sold."},
	{SubjectCode: "FAC", Band: "senior", Term: 2,
		Question:    "A trial balance that balances proves that:",
		Options:     [4]string{"No error exists", "Debits equal credits", "Profit was made", "Cash is safe"},
		AnswerIndex: 1,
		Explanation: "Balancing only proves arithmetical equality, not error freedom."},
	{SubjectCode: "FAC", Band: "senior", Term: 2,
		Question:    "Depreciation is charged on fixed assets to spread their:",
		Options:     [4]string{"Purchase tax", "Cost over useful life", "Insurance", "Resale price"},
		AnswerIndex: 1,
		Explanation: "Depreciation matches asset cost with the periods it serves."},

	// Third Term
	{SubjectCode: "FAC", Band: "senior", Term: 3,
		Question:    "The double column cash book records:",
		Options:     [4]string{"Cash and bank", "Sales and purchases", "Assets only", "Debtors only"},
		AnswerIndex: 0,
		Explanation: "Two columns track cash and bank movements side by side."},
	{SubjectCode: "FAC", Band: "senior", Term: 3,
		Question:    "Which error will the trial balance NOT reveal?",
		Options:     [4]string{"Wrong side posting", "Error of omission", "Unequal amounts", "Wrong casting"},
		AnswerIndex: 1,
		Explanation: "A completely omitted transaction keeps both sides equal."},
	{SubjectCode: "FAC", Band: "senior", Term: 3,
		Question:    "Expenses paid in advance are treated as:",
		Options:     [4]string{"Liabilities", "Current assets", "Incomes", "Drawings"},
		AnswerIndex: 1,
		Explanation: "Prepaid expenses carry benefit into the next period, so they are assets."},
}

// Part two expansions.
var examBankCommerceP2 = []SeedExamQuestion{
        {SubjectCode: "COM", Band: "senior", Term: 1,
                Question:    "Trade by direct exchange of goods for goods, without money, is:",
                Options:     [4]string{"Barter", "Retailing", "Wholesale", "Hiring"},
                AnswerIndex: 0,
                Explanation: "Barter swaps goods directly and needs a double coincidence of wants."},
        {SubjectCode: "COM", Band: "senior", Term: 2,
                Question:    "The channel producer to wholesaler to retailer to consumer is called:",
                Options:     [4]string{"Direct channel", "Indirect channel", "Reverse channel", "No channel"},
                AnswerIndex: 1,
                Explanation: "Middlemen between producer and consumer make the channel indirect."},
        {SubjectCode: "COM", Band: "senior", Term: 3,
                Question:    "A document sent to correct an overcharge on an invoice is a:",
                Options:     [4]string{"Credit note", "Debit note", "Prospectus", "Waybill"},
                AnswerIndex: 0,
                Explanation: "Credit notes reduce the buyer's debt to the seller."},
}

var examBankAccountingP2 = []SeedExamQuestion{
        {SubjectCode: "FAC", Band: "senior", Term: 1,
                Question:    "The principal book of account is the:",
                Options:     [4]string{"Ledger", "Cash book only", "Sales day book", "Petty cash book"},
                AnswerIndex: 0,
                Explanation: "All accounts collect in the ledger; day books feed it."},
        {SubjectCode: "FAC", Band: "senior", Term: 2,
                Question:    "Returns of goods by a customer are recorded in the:",
                Options:     [4]string{"Sales returns book", "Purchases book", "Cash book", "Journal proper only"},
                AnswerIndex: 0,
                Explanation: "Sales returns (returns inwards) tracks goods sent back."},
        {SubjectCode: "FAC", Band: "senior", Term: 3,
                Question:    "The accounting concept that assumes the business will continue operating is:",
                Options:     [4]string{"Going concern", "Money measurement", "Prudence", "Materiality"},
                AnswerIndex: 0,
                Explanation: "Going concern underpins valuing assets for continued use."},
}
