// Primary wider starter questions: National Values, Pre-vocational
// and Cultural & Creative Arts (Primary band). Original content
// written for Renance.

package school

var examBankPrimaryWider = []SeedExamQuestion{
	// National Values Education (Primary)
	{SubjectCode: "NVE-P", Band: "primary", Term: 1,
		Question:    "Greeting elders shows that a child is:",
		Options:     [4]string{"Rude", "Respectful", "Lazy", "Noisy"},
		AnswerIndex: 1,
		Explanation: "Greetings are a mark of respect in Nigerian culture."},
	{SubjectCode: "NVE-P", Band: "primary", Term: 1,
		Question:    "Returning money you found shows:",
		Options:     [4]string{"Honesty", "Fear", "Anger", "Pride"},
		AnswerIndex: 0,
		Explanation: "Honesty means returning what is not yours."},
	{SubjectCode: "NVE-P", Band: "primary", Term: 1,
		Question:    "A community is a group of people living:",
		Options:     [4]string{"Alone", "Together in one place", "In cars", "In the sky"},
		AnswerIndex: 1,
		Explanation: "Communities share a place and help one another."},
	{SubjectCode: "NVE-P", Band: "primary", Term: 2,
		Question:    "Civic rules are made to keep people:",
		Options:     [4]string{"Sad", "Safe and orderly", "Late", "Hungry"},
		AnswerIndex: 1,
		Explanation: "Rules protect everyone and keep order."},
	{SubjectCode: "NVE-P", Band: "primary", Term: 2,
		Question:    "The national pledge is recited while:",
		Options:     [4]string{"Sitting", "Standing at attention", "Sleeping", "Running"},
		AnswerIndex: 1,
		Explanation: "We stand to honour the nation during the pledge."},
	{SubjectCode: "NVE-P", Band: "primary", Term: 2,
		Question:    "Which of these is a national symbol of Nigeria?",
		Options:     [4]string{"The flag", "A school bag", "A football", "A pencil"},
		AnswerIndex: 0,
		Explanation: "The green-white flag represents the nation."},
	{SubjectCode: "NVE-P", Band: "primary", Term: 3,
		Question:    "Helping a classmate who falls down shows:",
		Options:     [4]string{"Kindness", "Jealousy", "Fear", "Anger"},
		AnswerIndex: 0,
		Explanation: "Kindness is caring for others in need."},
	{SubjectCode: "NVE-P", Band: "primary", Term: 3,
		Question:    "People who keep our streets clean are:",
		Options:     [4]string{"Sanitation workers", "Pilots", "Tailors", "Chefs"},
		AnswerIndex: 0,
		Explanation: "Sanitation workers protect community health."},
	{SubjectCode: "NVE-P", Band: "primary", Term: 3,
		Question:    "Paying school fees on time is the duty of:",
		Options:     [4]string{"Parents and guardians", "Babies", "Visitors", "Strangers"},
		AnswerIndex: 0,
		Explanation: "Guardians sponsor learning; pupils study hard in return."},
}

var examBankPrevocational = []SeedExamQuestion{
	{SubjectCode: "PVS-P", Band: "primary", Term: 1,
		Question:    "The person who treats sick people is a:",
		Options:     [4]string{"Doctor", "Driver", "Farmer", "Tailor"},
		AnswerIndex: 0,
		Explanation: "Doctors work in hospitals and clinics to treat illness."},
	{SubjectCode: "PVS-P", Band: "primary", Term: 1,
		Question:    "Yam, cassava and maize are examples of:",
		Options:     [4]string{"Crops", "Animals", "Tools", "Rivers"},
		AnswerIndex: 0,
		Explanation: "They are crops grown by farmers."},
	{SubjectCode: "PVS-P", Band: "primary", Term: 1,
		Question:    "A person who cuts and sews clothes is a:",
		Options:     [4]string{"Tailor", "Banker", "Pilot", "Plumber"},
		AnswerIndex: 0,
		Explanation: "Tailors make and mend garments."},
	{SubjectCode: "PVS-P", Band: "primary", Term: 2,
		Question:    "Which tool does a carpenter use?",
		Options:     [4]string{"Saw", "Spoon", "Broom", "Pen"},
		AnswerIndex: 0,
		Explanation: "Carpenters cut and shape wood with saws."},
	{SubjectCode: "PVS-P", Band: "primary", Term: 2,
		Question:    "Foods preserved by drying last longer because drying removes:",
		Options:     [4]string{"Water", "Taste", "Colour", "Vitamins only"},
		AnswerIndex: 0,
		Explanation: "Without moisture, germs find it hard to grow."},
	{SubjectCode: "PVS-P", Band: "primary", Term: 2,
		Question:    "The man who fixes leaking pipes is a:",
		Options:     [4]string{"Plumber", "Lawyer", "Nurse", "Chef"},
		AnswerIndex: 0,
		Explanation: "Plumbers install and repair water pipes."},
	{SubjectCode: "PVS-P", Band: "primary", Term: 3,
		Question:    "Fish farming is the rearing of fish in:",
		Options:     [4]string{"Ponds", "Deserts", "Trees", "Classrooms"},
		AnswerIndex: 0,
		Explanation: "Ponds and tanks hold fish raised for food."},
	{SubjectCode: "PVS-P", Band: "primary", Term: 3,
		Question:    "A potter makes things with:",
		Options:     [4]string{"Clay", "Paper", "Iron", "Glass"},
		AnswerIndex: 0,
		Explanation: "Potters shape clay pots by hand or wheel."},
	{SubjectCode: "PVS-P", Band: "primary", Term: 3,
		Question:    "Which job helps keep a community's electricity running?",
		Options:     [4]string{"Electrician", "Tailor", "Baker", "Driver"},
		AnswerIndex: 0,
		Explanation: "Electricians install and repair electrical wiring."},
}

var examBankCCA = []SeedExamQuestion{
	{SubjectCode: "CCA-P", Band: "primary", Term: 1,
		Question:    "Red, yellow and blue are called ______ colours.",
		Options:     [4]string{"Primary", "Secondary", "Dark", "Cold"},
		AnswerIndex: 0,
		Explanation: "They mix to make every other colour."},
	{SubjectCode: "CCA-P", Band: "primary", Term: 1,
		Question:    "A drawing made of lines only, with no colour, is a:",
		Options:     [4]string{"Sketch", "Poster", "Collage", "Mosaic"},
		AnswerIndex: 0,
		Explanation: "Sketches capture shape with lines."},
	{SubjectCode: "CCA-P", Band: "primary", Term: 1,
		Question:    "Which of these is a musical instrument?",
		Options:     [4]string{"Guitar", "Basket", "Kettle", "Broom"},
		AnswerIndex: 0,
		Explanation: "Guitars make music with vibrating strings."},
	{SubjectCode: "CCA-P", Band: "primary", Term: 2,
		Question:    "Mixing blue and yellow paint gives:",
		Options:     [4]string{"Green", "Brown", "Pink", "Grey"},
		AnswerIndex: 0,
		Explanation: "Blue plus yellow makes green."},
	{SubjectCode: "CCA-P", Band: "primary", Term: 2,
		Question:    "Traditional Nigerian cloth decorated with wax patterns is:",
		Options:     [4]string{"Ankara", "Denim", "Silk", "Wool"},
		AnswerIndex: 0,
		Explanation: "Ankara prints are popular across Nigeria."},
	{SubjectCode: "CCA-P", Band: "primary", Term: 2,
		Question:    "A person who writes songs is a:",
		Options:     [4]string{"Composer", "Cook", "Carpenter", "Cobbler"},
		AnswerIndex: 0,
		Explanation: "Composers create music and lyrics."},
	{SubjectCode: "CCA-P", Band: "primary", Term: 3,
		Question:    "Clay pots and woven baskets are examples of Nigerian:",
		Options:     [4]string{"Crafts", "Crops", "Games", "Roads"},
		AnswerIndex: 0,
		Explanation: "Crafts carry culture through handmade objects."},
	{SubjectCode: "CCA-P", Band: "primary", Term: 3,
		Question:    "Moving the body in time with music is called:",
		Options:     [4]string{"Dancing", "Drawing", "Reading", "Sleeping"},
		AnswerIndex: 0,
		Explanation: "Dance expresses rhythm through movement."},
	{SubjectCode: "CCA-P", Band: "primary", Term: 3,
		Question:    "The lines at the top and bottom of a music staff are drawn:",
		Options:     [4]string{"Horizontally", "Vertically", "In circles", "Randomly"},
		AnswerIndex: 0,
		Explanation: "The staff has five horizontal lines."},
}
