'use client';

// Report-card PDF, strict black & white: school logo + name header,
// student block, the subject table, overall average and remarks. One
// file per student - the same doctrine as the per-topic note export.

import { jsPDF } from 'jspdf';
import { termLabel, type ResultSheet } from '@/lib/school';

export async function downloadReportCardPDF(sheet: ResultSheet): Promise<void> {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();
  const M = 48;
  let y = M;

  // header band
  doc.setFillColor(0, 0, 0);
  doc.rect(0, 0, W, 8, 'F');

  // logo (data URL PNG from the school profile)
  if (sheet.schoolLogoUrl?.startsWith('data:image')) {
    try {
      doc.addImage(sheet.schoolLogoUrl, 'PNG', M, y, 56, 56);
    } catch {
      /* a bad image never blocks the report card */
    }
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text(sheet.schoolName || 'Report Card', M + (sheet.schoolLogoUrl ? 70 : 0), y + 22);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`${sheet.className} - ${termLabel(sheet.term)} - ${sheet.session || ''}`, M + (sheet.schoolLogoUrl ? 70 : 0), y + 40);

  y += 78;

  // student block
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text(sheet.studentName, M, y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  if (sheet.admissionNo) doc.text(`Admission no: ${sheet.admissionNo}`, W - M, y, { align: 'right' });
  y += 14;
  doc.text(
    sheet.status === 'finalized' ? 'Finalized result' : 'Draft result (not yet finalized)',
    M,
    y,
  );
  y += 18;

  // table head
  doc.setFillColor(0, 0, 0);
  doc.rect(M, y, W - 2 * M, 20, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  const cols = [
    { x: M + 6, w: 150, label: 'Subject' },
    { x: M + 156, w: 42, label: 'CA1' },
    { x: M + 198, w: 42, label: 'CA2' },
    { x: M + 240, w: 42, label: 'Exam' },
    { x: M + 282, w: 42, label: 'Total' },
    { x: M + 324, w: 40, label: 'Grade' },
    { x: M + 364, w: 40, label: 'Pos' },
    { x: M + 404, w: 46, label: 'Avg' },
  ];
  for (const c of cols) doc.text(c.label, c.x, y + 14);
  doc.setTextColor(0, 0, 0);
  y += 20;

  // rows
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  for (const it of sheet.items) {
    if (y > 760) {
      doc.addPage();
      y = M;
    }
    const rowVals = [
      it.subjectName.slice(0, 30),
      String(it.ca1 ?? 0),
      String(it.ca2 ?? 0),
      String(it.exam ?? 0),
      String(it.total ?? 0),
      it.grade || '',
      it.position ? String(it.position) : '-',
      it.classAverage ? String(it.classAverage) : '-',
    ];
    rowVals.forEach((v, i) => doc.text(v, cols[i].x, y + 12));
    y += 20;
    doc.setDrawColor(210, 210, 210);
    doc.line(M, y, W - M, y);
  }

  y += 16;
  const total = sheet.items.reduce((a, b) => a + (b.total || 0), 0);
  const count = sheet.items.length || 1;
  const average = Math.round((total / count) * 100) / 100;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text(`Overall average: ${average} (${sheet.items.length} subject${sheet.items.length === 1 ? '' : 's'})`, M, y);
  y += 22;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  if (sheet.teacherReport) {
    const lines = doc.splitTextToSize(`Teacher's remark: ${sheet.teacherReport}`, W - 2 * M);
    doc.text(lines, M, y);
    y += lines.length * 13 + 6;
  }
  if (sheet.principalReport) {
    const lines = doc.splitTextToSize(`Principal's remark: ${sheet.principalReport}`, W - 2 * M);
    doc.text(lines, M, y);
    y += lines.length * 13 + 6;
  }
  if (sheet.pin) {
    y += 6;
    doc.setFont('helvetica', 'bold');
    doc.text(`Result-check PIN: ${sheet.pin}`, M, y);
    doc.setFont('helvetica', 'normal');
    y += 14;
    doc.setFontSize(8.5);
    doc.text('Students check this PIN on the Renance result checker.', M, y);
  }

  // footer
  doc.setFontSize(8.5);
  doc.setTextColor(120, 120, 120);
  doc.text('Generated by Renance - Your Guide to Academic Success', W / 2, 812, { align: 'center' });

  const safe = sheet.studentName.replace(/[^a-z0-9]+/gi, '-').toLowerCase();
  doc.save(`${safe || 'report'}-${termLabel(sheet.term).toLowerCase().replace(' ', '-')}-${sheet.session || ''}.pdf`);
}
