#!/usr/bin/env python3
"""Primary 4 scheme data: ten subjects, three terms, ten weeks each."""

PRIMARY_4 = {
    "English Studies": {
        1: [
            ("Revision of primary three work", "Phonics and grammar warm up\nReading fluency drill"),
            ("Comprehension: the new pupil", "Read the passage\nAnswer literal questions"),
            ("Grammar: common and proper nouns", "Sort the nouns\nCapital letters for names"),
            ("Grammar: singular and plural", "Regular and irregular plurals\nChange the words"),
            ("Vocabulary: new words in context", "Meaning from the passage\nSentence making"),
            ("Composition: describing my school", "Paragraph plan\nWrite four sentences"),
            ("Phonics: consonant digraphs", "sh, ch, th, ph words\nSort and read"),
            ("Reading: using the dictionary", "Guide words practice\nFind the meanings"),
            ("Handwriting and dictation", "Cursive practice\nParagraph dictation"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Comprehension: helping at home", "Read the passage\nAnswer questions in full sentences"),
            ("Grammar: pronouns", "He, she, it, they\nReplace nouns with pronouns"),
            ("Grammar: present and past tense", "Change the tense\nTime words practice"),
            ("Grammar: adjectives", "Describing words in sentences\nComparatives: taller, tallest"),
            ("Vocabulary: compound words", "Classroom, football, cupboards\nBuild and explain"),
            ("Composition: a letter to my cousin", "Friendly letter format\nGreeting, body, closing"),
            ("Punctuation", "Full stop, comma, question mark\nPunctuate the passage"),
            ("Reading: fluency and expression", "Read aloud in pairs\nReader's theatre"),
            ("Story writing: my best day", "Beginning, middle, end\nWrite and read aloud"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Comprehension: the market day", "Read the passage\nInference questions"),
            ("Grammar: adverbs", "Quickly, gently, well\nUse adverbs in sentences"),
            ("Grammar: prepositions", "Place and time prepositions\nFill the gaps"),
            ("Grammar: conjunctions", "and, but, or, because\nJoin the sentences"),
            ("Vocabulary: synonyms and antonyms", "Word pairs\nWord ladder game"),
            ("Composition: my favourite food", "Descriptive paragraph\nSteps and reasons"),
            ("Letter writing: formal style", "The head teacher's letter\nSimple formal letter"),
            ("Poetry: simple rhymes", "Read a children's poem\nRhyming words hunt"),
            ("Drama: short scene", "Role play a market scene\nSpeak with expression"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Mathematics": {
        1: [
            ("Revision of numbers to 500", "Count, read, write\nPlace value drill"),
            ("Numbers to 1000", "Thousands place\nRead and write numbers"),
            ("Place value to 1000", "Expanded form\nBuild the number"),
            ("Addition to 1000 without carrying", "Column addition\nQuick checks"),
            ("Addition to 1000 with carrying", "Carry tens and hundreds\nWord problems"),
            ("Subtraction to 1000", "Borrowing practice\nCheck by addition"),
            ("Multiplication tables 2 to 5", "Recite and apply\nMissing factors"),
            ("Multiplication by one digit", "Column method\nWord problems"),
            ("Division by one digit", "Sharing and grouping\nRemainder talk"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Factors and multiples", "Find the factors\nList the multiples"),
            ("Common multiples and LCM basics", "List and compare\nLowest common multiple"),
            ("Fractions: equivalent fractions", "Half equals two quarters\nFraction wall work"),
            ("Fractions: addition with same denominator", "Add the parts\nSimplify the answer"),
            ("Decimals: tenths", "Fraction to decimal\nPlace value of tenths"),
            ("Money: addition and subtraction", "Naira and kobo sums\nShopping problems"),
            ("Length: kilometres and metres", "Convert and compare\nRoad distance problems"),
            ("Perimeter of rectangles", "Add the sides\nMeasure and compute"),
            ("Area by counting squares", "Cover the surface\nSquare units"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Multiplication by two digits", "Column multiplication\nEstimate first"),
            ("Division with remainders", "Long division steps\nCheck by multiplying"),
            ("Word problems: four operations", "Choose the operation\nSolve and explain"),
            ("Fractions: of quantities", "Half of 24\nFraction of a group"),
            ("Decimals: hundredths", "Read and write decimals\nCompare decimals"),
            ("Capacity and weight problems", "Litres and kilograms\nMixed word problems"),
            ("Time: 24 hour clock", "Morning and afternoon\nTimetable reading"),
            ("Lines and angles basics", "Straight, right angle\nFind angles around us"),
            ("Data: simple bar charts", "Collect and draw\nRead the chart"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Basic Science and Technology": {
        1: [
            ("Living things: characteristics", "Feeding, growth, movement\nClassify around us"),
            ("The human digestive system", "Mouth to stomach\nFollow the food journey"),
            ("Teeth: types and care", "Incisors and molars\nBrushing habits"),
            ("Food and energy", "Energy giving foods\nBalanced meal plate"),
            ("Common diseases", "Malaria and cholera\nPrevention habits"),
            ("Plants: photosynthesis basics", "Leaves make food\nSun, water, air"),
            ("Seed germination", "Conditions for growth\nBean jar experiment"),
            ("Insects: useful and harmful", "Bees and mosquitoes\nSort the insects"),
            ("The water cycle", "Evaporation to rain\nDraw the cycle"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Matter: solid, liquid, gas", "Sort the materials\nChange of state talk"),
            ("Mixtures and separation basics", "Sand and water\nSieving and filtering"),
            ("Energy: sources and uses", "Sun, food, fuel, battery\nSort the sources"),
            ("Light: sources and shadows", "Transparent and opaque\nShadow games"),
            ("Reflection of light", "Mirrors and shiny things\nBounce the light"),
            ("Sound: production and hearing", "Vibrations make sound\nLoud and soft"),
            ("Simple machines: levers", "Seesaw, scissors, wheelbarrow\nParts of a lever"),
            ("Simple machines: pulleys", "Well pulley demo\nLift with less effort"),
            ("Friction", "Rough and smooth surfaces\nUseful and wasteful friction"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Electricity: simple circuits", "Cell, wire, bulb\nMake the bulb light"),
            ("Conductors and insulators", "Test the materials\nSort and explain"),
            ("Safety with electricity", "Wet hands and sockets\nSafety rules"),
            ("Magnetism basics", "Magnetic materials\nAttract and repel"),
            ("Uses of magnets", "Compass and fridge magnets\nEveryday uses"),
            ("Technology: products around us", "Tools at home and school\nName the technology"),
            ("Building: materials and tools", "Cement, wood, iron\nName the tools"),
            ("Designing a simple product", "Plan and make a holder\nEvaluate my product"),
            ("Maintenance of machines", "Oil and clean tools\nWhy maintain"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Information Technology": {
        1: [
            ("Parts of a computer", "Monitor, keyboard, mouse, CPU\nLabel the parts"),
            ("Care of the computer", "Dust, water, food away\nClean habits"),
            ("Using the mouse", "Click and double click\nMove and point games"),
            ("Using the keyboard", "Letters and numbers keys\nType my name"),
            ("Opening a drawing program", "Open and explore\nDraw simple shapes"),
            ("Drawing with shapes", "Circle, square, line tools\nDraw a house"),
            ("Saving my work", "Save to the folder\nFind my file again"),
            ("Typing simple sentences", "Two hands on the keys\nType and print"),
            ("Computer in the bank and school", "ICT around us\nName the uses"),
            ("Revision and assessment", "Term work review\nPractical quiz"),
        ],
        2: [
            ("Revision of computer parts", "Label and match\nFunctions recap"),
            ("Input and output devices", "Keyboard in, monitor out\nSort the devices"),
            ("The desktop and icons", "Open programs from icons\nArrange my window"),
            ("Typing paragraphs", "Capital and full stop keys\nType a short story"),
            ("Editing text", "Delete and backspace\nCorrect my work"),
            ("Font and colour", "Change size and colour\nMake a title page"),
            ("Printing my work", "Print preview\nPrint my story"),
            ("Internet: safe searching basics", "Ask an adult\nSearch for a topic"),
            ("Email for children basics", "What is an email\nWrite to the class"),
            ("Revision and assessment", "Term work review\nPractical quiz"),
        ],
        3: [
            ("Files and folders", "Create and rename\nOrganise my work"),
            ("Tables in a word processor", "Insert a table\nFill the rows"),
            ("Pictures in documents", "Insert clip art\nIllustrate my story"),
            ("Presentation basics", "Make three slides\nPresent to the class"),
            ("Spreadsheet basics", "Cells and rows\nMake a marks table"),
            ("Simple calculations in spreadsheets", "Add the cells\nTotal my scores"),
            ("Charts from data", "Make a bar chart\nRead my chart"),
            ("Internet safety rules", "Never share my name\nTell an adult"),
            ("Technology careers", "Engineer, programmer, designer\nTalk about the jobs"),
            ("Revision and assessment", "Year work review\nEnd of year practical"),
        ],
    },
    "National Values Education": {
        1: [
            ("My rights as a child", "Name and shelter rights\nSay my rights"),
            ("My duties at school", "Learn and obey rules\nDo my duties"),
            ("Community leaders", "Kings and chiefs\nTheir roles"),
            ("Government services", "Hospitals and schools\nWho provides them"),
            ("Patriotism", "Love of country\nPatriotic songs"),
            ("National consciousness", "Nigeria my country\nStates on the map"),
            ("Avoiding dishonesty", "Why people cheat\nHonesty stories"),
            ("Contentment", "Be happy with what you have\nGreed stories"),
            ("Safety in the community", "Stranger danger rules\nReport to adults"),
            ("Revision and assessment", "Term work review\nOral quiz"),
        ],
        2: [
            ("National values: unity", "Unity in diversity\nPeoples of Nigeria"),
            ("National values: peace", "Peaceful living\nConflict resolution"),
            ("Democracy: simple meaning", "Rule by the people\nClass election demo"),
            ("Voting and choice", "Choose a class captain\nFree and fair"),
            ("The constitution: simple idea", "Rules of the nation\nRights it gives"),
            ("Citizenship duties", "Pay taxes, obey laws\nBe a good citizen"),
            ("Corruption: say no", "Effects of bribery\nReport bad behaviour"),
            ("Hard work and integrity", "Diligence stories\nIntegrity pays"),
            ("Environment: my responsibility", "Keep Nigeria clean\nSanitation habits"),
            ("Revision and assessment", "Term work review\nOral quiz"),
        ],
        3: [
            ("Family life: roles and respect", "Each member matters\nRespect all roles"),
            ("Marriage as an institution", "Why families form\nHealthy family talk"),
            ("Cultural heritage", "Nigerian cultures\nRespect all cultures"),
            ("Traditional rulers", "Roles in the community\nRespect for elders"),
            ("Religion and peace", "Worship without fighting\nTolerance talk"),
            ("Discrimination: say no", "Treat all fairly\nKindness to all"),
            ("Drug abuse basics", "Harmful substances\nSay no to drugs"),
            ("Peer pressure", "Choose my company\nRefuse bad pressure"),
            ("Volunteering", "Help without pay\nCommunity service"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Cultural and Creative Arts": {
        1: [
            ("Revision of elements of art", "Line, shape, colour\nIdentify in pictures"),
            ("Drawing: human figure", "Head and body proportions\nDraw my friend"),
            ("Colour wheel basics", "Primary colours\nMix secondary colours"),
            ("Rhythm patterns", "Echo rhythm games\nPlay in groups"),
            ("Nigerian instruments: drums", "Types of drums\nSimple drum patterns"),
            ("Craft: wire work", "Bend and shape\nMake simple figures"),
            ("Traditional dances", "Dance of my area\nLearn the steps"),
            ("Drama: storytelling on stage", "Narrate and act\nFolk tale play"),
            ("Making musical shakers", "Fill and decorate\nPlay with songs"),
            ("Revision and assessment", "Term work review\nDisplay"),
        ],
        2: [
            ("Still life drawing", "Arrange objects\nDraw what I see"),
            ("Perspective basics", "Near and far\nSimple depth in drawing"),
            ("Tie and dye: patterns", "Tying techniques\nDye the cloth"),
            ("Music notation: staff basics", "Lines and spaces\nName the notes"),
            ("Singing in parts", "Melody and harmony tries\nTwo group singing"),
            ("Craft: papier mache bowls", "Layer and dry\nPaint the bowl"),
            ("Cultural festivals in Nigeria", "Durbar and new yam\nTalk and draw"),
            ("Drama: radio play", "Voice acting only\nRecord and listen"),
            ("Choreography basics", "Plan simple moves\nDance to a song"),
            ("Revision and assessment", "Term work review\nDisplay"),
        ],
        3: [
            ("Landscapes", "Sky and ground lines\nPaint my village"),
            ("Printmaking basics", "Leaf and sponge prints\nPrint a pattern"),
            ("Clay: pinch and coil pots", "Build a pot\nDecorate and dry"),
            ("Music composition basics", "Make a four beat rhythm\nPerform my rhythm"),
            ("Nigerian national music", "Anthem and pledge songs\nSing with pride"),
            ("Costume and make up", "Design for a play\nApply simple make up"),
            ("Stage craft: props", "Make simple props\nSet the stage"),
            ("Dance drama production", "Plan and perform\nFull class production"),
            ("Exhibition and display", "Mount my works\nExplain my art"),
            ("Revision and assessment", "Year work review\nEnd of year display"),
        ],
    },
    "Pre-Vocational Studies": {
        1: [
            ("Home economics: the family house", "Rooms in the house\nUses of each room"),
            ("Cleaning materials", "Brooms and detergents\nChoose and use"),
            ("Cooking terms", "Boil, fry, roast\nMatch to foods"),
            ("Kitchen utensils", "Pots and ladles\nName and use"),
            ("Agriculture: farm tools", "Cutlass and hoe\nCare of tools"),
            ("Crops we grow", "Cereals and legumes\nSort the crops"),
            ("Planting maize", "Spacing and depth\nPlant the demo plot"),
            ("Animal husbandry: goats", "Housing and feeding\nDaily routine"),
            ("Food nutrients basics", "Energy and protein\nSort the foods"),
            ("Revision and assessment", "Term work review\nPractical quiz"),
        ],
        2: [
            ("Laundry: washing cottons", "Soak, wash, rinse, dry\nWash my handkerchief"),
            ("Ironing basics", "Safe ironing\nIron under supervision"),
            ("Simple stitches", "Tacking and running\nSew a sampler"),
            ("Mending clothes", "Sew loose seams\nReplace a button"),
            ("Agriculture: transplanting", "Seedling care\nTransplant tomatoes"),
            ("Weeds and pests", "Common farm weeds\nSimple control"),
            ("Manure and compost", "Make compost\nApply to beds"),
            ("Poultry: layers", "Feeding and eggs\nRecord keeping"),
            ("Food storage", "Dry and store grains\nStorage pests"),
            ("Revision and assessment", "Term work review\nPractical quiz"),
        ],
        3: [
            ("Food preparation: soups", "Ingredients for egusi\nWatch the cooking"),
            ("Serving food", "Table manners\nSet and serve"),
            ("Baking: simple biscuits", "Measure and mix\nBake and taste"),
            ("Sewing: simple apron", "Cut and sew\nFinish the edges"),
            ("Agriculture: harvesting", "When to harvest\nHarvest the plot"),
            ("Processing crops", "Shell and winnow\nGrind the maize"),
            ("Marketing produce", "Weigh and price\nSell the harvest"),
            ("Animal products", "Meat, milk, eggs\nUses of products"),
            ("Entrepreneurship basics", "Small sales ideas\nCount the profit"),
            ("Revision and assessment", "Year work review\nEnd of year practical"),
        ],
    },
    "Physical and Health Education": {
        1: [
            ("Revision of athletics basics", "Track events recap\nWarm up drills"),
            ("Sprint starts", "Crouch start practice\nReact to the whistle"),
            ("Relay baton exchange", "Down sweep pass\nTeam practice"),
            ("Football: passing and control", "Inside foot pass\nTrap the ball"),
            ("Basketball: dribbling", "Low dribble drills\nChange of pace"),
            ("Volleyball: the serve", "Under arm serve\nServe to target"),
            ("Health: personal hygiene", "Daily cleaning routine\nGrooming kit"),
            ("Nutrition and exercise", "Eat to play\nBalanced diet plate"),
            ("Posture correction", "Standing and sitting well\nSimple drills"),
            ("Revision and assessment", "Term work review\nSkills display"),
        ],
        2: [
            ("Athletics: middle distance", "800 metre pace talk\nRun and time"),
            ("Long jump: full approach", "Run, take off, land\nMeasure and record"),
            ("High jump: scissors technique", "Approach curve\nScissors over the bar"),
            ("Handball: dribbling and passing", "Bounce and pass drills\nSmall game"),
            ("Table tennis: forehand drive", "Grip and stance\nDrive practice"),
            ("Traditional games", "Board and field games\nPlay and teach"),
            ("Health: first aid basics", "D R ABC basics\nSimple bandaging"),
            ("Diseases: communicable", "Spread and prevention\nHygiene habits"),
            ("Fitness components", "Strength and endurance\nTest my fitness"),
            ("Revision and assessment", "Term work review\nSkills display"),
        ],
        3: [
            ("Athletics: hurdles basics", "Lead leg practice\nSimple hurdle drills"),
            ("Gymnastics: rolls", "Forward and backward roll\nSafe mat work"),
            ("Gymnastics: balances", "Partner balances\nHold and count"),
            ("Football: shooting and goalkeeping", "Aim and save\nSmall sided game"),
            ("Basketball: passing and shooting", "Chest pass\nSet shot practice"),
            ("Volleyball: the rally", "Serve and return\nKeep the ball up"),
            ("Health: drug awareness", "Harmful substances\nSay no to drugs"),
            ("Environment and health", "Clean water and air\nSanitation habits"),
            ("Sportsmanship", "Win humbly, lose with grace\nFair play talk"),
            ("Revision and assessment", "Year work review\nEnd of year display"),
        ],
    },
    "Christian Religious Studies": {
        1: [
            ("God speaks to us", "Through the Bible\nListen and obey"),
            ("The call of Samuel", "Speak Lord, I listen\nGod calls children too"),
            ("David the shepherd boy", "Faithful in small things\nCare for my duties"),
            ("David and Goliath", "Courage with God\nFace my giants"),
            ("Solomon asks for wisdom", "Wisdom is best\nAsk God for wisdom"),
            ("The wisdom of Solomon", "Two mothers story\nWise decisions"),
            ("Elijah trusts God", "Ravens feed him\nGod provides"),
            ("Elisha helps others", "The widow's oil\nGod multiplies little"),
            ("Jonah learns obedience", "Run away and return\nObey God's call"),
            ("Revision and assessment", "Term work review\nStories and songs"),
        ],
        2: [
            ("Jesus: the promised saviour", "Old promises fulfilled\nHope of the world"),
            ("John the Baptist prepares the way", "Repent and prepare\nPrepare my heart"),
            ("The temptation of Jesus", "Jesus used the word\nOvercome temptation"),
            ("The beatitudes", "Blessed are the meek\nLive the blessings"),
            ("The Lord's prayer", "Teach us to pray\nPray with meaning"),
            ("The parable of the sower", "Seed on soils\nGood soil heart"),
            ("The lost sheep", "The shepherd searches\nGod seeks me"),
            ("The prodigal son", "Return and forgive\nGod welcomes back"),
            ("The widow's mite", "Give with the heart\nMy giving matters"),
            ("Revision and assessment", "Term work review\nStories and songs"),
        ],
        3: [
            ("The early church", "Pentecost power\nThe Spirit helps us"),
            ("Peter heals the lame man", "In Jesus' name\nFaith in action"),
            ("Stephen the faithful", "Bold witness\nStand for truth"),
            ("Philip and the Ethiopian", "Share the good news\nTell others"),
            ("Saul meets Jesus", "Road to Damascus\nGod changes hearts"),
            ("Paul the missionary", "Journeys for the gospel\nServe with purpose"),
            ("Paul in prison", "Songs at midnight\nPraise in trials"),
            ("Love: the greatest command", "1 Corinthians 13 talk\nWalk in love"),
            ("The fruit of the spirit", "Nine fruit list\nBear good fruit"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Islamic Religious Studies": {
        1: [
            ("Surah Al-Muzzammil", "Recite together\nStand in night prayer"),
            ("Surah Al-Muddaththir", "Recite and memorise\nCall to the mission"),
            ("The first revelation", "Cave Hira and Jibril\nRead in the name"),
            ("The early Muslims", "First believers\nSteadfastness"),
            ("Salat al-Jama'ah", "Praying in congregation\nRows and order"),
            ("Du'a: entering and leaving home", "Home du'as\nRecite with meaning"),
            ("Asma ul Husna: Allah's names", "Ar-Rahman, Ar-Rahim\nCall on Allah"),
            ("Charity: sadaqah", "Give always\nEven a smile is charity"),
            ("Brotherhood of the companions", "Support each other\nLove for others"),
            ("Revision and assessment", "Term work review\nRecitations"),
        ],
        2: [
            ("Surah Al-Qalam 1 to 10", "Recite together\nThe pen and knowledge"),
            ("Surah Al-Haqqah 1 to 10", "Recite and memorise\nTruth of the hereafter"),
            ("Life of the Prophet in Makkah", "Calling to Islam\nPatience under harm"),
            ("The boycott years", "Hardship in the valley\nEndurance lessons"),
            ("Salat: sunnah prayers", "Rawatib recitation\nFollow the Prophet"),
            ("Du'a: travel du'a", "Journey supplication\nRecite before trips"),
            ("Asma ul Husna: more names", "Al-Malik, Al-Quddus\nMeanings and use"),
            ("Trust in Allah: tawakkul", "Birds of the sky\nWork and trust"),
            ("Truthfulness of the companions", "Abu Bakr the truthful\nHonesty always"),
            ("Revision and assessment", "Term work review\nRecitations"),
        ],
        3: [
            ("Surah Al-Jinn 1 to 5", "Recite together\nHidden creation"),
            ("Surah Yasin 1 to 12", "Recite and memorise\nHeart of the Qur'an"),
            ("The Hijrah journey", "Plan and departure\nTrust in action"),
            ("Life in Madinah", "Building the mosque\nCommunity building"),
            ("Salat al-Jumu'ah", "Friday prayer basics\nCleanliness and early arrival"),
            ("Du'a: forgiveness", "Istighfar words\nSeek pardon daily"),
            ("Asma ul Husna: more names", "As-Salam, Al-Mu'min\nLive the meanings"),
            ("The Charter of Madinah", "Peace with neighbours\nTolerance lessons"),
            ("Gratitude: shukr", "Thank Allah always\nCount blessings"),
            ("Revision and assessment", "Year work review\nEnd of year recitations"),
        ],
    },
}
