#!/usr/bin/env python3
"""Primary 5 scheme data: ten subjects, three terms, ten weeks each."""

PRIMARY_5 = {
    "English Studies": {
        1: [
            ("Revision of primary four work", "Grammar and comprehension warm up\nReading fluency drill"),
            ("Comprehension: the football match", "Read the passage\nLiteral and inference questions"),
            ("Grammar: countable and uncountable nouns", "Much and many\nUse in sentences"),
            ("Grammar: future tense", "Will and going to\nTalk about plans"),
            ("Vocabulary: word families", "Care, careful, carefully\nBuild word families"),
            ("Composition: informal letter", "Letter to my uncle\nFormat and content"),
            ("Phonics: silent letters", "knee, write, island\nRead and spell"),
            ("Dictionary and thesaurus use", "Guide words and synonyms\nResearch practice"),
            ("Summary writing basics", "Find the main ideas\nWrite in own words"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Comprehension: the traffic warden", "Read the passage\nAnswer in full sentences"),
            ("Grammar: active sentences", "Subject and verb agreement\nCorrect the errors"),
            ("Grammar: adverbials of time and place", "Where and when words\nUse in paragraphs"),
            ("Grammar: question tags", "It is hot, is it not\nForm and use"),
            ("Vocabulary: idioms for children", "Rain cats and dogs talk\nMeaning and use"),
            ("Composition: formal letter", "Letter to the head teacher\nTwo addresses format"),
            ("Punctuation: apostrophe and quotation marks", "Possession and speech\nPunctuate dialogue"),
            ("Reading: comprehension of adverts", "Read a poster advert\nFind key details"),
            ("Story writing: adventure", "Plan with a map\nWrite and illustrate"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Comprehension: the new road", "Read the passage\nVocabulary in context"),
            ("Grammar: reported speech basics", "He said he was tired\nChange the speech"),
            ("Grammar: conditional sentences basics", "If it rains, we stay\nComplete the sentences"),
            ("Grammar: comparison of adverbs", "Faster, most quickly\nCompare actions"),
            ("Vocabulary: proverbs", "Nigerian proverbs\nMeaning and use"),
            ("Composition: descriptive writing", "Describe the market\nSenses in description"),
            ("Formal letter: application basics", "Letter for permission\nPolite requests"),
            ("Poetry: imagery", "Read a nature poem\nFind the pictures in words"),
            ("Drama and dialogue writing", "Write a dialogue\nPerform the scene"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Mathematics": {
        1: [
            ("Revision of numbers to 1000", "Read and write\nPlace value drill"),
            ("Numbers to 10 000", "Ten thousands place\nRead and write"),
            ("Roman numerals", "I to XX\nRead and write dates"),
            ("Addition to 10 000", "Column addition\nWord problems"),
            ("Subtraction to 10 000", "Borrowing across zeros\nWord problems"),
            ("Multiplication by two digits", "Column method\nEstimate and check"),
            ("Division by two digits", "Long division steps\nCheck answers"),
            ("HCF and LCM", "Common factors\nCommon multiples"),
            ("Fractions: ordering and comparing", "Like and unlike fractions\nOrder on a line"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Fractions: addition of unlike fractions", "Find common denominators\nAdd and simplify"),
            ("Fractions: subtraction", "Borrowing with fractions\nWord problems"),
            ("Decimals: addition and subtraction", "Line the points\nMoney problems"),
            ("Decimals: multiplication", "Multiply by ten\nDecimal products"),
            ("Percentage basics", "Percent of numbers\nDiscounts and marks"),
            ("Ratio and proportion basics", "Compare quantities\nSharing in ratio"),
            ("Average (mean)", "Sum and divide\nFind the average age"),
            ("Profit and loss basics", "Cost and selling price\nSimple profit sums"),
            ("Money: interest basics", "Simple interest ideas\nSavings talk"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Geometry: angles on lines", "Acute, right, obtuse\nMeasure with protractor"),
            ("Angles in a triangle", "Sum of angles\nFind the missing angle"),
            ("Perimeter and area of rectangles", "Formulas in use\nComposite shapes"),
            ("Area of triangles", "Half base times height\nCalculate and apply"),
            ("Volume of cuboids", "Length by width by height\nCount unit cubes"),
            ("Capacity and volume problems", "Litres and cubic units\nWord problems"),
            ("Speed, distance and time basics", "Distance over time\nSimple journeys"),
            ("Data: pie charts basics", "Fractions of a circle\nRead and draw"),
            ("Probability basics", "Likely and unlikely\nSimple experiments"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Basic Science and Technology": {
        1: [
            ("Human body: the circulatory system", "Heart and blood flow\nPulse counting"),
            ("The respiratory system", "Breathing in and out\nClean air importance"),
            ("The excretory system", "Kidneys and skin\nWaste removal talk"),
            ("The nervous system basics", "Brain and nerves\nReflex actions"),
            ("Drugs and the body", "Useful and harmful drugs\nFollow prescriptions"),
            ("Plant reproduction: flowers", "Pollination basics\nParts of a flower"),
            ("Seed dispersal", "Wind, water, animals\nMatch seeds to agents"),
            ("Farming and crop rotation", "Why rotate crops\nPlan a rotation"),
            ("Erosion basics", "Water and wind erosion\nControl methods"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Matter: changes of state", "Melting and freezing\nHeating and cooling"),
            ("Physical and chemical changes", "Rusting and burning\nSort the changes"),
            ("Energy conversion", "Electric to light\nTrace the conversions"),
            ("Heat transfer", "Conduction in metals\nEveryday examples"),
            ("Light: refraction basics", "Bending of light\nStraw in water demo"),
            ("Sound: pitch and volume", "Frequency basics\nBottle orchestra"),
            ("Friction: advantages and reduction", "Lubricants and wheels\nDesign a test"),
            ("Simple machines: gears and wheels", "Bicycle gears\nMechanical advantage talk"),
            ("Technology: levers in the body", "Arm as a lever\nMuscles and joints"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Electricity: series circuits", "Two bulbs in a row\nCompare brightness"),
            ("Electricity: parallel circuits", "Independent bulbs\nHouse wiring talk"),
            ("Electromagnets", "Coil and nail\nMake and test"),
            ("Electronics basics", "Diodes and LEDs\nSimple components"),
            ("Space and the solar system", "Planets in order\nModel the system"),
            ("The earth and its movement", "Day and night\nSeasons talk"),
            ("The moon and eclipses", "Phases of the moon\nEclipse safety"),
            ("Satellites and communication", "How TV signals travel\nUses of satellites"),
            ("Design project: model bridge", "Plan and build\nTest the strength"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Information Technology": {
        1: [
            ("Revision of word processing", "Format a document\nSave and print"),
            ("The operating system", "What Windows does\nFiles and windows"),
            ("Typing speed practice", "Home row discipline\nTimed drills"),
            ("Inserting tables and shapes", "Make a time table\nDesign a card"),
            ("Headers and footers", "Page numbers\nTitles on every page"),
            ("Spell check tools", "Find the red lines\nCorrect my work"),
            ("Presentation: slide design", "Layouts and themes\nDesign my slides"),
            ("Adding animation", "Simple transitions\nPresent with effects"),
            ("Presenting to an audience", "Speak and click\nClass presentation"),
            ("Revision and assessment", "Term work review\nPractical quiz"),
        ],
        2: [
            ("Spreadsheets: rows and columns", "Navigate the sheet\nEnter data"),
            ("Formulas: sum and average", "Add ranges\nAverage the marks"),
            ("Charts: bar and pie", "Create from data\nLabel and read"),
            ("Sorting and filtering", "Arrange my data\nFind the biggest"),
            ("The internet: browsers", "Address bar basics\nSearch safely"),
            ("Research on the internet", "Find facts for school\nRecord the sources"),
            ("Email: compose and reply", "Write clear emails\nAttach a file"),
            ("Cloud folders basics", "Save and share\nAccess my work"),
            ("Digital citizenship", "Be kind online\nReport bad content"),
            ("Revision and assessment", "Term work review\nPractical quiz"),
        ],
        3: [
            ("Coding: what is a program", "Follow and write steps\n unplugged activities"),
            ("Block coding basics", "Move the sprite\nSimple animations"),
            ("Loops in coding", "Repeat blocks\nDance patterns"),
            ("Conditions in coding", "If this then that\nQuiz game build"),
            ("Debugging", "Find the error\nFix my program"),
            ("Robotics talk", "Sensors and machines\nHow robots help"),
            ("Internet safety: passwords", "Strong passwords\nKeep them secret"),
            ("Multimedia projects", "Sound and pictures\nMake a short video plan"),
            ("Technology and society", "Benefits and dangers\nBalanced use talk"),
            ("Revision and assessment", "Year work review\nEnd of year project"),
        ],
    },
    "National Values Education": {
        1: [
            ("Democracy in the classroom", "Elections and choice\nClass government"),
            ("The arms of government", "Executive, legislature, judiciary\nSimple duties"),
            ("The rule of law", "No one above the law\nFair treatment"),
            ("Rights and duties of citizens", "Match rights to duties\nCitizen talk"),
            ("National symbols: the coat of arms", "Parts and meanings\nDraw and label"),
            ("National honours", "Why we honour people\nHeroes of Nigeria"),
            ("Corruption and its effects", "How bribery harms\nSay no always"),
            ("Community development", "Self help projects\nMy contribution"),
            ("Media and information", "Radio, TV, newspapers\nUse with care"),
            ("Revision and assessment", "Term work review\nOral quiz"),
        ],
        2: [
            ("Civic values: honesty in public life", "Leaders we trust\nIntegrity stories"),
            ("Human rights: child rights act", "Rights of Nigerian children\nKnow my rights"),
            ("Responsibilities of leaders", "Serve the people\nAccountability talk"),
            ("Voting procedures", "From registration to vote\nFree and fair"),
            ("Peace and conflict resolution", "Dialogue first\nMediation practice"),
            ("Security awareness", "Security agencies\nReport and stay safe"),
            ("Environmental protection", "Deforestation talk\nPlant trees projects"),
            ("Global citizenship", "Nigeria and the world\nUN basics"),
            ("National economy basics", "Resources of Nigeria\nUse them well"),
            ("Revision and assessment", "Term work review\nOral quiz"),
        ],
        3: [
            ("Family health and values", "Healthy home habits\nValues at home"),
            ("Gender respect", "Equal worth\nRespect everyone"),
            ("Cultural diversity in Nigeria", "Many peoples one nation\nCelebrate cultures"),
            ("Ethnic tolerance", "No tribal hatred\nUnity in diversity"),
            ("Religious tolerance", "Worship in peace\nRespect all faiths"),
            ("Drug abuse prevention", "Effects on the body\nRefusal skills"),
            ("Human trafficking awareness", "False promises abroad\nReport and stay safe"),
            ("Emergency management", "Fire and flood response\nEmergency numbers"),
            ("Patriotism in action", "Serve my nation\nProject: keep Nigeria clean"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Cultural and Creative Arts": {
        1: [
            ("Elements and principles of design", "Balance and rhythm in art\nAnalyse artworks"),
            ("Drawing: figures in motion", "Action lines\nDraw a footballer"),
            ("Painting: watercolour basics", "Wet on wet\nPaint a landscape"),
            ("Music: key signatures basics", "Sharps and flats\nSing in key"),
            ("Nigerian composers", "Fela Sowande talk\nListen and discuss"),
            ("Craft: leather work basics", "Cut and stitch\nMake a key holder"),
            ("Dance: choreographing a group piece", "Formation basics\nRehearse the piece"),
            ("Drama: script writing", "Write a two scene play\nCast and read"),
            ("Theatre: lighting and sound", "Effects on stage\nPlan the show"),
            ("Revision and assessment", "Term work review\nDisplay"),
        ],
        2: [
            ("Printmaking: lino and stamp", "Design and cut safely\nPrint an edition"),
            ("Graphics: poster design", "Message and image\nDesign a campaign poster"),
            ("Lettering styles", "Block and script\nNeat headings"),
            ("Music: sight singing basics", "Read simple melodies\nSing at first sight"),
            ("Instruments: recorder basics", "Fingering and tone\nPlay simple tunes"),
            ("Craft: bead and jewellery", "Design and string\nMake a set"),
            ("Dance: Nigerian contemporary", "Fuse styles\nCreate a routine"),
            ("Drama: directing basics", "Blocking and cues\nDirect my group"),
            ("Cultural administration", "Museums and galleries\nPlan a class gallery"),
            ("Revision and assessment", "Term work review\nDisplay"),
        ],
        3: [
            ("Sculpture: paper and clay", "Armature basics\nMake a figure"),
            ("Textile: applique", "Cut and stitch layers\nMake a wall hanging"),
            ("Batik basics", "Wax and dye\nMake patterns"),
            ("Music: harmony singing", "Two and three parts\nPerform in choir"),
            ("Concert production", "Programme and rehearsal\nClass concert"),
            ("Dance drama: full production", "Story, music, dance\nPerform for school"),
            ("Film and video basics", "Storyboard a short\nShoot with a tablet"),
            ("Art and technology", "Digital drawing apps\nCreate digital art"),
            ("Portfolio building", "Select my best works\nPresent my portfolio"),
            ("Revision and assessment", "Year work review\nEnd of year exhibition"),
        ],
    },
    "Pre-Vocational Studies": {
        1: [
            ("Home economics: family resources", "Time, money, energy\nUse wisely"),
            ("Meal planning basics", "Balanced meals\nPlan a day menu"),
            ("Cooking methods: boiling and steaming", "Watch the demos\nCompare the results"),
            ("Laundry: sorting clothes", "Colours and whites\nWash correctly"),
            ("Textiles: fibres", "Cotton and wool\nIdentify fibres"),
            ("Agriculture: soil preparation", "Tilling and ridging\nPrepare the bed"),
            ("Crop propagation", "Seeds and stems\nPlant by cuttings"),
            ("Livestock: sheep and goats", "Breed basics\nCare routines"),
            ("Farm records", "Keep simple records\nTrack inputs"),
            ("Revision and assessment", "Term work review\nPractical quiz"),
        ],
        2: [
            ("Food nutrients: proteins", "Body building foods\nPlan protein meals"),
            ("Cooking: frying safely", "Oil temperature\nSafe frying habits"),
            ("Preservation: canning and bottling", "Preserve fruits\nBottle the juice"),
            ("Sewing: pattern basics", "Read simple patterns\nCut and pin"),
            ("Making an apron", "Measure and cut\nSew the apron"),
            ("Agriculture: irrigation basics", "Watering methods\nSet a watering plan"),
            ("Weed control", "Hand and mulch methods\nKeep beds clean"),
            ("Poultry: broilers", "Feed and weight\nGrowth records"),
            ("Agro business basics", "Cost and sales\nSimple accounts"),
            ("Revision and assessment", "Term work review\nPractical quiz"),
        ],
        3: [
            ("Food service at home", "Serve family meals\nEtiquette practice"),
            ("Cooking: local delicacies", "Cook a local dish\nDocument the steps"),
            ("Budgeting for food", "Market list and prices\nShop within budget"),
            ("Clothing: repairing and mending", "Patch and darn\nExtend garment life"),
            ("Simple embroidery", "Stitches and patterns\nDecorate a tray cloth"),
            ("Agriculture: harvest and storage", "Harvest mature crops\nStore properly"),
            ("Processing: garri and palm oil", "Watch the process\nDocument the stages"),
            ("Marketing: advert skills", "Price and display\nSell at the class market"),
            ("Career paths in home economics and agriculture", "Chef, tailor, agronomist\nCareer plan talk"),
            ("Revision and assessment", "Year work review\nEnd of year practical"),
        ],
    },
    "Physical and Health Education": {
        1: [
            ("Athletics: relay technique", "Takeover zones\nBlind passes"),
            ("Athletics: shot put basics", "Grip and stance\nPut from the shoulder"),
            ("Football: tactics basics", "Position play\nSmall sided games"),
            ("Basketball: lay up", "Steps and release\nPractice the lay up"),
            ("Handball: shooting techniques", "Jump shot basics\nGoal side practice"),
            ("Gymnastics: cartwheel basics", "Hand placement\nSpotting safety"),
            ("Health: the endocrine talk", "Growth and change\nPuberty basics"),
            ("Drugs in sports", "Fair play\nNo substance abuse"),
            ("Environmental health: waste", "Refuse disposal\nRecycling basics"),
            ("Revision and assessment", "Term work review\nSkills display"),
        ],
        2: [
            ("Athletics: discus basics", "Grip and swing\nSafe throwing"),
            ("Athletics: race walking", "Technique rules\nJudge the walk"),
            ("Volleyball: spiking basics", "Approach and jump\nTiming drills"),
            ("Volleyball: blocking", "Read the attacker\nBlock at the net"),
            ("Table tennis: backhand", "Stroke practice\nRally drills"),
            ("Traditional sports: wrestling basics", "Rules and safety\nBalance drills"),
            ("Health: communicable diseases", "Modes of spread\nPrevention charts"),
            ("First aid: fractures", "Immobilise and refer\nImprovised splints"),
            ("Physical fitness: circuit training", "Stations design\nComplete the circuit"),
            ("Revision and assessment", "Term work review\nSkills display"),
        ],
        3: [
            ("Athletics: pentathlon talk", "Five events overview\nPlan my events"),
            ("Gymnastics: vaulting basics", "Run and rebound\nSafe landing"),
            ("Football: defending", "Marking and tackle\nZone defending"),
            ("Basketball: zone defence", "Positions on court\nPlay the zone"),
            ("Hockey basics", "Grip and dribble\nSmall game"),
            ("Recreation and leisure", "Healthy leisure choices\nPlan family recreation"),
            ("Health: non communicable diseases", "Diabetes and hypertension talk\nPrevention habits"),
            ("Family health: maternal care", "Care for mothers\nSupport roles"),
            ("Sports administration basics", "Rules and officials\nOfficiate a mini game"),
            ("Revision and assessment", "Year work review\nEnd of year display"),
        ],
    },
    "Christian Religious Studies": {
        1: [
            ("God the creator of all", "Creation reflection\nCare for the earth"),
            ("The omnipotence of God", "Nothing too hard\nTrust God's power"),
            ("The love of God", "For God so loved\nShare the love"),
            ("The mercy of God", "The forgiven debtor\nBe merciful"),
            ("The faithfulness of God", "Noah's covenant\nGod keeps promises"),
            ("The holiness of God", "Be holy as He is holy\nLive pure lives"),
            ("The justice of God", "Fair judgment\nAct justly"),
            ("The presence of God", "God with us always\nPray without fear"),
            ("Worship in spirit", "True worship\nWorship with my life"),
            ("Revision and assessment", "Term work review\nStories and songs"),
        ],
        2: [
            ("Jesus: the word made flesh", "John chapter one talk\nJesus is God with us"),
            ("The miracles of Jesus: nature", "Calming the storm\nTrust Jesus in trouble"),
            ("The miracles of Jesus: healing", "The blind man sees\nJesus cares for the sick"),
            ("The parable of the talents", "Use my gifts well\nMultiply my talents"),
            ("The parable of the good Samaritan", "Who is my neighbour\nShow mercy"),
            ("The rich fool", "Greed warning\nStore treasure in heaven"),
            ("The wise and foolish builders", "Build on the rock\nObey the word"),
            ("Jesus and the children", "Let them come\nJesus values me"),
            ("The triumphal entry", "Hosanna praise\nWelcome the king"),
            ("Revision and assessment", "Term work review\nStories and songs"),
        ],
        3: [
            ("The Holy Spirit promised", "The comforter comes\nThe Spirit helps me"),
            ("The spirit filled church", "Sharing and prayer\nLive in fellowship"),
            ("Gifts of the spirit", "Many gifts one spirit\nUse my gift"),
            ("Prayer and fasting", "Discipline of prayer\nMy prayer plan"),
            ("Christian giving", "Cheerful givers\nMy giving plan"),
            ("Soul winning", "Fishers of men\nTell my friends"),
            ("Christian homes", "Love and respect\nBuild a godly home"),
            ("Christian leadership", "Serve like Jesus\nLead by serving"),
            ("Living for Christ daily", "Daily devotion\nWalk with God"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Islamic Religious Studies": {
        1: [
            ("Surah Al-Baqarah 1 to 5", "Recite together\nCharacter of the believers"),
            ("Surah Al-Imran 1 to 9", "Recite and memorise\nRevelation talk"),
            ("Tafsir basics: Surah Al-Fatihah", "Deep meaning\nSeven verses lessons"),
            ("The Prophets of Allah", "Stories and lessons\nFollow the messengers"),
            ("Salat al-Tarawih and qiyam", "Night prayers\nRamadan worship"),
            ("Du'a: protection du'as", "Morning and evening\nRecite with trust"),
            ("Asma ul Husna: Ar-Razzaq", "Allah provides\nWork and pray"),
            (" Zakat calculation basics", "When zakat is due\nSimple calculation"),
            ("Unity of the ummah", "One brotherhood\nPeaceful coexistence"),
            ("Revision and assessment", "Term work review\nRecitations"),
        ],
        2: [
            ("Surah An-Nisa 1 to 10", "Recite together\nRights and justice"),
            ("Surah Al-Ma'idah 1 to 5", "Recite and memorise\nFulfil the covenant"),
            ("Tafsir basics: Ayat al-Kursi", "Greatness of Allah\nRecite after prayers"),
            ("The Prophet's last sermon", "Equality and rights\nLessons for today"),
            ("Salat al-Janazah", "Funeral prayer basics\nRemember the hereafter"),
            ("Du'a: visiting the sick", "Care for the sick\nDu'a of comfort"),
            ("Asma ul Husna: Al-Adl", "Allah the just\nLive justly"),
            ("Halal earnings", "Honest income\nNo cheating in trade"),
            ("Islamic history: the caliphs", "Abu Bakr and Umar\nLeadership lessons"),
            ("Revision and assessment", "Term work review\nRecitations"),
        ],
        3: [
            ("Surah Al-Kahf 1 to 10", "Recite together\nTrials and faith"),
            ("Surah Maryam 1 to 15", "Recite and memorise\nDevotion lessons"),
            ("Tafsir basics: the short surahs", "Lessons from Juz Amma\nApply the meanings"),
            ("The pillars of Islam review", "Five pillars mastery\nLive the pillars"),
            ("Ihsan: excellence in worship", "Worship as if seeing Him\nCharacter of ihsan"),
            ("Du'a: seeking knowledge", "Study du'as\nPray for wisdom"),
            ("Asma ul Husna: Al-Wadud", "Allah the loving\nSpread love and mercy"),
            ("Islamic civilization", "Learning and science\nMuslim scholars"),
            ("Da'wah basics", "Invite with wisdom\nGood character first"),
            ("Revision and assessment", "Year work review\nEnd of year recitations"),
        ],
    },
}
