#!/usr/bin/env python3
"""Nursery 1 scheme data, part A: Letter Work, Number Work, Rhymes, Social Habits."""

NURSERY_1_A = {
    "Letter Work": {
        1: [
            ("Standing and sleeping lines", "Holding the pencil the right way\nTracing standing lines from top to bottom\nTracing sleeping lines from left to right"),
            ("Tracing patterns", "Zigzag lines\nWavy lines\nCurves from left to right"),
            ("Tracing circles", "Drawing circles in the air\nTracing big circles on paper\nColouring inside a circle"),
            ("Letter Aa", "Sound of A as in apple\nTracing capital A\nTracing small a"),
            ("Letter Bb", "Sound of B as in ball\nTracing capital B\nTracing small b"),
            ("Letter Cc", "Sound of C as in cat\nTracing capital C\nTracing small c"),
            ("Letter Dd", "Sound of D as in drum\nTracing capital D\nTracing small d"),
            ("Letter Ee", "Sound of E as in egg\nTracing capital E\nTracing small e"),
            ("Letter Ff", "Sound of F as in fan\nTracing capital F\nTracing small f"),
            ("Revision and colouring fun", "Say the sounds A to F\nMatch letters to pictures\nColour the letters we learned"),
        ],
        2: [
            ("Letter Gg", "Sound of G as in goat\nTracing capital G\nTracing small g"),
            ("Letter Hh", "Sound of H as in hat\nTracing capital H\nTracing small h"),
            ("Letter Ii", "Sound of I as in ink\nTracing capital I\nTracing small i"),
            ("Letter Jj", "Sound of J as in jug\nTracing capital J\nTracing small j"),
            ("Letter Kk", "Sound of K as in kite\nTracing capital K\nTracing small k"),
            ("Letter Ll", "Sound of L as in leaf\nTracing capital L\nTracing small l"),
            ("Letters Aa to Ll", "Say each sound from A to L\nFind the letter the teacher calls\nTrace our favourite letters"),
            ("Letter Mm", "Sound of M as in moon\nTracing capital M\nTracing small m"),
            ("Letter Nn", "Sound of N as in nose\nTracing capital N\nTracing small n"),
            ("Revision and matching", "Match capital to small letters\nMatch letters to pictures\nSing the letter song"),
        ],
        3: [
            ("Letter Oo", "Sound of O as in orange\nTracing capital O\nTracing small o"),
            ("Letter Pp", "Sound of P as in pen\nTracing capital P\nTracing small p"),
            ("Letter Qq", "Sound of Q as in queen\nTracing capital Q\nTracing small q"),
            ("Letter Rr", "Sound of R as in rope\nTracing capital R\nTracing small r"),
            ("Letter Ss", "Sound of S as in sun\nTracing capital S\nTracing small s"),
            ("Letter Tt", "Sound of T as in tap\nTracing capital T\nTracing small t"),
            ("Letter Uu", "Sound of U as in umbrella\nTracing capital U\nTracing small u"),
            ("Letter Vv and Ww", "Sound of V as in van\nSound of W as in water\nTrace Vv and Ww"),
            ("Letters Oo to Ww", "Say the sounds from O to W\nCircle the letter the teacher says\nTrace the letters neatly"),
            ("Revision of all letters", "Say the whole alphabet together\nMatch every letter to its picture\nFree tracing practice"),
        ],
    },
    "Number Work": {
        1: [
            ("Counting 1 and 2", "Say one and two with objects\nPick one sweet, pick two sweets\nTrace number 1 and 2"),
            ("Number 3", "Count three fingers\nPick three blocks\nTrace number 3"),
            ("Number 4", "Count four cups\nClap four times\nTrace number 4"),
            ("Number 5", "Count five stones\nJump five times\nTrace number 5"),
            ("Counting 1 to 5", "Count together from 1 to 5\nArrange number cards 1 to 5\nMatch numbers to objects"),
            ("Number 6", "Count six buttons\nPoint to six children\nTrace number 6"),
            ("Number 7", "Count seven leaves\nClap seven times\nTrace number 7"),
            ("Number 8", "Count eight crayons\nStamp eight times\nTrace number 8"),
            ("Number 9 and 10", "Count nine and ten with objects\nCount ten fingers\nTrace 9 and 10"),
            ("Revision 1 to 10", "Count 1 to 10 together\nArrange cards 1 to 10\nCount objects in class"),
        ],
        2: [
            ("Counting 11 and 12", "Count 11 and 12 with counters\nTrace 11 and 12"),
            ("Counting 13 and 14", "Count 13 and 14 with counters\nTrace 13 and 14"),
            ("Counting 15 and 16", "Count 15 and 16 with counters\nTrace 15 and 16"),
            ("Counting 17 and 18", "Count 17 and 18 with counters\nTrace 17 and 18"),
            ("Counting 19 and 20", "Count 19 and 20 with counters\nTrace 19 and 20"),
            ("Counting 1 to 20", "Count from 1 to 20 together\nFill the missing number on the board"),
            ("Big and small", "Sort big and small objects\nCircle the big one, circle the small one"),
            ("More and less", "Which plate has more sweets\nWhich plate has less"),
            ("Sorting and matching", "Match one object to one partner\nSort blocks by colour"),
            ("Revision", "Count 1 to 20 in turns\nBig or small game\nMore or less game"),
        ],
        3: [
            ("Counting 21 to 30", "Count from 21 to 30 with a number line\nTrace the tens 20 and 30"),
            ("Counting 31 to 40", "Count from 31 to 40\nFind 35 on the number line"),
            ("Counting 41 to 50", "Count from 41 to 50\nTrace 50"),
            ("Counting 1 to 50", "Count 1 to 50 together in parts\nFill missing numbers to 50"),
            ("Simple addition with objects", "Put two blocks and one block together\nCount how many now"),
            ("Simple subtraction with objects", "Take five sweets and eat one\nCount how many are left"),
            ("Shapes around us", "Circle, square and triangle\nFind circles in the classroom"),
            ("Sorting by size and colour", "Put all red blocks together\nPut all big books together"),
            ("Patterns", "Copy a simple colour pattern\nContinue the pattern red, blue, red, what next"),
            ("Revision", "Count 1 to 50 in turns\nAdd and take away with objects\nShape hunt in class"),
        ],
    },
    "Rhymes": {
        1: [
            ("Welcome song", "Sing the welcome song together\nClap along with the beat"),
            ("Twinkle twinkle little star", "Recite with actions\nPoint to stars in the picture"),
            ("Rain rain go away", "Recite with actions\nTalk about rain and sun"),
            ("Pat a cake", "Recite with clapping game\nTake turns in pairs"),
            ("Johnny Johnny yes papa", "Recite with role play\nEat sugar or no sugar game"),
            ("Baa baa black sheep", "Recite with actions\nCount the bags of wool one two three"),
            ("Ding dong bell", "Recite together\nAct the cat and the mouse"),
            ("Humpty Dumpty", "Recite with actions\nTalk about being careful"),
            ("Old MacDonald", "Sing with animal sounds\nName farm animals"),
            ("Rhyme day revision", "Pick our favourite rhymes\nSing and clap as a class"),
        ],
        2: [
            ("One two buckle my shoe", "Recite and count along\nClap on every number"),
            ("Head, shoulders, knees and toes", "Sing and touch each body part\nSpeed up slowly"),
            ("If you are happy and you know it", "Sing with clapping and stomping\nAdd our own actions"),
            ("The wheels on the bus", "Sing with round and round actions\nTalk about the bus ride"),
            ("Five little monkeys", "Recite and count down from five\nJump five times"),
            ("Twinkle twinkle with new words", "Change a word in the rhyme\nSing our new version"),
            ("Little Miss Muffet", "Recite with actions\nTalk about spiders"),
            ("Jack and Jill", "Recite with actions\nTalk about helping each other"),
            ("Pussy cat, pussy cat", "Recite with actions\nAct the cat and the queen"),
            ("Rhyme concert", "Every child picks one rhyme\nSing for the class"),
        ],
        3: [
            ("Mary had a little lamb", "Recite with actions\nTalk about pets"),
            ("Hickory dickory dock", "Recite and count the hours\nAct the mouse and the clock"),
            ("Row, row, row your boat", "Sing in pairs with rowing actions"),
            ("London Bridge is falling down", "Play the bridge game and sing"),
            ("Ring a ring o roses", "Sing in a circle and all fall down"),
            ("Bingo the dog", "Sing and clap the missing letters\nSpell BINGO together"),
            ("Ten green bottles", "Count down from ten together\nHold up number cards"),
            ("Incy wincy spider", "Recite with finger actions\nTalk about up and down"),
            ("Our own class rhyme", "Make a short rhyme about our school\nSay it together"),
            ("Rhyme festival", "Sing all term rhymes in groups\nClap for every group"),
        ],
    },
    "Social Habits": {
        1: [
            ("My name and my class", "Say my full name\nSay my class and my teacher's name"),
            ("Greeting people", "Greet in the morning and in the evening\nGreet our elders the right way"),
            ("My body belongs to me", "Point to my body parts\nMy body is private to me"),
            ("My family", "Name the people in my family\nDraw my family"),
            ("Sharing with friends", "Share crayons with a partner\nSay please and thank you"),
            ("Saying sorry", "What to do when we hurt a friend\nSay sorry and make up"),
            ("Classroom rules", "Listen to our class rules\nWalk, do not run"),
            ("Taking turns", "Wait for my turn on the slide\nTake turns with the toy"),
            ("Keeping the class clean", "Put waste in the bin\nArrange chairs after play"),
            ("Revision and role play", "Act greeting, sharing and sorry\nSay our class rules"),
        ],
        2: [
            ("Good manners at the table", "Wash hands before eating\nChew with the mouth closed"),
            ("Helping at home", "Pick up my toys\nRun small errands for mummy"),
            ("Helping in class", "Share the books\nWater the class plant"),
            ("Respecting elders", "Greet and listen when elders talk\nDo not interrupt"),
            ("Making friends", "Say my name to a new friend\nPlay together kindly"),
            ("Kind hands and kind words", "Hands are not for hitting\nUse kind words only"),
            ("My school and my home", "Say my address with help\nSay my school name"),
            ("Safe people", "Who I can run to for help\nNever follow strangers"),
            ("Teamwork", "Build one tower together\nClean up together"),
            ("Revision and drama", "Act helping and kindness\nSing the good manners song"),
        ],
        3: [
            ("Being honest", "Say the truth always\nReturn what is not mine"),
            ("Being responsible", "Keep my own bag and bottle\nDo my little jobs myself"),
            ("Respecting our flag and anthem", "Stand for the anthem\nHandle the flag with respect"),
            ("Our community helpers", "Name the teacher, doctor, nurse and police\nSay what each one does"),
            ("Kindness to animals", "Feed animals gently\nDo not throw stones at animals"),
            ("Good behaviour outside", "Behaviour in the market and worship places\nUse a quiet voice in public"),
            ("Solving little quarrels", "Use words, not hands\nCall the teacher when it is too big"),
            ("Neatness and self care", "Brush my teeth twice daily\nComb my hair, trim my nails"),
            ("Children's rights", "Every child deserves food, love and school\nTell a trusted adult when I feel unsafe"),
            ("Revision and culture day", "Dress and greet in our cultures\nRecite our manners rules"),
        ],
    },
}
