#!/usr/bin/env python3
"""Nursery 2 scheme data, part B: Health Habits, Basic Science and Discovery, Creative Arts, Moral Instruction, Handwriting."""

NURSERY_2_B = {
    "Health Habits": {
        1: [
            ("Daily hygiene routine", "Bath, brush, comb every day\nMy morning routine chart"),
            ("Hand washing steps", "Six steps of hand washing\nWash before and after eating"),
            ("Toilet hygiene", "Use the toilet neatly\nFlush and wash hands"),
            ("Healthy breakfast", "Why breakfast matters\nName good morning foods"),
            ("Fruits and vegetables", "Eat the rainbow every week\nTaste a new fruit"),
            ("Junk food watch", "Sweets and soda are sometimes food\nChoose water and fruit"),
            ("Water for the body", "Drink water through the day\nMy own water bottle"),
            ("Posture", "Sit straight when writing\nStand tall"),
            ("Rest and sleep", "Ten hours of sleep helps me grow\nQuiet time after lunch"),
            ("Revision and hygiene check", "Nails and uniform check\nHealthy plate craft"),
        ],
        2: [
            ("Exercise every day", "Run, skip and stretch\nMorning exercise circle"),
            ("Safety on the stairs", "Hold the rail, one step at a time\nNo playing on stairs"),
            ("Playground safety", "Take turns on the slide\nSand stays low"),
            ("Sun safety", "Shade and water in hot sun\nWear a cap outside"),
            ("Rainy day safety", "Boots and raincoat\nDo not wade in flood water"),
            ("Insects and bites", "Do not disturb bees\nTell the teacher about bites"),
            ("Wounds and first help", "Tell an adult when I bleed\nWash and cover small cuts"),
            ("Sickness and rest", "Rest when I am ill\nTake medicine only from adults"),
            ("Clinic visit", "The nurse checks height, weight and eyes\nDo not fear the clinic"),
            ("Revision and safety patrol", "Spot the unsafe picture\nSafety rules quiz"),
        ],
        3: [
            ("My body grows", "Bones, muscles and blood\nMilk, eggs and beans build me"),
            ("Dental care deep dive", "Brush twice, spit, do not swallow\nVisit the dentist yearly"),
            ("Eye care", "Good light for reading\nRest eyes between play"),
            ("Ear care", "Do not put sticks in ears\nClean outside with a towel"),
            ("Germs and diseases", "Cough spreads germs\nCover mouth and wash hands"),
            ("Malaria watch", "Mosquitoes bite at dusk\nSleep under treated nets"),
            ("Clean water and food", "Drink clean water\nCover food from flies"),
            ("Traffic safety", "Look left, right and left again\nUse the zebra crossing"),
            ("My health card", "Record my height and weight\nKnow my growth"),
            ("Revision and health week", "Health talk by the nurse\nHealth habits certificates"),
        ],
    },
    "Basic Science and Discovery": {
        1: [
            ("Back to discovery", "What is science, asking why\nOur discovery corner rules"),
            ("My body inside", "Heart beats, lungs breathe\nFeel my heartbeat after running"),
            ("Teeth types", "Biting and chewing teeth\nCount my teeth"),
            ("Animals around school", "Birds, lizards and insects\nWalk and spot animals"),
            ("Animal coverings", "Fur, feathers and scales\nSort animal cards"),
            ("How animals move", "Walk, fly, swim, crawl\nAct animal movements"),
            ("Plants in our compound", "Name trees, grass and flowers\nBark rubbing art"),
            ("Seeds", "Collect seeds of different sizes\nSort big and small seeds"),
            ("Water everywhere", "Sources of water, rain, tap, river\nHow we use water"),
            ("Revision and discovery walk", "Nature walk collection\nShow and tell my find"),
        ],
        2: [
            ("The sun and energy", "The sun warms and lights the earth\nSun safety while playing"),
            ("Shadows through the day", "Trace my shadow morning and noon\nShadows move with the sun"),
            ("Light sources", "Sun, torch, lamp, candle\nSort light and dark"),
            ("Sound makers", "Drum, bell, whistle\nLoud and soft sorting"),
            ("Hot and cold things", "Sun is hot, ice is cold\nSort hot and cold pictures"),
            ("Melting and freezing", "Ice melts in the sun\nWater becomes ice in the freezer"),
            ("Machines around us", "Fan, blender, car\nMachines make work easy"),
            ("Wheels and ramps", "Roll cars down the ramp\nSteep or gentle, which is faster"),
            ("Building and balancing", "Build tall towers\nBalance scales with blocks"),
            ("Revision and inventors day", "Show my machine or tower\nTalk like a scientist"),
        ],
        3: [
            ("Living things grow", "Baby to adult, human and animal\nOrder the growth cards"),
            ("Plant life cycle", "Seed, sprout, plant, flower, fruit\nOrder the cycle cards"),
            ("Butterfly life cycle", "Egg, caterpillar, pupa, butterfly\nAct the cycle"),
            ("Habitats", "Fish in water, birds in trees\nMatch animal to habitat"),
            ("Food chains start", "Grass feeds the goat, goat feeds us\nSimple food chain cards"),
            ("Reuse and recycle", "Sort bottles, paper and cans\nMake a bottle planter"),
            ("Caring for the earth", "Do not waste water and light\nPlant a class tree"),
            ("Weather and seasons", "Rainy season and dry season\nDress for the weather"),
            ("Day sky and night sky", "Sun, clouds and rainbow\nMoon shapes change"),
            ("Revision and science fair", "Present my cycle or planter\nParents' science walk"),
        ],
    },
    "Creative Arts": {
        1: [
            ("Back to art", "Art tools and their care\nFree colouring warm up"),
            ("Drawing with shapes", "House from square and triangle\nBus from rectangles and circles"),
            ("Patterns", "Stripes, dots and zigzag\nDecorate a shirt outline"),
            ("Primary colours", "Red, yellow, blue\nSort objects by primary colour"),
            ("Secondary colours", "Mix to make orange, green, purple\nPaint a colour wheel flower"),
            ("Clay animals", "Mould my favourite animal\nAdd ears and tail"),
            ("Paper plate masks", "Make an animal mask\nCut eyes and add whiskers"),
            ("Tie and dye play", "Rubber band patterns on cloth\nDip and open the surprise"),
            ("Collage of Nigeria", "Green and white collage\nFlag art with paper"),
            ("Art exhibition", "Mount the term works\nGallery walk with friends"),
        ],
        2: [
            ("Portrait of a friend", "Look and draw a friend\nAdd their smile"),
            ("Still life fruit bowl", "Draw the fruits on the table\nColour what I see"),
            ("Landscape", "Sky, sun, trees and house\nLayer my picture"),
            ("Weaving progress", "Weave a bigger mat\nTwo colour patterns"),
            ("Beads and buttons art", "Sort, thread and glue\nMake a class button tree"),
            ("Papier mache bowl", "Layer paper strips with paste\nPaint my bowl"),
            ("Clay coil pots", "Roll coils and stack them\nSmooth and paint"),
            ("Print making", "Stamp patterns with carved sponges\nRepeat my design"),
            ("Cultural craft", "Calabash decoration\nAdire pattern drawing"),
            ("Art festival", "Show my best three works\nTalk about my art"),
        ],
        3: [
            ("Graduation art plan", "Plan my big art piece\nSketch first, then colour"),
            ("Class mural design", "Vote the mural theme\nDraw the outline together"),
            ("Mural painting", "Everyone paints a section\nBlend colours as a team"),
            ("Card making", "Thank you card for mummy and daddy\nPop up card surprise"),
            ("Book mark craft", "Design and decorate bookmarks\nGift to a friend"),
            ("Crown and cap craft", "Make my graduation crown\nMeasure, cut and decorate"),
            ("Drum making", "Decorate a tin or clay drum\nPlay the class beat"),
            ("Dance and drama art", "Face painting for the play\nCostume making"),
            ("Photography walk", "Look through the class camera\nFrame the school garden"),
            ("Graduation gallery", "Full display of term works\nArt awards day"),
        ],
    },
    "Moral Instruction": {
        1: [
            ("New term new choices", "Set my little goal for the term\nKind, honest, hardworking"),
            ("The golden rule", "Do to others what I love\nPractise in pairs"),
            ("Respect for the flag", "Stand and sing with respect\nFlag etiquette"),
            ("Telling the truth", "Story of the truthful child\nTruth builds trust"),
            ("No stealing", "Ask before taking\nReturn borrowed things"),
            ("Cleanliness", "Clean body, clean room\nCleaning is a good habit"),
            ("Obedience brings peace", "Obey mummy, daddy and teacher\nObey the first time"),
            ("Forgiving friends", "Let go and be free\nMake peace quickly"),
            ("Gratitude to God", "Thank God for family, food and school\nCount my blessings"),
            ("Revision and character awards", "Recite our rules\nCharacter star ceremony"),
        ],
        2: [
            ("Love in action", "Help without being asked\nKindness jar for the class"),
            ("Self control", "Angry feelings are normal\nCalm tools, breathe, count, walk"),
            ("Diligence", "Finish what I start\nLittle jobs done well"),
            ("Contentment", "Happy with what I have\nGreed steals joy"),
            ("Courage", "Do right even when afraid\nStand up for the picked on child"),
            ("Loyalty", "Keep safe secrets\nDefend my friends' good name"),
            ("Fairness", "Share and take turns\nPlay by the rules"),
            ("Service to others", "Serve at home and in class\nBe the helper"),
            ("Peace making", "Be a bridge, not a bomb\nSolve quarrels with words"),
            ("Revision and service awards", "Share our service stories\nHelper of the term"),
        ],
        3: [
            ("My values ladder", "Honesty, kindness, hard work\nPick my top value"),
            ("Leadership is service", "Great leaders serve\nAct a serving leader"),
            ("Integrity", "Same inside and outside\nDo right when nobody watches"),
            ("Respect for all work", "Every work has dignity\nGreet and thank all workers"),
            ("Patriotism", "Love Nigeria, keep her clean\nSay the pledge with meaning"),
            ("Stewardship", "Care for school property\nCare for the earth"),
            ("Peer pressure basics", "My choice, my responsibility\nSay no with respect"),
            ("Media choices", "Choose good programmes\nTell adults what troubles me"),
            ("Graduation gratitude", "Thank my teachers and parents\nWrite a thank you card"),
            ("Revision and values day", "Present my values ladder\nGraduation character awards"),
        ],
    },
    "Handwriting": {
        1: [
            ("Pencil grip refresh", "Tripod grip practice\nRelax and write"),
            ("Letter families 1", "c, a, d, g, o, q same family\nWrite the family rows"),
            ("Letter families 2", "l, t, i, u, y\nWrite the family rows"),
            ("Letter families 3", "r, n, m, h, b, p\nWrite the family rows"),
            ("Words 1", "cat, dog, sun, hat\nWrite and read"),
            ("Words 2", "hand, milk, ball, star\nWrite on the line"),
            ("Sentences 1", "The cat is fat.\nFinger spaces and full stops"),
            ("Numbers 1 to 20", "Write in neat rows\nCheck my formation"),
            ("Numbers 21 to 50", "Write tens neatly\n50 is our champion"),
            ("Revision and best page", "Choose my best page\nHandwriting wall of fame"),
        ],
        2: [
            ("Joining letters 1", "c a d joins\nFirst join patterns"),
            ("Joining letters 2", "in, un, am joins\nWrite joined words"),
            ("Joining letters 3", "on, im, an joins\nWrite joined rows"),
            ("Joined words", "sun, cup, pin, mat\nWrite and read joined"),
            ("Joined sentences", "The sun is up.\nWrite joined with spaces"),
            ("Neat numbers", "1 to 50 aligned rows\nTabular neatness"),
            ("Days of the week", "Write and spell the days\nMonday to Sunday"),
            ("My name joined", "Write my name joined\nSign my work"),
            ("Copy work", "Copy two lines from the board\nCheck spacing and joins"),
            ("Revision and handwriting star", "Best joined writing\nStar of neat writing"),
        ],
        3: [
            ("Joined fluency", "Write a full line without lifting\nKeep the slope"),
            ("Paragraph copy", "Copy a short paragraph\nMargins and spacing"),
            ("Punctuation", "Capital letters and full stops\nQuestion mark and comma"),
            ("Sentence building", "Make and write my sentence\nAbout my best friend"),
            ("Short story writing", "Three sentences about my holiday\nRead my story aloud"),
            ("Number words", "one to twenty words\nWrite and match"),
            ("Address writing", "My house address neatly\nKnow my address"),
            ("Card writing", "Write inside my graduation card\nBest wishes lines"),
            ("Dictation practice", "Teacher says, I write\nFive words and one sentence"),
            ("Revision and handwriting certificate", "Final best page\nHandwriting graduation award"),
        ],
    },
}
