#!/usr/bin/env python3
"""Primary 6 scheme data: ten subjects, three terms, ten weeks each."""

PRIMARY_6 = {
    "English Studies": {
        1: [
            ("Revision of primary five work", "Reading and writing warm up\nGrammar drill"),
            ("Comprehension: discipline", "Read and answer questions\nVocabulary from the passage"),
            ("Grammar: parts of speech review", "Nouns, verbs, adjectives, adverbs\nIdentify in passages"),
            ("Grammar: tenses", "Simple past and present perfect\nChange the tense"),
            ("Vocabulary: word families", "Root words with prefixes and suffixes\nBuild new words"),
            ("Composition: argument essay", "Should children use phones\nPlan and write"),
            ("Letter writing: formal", "Write to the head teacher\nFormal format"),
            ("Oral English: diphthongs", "oi, ou, ie sounds\nPronunciation drill"),
            ("Literature: poem study", "Read and discuss a Nigerian poem\nFigures of speech"),
            ("Revision and assessment", "Term review\nClass test"),
        ],
        2: [
            ("Comprehension: leadership", "Read and answer questions\nSummary skills"),
            ("Grammar: conjunctions", "And, but, because, although\nJoin the sentences"),
            ("Grammar: direct and reported speech", "Change speech forms\nPunctuation rules"),
            ("Vocabulary: idioms", "Common idioms and meanings\nUse in sentences"),
            ("Composition: narrative", "My most memorable day\nPlan, write, edit"),
            ("Letter writing: informal", "Write to my cousin\nInformal format"),
            ("Oral English: stress and intonation", "Word stress drill\nQuestion tunes"),
            ("Literature: prose study", "Characters and setting\nAnswer literature questions"),
            ("Summary writing", "Pick the main points\nOne paragraph summary"),
            ("Revision and assessment", "Term review\nClass test"),
        ],
        3: [
            ("Comprehension: honesty", "Read and answer questions\nInference practice"),
            ("Grammar: active and passive voice", "Change the voice\nWhen to use each"),
            ("Grammar: prepositions and phrasal verbs", "Common phrasal verbs\nFill in drills"),
            ("Vocabulary: exam words", "Words from past papers\nSpelling and meaning"),
            ("Composition: expository", "The importance of education\nPlan and write"),
            ("Letter writing practice", "Choose formal or informal\nFull letter"),
            ("Oral English: revision", "All sounds review\nReading aloud test"),
            ("Literature: drama study", "Read a short play\nAct a scene"),
            ("Common entrance practice", "Past questions practice\nMark and correct"),
            ("Revision and assessment", "End of primary review\nGraduation test"),
        ],
    },
    "Mathematics": {
        1: [
            ("Whole numbers to one million", "Read, write, compare\nPlace value chart"),
            ("Fractions review", "Equivalent fractions\nAdd and subtract fractions"),
            ("Decimals", "Place value of decimals\nAdd and subtract"),
            ("Multiplication", "Multiply by two digit numbers\nWord problems"),
            ("Division", "Long division\nWord problems"),
            ("Percentages", "Fraction to percentage\nSimple percentage of amounts"),
            ("Ratio and proportion", "Simple ratios\nShare in a ratio"),
            ("Money", "Profit and loss basics\nShopping problems"),
            ("Length, weight, capacity", "Convert units\nReal life measuring"),
            ("Revision and assessment", "Term review\nClass test"),
        ],
        2: [
            ("Angles", "Types of angles\nMeasure with protractor"),
            ("Lines and shapes", "Parallel and perpendicular\nProperties of quadrilaterals"),
            ("Perimeter and area", "Rectangles and squares\nCompound shapes"),
            ("Volume", "Cubes and cuboids\nCount unit cubes"),
            ("Time and speed", "12 and 24 hour clock\nDistance, speed, time basics"),
            ("Money and finance", "Simple interest\nBudget planning"),
            ("Data handling", "Bar charts and pie charts\nRead and draw"),
            ("Averages", "Mean of sets of data\nReal life averages"),
            ("Number patterns", "Sequences and rules\nFind the nth term simply"),
            ("Revision and assessment", "Term review\nClass test"),
        ],
        3: [
            ("Fractions, decimals, percentages", "Convert between forms\nExam style questions"),
            ("Simple interest and discount", "Calculate interest\nShopping discounts"),
            ("Ratio and rate", "Rate problems\nSharing problems"),
            ("Algebra basics", "Simple equations\nFind the unknown"),
            ("Geometry revision", "Angles, triangles, circles\nConstruction basics"),
            ("Area and volume revision", "Compound area\nCylinder introduction"),
            ("Statistics revision", "Mean, mode, range\nCharts interpretation"),
            ("Everyday arithmetic", "Multi step word problems\nCommon entrance style"),
            ("Common entrance practice", "Past paper practice\nMark and correct"),
            ("Revision and assessment", "End of primary review\nGraduation test"),
        ],
    },
    "Basic Science and Technology": {
        1: [
            ("The human reproductive system", "Adolescence changes\nResponsible living"),
            ("The nervous system", "Brain and nerves\nReaction games"),
            ("The circulatory system", "Heart and blood\nPulse measurement"),
            ("The respiratory system", "Lungs and breathing\nClean air matters"),
            ("The digestive system", "Organs of digestion\nHealthy eating"),
            ("Drugs and health", "Drug use and misuse\nSay no to drug abuse"),
            ("Food processing", "Preservation methods\nWhy we preserve"),
            ("Simple machine review", "Levers, pulleys, gears\nMachine project"),
            ("Electricity projects", "Series circuits\nMake a torch"),
            ("Revision and project", "Term review\nShow my project"),
        ],
        2: [
            ("The solar system", "Planets and the sun\nModel of the system"),
            ("The earth and moon", "Day, night and seasons\nEclipse basics"),
            ("Satellites and space travel", "How satellites help us\nSpace exploration talk"),
            ("Energy transformation", "Chemical to heat to motion\nEnergy chain cards"),
            ("Force and motion", "Speed and friction\nRamp experiments"),
            ("Pressure", "Air and water pressure\nSyringe experiments"),
            ("Density and flotation", "Why ships float\nDensity columns"),
            ("Materials and their properties", "Metals, polymers, ceramics\nMaterial testing"),
            ("Making things: technology", "Build a model bridge\nPlan and construct"),
            ("Revision and project", "Term review\nShow my project"),
        ],
        3: [
            ("The environment and us", "Ecosystems and habitats\nProtect the environment"),
            ("Water cycle and conservation", "Save water campaign\nWater audit"),
            ("Air and noise pollution", "Causes and effects\nSchool pollution survey"),
            ("Waste management", "Reduce, reuse, recycle\nClass recycling plan"),
            ("Climate and weather", "Weather instruments\nOur weather station"),
            ("Bush burning and deforestation", "Effects on the land\nPlant a tree"),
            ("Erosion control", "Types of erosion\nSimple control methods"),
            ("First aid and safety", "Full first aid practice\nEmergency drills"),
            ("Science and careers", "Science jobs in Nigeria\nMy career dream"),
            ("Revision and science fair", "Year review\nPresent my project"),
        ],
    },
    "National Values Education": {
        1: [
            ("Civic: national honour awards", "CON, OFR and others\nHonour for service"),
            ("Civic: goods and services", "Producers and consumers\nLocal market study"),
            ("Social: peer pressure", "Say no with confidence\nRefusal skills"),
            ("Social: conflict resolution", "Mediation steps\nRole play peace"),
            ("Security: human trafficking", "What it is, how to avoid\nReport to trusted adults"),
            ("Security: kidnapping watch", "Safety in public\nCode words with family"),
            ("Civic: the constitution", "Rules for the nation\nRights and duties"),
            ("Social: national economy", "How Nigeria earns\nMade in Nigeria"),
            ("Security: cyber safety", "Scams and strangers online\nProtect my details"),
            ("Revision and project", "Values quiz\nMy values portfolio"),
        ],
        2: [
            ("Civic: democracy", "Elections and voting\nMock election"),
            ("Civic: the arms of government", "Executive, legislature, judiciary\nWho does what"),
            ("Social: problems of the nation", "Unemployment and corruption\nWhat can children do"),
            ("Social: family as agent", "The family shapes me\nMy role in the family"),
            ("Security: drug trafficking", "Dangers and laws\nSay no and report"),
            ("Security: cultism", "What cultism destroys\nChoose good friends"),
            ("Civic: citizenship", "Rights and responsibilities\nGood citizen chart"),
            ("Social: virtues", "Honesty, courage, service\nVirtue of the week"),
            ("Security: emergency response", "Fire, flood, accident\nResponse drills"),
            ("Revision and project", "Values quiz\nMy values portfolio"),
        ],
        3: [
            ("Civic: nation building", "My contribution\nService project"),
            ("Civic: national economy", "Agriculture and industry\nEnterprise ideas"),
            ("Social: global citizenship", "Nigeria in the world\nUN goals for children"),
            ("Social: technology and society", "Benefits and dangers\nDigital balance"),
            ("Security: personal security", "Situational awareness\nSafe routines"),
            ("Security: community watch", "See something, say something\nTrusted adults list"),
            ("Civic: leadership and service", "Servant leadership\nLead a class project"),
            ("Social: gratitude and legacy", "Leave primary school well\nLegacy project"),
            ("Security: graduation safety", "Safe celebrations\nPlan with parents"),
            ("Revision and project", "End of year review\nValues graduation"),
        ],
    },
    "Pre-Vocational Studies": {
        1: [
            ("Agriculture: crop production", "Land preparation steps\nPlant our beds"),
            ("Agriculture: animal husbandry", "Routines in animal care\nRecord keeping"),
            ("Home economics: adolescence grooming", "Personal presentation\nGrooming checklist"),
            ("Home economics: sewing machine", "Parts of the machine\nMachine practice"),
            ("Agriculture: agricultural extension", "Farmers learn new ways\nExtension visit talk"),
            ("Home economics: meal planning", "Plan a balanced menu\nBudget the menu"),
            ("Agriculture: agribusiness", "Farming as business\nSimple farm accounts"),
            ("Home economics: garment construction", "Cut and sew an apron\nFinish the edges"),
            ("Entrepreneurship: business ideas", "From skill to service\nMy business plan"),
            ("Revision and exhibition", "Show my apron and beds\nExhibition day"),
        ],
        2: [
            ("Agriculture: fish farming", "Pond basics\nCaring for fish"),
            ("Agriculture: forestry", "Trees and timber\nReplanting matters"),
            ("Home economics: food preservation", "Dry, freeze, can\nPreserve a fruit"),
            ("Home economics: laundry work", "Wash, starch, iron\nLaundry steps"),
            ("Agriculture: farm machinery", "Tractors and planters\nMachine safety"),
            ("Home economics: family living", "Roles in the home\nPeaceful home habits"),
            ("Entrepreneurship: marketing", "Price, promote, sell\nSell day plan"),
            ("Entrepreneurship: record keeping", "Simple books of account\nMy sales record"),
            ("Agriculture: harvest and storage", "Harvest properly\nStore to last"),
            ("Revision and exhibition", "Show my work\nMarket day"),
        ],
        3: [
            ("Agriculture: graduation farm project", "Plan our project farm\nExecute and record"),
            ("Agriculture: Nigerian cash crops", "Cocoa, palm, groundnut\nMap the crops"),
            ("Home economics: hospitality", "Welcoming guests\nServing practice"),
            ("Home economics: consumer education", "Wise buying\nCompare and choose"),
            ("Entrepreneurship: craft enterprise", "Produce to sell\nCost and profit"),
            ("Entrepreneurship: savings culture", "Bank and savings basics\nMy savings book"),
            ("Home economics: career paths", "Catering, tailoring, nursing\nMy interest map"),
            ("Agriculture: career paths", "Veterinary, fisheries, agronomy\nMy interest map"),
            ("Project completion", "Finish all projects\nPrepare to exhibit"),
            ("Revision and exhibition", "Graduation exhibition\nShow and tell"),
        ],
    },
    "Cultural and Creative Arts": {
        1: [
            ("Art: still life drawing", "Shade with light and shadow\nDraw the arrangement"),
            ("Music: staff notation", "Lines and spaces\nRead simple notes"),
            ("Art: perspective", "One point perspective\nDraw the street"),
            ("Music: Nigerian composers", "Listen and discuss\nMy favourite piece"),
            ("Art: sculpture in the round", "Clay figure on an armature\nFinish and display"),
            ("Drama: play production", "Audition and roles\nRehearse"),
            ("Art: batik", "Wax and dye\nMake my scarf"),
            ("Music: recorder or voice", "Learn a melody\nPerform in pairs"),
            ("Dance: cultural ballet", "Choreograph a piece\nCostume plan"),
            ("Revision and showcase", "Show my works\nClass concert"),
        ],
        2: [
            ("Art: landscape painting", "Paint with a palette\nMix natural colours"),
            ("Music: harmony basics", "Sing in two parts\nRound singing"),
            ("Art: graphic design", "Poster and flyer design\nMake the sports poster"),
            ("Music: music technology", "Digital beats\nMake a simple loop"),
            ("Art: architecture", "Nigerian buildings\nDraw my dream house"),
            ("Drama: stage craft", "Set, light, sound\nCrew practice"),
            ("Art: ceramics", "Coil and glaze\nFire and display"),
            ("Music: performance polish", "Stage presence\nMic technique"),
            ("Dance: contemporary moves", "Blend styles\nGroup routine"),
            ("Revision and showcase", "Show my works\nClass concert"),
        ],
        3: [
            ("Art: graduation banner", "Design the class banner\nTeam painting"),
            ("Music: graduation songs", "Learn the repertoire\nSolo slots"),
            ("Art: portfolio completion", "Mount my best works\nArtist statement"),
            ("Drama: graduation play", "Full production\nPerform for school"),
            ("Music: instrumental ensemble", "Drums, shakers, keys\nPlay together"),
            ("Art: body decoration art", "Cultural adornment\nRespectful design"),
            ("Dance: graduation medley", "Blend our cultures\nRehearse the finale"),
            ("Music: original class song", "Write and arrange\nRecord our song"),
            ("Full dress rehearsal", "Run the whole show\nFinal notes"),
            ("Graduation showcase", "Perform for parents\nGrand finale"),
        ],
    },
    "Physical and Health Education": {
        1: [
            ("Athletics: track events", "Sprints and relays\nTechnique drills"),
            ("Athletics: field events", "Long jump and high jump\nLanding safety"),
            ("Ball games: basketball", "Dribble, pass, shoot\nMini game"),
            ("Ball games: volleyball", "Serve and volley\nMini game"),
            ("Gymnastics: tumbling", "Forward and backward roll\nBalance poses"),
            ("Fitness testing", "Measure my fitness\nSet my targets"),
            ("Health: puberty education", "Body changes\nHygiene and confidence"),
            ("Health: substance abuse", "Effects of alcohol and tobacco\nChoose health"),
            ("First aid and sports injury", "Sprains and strains\nRICE method"),
            ("Revision and house sports", "Inter house practice\nCertificates"),
        ],
        2: [
            ("Athletics: middle distance", "400 and 800 metres\nPacing practice"),
            ("Ball games: hockey", "Dribble and pass\nMini game"),
            ("Ball games: table tennis", "Serve and rally\nMini tournament"),
            ("Gymnastics: apparatus", "Vault and beam basics\nSpotting rules"),
            ("Rhythmic gymnastics", "Ribbon and hoop\nRoutine practice"),
            ("Health: nutrition for athletes", "Eat to perform\nMatch day meals"),
            ("Health: mental fitness", "Focus and calm\nBreathing practice"),
            ("First aid: bleeding and shock", "Treat and reassure\nCall for help"),
            ("Outdoor pursuits", "Orienteering fun\nMap and compass play"),
            ("Revision and house sports", "Inter house practice\nCertificates"),
        ],
        3: [
            ("Athletics: full meet prep", "Choose my events\nTrain my event"),
            ("Ball games: football tactics", "Positions and formations\nMatch play"),
            ("Ball games: cricket basics", "Bat and bowl\nMini game"),
            ("Swimming skills", "Water confidence\nStrokes practice"),
            ("Fitness: lifelong habits", "Design my routine\nTrack my week"),
            ("Health: disease prevention", "Immunisation and hygiene\nHealth talk"),
            ("Health: first aid full course", "CPR awareness\nRecovery position"),
            ("Health: consumer health", "Read food labels\nChoose wisely"),
            ("Sports festival", "Inter house competition\nRecords and fun"),
            ("Revision and graduation sports", "Final games day\nAwards"),
        ],
    },
    "Christian Religious Studies": {
        1: [
            ("God's purpose for us", "Created for good works\nMy purpose talk"),
            ("Choices and consequences", "Adam and Eve, David and Bathsheba\nChoose wisely"),
            ("Peter's restoration", "Failure is not the end\nGod restores"),
            ("The gifts of the Spirit", "Gifts serve others\nDiscover my gift"),
            ("The beatitudes", "Blessed are...\nLive the attitudes"),
            ("Christian giving", "The widow's mite\nGive from the heart"),
            ("Prayer and fasting", "Jesus teaches prayer\nMy prayer life"),
            ("Overcoming temptation", "Jesus in the wilderness\nEscape routes"),
            ("The second coming", "Be ready always\nLive ready"),
            ("Revision and memory work", "Verses of the year\nBible quiz"),
        ],
        2: [
            ("The acts of the apostles", "Church is born\nSpirit power"),
            ("Missions: Paul's letters", "Letters to the churches\nEncourage one another"),
            ("Christian persecution", "Standing firm\nCourage stories"),
            ("Faith and works", "James teaches\nShow my faith"),
            ("The tongue", "Words that heal or hurt\nGuard my speech"),
            ("Wealth and generosity", "Rich toward God\nGenerous habits"),
            ("Marriage and family God's way", "Honour and love\nFamily devotion"),
            ("Christian youth and purity", "Keep yourself pure\nBoundaries and friends"),
            ("Discernment", "Test every spirit\nWise choices"),
            ("Revision and memory work", "Verses of the year\nBible quiz"),
        ],
        3: [
            ("Graduation gratitude", "Thank God for primary school\nThanksgiving service"),
            ("David's leadership", "Shepherd to king\nLead with heart"),
            ("Nehemiah rebuilds", "Vision and work\nBuild my Jerusalem"),
            ("Esther's courage", "For such a time\nStand for others"),
            ("Daniel's discipline", "Prayer and integrity\nDaily disciplines"),
            ("The great commission", "Go and tell\nMy mission field"),
            ("Walking in the Spirit", "Fruit that lasts\nSpirit led habits"),
            ("Eternal perspective", "Store treasures in heaven\nLive with the end in mind"),
            ("Commissioning service", "Prayer for primary six\nBlessings over us"),
            ("Revision and thanksgiving", "Year in review\nPraise concert"),
        ],
    },
    "Islamic Religious Studies": {
        1: [
            ("Surah Al-Mulk part 1", "Recite and meaning\nAllah's kingdom"),
            ("Surah Al-Mulk part 2", "Recite and meaning\nReflection on creation"),
            ("Hadith studies", "Selected hadith and lessons\nLive the sunnah"),
            ("Fiqh: purification", "Taharah details\nComplete wudu"),
            ("Fiqh: salah conditions", "Valid prayer\nPrayer review"),
            ("Seerah: the early years", "Prophet Muhammad's childhood\nLessons from his life"),
            ("Seerah: the revelation", "First revelation in Hira\nSeek knowledge"),
            ("Islamic economics basics", "Halal earning\nHonest trade"),
            ("Islamic history: Hijrah", "The migration\nSacrifice for faith"),
            ("Revision and recitation", "Term review\nQur'an competition"),
        ],
        2: [
            ("Surah An-Naba part 1", "Recite and meaning\nThe great news"),
            ("Surah An-Naba part 2", "Recite and meaning\nThe day of judgement"),
            ("Hadith on character", "Good character hadith\nMy character plan"),
            ("Fiqh: sawm", "Fasting rules\nRamadan practice"),
            ("Fiqh: zakat", "Calculating and giving\nPurify my wealth"),
            ("Seerah: the Madinah community", "Building the ummah\nCommunity service"),
            ("Seerah: treaties and peace", "Peace agreements\nChoose peace"),
            ("Islamic law basics", "Halal and haram\nGuided choices"),
            ("Islamic civilisation", "Knowledge and invention\nMuslim scholars"),
            ("Revision and recitation", "Term review\nQur'an competition"),
        ],
        3: [
            ("Surah Al-Balad", "Recite and meaning\nThe uphill task"),
            ("Surah Ash-Shams", "Recite and meaning\nPurify my soul"),
            ("Hadith on knowledge", "Seeking knowledge hadith\nMy study plan"),
            ("Fiqh: hajj", "Rites of hajj\nThe journey of unity"),
            ("Seerah: the farewell sermon", "Key messages\nEquality and kindness"),
            ("Seerah: the legacy", "What the Prophet left\nFollow the legacy"),
            ("Islamic etiquette", "Adab in all things\nExcellent manners"),
            ("Service to humanity", "Islam and charity work\nMy service project"),
            ("Preparation for secondary school", "Faith on the next level\nKeep the habits"),
            ("Revision and graduation", "Year review\nDu'a for the class"),
        ],
    },
    "Information Technology": {
        1: [
            ("Computer systems review", "Hardware and software\nLabel the system unit"),
            ("Word processing mastery", "Format documents\nType my essay"),
            ("Spreadsheets basics", "Rows, columns, cells\nMake my marks sheet"),
            ("Spreadsheet formulas", "SUM and AVERAGE\nCalculate my class data"),
            ("Presentations", "Design slides\nPresent my topic"),
            ("Internet research", "Search well, cite sources\nResearch project"),
            ("Digital drawing", "Draw with tools\nDesign the class poster"),
            ("Typing speed", "Home keys drill\nMeasure my speed"),
            ("Data and charts", "Turn data to charts\nChart my scores"),
            ("Revision and project", "Show my documents\nICT exhibition"),
        ],
        2: [
            ("Coding concepts", "Sequences and loops\nBlock coding tasks"),
            ("Scratch project", "Build a game\nDebug my game"),
            ("Algorithms", "Step by step thinking\nWrite my algorithm"),
            ("Databases basics", "Records and fields\nMake a class database"),
            ("Email and cloud", "Attach and share\nOrganise my files"),
            ("Internet safety", "Passwords and privacy\nProtect my account"),
            ("Multimedia", "Edit photos and audio\nMake the class jingle"),
            ("Networking basics", "LAN and the internet\nHow data travels"),
            ("AI awareness", "What AI can and cannot do\nTry a chatbot wisely"),
            ("Revision and project", "Show my game\nICT exhibition"),
        ],
        3: [
            ("Common entrance ICT review", "Theory questions\nPractical tasks"),
            ("Advanced word processing", "Tables and mail merge\nMake the graduation list"),
            ("Spreadsheet project", "Budget for graduation\nCharts and totals"),
            ("Coding project", "Plan and code\nPresent my app idea"),
            ("Web basics", "How websites work\nWrite simple HTML"),
            ("Digital citizenship", "Etiquette and law\nMy digital pledge"),
            ("Entrepreneurship with ICT", "Digital services\nMy tech service plan"),
            ("Portfolio building", "Collect my best work\nOrganise my folder"),
            ("Graduation presentation", "Present my portfolio\nDemo day"),
            ("Revision and graduation project", "Final showcase\nICT awards"),
        ],
    },
}
