#!/usr/bin/env python3
"""SSS 3 scheme data: fourteen subjects, three terms, ten weeks each (WAEC year)."""

SSS_3 = {
    "English Language": {
        1: [
            ("Revision of sss two work", "Lexis and structure warm up\nEssay review"),
            ("Comprehension: summary skills", "Passage drills\nOwn word summaries"),
            ("Lexis: antonyms and synonyms", "Exam word lists\nSentence completion"),
            ("Structure: clause types", "Main and subordinate\nIdentify and use"),
            ("Essay: argumentative", "Practise and polish\nCounter view practice"),
            ("Letter: formal and semi formal", "WAEC formats\nTimed letters"),
            ("Oral: vowels and consonants", "All phonemes drill\nMinimal pairs"),
            ("Oral: stress and rhymes", "Word and sentence stress\nRhyme identification"),
            ("Objective drills", "Lexis and structure sets\nError analysis"),
            ("Revision and WAEC practice", "Past paper one\nMark and correct"),
        ],
        2: [
            ("Comprehension: inference", "Read between lines\nEvidence answers"),
            ("Summary: pruning", "Drop examples and repeats\nCount the sentences"),
            ("Structure: concord", "Subject verb agreement\nCommon traps"),
            ("Structure: idioms and collocations", "Exam idioms\nUse correctly"),
            ("Essay: expository", "Practise and polish\nPlan fast, write well"),
            ("Objective drills two", "Mixed sets\nTiming practice"),
            ("Oral: emphatic stress", "Stress changes meaning\nDrill questions"),
            ("Register practice", "Medicine, law, agriculture registers\nFill the gaps"),
            ("Mock paper one", "Full paper\nMark and review"),
            ("Revision and WAEC practice", "Past paper two\nMark and correct"),
        ],
        3: [
            ("WAEC marathon: comprehension", "Daily passages\nMark and learn"),
            ("WAEC marathon: summary", "Timed summaries\nPeer marking"),
            ("WAEC marathon: structure", "Daily drills\nError logs"),
            ("WAEC marathon: essay", "Two essays per week\nModel answers"),
            ("WAEC marathon: oral", "Full oral practice\nTape drills"),
            ("Mock examination", "Full dress\nMark and review"),
            ("Weakness clinics", "Fix my weak areas\nTargeted practice"),
            ("Speed and accuracy", "Beat the clock drills\nScore tracking"),
            ("Final mock", "Last full paper\nFinal notes"),
            ("WAEC readiness", "Exam day strategy\nBlessings and send off"),
        ],
    },
    "Mathematics": {
        1: [
            ("Revision of sss two work", "Algebra and geometry warm up\nQuiz"),
            ("Indices and logarithms", "Laws and equations\nExam questions"),
            ("Surds", "Simplify and rationalise\nExam questions"),
            ("Quadratic equations", "Formula and completing squares\nWord problems"),
            ("Simultaneous equations", "Linear and one quadratic\nExam questions"),
            ("Trigonometry: sine rule", "Triangles and bearings\nExam questions"),
            ("Trigonometry: cosine rule", "Mixed triangle problems\nExam questions"),
            ("Circle theorems", "Angles and proofs\nExam questions"),
            ("Coordinate geometry", "Gradient and midpoint\nExam questions"),
            ("Revision and WAEC practice", "Past paper one\nMark and correct"),
        ],
        2: [
            ("Statistics: measures", "Mean, median, mode, range\nGrouped data"),
            ("Probability", "Combined events\nExam questions"),
            ("Percentages and finance", "Interest, discount, tax\nExam questions"),
            ("Mensuration", "Area and volume revision\nSector and segment"),
            ("Transformation geometry", "Reflection, rotation, enlargement\nExam questions"),
            ("Variation", "Direct, inverse, joint\nExam questions"),
            ("Inequalities", "Linear inequalities\nGraph solutions"),
            ("Word problems marathon", "Mixed applications\nTimed practice"),
            ("Mock paper one", "Full paper\nMark and review"),
            ("Revision and WAEC practice", "Past paper two\nMark and correct"),
        ],
        3: [
            ("WAEC marathon: algebra", "Daily drills\nError logs"),
            ("WAEC marathon: geometry", "Theorems and construction\nDiagram practice"),
            ("WAEC marathon: trigonometry", "Bearings and heights\nCalculation drills"),
            ("WAEC marathon: statistics", "Data and probability\nPast questions"),
            ("WAEC marathon: mensuration", "Solids and sectors\nPast questions"),
            ("Mock examination", "Full dress\nMark and review"),
            ("Weakness clinics", "Fix my weak topics\nTargeted drills"),
            ("Speed and accuracy", "Objective speed rounds\nScore tracking"),
            ("Final mock", "Last full paper\nFinal notes"),
            ("WAEC readiness", "Exam day strategy\nSend off"),
        ],
    },
    "Physics": {
        1: [
            ("Revision of sss two work", "Mechanics and waves warm up\nQuiz"),
            ("Measurement and units", "Dimensions and errors\nExam questions"),
            ("Kinematics", "Motion graphs\nEquations of motion"),
            ("Dynamics", "Newton laws\nMomentum problems"),
            ("Work, energy, power", "Conservation problems\nExam questions"),
            ("Circular motion", "Angular velocity\nExam questions"),
            ("Waves: properties", "Equations and graphs\nExam questions"),
            ("Sound", "Resonance and harmonics\nExam questions"),
            ("Light: reflection and refraction", "Mirrors and lenses\nRay diagrams"),
            ("Revision and WAEC practice", "Past paper one\nMark and correct"),
        ],
        2: [
            ("Electricity: current", "Ohm law and circuits\nExam questions"),
            ("Electricity: fields", "Capacitors and cells\nExam questions"),
            ("Magnetism", "Fields and forces\nExam questions"),
            ("Electromagnetic induction", "Generators and transformers\nExam questions"),
            ("Heat: temperature and measurement", "Thermometers\nExam questions"),
            ("Heat: transfer", "Conduction, convection, radiation\nExam questions"),
            ("Heat: gas laws", "Boyle and Charles\nExam questions"),
            ("Modern physics", "Photoelectric and nuclear\nExam questions"),
            ("Mock paper one", "Full paper\nMark and review"),
            ("Revision and WAEC practice", "Past paper two\nMark and correct"),
        ],
        3: [
            ("WAEC marathon: mechanics", "Daily calculations\nError logs"),
            ("WAEC marathon: waves and light", "Diagrams and drills\nPast questions"),
            ("WAEC marathon: electricity", "Circuit problems\nPast questions"),
            ("WAEC marathon: heat", "Gas laws drills\nPast questions"),
            ("WAEC marathon: modern physics", "Nuclear questions\nPast questions"),
            ("Mock examination", "Full dress\nMark and review"),
            ("Practical marathon", "Waec practical style\nMeasure and record"),
            ("Weakness clinics", "Fix my weak topics\nTargeted drills"),
            ("Final mock", "Last full paper\nFinal notes"),
            ("WAEC readiness", "Exam day strategy\nSend off"),
        ],
    },
    "Chemistry": {
        1: [
            ("Revision of sss two work", "Bonding and equations warm up\nQuiz"),
            ("Atomic structure", "Configuration and isotopes\nExam questions"),
            ("Periodic table", "Trends and groups\nExam questions"),
            ("Chemical bonding", "Ionic and covalent\nExam questions"),
            ("Stoichiometry", "Mole calculations\nExam questions"),
            ("Acids and bases", "Titration calculations\nExam questions"),
            ("Redox reactions", "Oxidation numbers\nExam questions"),
            ("Electrolysis", "Faraday laws\nExam questions"),
            ("Energy changes", "Enthalpy basics\nExam questions"),
            ("Revision and WAEC practice", "Past paper one\nMark and correct"),
        ],
        2: [
            ("Rates of reaction", "Factors and graphs\nExam questions"),
            ("Equilibrium", "Reversible reactions\nExam questions"),
            ("Organic: alkanes and alkenes", "Isomers and reactions\nExam questions"),
            ("Organic: alkynes and alkanols", "Functional groups\nExam questions"),
            ("Organic: acids and esters", "Preparation and uses\nExam questions"),
            ("Metals and extraction", "Iron and aluminium\nExam questions"),
            ("Non metals", "Nitrogen, sulphur, carbon\nExam questions"),
            ("Water and hardness", "Treatment processes\nExam questions"),
            ("Mock paper one", "Full paper\nMark and review"),
            ("Revision and WAEC practice", "Past paper two\nMark and correct"),
        ],
        3: [
            ("WAEC marathon: physical chemistry", "Mole and energy drills\nPast questions"),
            ("WAEC marathon: inorganic", "Groups and extraction\nPast questions"),
            ("WAEC marathon: organic", "All functional groups\nPast questions"),
            ("Mock examination", "Full dress\nMark and review"),
            ("Practical marathon", "Titration and salt analysis\nPractice sessions"),
            ("Qualitative analysis drills", "Cations and anions\nFast identification"),
            ("Weakness clinics", "Fix my weak topics\nTargeted drills"),
            ("Speed and accuracy", "Objective speed rounds\nScore tracking"),
            ("Final mock", "Last full paper\nFinal notes"),
            ("WAEC readiness", "Exam day strategy\nSend off"),
        ],
    },
    "Biology": {
        1: [
            ("Revision of sss two work", "Cells and systems warm up\nQuiz"),
            ("Cell structure and organisation", "Organelles and functions\nDiagram drills"),
            ("Cell division", "Mitosis and meiosis\nStages practice"),
            ("Nutrition in plants", "Photosynthesis experiments\nExam questions"),
            ("Nutrition in animals", "Digestive systems\nExam questions"),
            ("Transport systems", "Blood and lymph\nExam questions"),
            ("Respiration", "Aerobic and anaerobic\nExam questions"),
            ("Excretion", "Kidney and skin\nExam questions"),
            ("Coordination", "Nervous and hormonal\nExam questions"),
            ("Revision and WAEC practice", "Past paper one\nMark and correct"),
        ],
        2: [
            ("Reproduction in plants", "Flowers and pollination\nExam questions"),
            ("Reproduction in animals", "Systems and development\nExam questions"),
            ("Genetics", "Mendel and inheritance\nCrosses practice"),
            ("Evolution", "Theories and evidence\nExam questions"),
            ("Ecology: ecosystems", "Food webs and chains\nField work"),
            ("Ecology: factors", "Biotic and abiotic\nHabitat studies"),
            ("Conservation", "Nigerian reserves\nConservation plans"),
            ("Diseases and immunity", "Pathogens and defence\nExam questions"),
            ("Mock paper one", "Full paper\nMark and review"),
            ("Revision and WAEC practice", "Past paper two\nMark and correct"),
        ],
        3: [
            ("WAEC marathon: physiology", "Systems drills\nDiagram practice"),
            ("WAEC marathon: ecology", "Habitat questions\nPast questions"),
            ("WAEC marathon: genetics", "Crosses and pedigree\nPast questions"),
            ("Mock examination", "Full dress\nMark and review"),
            ("Practical marathon", "Specimens and microscopy\nPractice sessions"),
            ("Dissection and drawing", "Label with precision\nDrawing drills"),
            ("Weakness clinics", "Fix my weak topics\nTargeted drills"),
            ("Speed and accuracy", "Objective speed rounds\nScore tracking"),
            ("Final mock", "Last full paper\nFinal notes"),
            ("WAEC readiness", "Exam day strategy\nSend off"),
        ],
    },
    "Economics": {
        1: [
            ("Revision of sss two work", "Demand and supply warm up\nQuiz"),
            ("Basic economic problems", "Scarcity and choice\nExam questions"),
            ("Demand theory", "Elasticity applications\nExam questions"),
            ("Supply theory", "Elasticity of supply\nExam questions"),
            ("Price determination", "Equilibrium analysis\nExam questions"),
            ("Production theory", "Factors and productivity\nExam questions"),
            ("Cost and revenue", "Fixed and variable costs\nExam questions"),
            ("Market structures", "Perfect competition to monopoly\nExam questions"),
            ("Business organisations", "Sole trader to company\nExam questions"),
            ("Revision and WAEC practice", "Past paper one\nMark and correct"),
        ],
        2: [
            ("Population theory", "Census and growth\nNigerian population"),
            ("Labour market", "Wages and unemployment\nExam questions"),
            ("Money and inflation", "Causes and control\nExam questions"),
            ("Banking", "Central and commercial\nExam questions"),
            ("Public finance", "Taxation and budget\nExam questions"),
            ("National income", "GDP calculations\nExam questions"),
            ("International trade", "Balance of payments\nExam questions"),
            ("Economic development", "Growth plans\nNigeria's plans"),
            ("Mock paper one", "Full paper\nMark and review"),
            ("Revision and WAEC practice", "Past paper two\nMark and correct"),
        ],
        3: [
            ("WAEC marathon: micro", "Demand to market structures\nPast questions"),
            ("WAEC marathon: macro", "Money to national income\nPast questions"),
            ("WAEC marathon: development", "Trade and plans\nPast questions"),
            ("Mock examination", "Full dress\nMark and review"),
            ("Data response drills", "Tables and graphs\nInterpretation practice"),
            ("Weakness clinics", "Fix my weak topics\nTargeted drills"),
            ("Essay practice", "Structure and speed\nTimed essays"),
            ("Speed and accuracy", "Objective rounds\nScore tracking"),
            ("Final mock", "Last full paper\nFinal notes"),
            ("WAEC readiness", "Exam day strategy\nSend off"),
        ],
    },
    "Government": {
        1: [
            ("Revision of sss two work", "Concepts warm up\nQuiz"),
            ("Basic concepts review", "Power, authority, legitimacy\nExam questions"),
            ("The state and nation", "Features of a state\nExam questions"),
            ("Democracy", "Types and practice\nExam questions"),
            ("Rule of law", "Principles and limits\nExam questions"),
            ("Separation of powers", "Checks and balances\nExam questions"),
            ("Constitutions", "Written and unwritten\nExam questions"),
            ("Federalism", "Nigerian federalism\nExam questions"),
            ("Political parties", "Functions and types\nExam questions"),
            ("Revision and WAEC practice", "Past paper one\nMark and correct"),
        ],
        2: [
            ("Electoral systems", "Voting and elections\nExam questions"),
            ("Public opinion", "Formation and measurement\nExam questions"),
            ("Pressure groups", "Types and tactics\nExam questions"),
            ("Civil service", "Structure and role\nExam questions"),
            ("Local government", "Reforms and functions\nExam questions"),
            ("Military in politics", "Coups and rule\nExam questions"),
            ("Foreign policy", "Nigeria's policy\nExam questions"),
            ("International organisations", "UN, AU, ECOWAS\nExam questions"),
            ("Mock paper one", "Full paper\nMark and review"),
            ("Revision and WAEC practice", "Past paper two\nMark and correct"),
        ],
        3: [
            ("WAEC marathon: concepts", "Definitions and examples\nPast questions"),
            ("WAEC marathon: institutions", "Organs of government\nPast questions"),
            ("WAEC marathon: Nigeria politics", "Pre and post independence\nPast questions"),
            ("WAEC marathon: international", "Organisations and policies\nPast questions"),
            ("Mock examination", "Full dress\nMark and review"),
            ("Essay drills", "Point and evidence\nTimed essays"),
            ("Weakness clinics", "Fix my weak topics\nTargeted drills"),
            ("Current affairs", "Nigeria today\nQuiz rounds"),
            ("Final mock", "Last full paper\nFinal notes"),
            ("WAEC readiness", "Exam day strategy\nSend off"),
        ],
    },
    "Literature-in-English": {
        1: [
            ("Revision of set texts", "Plot and characters warm up\nQuiz"),
            ("Figures of speech", "Identification drills\nUse in essays"),
            ("Drama: set text one", "Act by act study\nCharacter questions"),
            ("Drama: themes", "Central themes\nEssay practice"),
            ("Prose: set text", "Chapters discussion\nCharacter mapping"),
            ("Prose: style", "Narrator and language\nEssay practice"),
            ("Poetry: set poems", "Line by line study\nTheme and mood"),
            ("Poetry: devices", "Sound and sense\nEssay practice"),
            ("Essay writing for literature", "PEEL paragraphs\nTimed essays"),
            ("Revision and WAEC practice", "Past paper one\nMark and correct"),
        ],
        2: [
            ("Drama: text two", "Act by act study\nCompare the texts"),
            ("Drama: dramatic techniques", "Irony and conflict\nEssay practice"),
            ("Prose: themes", "Themes and lessons\nEssay practice"),
            ("Prose: setting and plot", "Structure questions\nEssay practice"),
            ("Poetry: new poems", "Reading unseen poems\nAnswer drills"),
            ("Poetry: comparison", "Compare two poems\nEssay practice"),
            ("Context questions", "Quote and explain\nDrills"),
            ("Character analysis", "Main and minor\nEssay practice"),
            ("Mock paper one", "Full paper\nMark and review"),
            ("Revision and WAEC practice", "Past paper two\nMark and correct"),
        ],
        3: [
            ("WAEC marathon: drama", "Both texts revision\nPast questions"),
            ("WAEC marathon: prose", "Both texts revision\nPast questions"),
            ("WAEC marathon: poetry", "All poems revision\nPast questions"),
            ("Mock examination", "Full dress\nMark and review"),
            ("Unseen drills", "Prose and poem\nTimed answers"),
            ("Weakness clinics", "Fix my weak texts\nTargeted drills"),
            ("Essay mastery", "Quotes and analysis\nTimed essays"),
            ("Speed and accuracy", "Objective rounds\nScore tracking"),
            ("Final mock", "Last full paper\nFinal notes"),
            ("WAEC readiness", "Exam day strategy\nSend off"),
        ],
    },
    "Agricultural Science": {
        1: [
            ("Revision of sss two work", "Crops and soils warm up\nQuiz"),
            ("Agricultural ecology", "Ecosystem and habitats\nExam questions"),
            ("Rock formation", "Types and weathering\nExam questions"),
            ("Soil science", "Profile and properties\nExam questions"),
            ("Soil fertility", "Nutrients and cycles\nExam questions"),
            ("Land use", "Nigerian land use\nExam questions"),
            ("Crop classification", "Families and uses\nExam questions"),
            ("Crop husbandry", "Maize and cassava\nPractices drill"),
            ("Weed science", "Types and control\nExam questions"),
            ("Revision and WAEC practice", "Past paper one\nMark and correct"),
        ],
        2: [
            ("Animal anatomy", "Systems of farm animals\nExam questions"),
            ("Animal reproduction", "Breeds and breeding\nExam questions"),
            ("Animal nutrition", "Rations and digestion\nExam questions"),
            ("Animal health", "Diseases and parasites\nExam questions"),
            ("Fisheries", "Pond management\nExam questions"),
            ("Farm machinery", "Types and maintenance\nExam questions"),
            ("Farm surveying", "Instruments and plans\nExam questions"),
            ("Farm records", "Books and accounts\nExam questions"),
            ("Marketing", "Channels and prices\nExam questions"),
            ("Revision and WAEC practice", "Past paper two\nMark and correct"),
        ],
        3: [
            ("WAEC marathon: crop science", "Past questions\nDaily drills"),
            ("WAEC marathon: animal science", "Past questions\nDaily drills"),
            ("WAEC marathon: soil science", "Past questions\nDaily drills"),
            ("Mock examination", "Full dress\nMark and review"),
            ("Practical marathon", "Specimens and tools\nIdentification drills"),
            ("Weakness clinics", "Fix my weak topics\nTargeted drills"),
            ("Farm project completion", "Finish my plot\nYield records"),
            ("Speed and accuracy", "Objective rounds\nScore tracking"),
            ("Final mock", "Last full paper\nFinal notes"),
            ("WAEC readiness", "Exam day strategy\nSend off"),
        ],
    },
    "Further Mathematics": {
        1: [
            ("Revision of sss two work", "Pure math warm up\nQuiz"),
            ("Sets and functions", "Domain and range\nExam questions"),
            ("Polynomials", "Roots and factor theorem\nExam questions"),
            ("Binomial series", "Expansions\nExam questions"),
            ("Trigonometric identities", "Proofs and equations\nExam questions"),
            ("Sequences and series", "AP and GP advanced\nExam questions"),
            ("Matrices", "Operations and inverse\nExam questions"),
            ("Determinants", "Solving systems\nExam questions"),
            ("Complex numbers", "Argand diagrams\nExam questions"),
            ("Revision and exam practice", "Past paper one\nMark and correct"),
        ],
        2: [
            ("Differentiation", "Rules and applications\nExam questions"),
            ("Integration", "Techniques and areas\nExam questions"),
            ("Kinematics", "Motion calculus\nExam questions"),
            ("Statics", "Forces in equilibrium\nExam questions"),
            ("Dynamics", "Newton laws advanced\nExam questions"),
            ("Vectors", "Lines and planes\nExam questions"),
            ("Probability distributions", "Binomial and normal\nExam questions"),
            ("Data statistics", "Dispersion measures\nExam questions"),
            ("Mock paper one", "Full paper\nMark and review"),
            ("Revision and exam practice", "Past paper two\nMark and correct"),
        ],
        3: [
            ("Exam marathon: pure", "Past questions\nDaily drills"),
            ("Exam marathon: mechanics", "Past questions\nDaily drills"),
            ("Exam marathon: statistics", "Past questions\nDaily drills"),
            ("Mock examination", "Full dress\nMark and review"),
            ("Weakness clinics", "Fix my weak topics\nTargeted drills"),
            ("Proof mastery", "Write clean proofs\nTimed practice"),
            ("Speed and accuracy", "Objective rounds\nScore tracking"),
            ("Advanced clinics", "Harder questions\nStretch practice"),
            ("Final mock", "Last full paper\nFinal notes"),
            ("Exam readiness", "Exam day strategy\nSend off"),
        ],
    },
    "Commerce": {
        1: [
            ("Revision of sss two work", "Trade concepts warm up\nQuiz"),
            ("Introduction to commerce", "Scope and importance\nExam questions"),
            ("Home trade", "Channels and documents\nExam questions"),
            ("Foreign trade", "Export procedures\nExam questions"),
            ("Trade documents", "Invoice to bill of lading\nExam questions"),
            ("Transport", "Modes and choice\nExam questions"),
            ("Insurance", "Principles and types\nExam questions"),
            ("Banking", "Services and instruments\nExam questions"),
            ("Warehousing", "Types and functions\nExam questions"),
            ("Revision and WAEC practice", "Past paper one\nMark and correct"),
        ],
        2: [
            ("Business units", "Forms of ownership\nExam questions"),
            ("Partnership and companies", "Formation papers\nExam questions"),
            ("Cooperatives", "Principles and types\nExam questions"),
            ("Trade associations", "Chambers and unions\nExam questions"),
            ("Communication", "Business communication\nExam questions"),
            ("Advertising", "Types and media\nExam questions"),
            ("Marketing", "Mix and research\nExam questions"),
            ("Consumer protection", "Rights and agencies\nExam questions"),
            ("Mock paper one", "Full paper\nMark and review"),
            ("Revision and WAEC practice", "Past paper two\nMark and correct"),
        ],
        3: [
            ("WAEC marathon: trade", "Past questions\nDaily drills"),
            ("WAEC marathon: business units", "Past questions\nDaily drills"),
            ("WAEC marathon: aids to trade", "Past questions\nDaily drills"),
            ("Mock examination", "Full dress\nMark and review"),
            ("Weakness clinics", "Fix my weak topics\nTargeted drills"),
            ("Case studies", "Business scenarios\nSolve and discuss"),
            ("Speed and accuracy", "Objective rounds\nScore tracking"),
            ("Entrepreneurship project", "My business plan\nPresent the plan"),
            ("Final mock", "Last full paper\nFinal notes"),
            ("WAEC readiness", "Exam day strategy\nSend off"),
        ],
    },
    "Financial Accounting": {
        1: [
            ("Revision of sss two work", "Ledger warm up\nQuiz"),
            ("Accounting concepts", "Principles and conventions\nExam questions"),
            ("Books of original entry", "Journals and day books\nPractice sets"),
            ("Ledger accounts", "Posting rules\nPractice sets"),
            ("Trial balance", "Extract and balance\nPractice sets"),
            ("Trading, profit and loss", "Prepare full account\nPractice sets"),
            ("Balance sheet", "Assets and liabilities\nPractice sets"),
            ("Adjustments: accruals", "Prepayments and owing\nPractice sets"),
            ("Depreciation", "Straight line and reducing\nPractice sets"),
            ("Revision and WAEC practice", "Past paper one\nMark and correct"),
        ],
        2: [
            ("Bad debts and provisions", "Write off and provision\nPractice sets"),
            ("Bank reconciliation", "Adjust the cash book\nPractice sets"),
            ("Control accounts", "Sales and purchases\nPractice sets"),
            ("Manufacturing accounts", "Cost of production\nPractice sets"),
            ("Incomplete records", "Statement of affairs\nPractice sets"),
            ("Not for profit", "Receipts and payments\nPractice sets"),
            ("Partnership accounts", " appropriation account\nPractice sets"),
            ("Company accounts", "Share capital basics\nPractice sets"),
            ("Mock paper one", "Full paper\nMark and review"),
            ("Revision and WAEC practice", "Past paper two\nMark and correct"),
        ],
        3: [
            ("WAEC marathon: final accounts", "Past questions\nPractice sets"),
            ("WAEC marathon: adjustments", "Past questions\nPractice sets"),
            ("WAEC marathon: partnership", "Past questions\nPractice sets"),
            ("Mock examination", "Full dress\nMark and review"),
            ("Weakness clinics", "Fix my weak topics\nTargeted drills"),
            ("Speed and accuracy", "Objective rounds\nScore tracking"),
            ("Project: full set of accounts", "Do a full set\nSubmit my work"),
            ("Final mock", "Last full paper\nFinal notes"),
            ("WAEC readiness", "Exam day strategy\nSend off"),
        ],
    },
    "Civic Education": {
        1: [
            ("Revision of sss two work", "Values and democracy warm up\nQuiz"),
            ("Responsible parenthood", "Roles and challenges\nExam questions"),
            ("Traffic regulations", "Rules and agencies\nExam questions"),
            ("Interpersonal relationships", "Values that sustain\nExam questions"),
            ("Employment", "Types and creation\nExam questions"),
            (" Poverty and its reduction", "Causes and programmes\nExam questions"),
            ("Political apathy", "Causes and solutions\nExam questions"),
            ("Public service", "Principles and accountability\nExam questions"),
            ("Civil society participation", "NGOs and civic action\nExam questions"),
            ("Revision and WAEC practice", "Past paper one\nMark and correct"),
        ],
        2: [
            ("Democracy and participation", "Elections and civic duties\nExam questions"),
            ("Rule of law", "Application in Nigeria\nExam questions"),
            ("Human rights", "Protection agencies\nExam questions"),
            ("Children and women rights", "Laws and protection\nExam questions"),
            ("Ethical values", "Honesty and integrity\nExam questions"),
            ("Community service", "Projects that help\nMy service log"),
            ("National consciousness", "Symbols and identity\nExam questions"),
            ("Capitalist democracy", "Features and challenges\nExam questions"),
            ("Mock paper one", "Full paper\nMark and review"),
            ("Revision and WAEC practice", "Past paper two\nMark and correct"),
        ],
        3: [
            ("WAEC marathon: values", "Past questions\nDaily drills"),
            ("WAEC marathon: democracy", "Past questions\nDaily drills"),
            ("WAEC marathon: rights", "Past questions\nDaily drills"),
            ("Mock examination", "Full dress\nMark and review"),
            ("Weakness clinics", "Fix my weak topics\nTargeted drills"),
            ("Project: civic action", "Plan and act\nReport impact"),
            ("Speed and accuracy", "Objective rounds\nScore tracking"),
            ("Current affairs", "Nigeria and the world\nQuiz rounds"),
            ("Final mock", "Last full paper\nFinal notes"),
            ("WAEC readiness", "Exam day strategy\nSend off"),
        ],
    },
    "Geography": {
        1: [
            ("Revision of sss two work", "Map work warm up\nQuiz"),
            ("The earth as a planet", "Movements and effects\nExam questions"),
            ("Rocks", "Types and uses\nExam questions"),
            ("Plate tectonics", "Landforms of folding\nExam questions"),
            ("Volcanicity", "Landforms and features\nExam questions"),
            ("Weathering and erosion", "Processes and landforms\nExam questions"),
            ("River systems", "Course and features\nExam questions"),
            ("Climate of Nigeria", "Regions and seasons\nExam questions"),
            ("Map reading", "Contours and scale\nPractice drills"),
            ("Revision and WAEC practice", "Past paper one\nMark and correct"),
        ],
        2: [
            ("Population", "Distribution and migration\nExam questions"),
            ("Settlement", "Types and patterns\nExam questions"),
            ("Agriculture in Nigeria", "Systems and problems\nExam questions"),
            ("Minerals in Nigeria", "Distribution and mining\nExam questions"),
            ("Power and industry", "Location factors\nExam questions"),
            ("Transport in Nigeria", "Modes and networks\nExam questions"),
            ("Trade in Nigeria", "Internal and external\nExam questions"),
            ("Tourism", "Centres and benefits\nExam questions"),
            ("Mock paper one", "Full paper\nMark and review"),
            ("Revision and WAEC practice", "Past paper two\nMark and correct"),
        ],
        3: [
            ("WAEC marathon: physical", "Landforms and climate\nPast questions"),
            ("WAEC marathon: human", "Population and settlement\nPast questions"),
            ("WAEC marathon: economic", "Resources and industry\nPast questions"),
            ("WAEC marathon: map work", "Extract questions\nTimed drills"),
            ("Mock examination", "Full dress\nMark and review"),
            ("Weakness clinics", "Fix my weak topics\nTargeted drills"),
            ("Field project", "Study my area\nWrite my report"),
            ("Speed and accuracy", "Objective rounds\nScore tracking"),
            ("Final mock", "Last full paper\nFinal notes"),
            ("WAEC readiness", "Exam day strategy\nSend off"),
        ],
    },
}
