#!/usr/bin/env python3
"""JSS 1 scheme data: twelve subjects, three terms, ten weeks each."""

JSS_1 = {
    "English Studies": {
        1: [
            ("Revision of primary work", "Parts of speech recap\nReading and summary drill"),
            ("Comprehension: the new environment", "Read and answer\nVocabulary in context"),
            ("Listening and speaking: oral English", "Vowel sounds practice\nMinimal pairs"),
            ("Grammar: parts of speech review", "Nouns and pronouns\nIdentify in passages"),
            ("Grammar: noun number and case", "Regular and irregular plurals\nPossessive forms"),
            ("Vocabulary development: word formation", "Prefixes and suffixes\nBuild new words"),
            ("Composition: narrative writing", "My first day in school\nPlan and write"),
            ("Literature: types of literature", "Prose, poetry, drama\nExamples of each"),
            ("Reading: comprehension strategies", "Skimming and scanning\nTimed passages"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Comprehension: means of transport", "Read and answer\nSummary practice"),
            ("Listening: following directions", "Map talk exercises\nGive and take directions"),
            ("Grammar: verbs and tenses", "Present and past tense\nConsistent tense use"),
            ("Grammar: adjectives and comparison", "Comparative and superlative\nUse in writing"),
            ("Grammar: adverbs", "Formation and placement\nUse in paragraphs"),
            ("Vocabulary: synonyms and antonyms", "Word choice in context\nReplace and improve"),
            ("Composition: descriptive writing", "Describe my school compound\nSensory details"),
            ("Literature: figures of speech", "Simile and metaphor\nIdentify in poems"),
            ("Writing: informal letter", "Letter to a friend\nFormat and tone"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Comprehension: agriculture in Nigeria", "Read and answer\nInterpretive questions"),
            ("Listening: telephone conversations", "Polite phone talk\nRole play dialogues"),
            ("Grammar: prepositions and conjunctions", "Joining words in use\nFill the gaps"),
            ("Grammar: question formation", "Yes or no and wh questions\nAsk and answer"),
            ("Grammar: punctuation review", "Comma, colon, semicolon\nPunctuate passages"),
            ("Vocabulary: idioms and expressions", "Common idioms\nUse in context"),
            ("Composition: expository writing", "How to make garri\nProcess writing"),
            ("Literature: poetry appreciation", "Read and discuss\nTheme and mood"),
            ("Writing: argumentative basics", "My point with reasons\nSimple debate writing"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Mathematics": {
        1: [
            ("Whole numbers: place value", "Numbers in figures and words\nRoman numerals to 100"),
            ("Fractions: types and equivalents", "Proper and improper\nEquivalent fractions"),
            ("Fractions: operations", "Add and subtract like fractions\nWord problems"),
            ("Decimals: place value and operations", "Add and subtract decimals\nMoney problems"),
            ("Percentages", "Fraction to percent\nPercent of quantities"),
            ("Indices basics", "Squares and cubes\nIndex notation"),
            ("LCM and HCF", "Prime factorisation\nSolve with LCM and HCF"),
            ("Estimation and approximation", "Round to places\nEstimate answers"),
            ("Number patterns and sequences", "Arithmetic patterns\nFind the rule"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Algebraic expressions", "Terms and coefficients\nSimplify expressions"),
            ("Expansion of brackets", "Distributive law\nExpand and simplify"),
            ("Factorisation basics", "Common factors\nFactorise simple expressions"),
            ("Linear equations", "One unknown\nSolve and check"),
            ("Word problems with equations", "Translate to algebra\nSolve real problems"),
            ("Geometry: lines and angles", "Angle types\nAngles on a line and at a point"),
            ("Angles in polygons", "Triangle angle sum\nQuadrilateral angles"),
            ("Construction: bisection", "Bisect lines and angles\nCompass work"),
            ("Data collection and presentation", "Frequency tables\nBar charts and pie charts"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Statistics: measures of average", "Mean, median, mode\nFind all three"),
            ("Statistics: range and applications", "Spread of data\nReal data project"),
            ("Simple equations and inequalities", "Solve and graph\nNumber line work"),
            ("Graphs: Cartesian plane", "Plot coordinates\nLinear graphs"),
            ("Graphs: reading information", "Interpret graphs\nJourney graphs"),
            ("Scale drawing", "Map scales\nDraw to scale"),
            ("Mensuration: perimeter and area", "Rectangles and triangles\nComposite shapes"),
            ("Mensuration: volume and capacity", "Cuboids and cylinders\nWord problems"),
            ("Everyday arithmetic", "Taxes and bills\nSimple interest"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Basic Science": {
        1: [
            ("Science: what it is", "Branches of science\nScience and everyday life"),
            ("Scientific method", "Observe, question, test\nClass experiment"),
            ("Laboratory rules and safety", "Safe conduct in the lab\nFirst aid basics"),
            ("Measurements: length", "Metre rule use\nRecord and convert"),
            ("Measurements: mass and weight", "Beam balance\nDifference explained"),
            ("Measurements: time", "Clocks and stopwatches\nPendulum activity"),
            ("Living and non living things", "Characteristics of life\nClassify specimens"),
            ("Classification of living things", "Kingdoms overview\nSort the specimens"),
            ("The human body: skeleton", "Bones and joints\nLabel the skeleton"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Digestive system", "Organs and enzymes\nFollow the food path"),
            ("Circulatory system", "Heart and vessels\nPulse experiment"),
            ("Respiratory system", "Breathing mechanism\nModel the lungs"),
            ("Excretory system", "Kidneys and skin\nWaste and health"),
            ("Reproduction in humans", "Puberty basics\nFamily health talk"),
            ("Reproduction in plants", "Pollination and fertilisation\nFlower dissection"),
            ("Photosynthesis", "Conditions and products\nLeaf experiment"),
            ("Ecosystem basics", "Habitats and food chains\nBuild a food web"),
            ("Environmental pollution", "Air, water, land\nEffects and control"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Matter: states and properties", "Solids, liquids, gases\nChange of state demos"),
            ("Elements, compounds, mixtures", "Sort the substances\nEveryday examples"),
            ("Atoms and molecules basics", "Structure of the atom\nSimple models"),
            ("Energy: forms and sources", "Kinetic and potential\nRenewable energy talk"),
            ("Energy conversion devices", "Torch, fan, generator\nTrace the energy"),
            ("Electricity basics", "Circuits and symbols\nBuild simple circuits"),
            ("Magnetism", "Magnetic fields\nMake a compass"),
            ("Forces and motion basics", "Push and pull\nSpeed calculations"),
            ("Space science basics", "Solar system\nEarth movements"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Basic Technology": {
        1: [
            ("Technology: meaning and history", "Primitive to modern\nTrace the development"),
            ("Workshop safety", "Rules and accidents\nSafe working habits"),
            ("Materials: wood", "Types of timber\nIdentify and test"),
            ("Materials: metals", "Ferrous and non ferrous\nCommon examples"),
            ("Materials: ceramics and plastics", "Types and uses\nSort the samples"),
            ("Hand tools: measuring tools", "Rule, try square, calipers\nUse and care"),
            ("Hand tools: marking tools", "Pencils, scribers, dividers\nMark accurately"),
            ("Hand tools: cutting tools", "Saws and chisels\nSafe cutting practice"),
            ("Drawing instruments", "Board, tee square, set squares\nSet up and use"),
            ("Revision and assessment", "Term work review\nPractical quiz"),
        ],
        2: [
            ("Technical drawing: lines and lettering", "Line types\nFreehand lettering"),
            ("Drawing: borders and title blocks", "Sheet layout\nNeat presentation"),
            ("Geometric construction: bisection", "Bisect lines and angles\nConstruction practice"),
            ("Construction: polygons", "Triangles and quadrilaterals\nConstruct with instruments"),
            ("Construction: circles and tangents", "Circle theorems in drawing\nTangent practice"),
            ("Shapes: enlargement and reduction", "Scale factors\nRedraw to scale"),
            ("Isometric drawing", "Isometric axes\nDraw blocks in isometric"),
            ("Oblique drawing", "Cavalier and cabinet\nDraw simple objects"),
            ("Orthographic projection basics", "First angle views\nFront and end views"),
            ("Revision and assessment", "Term work review\nPractical quiz"),
        ],
        3: [
            ("Orthographic projection: three views", "Front, side, plan\nProject accurately"),
            ("Sectioning basics", "Cutting planes\nDraw sections"),
            ("Fastening methods", "Nails, screws, rivets\nJoin materials"),
            ("Woodwork joints", "Halving and housing joints\nMake a joint"),
            ("Metalwork processes", "Marking out and cutting\nSimple metal exercise"),
            ("Plastics processes", "Moulding basics\nForm simple shapes"),
            ("Electricity: simple circuits", "Components and symbols\nWire a board"),
            ("Electronic components", "Resistors and diodes\nIdentify and test"),
            ("Building: types and parts", "Foundation to roof\nLabel a building"),
            ("Revision and assessment", "Year work review\nEnd of year practical"),
        ],
    },
    "Business Studies": {
        1: [
            ("Business: meaning and scope", "Commerce and trade\nBusiness in society"),
            ("The office", "Types of offices\nOffice functions"),
            ("Office staff", "Clerical duties\nQualities of office staff"),
            ("Office equipment", "Machines and tools\nUses of equipment"),
            ("Business documents: introduction", "Letterheads and memos\nSimple documents"),
            ("The letter: business format", "Parts of a business letter\nWrite a simple letter"),
            ("Filing", "Why we file\nSimple filing methods"),
            ("Communication in business", "Verbal and written\nChoose the channel"),
            ("The market", "Buying and selling\nMarket structures talk"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Trade: home and foreign", "Wholesale and retail\nChain of distribution"),
            ("Retail trade", "Types of retailers\nCredit and cash sales"),
            ("Wholesale trade", "Role of the wholesaler\nWarehousing talk"),
            ("Documents: invoices and receipts", "Fill an invoice\nWrite a receipt"),
            ("Documents: order and delivery notes", "Process an order\nCheck deliveries"),
            ("Banking basics", "Types of accounts\nPay in and withdraw"),
            ("Cheques", "Parts of a cheque\nFill a cheque correctly"),
            ("Savings", "Why save\nSimple savings plan"),
            ("Simple bookkeeping", "Cash book basics\nRecord transactions"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Bookkeeping: double entry", "Debit and credit\nPost simple entries"),
            ("Ledger accounts", "Open and balance\nPersonal and real accounts"),
            ("Trial balance", "Check the equality\nSpot the errors"),
            ("Trading account basics", "Sales and cost of goods\nGross profit idea"),
            ("Profit and loss basics", "Expenses and net profit\nSimple computation"),
            ("Transport in business", "Modes of transport\nChoose the means"),
            ("Insurance basics", "Risk and cover\nSimple examples"),
            ("Entrepreneurship", "Traits of entrepreneurs\nStart small ideas"),
            ("Consumer protection", "Rights of buyers\nStandards organisations"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Civic Education": {
        1: [
            ("National values: meaning", "Values we share\nIdentify national values"),
            ("Honesty", "Truthfulness in life\nBenefits of honesty"),
            ("Cooperation", "Working together\nTeam projects"),
            ("Self reliance", "Skills for life\nBe productive"),
            ("Rights of citizens", "Fundamental rights\nKnow my rights"),
            ("Duties and obligations", "Obey laws, pay taxes\nPerform my duties"),
            ("Democracy: meaning", "Government by the people\nFeatures of democracy"),
            ("Rule of law", "Equality before the law\nApply the principle"),
            ("National consciousness", "Nigeria's identity\nSymbols and meanings"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("The constitution", "Meaning and sources\nWhy constitutions matter"),
            ("Features of the Nigerian constitution", "Key provisions\nRights and duties"),
            ("Federalism in Nigeria", "Three tiers of government\nPowers shared"),
            ("Citizenship: meaning", "Who is a citizen\nWays of becoming one"),
            ("Rights and duties of a citizen", "Balance of both\nCitizen practice"),
            ("Democracy: institutions", "INEC and parties\nElection processes"),
            ("Voting and elections", "Register and vote\nFree and fair polls"),
            ("Public opinion and the press", "Voice of the people\nMedia roles"),
            ("Civil society groups", "NGOs and unions\nRoles in society"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Capitalist democracy", "Features and values\nFree enterprise talk"),
            ("Political apathy", "Why people opt out\nDangers of apathy"),
            ("Popular participation", "Forms of participation\nJoin civic life"),
            ("Human rights: meaning", "Universal rights\nRights in Nigeria"),
            ("Human rights: promotion", "Agencies and bodies\nProtect the rights"),
            ("Environmental problems", "Pollution and erosion\nCommunity solutions"),
            (" Drug abuse: dangers", "Effects on youth\nPrevention strategies"),
            ("Civic duties in the community", "Sanitation and service\nParticipate locally"),
            ("Peace and conflict resolution", "Causes of conflict\nResolve peacefully"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Cultural and Creative Arts": {
        1: [
            ("Arts: meaning and branches", "Visual and performing arts\nArts in Nigeria"),
            ("Elements of art", "Line, shape, form, colour\nIdentify in works"),
            ("Principles of design", "Balance and harmony\nAnalyse compositions"),
            ("Drawing: shading techniques", "Hatching and blending\nShade simple forms"),
            ("Colour theory", "Primary and secondary\nColour mixing practice"),
            ("Music: theory basics", "Staff and note values\nRead simple rhythms"),
            ("Music: Nigerian folk songs", "Learn and perform\nSong types talk"),
            ("Dance: Nigerian dances", "Types and cultures\nLearn basic steps"),
            ("Drama: introduction", "Elements of drama\nSimple scene work"),
            ("Revision and assessment", "Term work review\nPractical display"),
        ],
        2: [
            ("Drawing: still life", "Compose and sketch\nTonal study"),
            ("Painting: poster colour", "Flat and gradient washes\nPaint a composition"),
            ("Crafts: basketry basics", "Materials and techniques\nWeave simple items"),
            ("Ceramics: hand building", "Pinch and coil\nMake a pot"),
            ("Music: recorder playing", "Notes B, A, G\nPlay simple tunes"),
            ("Music: choral singing", "Unison and rounds\nPerform a song"),
            ("Dance: choreography basics", "Motifs and repetition\nCreate a dance"),
            ("Drama: improvisation", "Build scenes together\nGroup performance"),
            ("Theatre arts: costume and makeup", "Design for characters\nApply basics"),
            ("Revision and assessment", "Term work review\nPractical display"),
        ],
        3: [
            ("Sculpture basics", "Modelling and carving\nMake a sculpture"),
            ("Graphics: logo design", "Symbols and identity\nDesign a logo"),
            ("Textile: tie and dye", "Patterns and techniques\nProduce a cloth"),
            ("Music: African instruments", "Chordophones and idiophones\nClassify instruments"),
            ("Music: composition basics", "Write a melody\nPerform my song"),
            ("Dance: dance drama", "Story in movement\nGroup production"),
            ("Drama: play production", "Rehearse and stage\nClass production"),
            ("Exhibition: mounting works", "Label and display\nOrganise an exhibition"),
            ("Arts appreciation", "Visit and discuss\nWrite a review"),
            ("Revision and assessment", "Year work review\nEnd of year display"),
        ],
    },
    "Home Economics": {
        1: [
            ("Home economics: meaning and areas", "Scope of the subject\nCareers in home economics"),
            ("The family", "Types of families\nFamily roles"),
            ("Family needs and goals", "Priorities at home\nPlan family goals"),
            ("Personal hygiene", "Daily grooming\nClean habits"),
            ("The home: rooms and uses", "Parts of the house\nCare of rooms"),
            ("Cleaning agents and tools", "Soaps and brooms\nUse correctly"),
            ("Food groups", "Six classes of food\nPlan a meal"),
            ("Kitchen tools", "Large and small equipment\nUse and care"),
            ("Laundry basics", "Sort, wash, dry\nWash simple items"),
            ("Revision and assessment", "Term work review\nPractical quiz"),
        ],
        2: [
            ("Food preparation terms", "Boil, bake, grill\nMatch to dishes"),
            ("Cooking methods: moist heat", "Boiling and steaming\nPrepare simple dishes"),
            ("Cooking methods: dry heat", "Roasting and baking\nPrepare simple dishes"),
            ("Food storage", "Store room and fridge\nPrevent spoilage"),
            ("Textiles: fibres and fabrics", "Natural and synthetic\nIdentify fabrics"),
            ("Basic stitches", "Running and back stitch\nSew a sampler"),
            ("Simple articles: handkerchief", "Cut and sew\nFinish neatly"),
            ("Home accidents", "Causes and prevention\nFirst aid basics"),
            ("Family resources", "Time and money management\nBudget basics"),
            ("Revision and assessment", "Term work review\nPractical quiz"),
        ],
        3: [
            ("Meal planning", "Balanced diet plans\nPlan family meals"),
            ("Table setting and etiquette", "Lay the table\nGood table manners"),
            ("Sewing machine basics", "Parts and threading\nMachine practice"),
            ("Simple garments: apron", "Cut and assemble\nSew the apron"),
            ("Clothing care", "Wash, iron, store\nCare for clothes"),
            ("Clothing repair", "Mend and patch\nRepair garments"),
            ("Consumer education", "Buy wisely\nCheck quality and labels"),
            ("Entrepreneurship at home", "Small home businesses\nPlan a mini venture"),
            ("Family health", "Immunisation and clinics\nHealthy family habits"),
            ("Revision and assessment", "Year work review\nEnd of year practical"),
        ],
    },
    "Information Technology": {
        1: [
            ("Computer: definition and generations", "History of computers\nGenerations recap"),
            ("Characteristics of computers", "Speed and accuracy\nWhy computers help"),
            ("Computer hardware: input devices", "Keyboard to scanners\nIdentify and use"),
            ("Computer hardware: output devices", "Monitors and printers\nIdentify and use"),
            ("The system unit", "CPU and memory\nInside the box"),
            ("Storage devices", "Hard disk and flash drives\nCompare capacities"),
            ("Software: types", "System and application\nExamples of each"),
            ("Operating system basics", "Windows introduction\nFiles and folders"),
            ("Keyboarding skills", "Home row technique\nSpeed and accuracy drills"),
            ("Revision and assessment", "Term work review\nPractical quiz"),
        ],
        2: [
            ("Word processing: introduction", "Features of word processors\nCreate documents"),
            ("Document formatting", "Fonts and paragraphs\nFormat a project"),
            ("Page layout", "Margins and orientation\nSet up pages"),
            ("Tables and lists", "Insert and edit\nOrganise information"),
            ("Graphics in documents", "Insert and position\nIllustrate my work"),
            ("Spreadsheet basics", "Cells, rows, columns\nEnter and edit data"),
            ("Spreadsheet formulas", "Sum and average\nCompute results"),
            ("Charts in spreadsheets", "Create and label\nPresent data"),
            ("Internet: introduction", "Networks and the web\nBrowse safely"),
            ("Revision and assessment", "Term work review\nPractical quiz"),
        ],
        3: [
            ("Email communication", "Compose, send, reply\nNetiquette rules"),
            ("Search skills", "Keywords and phrases\nResearch a topic"),
            ("Digital safety: threats", "Viruses and scams\nProtect my device"),
            ("Digital safety: passwords", "Strong passwords\nAccount protection"),
            ("Presentation software", "Slides and layouts\nBuild a deck"),
            ("Delivering presentations", "Slide shows\nPresent to class"),
            ("Multimedia basics", "Audio and video files\nPlay and organise"),
            ("Computers in society", "Schools, hospitals, banks\nCareer fields"),
            ("Emerging technologies", "AI and robots talk\nFuture of work"),
            ("Revision and assessment", "Year work review\nEnd of year practical"),
        ],
    },
    "Physical and Health Education": {
        1: [
            ("Physical education: meaning and goals", "Why we exercise\nFitness for life"),
            ("Athletics: track events", "Sprints and relays\nRules of track"),
            ("Athletics: field events", "Throws and jumps\nSafety in field events"),
            ("Football: basic skills", "Passing, dribbling, shooting\nSmall sided games"),
            ("Volleyball: basic skills", "Serve, pass, set\nRally practice"),
            ("Basketball: basic skills", "Dribble, pass, shoot\nMini games"),
            ("Recreation: meaning", "Indoor and outdoor games\nPlan recreation"),
            ("Health: personal hygiene", "Body care routines\nGrooming habits"),
            ("Health: nutrition", "Classes of food\nBalanced diet planning"),
            ("Revision and assessment", "Term work review\nSkills display"),
        ],
        2: [
            ("Gymnastics: tumbling", "Rolls and balances\nSafe practice"),
            ("Gymnastics: apparatus basics", "Bench and beam\nSpotting rules"),
            ("Handball: skills", "Dribble and shoot\nRules of handball"),
            ("Table tennis: skills", "Serve and strokes\nSingles play"),
            ("Track and field: officiating", "Roles of officials\nTime a race"),
            ("First aid: meaning and scope", "The first aider\nSimple treatments"),
            ("First aid: wounds and bleeding", "Control bleeding\nDress wounds"),
            ("Posture defects", "Kyphosis and scoliosis talk\nCorrective exercises"),
            ("Drug use and misuse", "Common abused drugs\nRefusal skills"),
            ("Revision and assessment", "Term work review\nSkills display"),
        ],
        3: [
            ("Sports and society", "Benefits of sports\nNational development"),
            ("Traditional sports", "Ayo and wrestling\nPlay and rules"),
            ("Swimming: basics", "Water safety\nFloating practice"),
            ("Rhythmic activities", "Marching and aerobics\nFollow the beat"),
            ("Physical fitness tests", "Endurance and strength\nMeasure my fitness"),
            ("Health: diseases", "Communicable diseases\nPrevention methods"),
            ("Health: the environment", "Sanitation and housing\nHealthy environment"),
            ("Family health", "Maternal and child care\nSupport the family"),
            ("Agencies promoting health", "WHO and NPHCDA\nTheir roles"),
            ("Revision and assessment", "Year work review\nEnd of year display"),
        ],
    },
    "Social Studies": {
        1: [
            ("Social studies: meaning and scope", "Why we study it\nAreas it covers"),
            ("Family: types and functions", "Nuclear and extended\nRoles of members"),
            ("Family as an agent", "Socialisation basics\nValues from home"),
            ("Community: meaning and types", "Rural and urban\nMy community"),
            ("Culture: meaning and features", "Material and non material\nCulture around us"),
            ("Cultural diversity in Nigeria", "Major ethnic groups\nRespect all cultures"),
            ("Socialisation: agents", "School, media, peers\nHow they shape us"),
            ("Norms and values", "Folkways and mores\nLive the values"),
            ("Environment: meaning", "Physical and social\nCare for the environment"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Population: meaning and census", "Why we count people\nNigeria's population"),
            ("Population structure", "Age and sex distribution\nRead the pyramids"),
            ("Migration", "Types and causes\nEffects on communities"),
            ("Resources: meaning and types", "Natural and human\nUse resources well"),
            ("Agriculture in Nigeria", "Food and cash crops\nFarming systems"),
            ("Industries in Nigeria", "Types and locations\nLocal industries"),
            ("Transport and communication", "Modes and networks\nEffects on life"),
            ("Social problems: meaning", "Common social problems\nCauses and effects"),
            ("Drug abuse", "Substances and effects\nPrevention strategies"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Conflict and cooperation", "Why conflicts arise\nResolve and cooperate"),
            ("National unity", "One Nigeria talk\nUnity symbols"),
            ("Democracy and development", "Citizens and nation building\nPlay my part"),
            ("Human rights", "Rights of citizens\nPromote the rights"),
            ("Law and order", "Why laws exist\nAgencies of order"),
            ("Leadership and followership", "Qualities of both\nBe a good follower"),
            ("Corruption", "Causes and effects\nFight corruption"),
            ("Globalisation basics", "World connections\nNigeria and the world"),
            ("Project: my community study", "Research my area\nPresent findings"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Agricultural Science": {
        1: [
            ("Agriculture: meaning and importance", "Branches of agriculture\nAgriculture in Nigeria"),
            ("Agricultural history", "From gathering to farming\nModern agriculture talk"),
            ("Farm tools: simple tools", "Cutlass and hoe\nUse and maintenance"),
            ("Farm tools: machinery", "Tractors and planters\nIdentify and uses"),
            ("Land preparation", "Clearing and tilling\nPrepare a seedbed"),
            ("Crop propagation: seeds", "Sexual propagation\nNursery practice"),
            ("Crop propagation: vegetative", "Cuttings and grafting\nDemonstrate a cutting"),
            ("Crop care: watering and weeding", "Routine practices\nCare the school garden"),
            ("Common weeds", "Identify weeds\nControl methods"),
            ("Revision and assessment", "Term work review\nPractical quiz"),
        ],
        2: [
            ("Soil: meaning and types", "Sandy, loamy, clay\nTest soil texture"),
            ("Soil profile and fertility", "Horizons of soil\nMaintain fertility"),
            ("Manures and fertilisers", "Organic and inorganic\nApply correctly"),
            ("Crop pests", "Insects and rodents\nControl of pests"),
            ("Crop diseases", "Signs of disease\nPrevention methods"),
            ("Common crops: cereals", "Maize and rice\nField identification"),
            ("Common crops: legumes", "Beans and groundnut\nField identification"),
            ("Animal husbandry: cattle", "Breeds and care\nHousing basics"),
            ("Animal husbandry: poultry", "Broilers and layers\nDaily care routine"),
            ("Revision and assessment", "Term work review\nPractical quiz"),
        ],
        3: [
            ("Animal feeds", "Types of feed\nFeed formulation basics"),
            ("Animal diseases", "Common diseases\nPrevention and care"),
            ("Fish farming", "Pond basics\nCare of fish"),
            ("Agricultural products processing", "Drying and milling\nProcess maize"),
            ("Storage of produce", "Stores and silos\nPrevent losses"),
            ("Marketing of produce", "Channels and prices\nSell the harvest"),
            ("Agro forestry basics", "Trees and crops\nPlant a tree"),
            ("Agricultural extension", "Extension agents\nRoles in farming"),
            ("Records and accounts", "Farm records book\nKeep simple records"),
            ("Revision and assessment", "Year work review\nEnd of year practical"),
        ],
    },
}
