#!/usr/bin/env python3
"""Primary 1 scheme data: nine subjects, three terms, ten weeks each."""

PRIMARY_1 = {
    "English Studies": {
        1: [
            ("Sounds of the alphabet", "Say each letter sound\nMatch letter to picture"),
            ("Phonics: a and b words", "ant, apple, ball, bat\nSay and point"),
            ("Phonics: c and d words", "cat, cup, drum, door\nSay and point"),
            ("Phonics: e and f words", "egg, elephant, fan, foot\nSay and point"),
            ("Phonics: g and h words", "goat, game, hat, hand\nSay and point"),
            ("Rhymes: simple songs", "Sing letter songs\nClap the beat"),
            ("Picture reading", "Name things in the picture\nSay simple sentences"),
            ("Writing: patterns and strokes", "Standing and sleeping lines\nTrace the patterns"),
            ("Writing: capital letters A to J", "Trace and copy\nSay each letter"),
            ("Revision and assessment", "Sounds and letters review\nOral and written quiz"),
        ],
        2: [
            ("Phonics: i and j words", "ink, iron, jam, jug\nSay and point"),
            ("Phonics: k and l words", "kite, key, leg, lion\nSay and point"),
            ("Phonics: m and n words", "man, moon, net, nose\nSay and point"),
            ("Phonics: o and p words", "ox, orange, pen, pot\nSay and point"),
            ("Simple sentences", "I can run. It is a cup.\nRead aloud together"),
            ("Rhymes: action songs", "Sing and act the rhyme\nClap and move"),
            ("Comprehension: my school", "Talk about my school\nAnswer simple questions"),
            ("Writing: capital letters K to T", "Trace and copy\nSay each letter"),
            ("Writing: small letters a to j", "Trace and copy neatly\nMatch to capitals"),
            ("Revision and assessment", "Term work review\nOral and written quiz"),
        ],
        3: [
            ("Phonics: q and r words", "queen, quilt, rat, rain\nSay and point"),
            ("Phonics: s and t words", "sun, sit, top, tap\nSay and point"),
            ("Phonics: u to z words", "umbrella, van, wet, yam, zebra\nSay and point"),
            ("Simple sentences about self", "My name is...\nI am a boy or girl"),
            ("Comprehension: my family", "Talk about my family\nAnswer simple questions"),
            ("Story time", "Listen to a short story\nRetell in my own words"),
            ("Writing: capital letters U to Z", "Trace and copy\nSay each letter"),
            ("Writing: small letters k to z", "Trace and copy neatly\nMatch to capitals"),
            ("Talking: greetings and manners", "Good morning, thank you\nRole play greetings"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Mathematics": {
        1: [
            ("Sorting and matching", "Group objects by colour\nMatch one to one"),
            ("Numbers 1 and 2", "Count and write 1 and 2\nCount real objects"),
            ("Numbers 3 and 4", "Count and write 3 and 4\nCount real objects"),
            ("Number 5", "Count and write 5\nCount five fingers"),
            ("Numbers 6 and 7", "Count and write 6 and 7\nFill the gaps"),
            ("Numbers 8 and 9", "Count and write 8 and 9\nFill the gaps"),
            ("Number 10", "Count and write 10\nCount ten bottle tops"),
            ("Shapes: circle and triangle", "Name and draw shapes\nFind shapes at home"),
            ("Simple patterns", "Copy and continue patterns\nBeads and colours"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Revision of numbers 1 to 10", "Count and order numbers\nFill the gaps"),
            ("Numbers 11 to 15", "Count and write tens and ones\nBundle sticks"),
            ("Numbers 16 to 20", "Count and write to 20\nBundle sticks"),
            ("Comparing numbers", "More than, less than\nUse counters"),
            ("Ordering numbers", "Biggest and smallest\nOrder number cards"),
            ("Addition with objects", "Put together and count\nTwo groups of tops"),
            ("Simple addition to 10", "Two plus one\nWrite the sums"),
            ("Subtraction with objects", "Take away and count\nEat some oranges story"),
            ("Simple subtraction from 10", "Five take away two\nWrite the answers"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Numbers 21 to 30", "Count and write to 30\nTens and ones"),
            ("Numbers 31 to 40", "Count and write to 40\nFill the gaps"),
            ("Numbers 41 to 50", "Count to 50\nTens and ones practice"),
            ("Addition of numbers to 20", "Add with counters\nWrite the sums"),
            ("Subtraction from numbers to 20", "Take away with counters\nWrite the answers"),
            ("Money: naira and kobo", "Coins and notes\nSimple shopping play"),
            ("Length: long and short", "Compare objects\nOrder by length"),
            ("Weight: heavy and light", "Carry and compare\nSort by weight"),
            ("Time: day and night", "Morning and evening\nDaily activities chart"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Basic Science and Technology": {
        1: [
            ("Myself: parts of the body", "Head, hands, legs\nPoint and name"),
            ("My senses: eyes and ears", "See and hear\nSimple games"),
            ("My senses: nose, tongue, skin", "Smell, taste, touch\nSort the pictures"),
            ("Living things around me", "Plants and animals\nName them"),
            ("Non living things around me", "Stone, water, chair\nSort the pictures"),
            ("Plants in my compound", "Grass, flowers, trees\nName and point"),
            ("Animals around me", "Goat, dog, fowl\nName their sounds"),
            ("Water and its uses", "Drinking, washing, cooking\nTalk about clean water"),
            ("Things in the sky", "Sun, moon, stars\nDay and night talk"),
            ("Revision and assessment", "Term work review\nPicture quiz"),
        ],
        2: [
            ("Keeping my body clean", "Bathing and washing\nCare of the teeth"),
            ("Healthy food", "Fruits and vegetables\nName good foods"),
            ("Safety at home", "Sharp objects and fire\nSay safe habits"),
            ("Safety on the road", "Look left and right\nCross with an adult"),
            ("The weather around us", "Sunny and rainy days\nDaily weather chart"),
            ("Soil around us", "Sand and loam\nFeel the soil"),
            ("Plants we can eat", "Vegetables and fruits\nName and taste"),
            ("Animals and their homes", "Dog kennel, bird nest\nMatch animal to home"),
            ("Simple machines at home", "Spoon, scissors, broom\nName and use"),
            ("Revision and assessment", "Term work review\nPicture quiz"),
        ],
        3: [
            ("Clean water and diseases", "Where germs hide\nWash before eating"),
            ("Air around us", "Moving air and wind\nBlow and feel"),
            ("Things that float and sink", "Try in a bowl of water\nSort the objects"),
            ("Colours around us", "Name the colours\nSort by colour"),
            ("Sound around us", "Loud and soft sounds\nMake simple sounds"),
            ("Growing a simple plant", "Beans in a cotton\nWater and watch"),
            ("Insects around us", "Butterfly, bee, ant\nObserve and name"),
            ("Energy: the sun", "Light and warmth\nWhy the sun helps plants"),
            ("Simple tools", "Spoon, cup, hoe\nUses of tools"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "National Values Education": {
        1: [
            ("My name and myself", "My name, age, sex\nSay about myself"),
            ("My family", "Father, mother, brothers, sisters\nRoles at home"),
            ("Good manners at home", "Greet and say thank you\nSimple rules"),
            ("Good manners in school", "Greet the teacher\nSit nicely"),
            ("Honesty: telling the truth", "Say the truth always\nShort story"),
            ("Care of things at home", "Keep toys and books safe\nTidy the room"),
            ("Respect for elders", "Greet elders properly\nHelp elders"),
            ("The national flag", "Green white green\nName the colours"),
            ("Loving my country", "Nigeria my country\nSay simple pledge words"),
            ("Revision and assessment", "Term work review\nOral quiz"),
        ],
        2: [
            ("My community", "People in my community\nName their work"),
            ("Helping one another", "Help at home and school\nKindness stories"),
            ("Obedience", "Obey parents and teachers\nWhy we obey"),
            ("Punctuality", "Come to school early\nDaily time table"),
            ("Cleanliness is next to Godliness", "Clean body and clothes\nClean the class"),
            ("Care of public things", "Desks, fans, toilets\nUse things well"),
            ("The national anthem", "Listen and sing\nSimple meaning"),
            ("The national pledge", "Recite the pledge\nSimple meaning"),
            ("Being a good pupil", "Hard work and respect\nClass rules"),
            ("Revision and assessment", "Term work review\nOral quiz"),
        ],
        3: [
            ("Rights of a child", "Food, shelter, school\nSay my rights"),
            ("Duties of a child", "Obey and help at home\nDo my school work"),
            ("Working hard", "Hard work pays\nHard work stories"),
            ("Money: needs and wants", "Things we need\nThings we want"),
            ("Saving money", "Keep money in a kolo\nWhy we save"),
            ("Our leaders", "President and governors\nRespect leaders"),
            ("National symbols", "Eagle and coat of arms\nName the symbols"),
            ("Living in peace", "Share and play well\nSettle quarrels nicely"),
            ("Festivals in Nigeria", "Christmas, Sallah, New Yam\nName the festivals"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Cultural and Creative Arts": {
        1: [
            ("Singing simple songs", "Action songs\nSing in groups"),
            ("Drawing simple objects", "Draw a ball and cup\nColour the drawing"),
            ("Colouring pictures", "Colour inside the lines\nEnjoy the colours"),
            ("Clapping rhythms", "Clap simple beats\nFollow the teacher"),
            ("Traditional dances", "Watch simple steps\nTry the steps"),
            ("Moulding with clay", "Mould balls and snakes\nMould simple shapes"),
            ("Craft: paper tearing", "Tear and paste paper\nMake a picture"),
            ("Drama: simple play", "Act mother and father\nFamily play"),
            ("Music: loud and soft", "Sing loud and soft\nListen and tell"),
            ("Revision and assessment", "Term work review\nDisplay my work"),
        ],
        2: [
            ("Nursery rhymes and folk songs", "Sing folk songs\nEnjoy the songs"),
            ("Drawing: my family", "Draw family members\nColour the drawing"),
            ("Pattern making", "Lines and circles patterns\nMake card patterns"),
            ("Rhythm with instruments", "Drum and shekere\nPlay simple beats"),
            ("Local dances", "Steps of my area\nDance in groups"),
            ("Craft: paper folding", "Fold a boat and plane\nFly the plane"),
            ("Beads and threading", "Thread bottle tops\nMake a necklace"),
            ("Drama: market scene", "Act buyer and seller\nMarket play"),
            ("Colour mixing", "Mix two colours\nName the new colour"),
            ("Revision and assessment", "Term work review\nDisplay my work"),
        ],
        3: [
            ("Songs about Nigeria", "Sing national songs\nEnjoy the songs"),
            ("Drawing: my school", "Draw the school\nColour the drawing"),
            ("Craft: weaving paper", "Weave paper strips\nMake a mat"),
            ("Rhythm and movement", "Move to the beat\nMarch and skip"),
            ("Cultural dances of Nigeria", "Dance steps of my area\nDress and dance"),
            ("Clay work: simple pots", "Mould a small pot\nDry the pot"),
            ("Drama: folk tale acting", "Act the tortoise story\nEnjoy the play"),
            ("Designing greeting cards", "Make a simple card\nWrite a greeting"),
            ("Exhibition of my works", "Show my works\nTalk about them"),
            ("Revision and assessment", "Year work review\nEnd of year display"),
        ],
    },
    "Pre-Vocational Studies": {
        1: [
            ("Things in the home", "Chairs, cups, spoons\nName and sort"),
            ("Jobs at home", "Sweeping and washing\nHelp at home"),
            ("The work of mummy and daddy", "What parents do\nTalk about work"),
            ("Tools in the kitchen", "Spoon, pot, cup\nName and sort"),
            ("Planting a seed", "Put maize in the soil\nWater it daily"),
            ("Caring for plants", "Water the plant\nWatch it grow"),
            ("Animals at home", "Fowl, goat, cat\nName and feed talk"),
            ("Food we eat", "Rice, beans, yam\nName the foods"),
            ("Keeping the compound clean", "Pick papers and sweep\nWork together"),
            ("Revision and assessment", "Term work review\nOral quiz"),
        ],
        2: [
            ("The market", "Buying and selling\nMarket items"),
            ("Trades in my area", "Carpenter, tailor, trader\nName their work"),
            ("Tools of workers", "Hoe, saw, scissors\nMatch tool to worker"),
            ("Planting vegetables", "Plant maize and beans\nCare for the garden"),
            ("Animals and their food", "Goat eats grass\nFowl eats grain"),
            ("Simple cooking", "Wash and peel\nWatch simple cooking"),
            ("Food preservation", "Dry pepper and fish\nWhy we dry food"),
            ("Poultry at home", "Keep fowls\nCare for the birds"),
            ("Craft with used items", "Use tins and bottles\nMake simple toys"),
            ("Revision and assessment", "Term work review\nOral quiz"),
        ],
        3: [
            ("Farming in my area", "Crops we grow\nName the crops"),
            ("Tools of the farmer", "Hoe and cutlass\nUses of the tools"),
            ("Planting a small garden", "Prepare the bed\nPlant the seeds"),
            ("Weeding the garden", "Remove the weeds\nCare for plants"),
            ("Harvesting", "Dig and pick\nStore the harvest"),
            ("Fish farming basics", "Fish in ponds\nTalk about fish"),
            ("Selling and buying", "Simple buying and selling\nCount the change"),
            ("Making simple snacks", "Wash fruits\nPrepare a fruit plate"),
            ("Safety with tools", "Carry tools well\nKeep tools away"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Physical and Health Education": {
        1: [
            ("Moving my body", "Walk, run, jump\nMove to commands"),
            ("Marching", "March on the spot\nMarch forward and back"),
            ("Running simple races", "Run short races\nRun in lanes"),
            ("Jumping", "Jump on the spot\nJump over a line"),
            ("Throwing and catching", "Throw a ball up\nCatch with two hands"),
            ("Body parts exercise", "Arms up and down\nBend and stretch"),
            ("Clean habits", "Wash hands after play\nClean games talk"),
            ("Playing safely", "No pushing on the line\nSafe playing rules"),
            ("Simple games: circle games", "Join the circle game\nFollow the rules"),
            ("Revision and assessment", "Term work review\nDisplay of skills"),
        ],
        2: [
            ("Balancing", "Stand on one leg\nWalk on a line"),
            ("Skipping", "Skip with a rope\nSkip in pairs"),
            ("Hopping", "Hop on one foot\nHop races"),
            ("Ball games: rolling", "Roll the ball to a friend\nStop the ball"),
            ("Ball games: bouncing", "Bounce and catch\nCount the bounces"),
            ("Animal movements", "Hop like a frog\nWalk like a crab"),
            ("Health: food and growth", "Eat good food\nGrow well"),
            ("Rest and sleep", "Rest after play\nSleep early"),
            ("Relay games", "Run and pass the top\nTeam games"),
            ("Revision and assessment", "Term work review\nDisplay of skills"),
        ],
        3: [
            ("Athletics: sprinting", "Short distance races\nRun fast safely"),
            ("Long jump basics", "Jump from a line\nLand with two feet"),
            ("Ball games: kicking", "Kick the ball\nSimple football play"),
            ("Safety in games", "Rules keep us safe\nPlay by the rules"),
            ("Posture: standing and sitting", "Stand tall, sit well\nGood posture habits"),
            ("Teeth care", "Brush twice daily\nClean teeth talk"),
            ("First aid: simple cuts", "Tell an adult\nWash and cover"),
            ("Clean water and exercise", "Drink clean water\nExercise daily"),
            ("Simple gymnastics", "Stretch and bend\nSafe simple moves"),
            ("Revision and assessment", "Year work review\nDisplay of skills"),
        ],
    },
    "Christian Religious Studies": {
        1: [
            ("God created the world", "God made all things\nThank God for creation"),
            ("God created me", "God made me special\nSay thank you prayers"),
            ("God loves me", "God cares for me\nSing about God's love"),
            ("My family is God's gift", "Thank God for family\nPray for family"),
            ("Talking to God", "Simple morning prayers\nThank you prayers"),
            ("Jesus loves children", "Jesus and the children story\nJesus loves me song"),
            ("Obeying God", "Obey parents and teachers\nSimple obedience story"),
            ("Thanking God", "Count my blessings\nThank you songs"),
            ("The Bible is God's word", "Hold and love the Bible\nSimple Bible stories"),
            ("Revision and assessment", "Term work review\nSongs and stories"),
        ],
        2: [
            ("God cares for us", "God feeds the birds\nGod cares for me more"),
            ("Praying to God", "When and how to pray\nThe Lord's prayer simple words"),
            ("Jesus the good shepherd", "The shepherd story\nJesus guides me"),
            ("Being kind to others", "The good neighbour story\nKind actions"),
            ("Saying sorry", "David said sorry\nGod forgives me"),
            ("Giving to others", "Share my things\nGiving stories"),
            ("Obeying my parents", "The obedient child story\nBlessing of obedience"),
            ("God's house", "Going to church\nRespect God's house"),
            ("Singing to God", "Praise songs\nSing with joy"),
            ("Revision and assessment", "Term work review\nSongs and stories"),
        ],
        3: [
            ("God answers prayers", "Hannah prayed\nGod hears me"),
            ("Jesus helps the sick", "Jesus healed the sick\nJesus cares for me"),
            ("Jesus feeds the people", "Five loaves story\nGod provides"),
            ("Telling the truth", "Truthful children story\nGod loves truth"),
            ("The honest boy", "Joseph story\nHonesty pays"),
            ("Helping the needy", "Dorcas helped people\nI can help too"),
            ("God made me to praise Him", "Praise God always\nPraise songs"),
            ("God keeps me safe", "God protected Daniel\nGod protects me"),
            ("The happy home", "A God fearing home\nPeace at home"),
            ("Revision and assessment", "Year work review\nSongs and stories"),
        ],
    },
    "Islamic Religious Studies": {
        1: [
            ("Allah created all things", "Allah made the world\nSay Alhamdulillah"),
            ("Allah created me", "Allah made me special\nThank Allah"),
            ("The Prophet Muhammad (SAW)", "The Prophet's simple life\nLove the Prophet"),
            ("The Mosque", "The house of Allah\nRespect the mosque"),
            ("Simple Du'a: before eating", "Bismillah before food\nAlhamdulillah after"),
            ("The Qur'an is Allah's book", "Hold and love the Qur'an\nListen to recitation"),
            ("Saying Salam", "Assalamu alaikum\nReply the salam"),
            ("Allah gives us food", "Allah provides\nThank Allah for food"),
            ("Love one another", "Be kind to friends\nKindness stories"),
            ("Revision and assessment", "Term work review\nRecitations"),
        ],
        2: [
            ("The five daily prayers", "Prayer times\nPrayer is important"),
            ("Wudu: washing before prayer", "How to make wudu\nKeep clean"),
            ("Du'a: sleeping and waking", "Du'a before sleep\nDu'a on waking"),
            ("The Prophet's family", "The Prophet loved children\nSimple stories"),
            ("Surah Al-Fatihah", "Recite together\nSimple meaning"),
            ("Good manners in Islam", "Greet and smile\nEat with the right hand"),
            ("Helping at home", "Help mummy and daddy\nReward of helping"),
            ("Allah's gifts", "Eyes, ears, food\nThank Allah"),
            ("Kindness to animals", "The Prophet was kind\nCare for animals"),
            ("Revision and assessment", "Term work review\nRecitations"),
        ],
        3: [
            ("Salat: praying together", "Praying in the mosque\nFollow the Imam"),
            ("The month of Ramadan", "Fasting is worship\nSimple fasting stories"),
            ("Giving to the poor", "Zakat is caring\nGive with a happy face"),
            ("Surah Al-Ikhlas", "Recite and memorise\nSimple meaning"),
            ("Honesty in Islam", "Always say the truth\nTruthful child story"),
            ("Obedience to parents", "Obey parents\nAllah loves obedience"),
            ("Cleanliness in Islam", "Cleanliness is part of faith\nClean habits"),
            ("My name in Islam", "Good names\nThe meaning of my name"),
            ("Love for the Qur'an", "Listen and recite\nCare for the Qur'an"),
            ("Revision and assessment", "Year work review\nRecitations"),
        ],
    },
}
