#!/usr/bin/env python3
"""Nursery 3 scheme data, part A: Letter Work, Number Work, Rhymes, Social Habits."""

NURSERY_3_A = {
    "Letter Work": {
        1: [
            ("Alphabet review", "Say and write Aa to Zz\nVowels and consonants sort"),
            ("Short a word families", "an, at, ap families\nBuild words with letter cards"),
            ("Short e families", "ed, en, et families\nPen, ten, hen, net"),
            ("Short i families", "id, ig, in, ip families\nBig pig in a wig"),
            ("Short o families", "og, op, ot families\nHop to the top"),
            ("Short u families", "ub, ug, un, ut families\nRun in the sun"),
            ("Blending drill", "Sound and blend ten words\nReading ladder game"),
            ("Simple sentences", "The hen has ten eggs.\nRead and copy"),
            ("Sight words 1", "the, and, a, I, to, is\nRead on sight, do not sound out"),
            ("Revision and reading race", "Word family relay\nSight word bingo"),
        ],
        2: [
            ("Sight words 2", "he, she, we, me, my, you\nFlash and read"),
            ("Consonant blends 1", "bl, cl, fl words, blue, clap, flag\nBlend and read"),
            ("Consonant blends 2", "sl, sm, sn words, slide, small, snap\nWord sort"),
            ("Consonant digraphs 1", "sh words, ship, shop, fish\nFish for sh words"),
            ("Consonant digraphs 2", "ch words, chat, chin, chip\nChip the ch words"),
            ("Digraph th", "this, that, thin, thick\nRead and sort"),
            ("Magic e with a", "a e words, cake, gate, lake\nMagic e wand"),
            ("Magic e with i and o", "kite, bike, home, stone\nChange pin to pine"),
            ("Reading sentences", "The kite is on the bike.\nRead with expression"),
            ("Revision and blend contest", "Digraph and blend games\nRead the class story"),
        ],
        3: [
            ("Reading fluency", "Read a page in one go\nPunctuation pause"),
            ("Comprehension 1", "Listen and answer who and what\nStory questions"),
            ("Comprehension 2", "Read and answer where and when\nFind the answer in the story"),
            ("Opposites and rhymes", "Big and little, day and night\nRhyme pairs game"),
            ("Simple writing", "Write my name, age and class\nOne sentence about me"),
            ("Picture composition", "Look and write two sentences\nWhat I see in the picture"),
            ("Story writing", "Write a three sentence story\nFirst, then, last"),
            ("Spelling drill", "Spell ten family words\nLook, cover, write, check"),
            ("Dictionary fun", "Words from a to z in the picture dictionary\nFind the word game"),
            ("Revision and reading graduation", "Read a full story alone\nReading certificate"),
        ],
    },
    "Number Work": {
        1: [
            ("Numbers to 100 review", "Count and write to 100\nFill the hundred chart gaps"),
            ("Number names review", "one to twenty words\nMatch and write"),
            ("Tens and ones", "34 is three tens four ones\nBundle sticks"),
            ("Ordering numbers", "Biggest to smallest\nOrder the number cards"),
            ("Addition to 10", "All pairs to ten\nWrite the number sentences"),
            ("Addition to 20", "No carrying with sticks\nSolve and write"),
            ("Subtraction from 20", "Take away with bundles\nWrite the answers"),
            ("Doubles and halves", "Double six, half of ten\nDomino doubles"),
            ("Shapes review", "Circle, square, triangle, rectangle\nShape sorting tray"),
            ("Revision and number quiz", "Mixed operation games\nNumber champion awards"),
        ],
        2: [
            ("Money 1", "Naira coins and notes\nRecognise 5, 10, 20, 50"),
            ("Money 2", "Buy and sell play market\nAdd prices and pay"),
            ("Time 1", "O'clock on the clock face\nMake my paper clock"),
            ("Time 2", "Half past\nDaily time table, school at 8 o'clock"),
            ("Length", "Longer and shorter with hand spans\nMeasure the desk"),
            ("Weight", "Heavy and lighter with the pan balance\nWeigh fruit and blocks"),
            ("Capacity", "Full, half and empty cups\nWater play measuring"),
            ("Data fun", "Count and mark favourites\nOur fruit pictograph"),
            ("Halves first step", "Half of shapes and objects\nFold and shade half"),
            ("Revision and maths market day", "Run the class market\nMeasure and weigh stations"),
        ],
        3: [
            ("Addition with carrying", "27 plus 15 with sticks and bundles\nCarry the ten"),
            ("Subtraction with borrowing", "42 take away 17\nBorrow a ten"),
            ("Word problems 1", "Add stories, birds and flowers\nDraw and solve"),
            ("Word problems 2", "Take away stories\nWrite the sentence and solve"),
            ("Multiplication as groups", "Two groups of five\nGroups and rows"),
            ("Division as sharing", "Share twelve sweets to three friends\nShare fairly"),
            ("Patterns and sequences", "Number patterns, 2, 4, 6, 8\nContinue my pattern"),
            ("Symmetry fun", "Butterfly symmetry\nFold and match halves"),
            ("Mental maths", "Quick add and take away\nBeat the timer"),
            ("Revision and graduation maths show", "Solve and explain\nMaths star certificates"),
        ],
    },
    "Rhymes": {
        1: [
            ("Choral welcome", "Sing our welcome round\nAdd harmony claps"),
            ("Twinkle twinkle with verses", "Verses with new stars\nSolos and duets"),
            ("Counting rhymes", "One two buckle, ten green bottles\nCount with props"),
            ("Animal rhymes", "Old MacDonald, five little ducks\nAnimal chorus"),
            ("Action rhymes", "Head shoulders, if you are happy\nFollow the leader"),
            ("Nursery rap", "Clap a simple beat and rap the alphabet\nGroup performance"),
            ("Call and response", "Teacher calls, class answers\nEcho rhymes"),
            ("Rhymes with instruments", "Shakers and drums with our rhymes\nKeep the beat"),
            ("Solo day", "Each child performs one rhyme\nEncourage every voice"),
            ("Rhyme concert", "Full concert for parents\nStanding ovation"),
        ],
        2: [
            ("Nigerian folk songs", "Songs in our languages\nYoruba, Hausa, Igbo song round"),
            ("Story songs", "Sing a story and act it\nCharacters and chorus"),
            ("Season songs", "Rainy season song\nDry season song"),
            ("Tables chant", "Two times tables chant\nRhythm with claps"),
            ("Days and months songs", "Seven days, twelve months\nCalendar chorus"),
            ("Patriotic songs", "Arise O compatriots\nSing with pride"),
            ("Call and response 2", "Longer echo rhymes\nSolo callers"),
            ("Movement medley", "Sing and move through stations\nFreeze dance"),
            ("Class composed song", "Write our own class song\nPerform together"),
            ("Music festival", "All songs of the year\nGraduation rehearsal"),
        ],
        3: [
            ("Graduation medley", "Mix our best rhymes and songs\nRehearse the order"),
            ("Solo performances", "Every child a solo slot\nMic practice"),
            ("Group dances", "Dance in small groups\nChoreograph simple steps"),
            ("Cultural dance", "Traditional steps from our cultures\nDrum accompaniment"),
            ("Praise and thanks songs", "Songs of gratitude\nThank you teachers"),
            ("Role play songs", "Act and sing community songs\nDoctor, teacher, driver"),
            ("Rhythm patterns", "Echo clap patterns\nSimple notation with dots"),
            ("Concert etiquette", "Bow, enter and exit nicely\nStage manners"),
            ("Dress rehearsal", "Full run on stage\nCheck costumes and props"),
            ("Graduation concert", "Perform for parents\nGraduation joy"),
        ],
    },
    "Social Habits": {
        1: [
            ("My school family", "Roles of everyone in school\nAppreciate all helpers"),
            ("Feelings deep dive", "Name complex feelings, proud, jealous\nTalk it out"),
            ("Conflict steps", "Stop, talk, listen, agree\nPractise with scenarios"),
            ("Team projects", "Plan and build together\nGroup poster task"),
            ("Responsibility chart", "My jobs at school\nMy jobs at home"),
            ("Money habits", "Save, spend wisely\nClass saving jar"),
            ("Digital basics", "Ask before using devices\nScreen time agreement"),
            ("Our neighbourhood", "Houses, shops, clinic, school\nMap my street"),
            ("Being inclusive", "No one plays alone\nInvite and include"),
            ("Revision and community project", "Class kindness project\nPresent our work"),
        ],
        2: [
            ("Government and leaders", "Who leads our school, state, country\nRespect for leaders"),
            ("Rules and laws", "Why we have rules\nRules at home, school, nation"),
            ("Voting fun", "Class election by votes\nCount and announce"),
            ("National symbols", "Flag, anthem, coat of arms\nSymbol matching"),
            ("Nigerian cultures", "Food, dress, dance across cultures\nCulture show and tell"),
            ("Tourist places", "Zuma rock, Yankari, Obudu\nWhere would I visit"),
            ("Honesty in public", "Return lost items\nLost and found box duty"),
            ("Environmental duty", "Clean up day plan\nSort and clean"),
            ("Safety in the community", "Trusted adults around me\nHelp points, police, clinic"),
            ("Revision and civic day", "Recite pledge and anthem\nCivic badge awards"),
        ],
        3: [
            ("Ready for primary school", "What changes in primary one\nQuestions and answers"),
            ("Self care mastery", "Dress, tie, pack my bag alone\nIndependence checklist"),
            ("Time management", "Morning routine on time\nUse my little timetable"),
            ("Study habits", "Where and when I do my best work\nMy study corner"),
            ("Speaking up", "Ask questions bravely\nShow and tell mastery"),
            ("Handling mistakes", "Mistakes help me grow\nFix it and try again"),
            ("Friendship skills", "Make and keep good friends\nSolve friend troubles"),
            ("Gratitude letters", "Write thanks to my teachers\nDeliver with a smile"),
            ("Memories book", "Our nursery years in pictures\nSign each other's page"),
            ("Revision and send off", "Celebrate our growth\nGraduation blessings"),
        ],
    },
}
