#!/usr/bin/env python3
"""SSS 1 scheme data: fourteen subjects, three terms, ten weeks each."""

SSS_1 = {
    "English Language": {
        1: [
            ("Revision of JSS work", "Grammar and structure recap\nDiagnostic test"),
            ("Comprehension: listening skills", "Listen to a talk\nAnswer inferential questions"),
            ("Oral English: vowels", "Pure vowels practice\nTranscribe simple words"),
            ("Grammar: noun phrases", "Structure of phrases\nIdentify in texts"),
            ("Grammar: tense and aspect", "Simple and continuous forms\nUse accurately"),
            ("Vocabulary: everyday registers", "Medicine and law terms\nUse in context"),
            ("Composition: narrative", "Write a story\nPlot and character"),
            ("Summary writing: main ideas", "Identify topic sentences\nWrite summaries"),
            ("Literature: introduction to genres", "Prose, poetry, drama\nRecommended texts talk"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Comprehension: reading for implied meaning", "Read between lines\nInference drills"),
            ("Oral English: consonants", "Consonant sounds\nCluster practice"),
            ("Grammar: adjectival phrases and clauses", "Restrictive and non restrictive\nUse in sentences"),
            ("Grammar: concord rules", "Proximity and notional concord\nCorrect errors"),
            ("Vocabulary: agriculture and environment", "Register words\nContextual use"),
            ("Composition: descriptive", "Describe a scene\nPrecise vocabulary"),
            ("Summary: phrase answers", "Answer in required words\nAvoid lifting"),
            ("Literature: poetry terms", "Stanza, rhyme, imagery\nAnalyse a poem"),
            ("Writing: formal letters", "Applications and requests\nRegister and format"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Comprehension: expository texts", "Read and interpret\nAnswer questions"),
            ("Oral English: stress and intonation", "Word and sentence stress\nRising and falling tones"),
            ("Grammar: adverbial clauses", "Time, place, reason clauses\nUse in writing"),
            ("Grammar: reported speech", "Backshift rules\nReport accurately"),
            ("Vocabulary: prefixes for meaning", "Negative prefixes\nBuild antonyms"),
            ("Composition: argumentative", "Support with logic\nCounter argument practice"),
            ("Summary: alternative expressions", "Replace phrases\nOwn words skill"),
            ("Literature: drama terms", "Dialogue and acts\nStudy an excerpt"),
            ("Writing: speeches", "Deliver a speech\nRhetorical devices"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Mathematics": {
        1: [
            ("Number bases", "Convert between bases\nArithmetic in bases"),
            ("Indices and logarithms", "Laws and tables\nSolve with logs"),
            ("Surds", "Simplify surds\nRationalise denominators"),
            ("Sets", "Venn diagrams\nSolve set problems"),
            ("Simple equations and variations", "Direct and inverse\nSolve variations"),
            ("Quadratic equations: factorisation", "Solve by factors\nWord problems"),
            ("Geometry: angles and polygons", "Angle properties\nSolve polygon problems"),
            ("Construction and loci", "Construct triangles\nLocus problems"),
            ("Statistics: data presentation", "Tables and charts\nInterpret data"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Algebraic fractions and functions", "Simplify and substitute\nFunction notation"),
            ("Quadratic equations: completing squares", "Complete the square\nDerive the formula"),
            ("Quadratic graphs", "Plot parabolas\nRead roots from graphs"),
            ("Trigonometric ratios", "SOH CAH TOA\nAngles of elevation"),
            ("Circle geometry: chords and angles", "Theorems and proofs\nApply the theorems"),
            ("Mensuration: areas", "Triangles and parallelograms\nComposite areas"),
            ("Mensuration: solids", "Prisms and cylinders\nVolume and surface area"),
            ("Statistics: measures of central tendency", "Mean, median, mode\nGrouped data"),
            ("Probability: simple events", "Sample spaces\nCalculate probabilities"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Logarithms: applications", "Solve exponential equations\nGrowth problems"),
            ("Sequences: arithmetic", "nth term and sum\nReal life problems"),
            ("Sequences: geometric", "nth term and sum\nApplications"),
            ("Straight line graphs", "Gradient and intercept\nEquation of lines"),
            ("Trigonometry: sine and cosine rules", "Solve triangles\nBearings problems"),
            ("Circle geometry: tangents", "Tangent theorems\nSolve circle problems"),
            ("Statistics: dispersion", "Range and deviations\nCompare data"),
            ("Probability: combined events", "Tree diagrams\nMutually exclusive events"),
            ("Everyday mathematics", "Taxes and tariffs\nFinancial maths"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Biology": {
        1: [
            ("Biology and living things", "Branches of biology\nCharacteristics of life"),
            ("Cell structure", "Plant and animal cells\nMicroscope work"),
            ("Cell organelles", "Functions of parts\nLabel and describe"),
            ("Cell processes: diffusion and osmosis", "Movement experiments\nDemonstrate osmosis"),
            ("Cell division: mitosis", "Stages of mitosis\nGrowth and repair"),
            ("Tissues and organs", "Levels of organisation\nExamples in organisms"),
            ("Nutrition in plants", "Photosynthesis details\nExperiment with light"),
            ("Nutrition in animals", "Classes of food\nBalanced diet study"),
            ("Digestive system", "Alimentary canal\nEnzyme actions"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Transport systems in plants", "Xylem and phloem\nTranspiration experiment"),
            ("Transport in animals", "Blood and circulation\nHeart structure"),
            ("Respiration", "Aerobic and anaerobic\nEnergy release"),
            ("Excretion", "Excretory organs\nKidney functions"),
            ("Skeleton and support", "Types of skeletons\nJoints and movement"),
            ("Coordination: nervous system", "Neurones and reflexes\nReflex arc study"),
            ("Coordination: hormones", "Endocrine glands\nHormone functions"),
            ("Reproduction in lower organisms", "Asexual methods\nObserve budding"),
            ("Reproduction in flowering plants", "Flower structure\nPollination types"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Reproduction in mammals", "Male and female systems\nDevelopment of foetus"),
            ("Genetics: heredity basics", "Mendel's laws\nMonohybrid crosses"),
            ("Genetics: applications", "Blood groups talk\nGenetic engineering intro"),
            ("Evolution basics", "Theories of evolution\nEvidence of evolution"),
            ("Ecology: habitat and niche", "Ecosystems studied\nLocal habitat visit"),
            ("Energy flow in ecosystems", "Food chains and webs\nPyramids of numbers"),
            ("Nutrient cycling", "Water and carbon cycles\nDraw the cycles"),
            ("Population studies", "Quadrat sampling\nEstimate populations"),
            ("Conservation", "Protect biodiversity\nNigerian parks talk"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Chemistry": {
        1: [
            ("Introduction to chemistry", "Nature and branches\nLaboratory rules"),
            ("Particulate nature of matter", "States of matter\nKinetic theory"),
            ("Atoms, molecules and ions", "Structure of atoms\nAtomic number and mass"),
            ("Periodic table", "Groups and periods\nPeriodic trends"),
            ("Chemical bonding: ionic", "Electron transfer\nProperties of ionic compounds"),
            ("Chemical bonding: covalent", "Shared electrons\nMolecular compounds"),
            ("Stoichiometry: mole concept", "Molar mass\nMole calculations"),
            ("Chemical equations", "Balance equations\nInterpret equations"),
            ("Acids, bases and salts", "Properties and pH\nNeutralisation"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Air and its components", "Composition of air\nCombustion study"),
            ("Water", "Properties and treatment\nHardness of water"),
            ("Oxides and hydroxides", "Types of oxides\nReactions with water"),
            ("Carbon and its compounds", "Allotropes of carbon\nSimple carbon compounds"),
            ("Hydrocarbons: alkanes", "Saturated chains\nNaming alkanes"),
            ("Hydrocarbons: alkenes and alkynes", "Unsaturated chains\nTests for unsaturation"),
            ("Petroleum and refining", "Fractions of crude oil\nUses of fractions"),
            ("Rates of reaction", "Factors affecting rate\nExperiments on rate"),
            ("Equilibrium basics", "Reversible reactions\nLe Chatelier intro"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Electrolysis", "Electrolytes and electrodes\nFaraday basics"),
            ("Electrochemical cells", "Galvanic cells\nCell notation talk"),
            ("Redox reactions", "Oxidation numbers\nBalance redox equations"),
            ("Metals and their compounds", "Iron and aluminium\nExtraction basics"),
            ("Non metals: chlorine", "Preparation and uses\nBleaching action"),
            ("Non metals: nitrogen", "Ammonia production\nUses of ammonia"),
            ("Non metals: sulphur", "Sulphuric acid talk\nContact process intro"),
            ("Organic: alcohols and acids", "Ethanol chemistry\nEthanoic acid"),
            ("Salt analysis basics", "Test for ions\nQualitative tests"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Physics": {
        1: [
            ("Introduction to physics", "Branches and measurement\nFundamental units"),
            ("Measurement: instruments", "Vernier and micrometer\nTake readings"),
            ("Motion: types", "Distance and displacement\nSpeed and velocity"),
            ("Motion: acceleration", "Equations of motion\nSolve problems"),
            ("Forces", "Types of forces\nEffects of forces"),
            ("Friction", "Laws of friction\nReduce friction"),
            ("Work, energy and power", "Calculations\nEnergy conversions"),
            ("Simple machines", "Levers and pulleys\nEfficiency calculations"),
            ("Heat: temperature scales", "Thermometers\nConvert scales"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Heat: expansion", "Solids, liquids, gases\nApplications of expansion"),
            ("Heat transfer", "Conduction, convection, radiation\nExperiments"),
            ("Waves: basics", "Types of waves\nWave properties"),
            ("Light: reflection", "Plane mirrors\nLaws of reflection"),
            ("Light: refraction", "Snell's law\nRefraction experiments"),
            ("Light: lenses", "Convex and concave\nImage formation"),
            ("Sound: production and propagation", "Vibrations\nSpeed of sound"),
            ("Sound: characteristics", "Pitch and loudness\nResonance talk"),
            ("Electricity: electrostatics", "Charges and fields\nElectroscope"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Electricity: current", "Ohm's law\nCircuit calculations"),
            ("Electricity: resistance", "Series and parallel\nCombine resistors"),
            ("Electricity: power and energy", "Electrical power\nCost of energy"),
            ("Magnetism", "Magnetic fields\nField patterns"),
            ("Electromagnetism", "Electromagnets\nMotor principle talk"),
            ("Electromagnetic induction", "Induced currents\nGenerators talk"),
            ("Radioactivity basics", "Radiations and decay\nSafety and uses"),
            ("Simple circuits: devices", "Diodes and transistors\nRectification talk"),
            ("Physics project", "Build and test\nPresent findings"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Civic Education": {
        1: [
            ("The fundamental of civic education", "Meaning and importance\nWhy we study it"),
            ("Values: meaning and types", "Societal values\nValues in practice"),
            ("Honesty and integrity", "Effects on society\nLive with integrity"),
            ("Cooperation and unity", "Benefits to nation\nPractice unity"),
            ("Self reliance and dignity of labour", "Work ethics\nBe self reliant"),
            ("Democracy: meaning and features", "Pillars of democracy\nPractice debate"),
            ("Constitution: meaning and features", "Types of constitutions\nNigerian constitution"),
            ("Rule of law", "Principles and application\nProtect rights"),
            ("Nationalism and national consciousness", "History of nationalism\nNigerian heroes"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Human rights: meaning and categories", "Universal declaration\nCategories of rights"),
            ("Human rights in Nigeria", "Chapter four rights\nEnforce my rights"),
            ("Rights: limitations and abuse", "Reasonable limits\nCases of abuse"),
            ("Citizenship: meaning", "Citizen vs alien\nAcquisition methods"),
            ("Citizenship: responsibilities", "Duties of citizens\nFulfil duties"),
            ("Democracy: institutions", "Executive and legislature\nJudiciary roles"),
            ("Elections and voting", "Electoral process\nParticipate properly"),
            ("Political parties", "Functions and types\nParty manifestos"),
            ("Public administration", "Civil service structure\nServe the public"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Capitalist democracy", "Features of capitalism\nBenefits and drawbacks"),
            ("Socialism and mixed economy", "Compare systems\nNigerian economy talk"),
            ("Political culture", "Values in politics\nBuild healthy culture"),
            ("Political socialisation", "How we learn politics\nAgents considered"),
            ("Civil society", "Roles of NGOs\nJoin civic groups"),
            ("Public opinion", "Formation and measurement\nVoice my opinion"),
            ("Media and democracy", "Press freedom\nResponsible journalism"),
            ("Corruption: national development", "Effects on growth\nAnti graft agencies"),
            ("Civic responsibilities in action", "Community projects\nExecute a project"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Commerce": {
        1: [
            ("Introduction to commerce", "Meaning and scope\nCommercial occupations"),
            ("Production", "Levels of production\nInterdependence of levels"),
            ("Trade: meaning and classification", "Home and foreign trade\nAids to trade"),
            ("Retail trade", "Functions of retailers\nTypes of retailers"),
            ("Wholesale trade", "Functions of wholesalers\nChannels of distribution"),
            ("Documents: trade documents", "Invoice and receipt\nPrepare documents"),
            ("Banking: types of banks", "Central and commercial\nFunctions of banks"),
            ("Banking: instruments", "Cheques and drafts\nComplete instruments"),
            ("Transport", "Modes of transport\nChoosing a mode"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Insurance", "Principles of insurance\nTypes of policies"),
            ("Warehousing", "Types of warehouses\nFunctions of warehousing"),
            ("Advertising", "Types and media\nAdvertising agencies"),
            ("Tourism", "Tourism in Nigeria\nBenefits to economy"),
            ("Foreign trade: basics", "Import and export\nBalance of trade"),
            ("Foreign trade: documents", "Bill of lading\nLetters of credit"),
            ("Ports and airports", "Customs and excise\nClearing and forwarding"),
            ("Chambers of commerce", "Roles of chambers\nTrade associations"),
            ("Business environment", "Internal and external\nSWOT basics"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Business units: sole proprietorship", "Features and sources of funds\nAdvantages and disadvantages"),
            ("Business units: partnership", "Formation and types\nDissolution talk"),
            ("Business units: companies", "Formation of companies\nShares and debentures"),
            ("Public enterprises", "Reasons for public ownership\nPrivatisation talk"),
            ("Cooperatives", "Types of cooperatives\nFormation rules"),
            ("Trade unions", "Roles of unions\nIndustrial actions"),
            ("Consumer protection", "Rights of consumers\nAgencies and laws"),
            ("Business documents: financial", "Statement of account\nReconcile documents"),
            ("Communication in business", "Business correspondence\nWrite business letters"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Economics": {
        1: [
            ("Economics: meaning and scope", "Basic economic problems\nWhy we study economics"),
            ("Wants and scarcity", "Scale of preference\nChoice and opportunity cost"),
            ("Production: factors", "Land, labour, capital, entrepreneur\nRewards of factors"),
            ("Division of labour and specialisation", "Advantages and limits\nExamples in industry"),
            ("Economic systems", "Capitalism and socialism\nMixed economy"),
            ("Demand", "Law of demand\nDemand schedules and curves"),
            ("Supply", "Law of supply\nSupply schedules and curves"),
            ("Price determination", "Equilibrium price\nPrice controls talk"),
            ("Basic tools: graphs and tables", "Read and draw\nInterpret data"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Theory of consumer behaviour", "Utility concepts\nLaw of diminishing utility"),
            ("Theory of production", "Total and marginal product\nLaw of variable proportions"),
            ("Cost and revenue concepts", "Fixed and variable costs\nRevenue calculations"),
            ("Market structures", "Perfect competition talk\nMonopoly features"),
            ("Population: theory", "Malthusian talk\nOptimum population"),
            ("Population census", "Importance of census\nNigerian census history"),
            ("Labour market", "Wage determination\nUnemployment types"),
            ("Trade unions and employment", "Roles of unions\nCollective bargaining"),
            ("Money: meaning and functions", "Qualities of money\nFunctions in economy"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Financial institutions", "Central bank functions\nCommercial banks"),
            ("Inflation", "Causes and effects\nControl of inflation"),
            ("Public finance", "Sources of revenue\nGovernment expenditure"),
            ("Taxation", "Types of taxes\nEffects of taxation"),
            ("National income", "Measuring income\nUses of national income"),
            ("International trade", "Basis for trade\nComparative advantage"),
            ("Balance of payments", "Components explained\nDeficits and surpluses"),
            ("Economic development", "Growth vs development\nDevelopment plans talk"),
            ("Agriculture in Nigeria", "Problems and prospects\nDiversification talk"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Financial Accounting": {
        1: [
            ("Accounting: meaning and users", "Users of accounts\nImportance of accounting"),
            ("Accounting equation", "Assets and liabilities\nDouble entry idea"),
            ("The ledger", "Rules of debit and credit\nOpen accounts"),
            ("Recording transactions", "Journalise entries\nPost to ledger"),
            ("Trial balance", "Prepare and check\nLocate errors"),
            ("Cash book: two column", "Record cash and bank\nBalance the cash book"),
            ("Cash book: three column", "Discount columns\nRecord with discounts"),
            ("Petty cash book", "Imprest system\nRecord small expenses"),
            ("Classification of accounts", "Real, personal, nominal\nClassify correctly"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Trading account", "Compute gross profit\nFormat the account"),
            ("Profit and loss account", "Compute net profit\nInclude expenses"),
            ("Balance sheet", "Arrange assets and liabilities\nBalance the sheet"),
            ("Final accounts of a sole trader", "Complete final accounts\nWork an example"),
            ("Adjustments: accruals and prepayments", "Adjust expenses\nUpdate accounts"),
            ("Adjustments: depreciation basics", "Straight line method\nRecord depreciation"),
            ("Adjustments: bad debts", "Write off debts\nProvision basics"),
            ("Subsidiary books: sales and purchases", "Day books in use\nPost from day books"),
            ("Returns books", "Returns inwards and outwards\nRecord returns"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Bank reconciliation", "Reasons for differences\nPrepare statements"),
            ("Control accounts", "Sales and purchases ledgers\nReconcile accounts"),
            ("Correction of errors", "Types of errors\nUse suspense accounts"),
            ("Depreciation: reducing balance", "Compute depreciation\nRecord asset disposal basics"),
            ("Partnership accounts: formation", "Capital accounts\nPartnership agreement"),
            ("Partnership accounts: appropriation", "Share profits\nInterest on capital talk"),
            ("Introduction to company accounts", "Shares and reserves\nSimple company format"),
            ("Not for profit accounts basics", "Receipts and payments\nIncome and expenditure intro"),
            ("Project: complete accounts", "Full set of accounts\nPresent the project"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Further Mathematics": {
        1: [
            ("Sets and operations", "Set notations advanced\nSolve harder problems"),
            ("Indices and logarithms advanced", "Log equations\nChange of base"),
            ("Surds advanced", "Manipulate surds\nRationalise complex forms"),
            ("Polynomials", "Factor theorem\nSolve polynomial equations"),
            ("Quadratic functions advanced", "Roots and discriminant\nNature of roots"),
            ("Inequalities", "Linear and quadratic\nSolve and graph"),
            ("Sequences and series", "Sum notation\nConvergence intro"),
            ("Trigonometry advanced", "Compound angles\nSolve trig equations"),
            ("Coordinate geometry", "Lines and circles\nFind intersections"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Functions and relations", "Injective and surjective\nComposite functions"),
            ("Calculus: differentiation basics", "First principles\nStandard derivatives"),
            ("Calculus: rules of differentiation", "Product and quotient\nChain rule"),
            ("Calculus: applications", "Maxima and minima\nRates of change"),
            ("Integration basics", "Indefinite integrals\nStandard integrals"),
            ("Integration: definite", "Areas under curves\nCompute areas"),
            ("Statistics advanced", "Measures of dispersion\nSkewness intro"),
            ("Probability advanced", "Conditional probability\nBayes intro"),
            ("Vectors: basics", "Vector algebra\nResultants"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Matrices", "Operations on matrices\nDeterminants 2x2 3x3"),
            ("Inverse matrices", "Find inverses\nSolve systems"),
            ("Linear transformations", "Matrices as transforms\nFind images"),
            ("Kinematics", "Motion equations advanced\nDisplacement and velocity"),
            ("Newton's laws advanced", "Connected particles\nSolve dynamics problems"),
            ("Work, energy and power advanced", "Work energy theorem\nPower problems"),
            ("Static forces", "Equilibrium of forces\nMoments and couples"),
            ("Projectiles", "Trajectory equations\nRange and height"),
            ("Project: mathematical modelling", "Model a real problem\nPresent solutions"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Geography": {
        1: [
            ("Geography: nature and scope", "Branches of geography\nImportance of geography"),
            ("The solar system", "Planets and the sun\nEarth in space"),
            ("Earth movements", "Rotation and revolution\nEffects explained"),
            ("Latitudes and longitudes", "Grid references\nLocate places"),
            ("Rocks: types", "Igneous, sedimentary, metamorphic\nIdentify rocks"),
            ("Plate tectonics basics", "Earth movements\nVolcanoes and earthquakes"),
            ("Weather: elements", "Temperature and rainfall\nMeasure the weather"),
            ("Climate: types", "Factors affecting climate\nNigerian climate"),
            ("Maps and scale", "Map reading skills\nMeasure distances"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Map work: contours", "Relief from contours\nDraw cross sections"),
            ("Geography of Nigeria: relief", "Physical regions\nDescribe the terrain"),
            ("Nigeria: drainage", "Rivers and lakes\nRiver Niger and Benue"),
            ("Nigeria: climate", "Seasons and belts\nRainfall distribution"),
            ("Nigeria: vegetation", "Forest to savannah\nVegetation belts"),
            ("Nigeria: soils", "Types and fertility\nSoil conservation"),
            ("Agriculture of Nigeria", "Crops and systems\nAgricultural zones"),
            ("Industry in Nigeria", "Industrial locations\nFactors of location"),
            ("Transport in Nigeria", "Networks and modes\nDevelop transport"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Population of Nigeria", "Distribution and structure\nPopulation problems"),
            ("Settlement: types", "Rural and urban\nSettlement patterns"),
            ("Urbanisation", "Growth of cities\nProblems and solutions"),
            ("Resources of Nigeria", "Minerals and power\nResource management"),
            ("ECOWAS", "Member countries\nBenefits of integration"),
            ("Africa: physical features", "Relief and drainage\nKey features studied"),
            ("Africa: climate and vegetation", "Zones explained\nInterdependence"),
            ("World: selected regions", "Case studies\nCompare regions"),
            ("Field work project", "Plan and execute\nReport the findings"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Government": {
        1: [
            ("Government: meaning and functions", "Why governments exist\nFunctions listed"),
            ("Basic concepts: power and authority", "Distinguish the terms\nLegitimacy talk"),
            ("Basic concepts: sovereignty", "Types of sovereignty\nWhere it lies"),
            ("Basic concepts: nation and state", "Features of a state\nNigeria as a state"),
            ("Democracy: meaning", "Features of democracy\nDirect and indirect"),
            ("Rule of law", "Principles by Dicey\nApplication in Nigeria"),
            ("Separation of powers", "Doctrine explained\nChecks and balances"),
            ("Constitutions", "Written and unwritten\nSources of constitutions"),
            ("Political ideologies", "Capitalism to socialism\nCompare ideologies"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Organs of government: legislature", "Composition and functions\nLaw making process"),
            ("Organs: executive", "Types and functions\nImplementation of laws"),
            ("Organs: judiciary", "Structure of courts\nIndependence of judiciary"),
            ("Federalism", "Features of federalism\nNigerian federalism"),
            ("Confederation and unitary systems", "Compare systems\nExamples worldwide"),
            ("Party systems", "One, two, multi party\nNigerian parties history"),
            ("Electoral systems", "Types of elections\nElectoral commission"),
            ("Public opinion", "Nature and functions\nMeasure opinion"),
            ("Pressure groups", "Types and roles\nExamples in Nigeria"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Colonial administration: indirect rule", "Lugard's system\nEffects on Nigeria"),
            ("Nationalism in Nigeria", "Causes of nationalism\nKey nationalists"),
            ("Constitutional development: 1914 to 1954", "Clifford to Lyttleton\nFeatures traced"),
            ("The 1960 independence constitution", "Features and weaknesses\nParliamentary system"),
            ("The 1979 and 1999 constitutions", "Presidential features\nCompare the two"),
            ("Military government in Nigeria", "Features and effects\nCoups and rule"),
            ("Local government", "Structure and functions\nReform history"),
            ("Public administration", "Civil service structure\nRoles and reforms"),
            ("Nigeria and international organisations", "UN, AU, ECOWAS\nRoles and benefits"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Literature in English": {
        1: [
            ("Introduction to literature", "Functions of literature\nGenres explained"),
            ("Literary appreciation", "How to read critically\nRespond to texts"),
            ("Figures of speech", "Metaphor and personification\nIdentify in texts"),
            ("Poetry: nature", "Types of poetry\nRead sample poems"),
            ("Poetry: devices", "Sound devices\nAnalyse a poem"),
            ("Drama: nature", "Types of drama\nElements of drama"),
            ("Drama: reading a text", "Recommended text study\nDiscuss the plot"),
            ("Prose: nature", "Elements of prose\nPlot structure"),
            ("Prose: reading a text", "Recommended text study\nCharacter analysis"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Figures of speech: advanced", "Irony and symbolism\nApply in analysis"),
            ("Poetry: themes", "Find the themes\nCompare poems"),
            ("Poetry: form and structure", "Sonnet and ode\nStudy the forms"),
            ("Drama: plot development", "Rising action to climax\nMap the plot"),
            ("Drama: characters", "Round and flat\nCharacterise roles"),
            ("Drama: themes", "Extract themes\nSupport with text"),
            ("Prose: point of view", "First and third person\nIdentify the voice"),
            ("Prose: themes", "Extract and discuss\nTextual evidence"),
            ("Literary terms mastery", "Glossary building\nQuiz practice"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Poetry: comparison", "Compare two poems\nWrite comparisons"),
            ("Poetry: appreciation essay", "Structure an essay\nModel essays"),
            ("Drama: dialogue and action", "Analyse scenes\nDramatic irony"),
            ("Drama: essay writing", "Answer drama questions\nModel essays"),
            ("Prose: narrative techniques", "Flashback and suspense\nIdentify techniques"),
            ("Prose: essay writing", "Answer prose questions\nModel essays"),
            ("Themes in African literature", "Recommended texts talk\nDiscuss traditions"),
            ("Oral literature", "Folktales and songs\nOral features"),
            ("General revision", "All genres practice\nPast questions"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Agricultural Science": {
        1: [
            ("Agriculture: meaning and branches", "Scope of agriculture\nCareer fields"),
            ("Importance of agriculture", "To economy and society\nProblems of agriculture"),
            ("Agricultural ecology", "Ecosystem basics\nAgro ecology talk"),
            ("Land use in Nigeria", "Tenure systems\nLand use act talk"),
            ("Climatic factors", "Rainfall and temperature\nEffects on crops"),
            ("Soil formation", "Processes of weathering\nProfile study"),
            ("Soil properties: physical", "Texture and structure\nTest samples"),
            ("Soil properties: chemical", "pH and nutrients\nTest soil pH"),
            ("Farm machinery: tractor", "Systems of tractor\nCouple implements"),
            ("Revision and assessment", "Term work review\nPractical quiz"),
        ],
        2: [
            ("Crop classification", "By use and life cycle\nClassify crops"),
            ("Crop culture: cereals", "Maize production\nField practice"),
            ("Crop culture: legumes", "Cowpea production\nField practice"),
            ("Crop culture: root crops", "Cassava production\nField practice"),
            ("Crop propagation methods", "Sexual and asexual\nDemonstrate grafting"),
            ("Crop husbandry practices", "Nursery to harvest\nFollow the cycle"),
            ("Weed science", "Types and control\n Weed management"),
            ("Crop pests", "Major pests\nControl strategies"),
            ("Crop diseases", "Causal agents\nDisease management"),
            ("Revision and assessment", "Term work review\nPractical quiz"),
        ],
        3: [
            ("Animal anatomy and physiology", "Systems studied\nLabel structures"),
            ("Animal reproduction", "Artificial insemination talk\nReproductive management"),
            ("Animal nutrition", "Ration formulation\nFeed trials talk"),
            ("Animal health", "Common diseases\nPrevention programs"),
            ("Poultry production", "Broiler and layer management\nRecord performance"),
            ("Fisheries and aquaculture", "Pond management\nHarvest techniques"),
            ("Agricultural economics basics", "Farm management ideas\nBudget a farm"),
            ("Agricultural extension", "Methods of extension\nAdopt technologies"),
            ("Practical project", "Crop or animal project\nExecute and report"),
            ("Revision and assessment", "Year work review\nEnd of year practical"),
        ],
    },
}
