#!/usr/bin/env python3
"""SSS 2 scheme data: fourteen subjects, three terms, ten weeks each."""

SSS_2 = {
    "English Language": {
        1: [
            ("Revision of SSS one work", "Grammar and summary recap\nDiagnostic drill"),
            ("Comprehension: argumentative texts", "Identify logic\nEvaluate arguments"),
            ("Oral English: diphthongs", "Diphthong sounds\nTranscribe words"),
            ("Grammar: noun clauses", "Functions of clauses\nUse in writing"),
            ("Grammar: tense sequence", "Reported tenses\nMaintain sequence"),
            ("Vocabulary: registers continued", "Engineering and finance\nUse precisely"),
            ("Composition: expository essays", "Explain with structure\nWrite a full essay"),
            ("Summary: topic sentences", "Locate and use\nCompress paragraphs"),
            ("Literature: recommended texts", "Study the texts\nPlot and themes"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Comprehension: narrative texts", "Read and interpret\nAnswer in own words"),
            ("Oral English: sentence stress", "Emphasis in speech\nPractice dialogues"),
            ("Grammar: adverbial clauses advanced", "Condition and concession\nUse accurately"),
            ("Grammar: phrasal verbs", "Meaning patterns\nUse in context"),
            ("Grammar: concord advanced", "Tricky subjects\nCorrect the errors"),
            ("Vocabulary: idiomatic usage", "Idioms in passages\nInterpret meanings"),
            ("Composition: formal letters advanced", "Complaints and requests\nModel letters"),
            ("Summary: precision writing", "Replace phrases\nWrite tight summaries"),
            ("Literature: themes analysis", "Extract and discuss\nTextual evidence"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Comprehension: summary passages", "Read and compress\nTimed practice"),
            ("Oral English: intonation patterns", "Tag responses\nPractice with texts"),
            ("Grammar: punctuation mastery", "Advanced punctuation\nEdit long passages"),
            ("Grammar: style and register", "Formal vs informal\nRewrite in register"),
            ("Vocabulary: antonyms and synonyms", "Word pairs practice\nExam style drills"),
            ("Composition: argumentative mastery", "Debate structure\nWrite to persuade"),
            ("Summary: final polish", "Avoid irrelevance\nScore higher"),
            ("Literature: essay mastery", "Write full essays\nPeer review"),
            ("Oral practice: speech delivery", "Deliver with confidence\nClass debate"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Mathematics": {
        1: [
            ("Revision of SSS one work", "Algebra and geometry recap\nDiagnostic test"),
            ("Logarithms and indices advanced", "Solve hard equations\nLog graphs talk"),
            ("Surds and quadratics advanced", "Symmetric functions\nForm equations"),
            ("Polynomials and the factor theorem", "Divide polynomials\nRemainder theorem"),
            ("Trigonometry: identities", "Prove identities\nSolve equations"),
            ("Trigonometry: graphs", "Sketch sine and cosine\nAmplitude and period"),
            ("Circle geometry: advanced theorems", "Cyclic quadrilaterals\nProve theorems"),
            ("Coordinate geometry: circles", "Equation of circles\nTangents and normals"),
            ("Statistics: cumulative frequency", "Ogive construction\nPercentiles and quartiles"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Differentiation: first principles", "Derive derivatives\nGradient functions"),
            ("Differentiation: rules", "Products and chains\nApply the rules"),
            ("Integration: techniques", "Substitution basics\nStandard forms"),
            ("Integration: applications", "Areas and volumes\nSolve problems"),
            ("Kinematics: calculus approach", "Velocity and acceleration\nSolve motion problems"),
            ("Probability: advanced", "Binomial talk\nCombined events mastery"),
            ("Vectors: 2D", "Components and resultants\nSolve geometry with vectors"),
            ("Static forces: moments", "Equilibrium conditions\nSolve force problems"),
            ("Mensuration: advanced solids", "Cones and spheres\nComposite solids"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Algebra: simultaneous and quadratic", "Solve systems\nHarder word problems"),
            ("Trigonometry: bearings and distances", "Solve survey problems\nThree figure bearings"),
            ("Circle geometry: proofs", "Write proofs\nExamination practice"),
            ("Statistics: applications", "Interpret real data\nProject data study"),
            ("Probability: examination style", "Solve past questions\nTime yourself"),
            ("Financial mathematics", "Interest and annuities\nEveryday finance"),
            ("Coordinate geometry: lines", "Parallel and perpendicular\nSolve with equations"),
            ("Sequences: applications", "Arithmetic and geometric\nSolve real problems"),
            ("General revision", "Past questions practice\nExamination strategy"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Biology": {
        1: [
            ("Revision of SSS one work", "Cell and systems recap\nDiagnostic test"),
            ("Photosynthesis: deep dive", "Light and dark reactions\nChromatography talk"),
            ("Chemosynthesis talk", "Bacteria nutrition\nCompare with photosynthesis"),
            ("Respiration: glycolysis", "Breakdown of glucose\nEnergy yield talk"),
            ("Respiration: aerobic pathways", "Krebs overview\nMitochondria role"),
            ("Anaerobic respiration", "Fermentation\nApplications in industry"),
            ("Excretion: kidney function", "Nephron structure\nDialysis talk"),
            ("Homeostasis", "Temperature and sugar control\nFeedback mechanisms"),
            ("Nervous coordination: synapse", "Impulse transmission\nReflex action study"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Hormonal coordination", "Pituitary and adrenal\nHormone disorders talk"),
            ("Sense organs: eye", "Structure and function\nImage formation"),
            ("Sense organs: ear", "Hearing and balance\nCare of the ear"),
            ("Reproduction: gametogenesis", "Sperm and ova\nHormonal control talk"),
            ("Development: pregnancy", "Implantation to birth\nAnte natal care"),
            ("Genetics: chromosomes", "Genes and DNA talk\nChromosome numbers"),
            ("Genetics: dihybrid crosses", "Mendel extended\nSolve crosses"),
            ("Genetics: sex determination", "XX and XY\nSex linked traits"),
            ("Evolution: mechanisms", "Natural selection\nSpeciation talk"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Ecology: biotic communities", "Succession basics\nStudy a community"),
            ("Ecology: population dynamics", "Growth curves\nFactors of change"),
            ("Ecology: measurement", "Quadrat and transect\nField sampling"),
            ("Ecosystems: energy flow", "Trophic levels\nEcological pyramids"),
            ("Nutrient cycles: nitrogen", "Cycle stages\nDraw and explain"),
            ("Pollution: water and air", "Sources and effects\nControl measures"),
            ("Conservation: Nigeria", "Forest reserves\nProtect biodiversity"),
            ("Pests and diseases of crops", "Agents and control\nField identification"),
            ("Food production and storage", "Increase production\nStore safely"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Chemistry": {
        1: [
            ("Revision of SSS one work", "Bonding and mole recap\nDiagnostic test"),
            ("Gas laws: Boyle and Charles", "Gas law calculations\nKinetic explanation"),
            ("Gas laws: general gas equation", "Combine the laws\nSolve problems"),
            ("Mole concept: volumetric analysis", "Standard solutions\nTitration calculations"),
            ("Acid base titrations", "Perform titrations\nCalculate concentration"),
            ("Energy changes: enthalpy", "Exothermic and endothermic\nBond energy talk"),
            ("Rates of reaction: factors", "Concentration and temperature\nCollision theory"),
            ("Chemical equilibrium", "Reversible reactions\nEquilibrium constants intro"),
            ("Solubility", "Saturated solutions\nSolubility curves"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Periodic chemistry: groups", "Group trends studied\nCompare elements"),
            ("Periodic chemistry: period three", "Oxides and chlorides\nTrend explanations"),
            ("Metals: sodium and calcium", "Compounds and uses\nReactions studied"),
            ("Metals: aluminium and iron", "Extraction methods\nCorrosion talk"),
            ("Metals: copper and alloys", "Properties and uses\nAlloy composition"),
            ("Non metals: oxygen", "Preparation and uses\nOxides studied"),
            ("Non metals: hydrogen", "Preparation and uses\nIsotopes talk"),
            ("Non metals: carbon dioxide", "Preparation and uses\nGreenhouse talk"),
            ("Organic chemistry: isomerism", "Structural isomers\nNaming isomers"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Organic: benzene and aromatics", "Structure of benzene\nAromatic reactions talk"),
            ("Organic: carbonyl compounds", "Aldehydes and ketones\nTests for carbonyls"),
            ("Organic: carboxylic acids", "Acid properties\nEsterification"),
            ("Organic: polymers", "Addition polymers\nEveryday polymers"),
            ("Electrochemistry: cells", "Standard potentials\nPredict reactions"),
            ("Electrochemistry: electrolysis applications", "Electroplating\nExtraction of aluminium"),
            ("Qualitative analysis: cations", "Test and identify\nGroup reagents"),
            ("Qualitative analysis: anions", "Test and identify\nConfirmatory tests"),
            ("Project: salt analysis", "Analyse unknown salts\nReport findings"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Physics": {
        1: [
            ("Revision of SSS one work", "Mechanics recap\nDiagnostic test"),
            ("Vectors and scalars", "Vector addition\nResolve components"),
            ("Projectile motion", "Trajectories\nRange calculations"),
            ("Newton's laws: applications", "Forces in systems\nSolve problems"),
            ("Momentum and impulse", "Conservation of momentum\nCollision problems"),
            ("Circular motion", "Centripetal force\nSolve problems"),
            ("Simple harmonic motion", "Oscillations studied\nPendulum experiments"),
            ("Energy: elastic and potential", "Hooke's law\nEnergy stored"),
            ("Thermal physics: gas laws", "Boyle and Charles\nKinetic theory link"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Waves: properties", "Superposition talk\nStanding waves"),
            ("Sound: waves in air", "Vibrations in pipes\nResonance tubes"),
            ("Light: mirrors and images", "Curved mirrors\nMirror formula"),
            ("Light: refraction in lenses", "Lens formula\nOptical devices"),
            ("Light: optical instruments", "Microscope and telescope\nMagnification talk"),
            ("Electricity: fields and potential", "Electric fields\nPotential difference talk"),
            ("Electricity: capacitors", "Capacitance basics\nEnergy stored"),
            ("Electricity: cells and circuits", "EMF and internal resistance\nSolve circuits"),
            ("Electricity: measurement", "Meters and bridges\nWheatstone bridge talk"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Magnetic fields: force on currents", "Fleming's rules\nSolve force problems"),
            ("Electromagnetic induction", "Lenz and Faraday\nInduction experiments"),
            ("Alternating current", "Peak and rms values\nTransformers talk"),
            ("Electronics: semiconductors", "Diodes and transistors\nRectification circuits"),
            ("Radioactivity: decay", "Half life calculations\nDecay series talk"),
            ("Radioactivity: applications", "Uses and dangers\nSafety rules"),
            ("Nuclear energy", "Fission and fusion\nReactors talk"),
            ("Quantum ideas: photoelectric effect", "Photons explained\nEinstein's equation talk"),
            ("Physics project", "Design and build\nPresent the project"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Civic Education": {
        1: [
            ("Democracy: deep dive", "Structures and practice\nCompare democracies"),
            ("Constitution: features", "Sources and amendments\nNigerian constitution study"),
            ("Federalism: practice in Nigeria", "Revenue allocation talk\nIntergovernmental relations"),
            ("Electoral process", "From registration to result\nElectoral reforms"),
            ("Political parties and manifestos", "Ideologies compared\nParty funding talk"),
            ("Human rights: enforcement", "Courts and commissions\nSeek redress"),
            ("Fundamental duties of citizens", "Obligations listed\nPerform duties"),
            ("Public service: ethics", "Accountability structures\nTransparency mechanisms"),
            ("Peace and conflict resolution", "Mediation skills\nResolve conflicts"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Democracy: participation", "Forms of participation\nActive citizenship"),
            ("Voters education", "Why votes matter\nVote protection"),
            ("Civil society organisations", "Roles in democracy\nJoin and contribute"),
            ("Public opinion: media roles", "Press and democracy\nEvaluate media"),
            ("Anti corruption: agencies", "EFCC and ICPC\nSupport the fight"),
            ("National unity: integration", "Policies of unity\nPromote integration"),
            ("Federal character", "Principle explained\nMerit vs quota talk"),
            ("Revenue sharing", "Allocation formula\nDebate the formula"),
            ("Citizenship education: project", "Research an issue\nPresent recommendations"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Globalisation: politics", "International relations\nNigeria's foreign policy"),
            ("International organisations", "UN and AU roles\nNigeria's contributions"),
            ("Human rights: global instruments", "Universal declaration study\nLocal application"),
            ("Democracy: challenges", "Threats to democracy\nStrengthen institutions"),
            ("Governance: accountability", "Audits and oversight\nDemand accountability"),
            ("Civic responsibilities: taxes", "Why taxes matter\nTax compliance talk"),
            ("Security challenges", "National security talk\nCommunity safety"),
            ("Environmental governance", "Climate policies\nAct responsibly"),
            ("Capstone project", "Civic action project\nExecute and report"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Commerce": {
        1: [
            ("Revision of SSS one work", "Trade and aids recap\nDiagnostic test"),
            ("Business units: comparison", "Sole trade to company\nChoose a form"),
            ("Formation of companies", "Registration process\nDocuments required"),
            ("Shares and debentures", "Types of shares\nDebenture features"),
            ("Company meetings", "AGM basics\nResolutions talk"),
            ("Dissolution of businesses", "Reasons for closure\nWind up procedures"),
            ("Stock exchange: operations", "Trading process\nBrokers and jobbers"),
            ("Stock exchange: securities", "Shares and bonds\nRead market quotes"),
            ("Business mergers", "Reasons for mergers\nTypes explained"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Management: functions", "Plan, organise, control\nApply functions"),
            ("Business organisation structures", "Line and staff\nDraw organograms"),
            ("Office practice: procedures", "Receiving visitors\nHandle mail"),
            ("Office machines: modern", "Computers and printers\nUse office tech"),
            ("Data processing basics", "Manual vs electronic\nProcess documents"),
            ("Business communication", "Reports and memos\nWrite effectively"),
            ("Meeting documents", "Notices and minutes\nPrepare minutes"),
            ("Sales promotion: techniques", "Discounts and display\nPromote a product"),
            ("Customer service", "Handle complaints\nServe well"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Transport: documents and insurance", "Freight documents\nInsure goods"),
            ("Customs and excise", "Import procedures\nClearing process"),
            ("Tourism business", "Travel agencies\nPackage tours"),
            ("Banking: e banking", "Transfers and cards\nUse safely"),
            ("Insurance: claims", "Claim procedures\nDocument losses"),
            ("Business risk", "Types of risks\nManage risks"),
            ("Business ethics", "Corporate responsibility\nTrade honestly"),
            ("Entrepreneurship: practice", "Write business plans\nPresent ventures"),
            ("Case studies in commerce", "Nigerian businesses\nAnalyse cases"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Economics": {
        1: [
            ("Revision of SSS one work", "Demand and supply recap\nDiagnostic test"),
            ("Elasticity: price elasticity of demand", "Calculate elasticity\nInterpret results"),
            ("Elasticity: other elasticities", "Income and cross elasticity\nApplications"),
            ("Consumer behaviour: utility", "Equi marginal utility\nSolve problems"),
            ("Production: costs", "Cost curves studied\nEconomies of scale"),
            ("Market structures: perfect competition", "Price takers talk\nShort run equilibrium"),
            ("Market structures: monopoly", "Price makers talk\nRegulation talk"),
            ("Market structures: oligopoly", "Few sellers talk\nCompetition forms"),
            ("Business organisations", "Forms and finance\nCompare forms"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Labour economics", "Efficiency of labour\nWage determination"),
            ("Unemployment", "Types and measurement\nSolutions discussed"),
            ("Money and inflation", "Value of money\nInflation accounting"),
            ("Banking: central bank", "Monetary policy tools\nControl money supply"),
            ("Banking: commercial banks", "Credit creation\nBank services"),
            ("Public finance: fiscal policy", "Taxation and spending\nStabilise economy"),
            ("National income accounting", "Compute national income\nUses and limits"),
            ("International trade: theory", "Absolute advantage\nComparative advantage"),
            ("Balance of payments", "Accounts explained\ncorrect disequilibria"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Economic development planning", "Plans in Nigeria\nEvaluate planning"),
            ("Agriculture in development", "Role and problems\nMechanisation talk"),
            ("Industrialisation", "Types of industry\nIndustrial policy talk"),
            ("Petroleum and the economy", "Oil revenue effects\nDiversify the economy"),
            ("Population economics", "Population growth effects\nHuman capital talk"),
            ("International economic organisations", "IMF and World Bank\nRoles and criticisms"),
            ("ECOWAS economy", "Trade within ECOWAS\nBenefits and costs"),
            ("Economic reforms", "Privatisation talk\nDeregulation talk"),
            ("Project: economic survey", "Collect local data\nAnalyse and report"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Financial Accounting": {
        1: [
            ("Revision of SSS one work", "Final accounts recap\nDiagnostic exercise"),
            ("Capital and revenue expenditure", "Distinguish correctly\nClassify items"),
            ("Depreciation: methods", "Straight line and reducing balance\nCompute depreciation"),
            ("Asset disposal", "Disposal accounts\nCompute profit or loss"),
            ("Accruals and prepayments: advanced", "Adjust entries\nPrepare adjusted accounts"),
            ("Bad debts and provisions", "Provision for doubtful debts\nAdjust the accounts"),
            ("Final accounts: adjustments", "Incorporate adjustments\nPrepare statements"),
            ("Manufacturing accounts basics", "Prime cost talk\nPrepare the account"),
            ("Control accounts: advanced", "Reconcile ledgers\nLocate errors"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Partnership: formation", "Partnership deed\nOpen capital accounts"),
            ("Partnership: appropriation", "Interest and salaries\nShare residual profits"),
            ("Partnership: admission", "Goodwill treatment\nAdjust capitals"),
            ("Partnership: dissolution", "Realisation account\nSettle the partnership"),
            ("Company accounts: issue of shares", "Journal entries\nRecord issues"),
            ("Company accounts: final accounts", "Company formats\nPrepare statements"),
            ("Company accounts: appropriation", "Dividends and reserves\nAppropriate profits"),
            ("Not for profit: receipts and payments", "Record for clubs\nPrepare the account"),
            ("Not for profit: income and expenditure", "Compute surplus or deficit\nPrepare the account"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Departmental accounts", "Allocate expenses\nCompute department profits"),
            ("Branch accounts basics", "Dependent branches\nPrepare branch account"),
            ("Introduction to public sector accounting", "Government funds\nCompare with private"),
            ("Purchases of business", "Business purchase entries\nRecord goodwill"),
            ("Statement of cash flows: intro", "Operating and investing\nPrepare simple statement"),
            ("Accounting ratios", "Liquidity ratios\nInterpret results"),
            ("Interpretation of accounts", "Analyse performance\nWrite reports"),
            ("Computerised accounting talk", "Accounting packages\nBenefits and risks"),
            ("Project: complete accounts set", "Prepare full accounts\nPresent analysis"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Further Mathematics": {
        1: [
            ("Revision of SSS one further maths", "Core topics recap\nDiagnostic test"),
            ("Polynomials: roots", "Symmetric functions\nForm new equations"),
            ("Rational functions", "Partial fractions\nDecompose expressions"),
            ("Binomial theorem", "Expand expressions\nFind specific terms"),
            ("Trigonometry: identities advanced", "Factor formulas\nSolve equations"),
            ("Trigonometry: inverse functions", "Evaluate inverses\nSolve equations"),
            ("Calculus: limits", "Evaluate limits\nContinuity talk"),
            ("Differentiation: implicit", "Differentiate implicitly\nFind tangents"),
            ("Integration: advanced techniques", "By parts intro\nSubstitutions advanced"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Application of integration", "Areas between curves\nVolumes of revolution"),
            ("Matrices: 3x3", "Determinants and inverses\nSolve systems"),
            ("Linear transformations: 2D", "Matrices and geometry\nFind invariant points"),
            ("Vectors: 3D", "Direction cosines\nDot and cross products"),
            ("Statics: friction", "Laws of friction\nAngle of friction"),
            ("Dynamics: projectiles", "Range and height\nSolve problems"),
            ("Dynamics: connected particles", "Pulleys and planes\nSolve systems"),
            ("Probability: distributions", "Binomial distribution\nMean and variance"),
            ("Statistics: correlation", "Scatter diagrams\nRegression intro"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Complex numbers", "Argand diagrams\nOperations on complexes"),
            ("De Moivre's theorem talk", "Powers of complexes\nRoots of equations talk"),
            ("Differentiation: parametric", "Differentiate parametrically\nFind second derivatives"),
            ("Integration: further techniques", "Partial fractions use\nIntegrate harder functions"),
            ("Differential equations: intro", "First order equations\nSolve by separation"),
            ("Moments of inertia talk", "Concepts explained\nSimple bodies"),
            ("Kinematics: vectors", "Vector motion\nSolve with calculus"),
            ("Probability: examination practice", "Solve past questions\nTime management"),
            ("Project: modelling", "Model real problems\nPresent the maths"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Geography": {
        1: [
            ("Revision of SSS one work", "Map work recap\nSkills refresh"),
            ("Weathering", "Types of weathering\nLandforms produced"),
            ("Mass movement", "Types and causes\nSlope failures"),
            ("Action of rivers", "Erosion and deposition\nRiver landforms"),
            ("Action of wind and water in deserts", "Desert landforms\nIdentify features"),
            ("Action of glaciers talk", "Glacial landforms\nCompare with rivers"),
            ("Coastal processes", "Waves and landforms\nCoastal features"),
            ("Nigeria: mineral resources", "Distribution studied\nExploit responsibly"),
            ("Nigeria: power resources", "Oil and hydro\nEnergy mix talk"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("World population", "Growth patterns\nPopulation policies"),
            ("Migration: types and effects", "Reasons to move\nEffects on areas"),
            ("Settlement: patterns and functions", "Classify settlements\nFunctions compared"),
            ("Urbanisation: processes", "Growth of towns\nUrban problems"),
            ("Rural land use", "Farming systems\nLand use patterns"),
            ("Urban land use", "Zones in cities\nModel cities talk"),
            ("World trade", "Patterns of trade\nTrade blocs talk"),
            ("Manufacturing industry: world", "Locations studied\nIndustrial regions"),
            ("Tourism geography", "Tourist regions\nBenefits and costs"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Geographic information systems talk", "GIS basics\nApplications"),
            ("Remote sensing talk", "Satellites in geography\nRead images"),
            ("Environmental management", "Sustainable use\nManage resources"),
            ("Climate change", "Evidence and effects\nGlobal responses"),
            ("Field work: river study", "Measure a stream\nWrite the report"),
            ("Field work: settlement study", "Survey a settlement\nAnalyse findings"),
            ("Maps: advanced interpretation", "Extract features\nAnswer map questions"),
            ("Photographs: interpretation", "Aerial and ground\nDescribe features"),
            ("General revision", "Physical and human recap\nPast questions"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Government": {
        1: [
            ("Revision of SSS one work", "Concepts recap\nDiagnostic test"),
            ("Nigeria: colonial rule", "British administration\nEffects on Nigeria"),
            ("Nationalist movements", "Parties and leaders\nRoad to independence"),
            ("Constitutional development: 1951 to 1960", "Macpherson and Lyttleton\nFeatures studied"),
            ("First Republic", "1960 to 1966 politics\nAchievements and collapse"),
            ("Military rule: 1966 to 1979", "Governments studied\nPolicies and effects"),
            ("Second Republic", "1979 to 1983 politics\nParties and fall"),
            ("Military rule: 1983 to 1999", "Regimes studied\nTransition programmes"),
            ("Fourth Republic", "1999 to date politics\nDemocratic gains"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Public administration: meaning", "Civil service defined\nFeatures of bureaucracies"),
            ("Civil service: structure", "Ministries and departments\nHierarchies explained"),
            ("Civil service: control", "Oversight mechanisms\nAccountability tools"),
            ("Local government in Nigeria", "Structure and functions\nReforms studied"),
            ("Public corporations", "Reasons and control\nPrivatisation debate"),
            ("Nigeria's foreign policy", "Principles traced\nAfrica as centre piece"),
            ("Nigeria and the UN", "Roles and contributions\nPeace keeping talk"),
            ("Nigeria and AU ECOWAS", "Regional roles\nBenefits assessed"),
            ("International relations: theories talk", "Key perspectives\nApply to Nigeria"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Comparative government: USA", "Presidential system\nFeatures studied"),
            ("Comparative government: UK", "Parliamentary system\nFeatures studied"),
            ("Comparative government: France", "Semi presidential talk\nCompare systems"),
            ("Political development: concepts", "Development indicators\nAssess Nigeria"),
            ("Political behaviour: parties and voting", "Voting patterns\nParty systems compared"),
            ("Electoral commissions", "Functions compared\nNigeria's INEC"),
            ("Democratisation", "Consolidating democracy\nChallenges discussed"),
            ("Conflict management", "Cases studied\nResolution mechanisms"),
            ("General revision", "Past questions practice\nExamination strategy"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Literature in English": {
        1: [
            ("Revision of literary terms", "Glossary recap\nApply the terms"),
            ("Reading the prescribed prose", "Set text study\nChapters discussed"),
            ("Prose: plot development", "Track the plot\nMap key events"),
            ("Prose: characters", "Study main characters\nSupport with extracts"),
            ("Prose: themes", "Identify themes\nDiscuss with evidence"),
            ("Reading the prescribed drama", "Set text study\nActs discussed"),
            ("Drama: conflict", "Identify conflicts\nAnalyse scenes"),
            ("Poetry: set poems", "Study prescribed poems\nLine by line reading"),
            ("Poetry: themes and devices", "Analyse deeply\nCompare poems"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Prose: style and language", "Narrative voice\nLanguage effects"),
            ("Prose: setting and atmosphere", "Study settings\nEffects on theme"),
            ("Drama: characterisation", "Motivations studied\nTrace development"),
            ("Drama: language and style", "Dialogue analysis\nDramatic techniques"),
            ("Drama: themes", "Central themes\nSupport from text"),
            ("Poetry: imagery", "Sensory pictures\nAnalyse images"),
            ("Poetry: tone and mood", "Identify tone\nJustify readings"),
            ("Poetry: comparative study", "Compare set poems\nWrite comparisons"),
            ("Essay writing: literature", "Plan literature essays\nModel answers"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Prose: full analysis", "Complete text study\nAnswer past questions"),
            ("Drama: full analysis", "Complete text study\nAnswer past questions"),
            ("Poetry: full analysis", "Complete poem study\nAnswer past questions"),
            ("Unseen prose practice", "Read and answer\nTimed exercises"),
            ("Unseen poetry practice", "Read and answer\nTimed exercises"),
            ("Essay mastery: drama", "Structure answers\nScore higher"),
            ("Essay mastery: prose", "Structure answers\nScore higher"),
            ("Essay mastery: poetry", "Structure answers\nScore higher"),
            ("General revision", "All genres practice\nExamination strategy"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Agricultural Science": {
        1: [
            ("Revision of SSS one work", "Crops and soils recap\nDiagnostic practical"),
            ("Crop improvement", "Methods of improvement\nSelect and breed talk"),
            ("Crop physiology: growth", "Growth curves\nMeasure growth"),
            ("Plant hormones talk", "Auxins and others\nApplications"),
            ("Crop production: beverages", "Cocoa production\nField practice"),
            ("Crop production: fibres", "Cotton production\nField practice"),
            ("Crop production: oil crops", "Oil palm production\nField practice"),
            ("Weed management: chemical", "Herbicide use\nApply safely"),
            ("Integrated pest management", "Combine methods\nProtect crops"),
            ("Revision and assessment", "Term work review\nPractical quiz"),
        ],
        2: [
            ("Animal improvement", "Selection and breeding\nImprove breeds"),
            ("Animal health management", "Disease prevention\nVaccination schedules"),
            ("Ruminant production: cattle", "Management systems\nRecord performance"),
            ("Ruminant production: sheep and goats", "Management practice\nHusbandry routines"),
            ("Non ruminants: pigs", "Housing and feeding\nManage a piggery"),
            ("Non ruminants: rabbits", "Care and breeding\nManage rabbits"),
            ("Poultry: management systems", "Deep litter and battery\nCompare systems"),
            ("Poultry: health and vaccination", "Common diseases\nVaccinate properly"),
            ("Agricultural mechanisation", "Machines in production\nOperate safely"),
            ("Revision and assessment", "Term work review\nPractical quiz"),
        ],
        3: [
            ("Farm surveying", "Instruments and methods\nSurvey a plot"),
            ("Farm planning", "Layout a farm\nDraw the plan"),
            ("Agricultural finance", "Sources of funds\nPrepare a budget"),
            ("Farm records and accounts", "Complete records\nAnalyse performance"),
            ("Agro forestry", "Trees with crops\nEstablish plots"),
            ("Fisheries management", "Culture systems\nManage ponds"),
            ("Post harvest handling", "Reduce losses\nHandle produce well"),
            ("Agricultural marketing", "Market structures\nMarket produce"),
            ("Entrepreneurship in agriculture", "Agribusiness ideas\nPlan a venture"),
            ("Revision and assessment", "Year work review\nEnd of year practical"),
        ],
    },
}
