#!/usr/bin/env python3
"""JSS 2 scheme data: twelve subjects, three terms, ten weeks each."""

JSS_2 = {
    "English Studies": {
        1: [
            ("Revision of JSS one work", "Grammar and tenses recap\nReading fluency drill"),
            ("Comprehension: the chest of jewels", "Read and answer\nVocabulary building"),
            ("Listening: public speaking", "Speak with confidence\nClass presentations"),
            ("Grammar: verbs, tenses and voice", "Active and passive basics\nChange the voice"),
            ("Grammar: pronouns and reference", "Personal and relative pronouns\nUse accurately"),
            ("Vocabulary: banking and commerce words", "Terms in context\nUse in sentences"),
            ("Composition: report writing", "Report an event\nFactual style"),
            ("Literature: drama terms", "Acts, scenes, dialogue\nRead a scene"),
            ("Summary writing", "Main and supporting ideas\nWrite a summary"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Comprehension: drug abuse", "Read and discuss\nAnswer interpretive questions"),
            ("Listening: note taking from talks", "Listen and outline\nNote taking practice"),
            ("Grammar: prepositional phrases", "Phrases in use\nIdentify and use"),
            ("Grammar: concord basics", "Subject verb agreement\nCorrect the errors"),
            ("Grammar: modifiers", "Adjectives and adverbs order\nPlace modifiers well"),
            ("Vocabulary: journalism words", "Newsroom terms\nUse in writing"),
            ("Composition: speech writing", "Write a short speech\nDeliver to class"),
            ("Literature: poetry devices", "Rhyme and rhythm\nAnalyse a poem"),
            ("Writing: argumentative essay", "Support a view\nReason and evidence"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Comprehension: tourism in Nigeria", "Read and answer\nVocabulary in context"),
            ("Listening: interviews", "Question and answer style\nConduct mini interviews"),
            ("Grammar: phrasal verbs", "Common phrasal verbs\nUse in context"),
            ("Grammar: reported speech", "Statements and questions\nReport accurately"),
            ("Grammar: punctuation mastery", "Dashes avoided, brackets used\nEdit paragraphs"),
            ("Vocabulary: science and technology words", "Terms in use\nBuild word power"),
            ("Composition: expository essay", "Explain a process\nStructure clearly"),
            ("Literature: prose analysis", "Plot and characters\nDiscuss a novel excerpt"),
            ("Writing: formal letter", "Letter of request\nTwo address format"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Mathematics": {
        1: [
            ("Revision of JSS one work", "Number operations recap\nQuick drills"),
            ("Indices and standard form", "Laws of indices\nWrite in standard form"),
            ("Surds basics", "Square roots\nSimple surd manipulation"),
            ("Algebraic fractions", "Simplify fractions\nSolve equations with fractions"),
            ("Linear equations and inequalities", "Solve and graph\nWord problems"),
            ("Quadratic expressions: expansion", "Expand products\nPerfect squares"),
            ("Factorisation: quadratic expressions", "Factorise trinomials\nApply to problems"),
            ("Geometry: circle theorems basics", "Chords and angles\nSimple theorems"),
            ("Trigonometry basics", "Sine, cosine, tangent\nRatios in right triangles"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Trigonometry: applications", "Heights and distances\nSolve real problems"),
            ("Bearings", "Compass bearings\nNavigation problems"),
            ("Statistics: grouped data", "Mean of grouped data\nTables and classes"),
            ("Statistics: presentation", "Histograms and ogives\nDraw and read"),
            ("Probability basics", "Chance experiments\nSimple probabilities"),
            ("Mensuration: circles", "Circumference and area\nSector and segment"),
            ("Mensuration: prisms", "Volume of prisms\nSurface area work"),
            ("Construction: loci basics", "Locus of points\nConstruct loci"),
            ("Simple interest and compound interest", "Compute interest\nCompare growth"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Numbers: rational and irrational", "Classify numbers\nOperations review"),
            ("Algebra: simultaneous equations", "Elimination and substitution\nSolve problems"),
            ("Algebra: quadratic equations", "Solve by factorisation\nApply to problems"),
            ("Geometry: polygons", "Interior and exterior angles\nRegular polygons"),
            ("Geometry: transformations", "Reflection and rotation\nTransform shapes"),
            ("Statistics: median and quartiles", "Find medians\nCumulative frequency basics"),
            ("Probability: applications", "Dice and coin problems\nReal life probability"),
            ("Mensuration: cylinders and cones", "Volume and surface area\nSolve applications"),
            ("Everyday mathematics", "Taxes, bills, budgets\nProject work"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Basic Science": {
        1: [
            ("Revision of JSS one work", "Body systems recap\nQuick review quiz"),
            ("Respiration and breathing", "Aerobic respiration\nBreathing rate experiment"),
            ("Excretion in organisms", "Organs of excretion\nWaste removal"),
            ("Circulation: blood and heart", "Blood components\nHeart rate exercise"),
            ("Skeleton and movement", "Joints and muscles\nMovement types"),
            ("Growth and development", "Puberty changes\nGrowth charts"),
            ("Habitats and adaptations", "Match organisms to habitats\nAdaptation examples"),
            ("Food chains and webs", "Energy flow\nBuild a web"),
            ("Conservation of resources", "Protect habitats\nRecycling project"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Elements and symbols", "First twenty elements\nLearn the symbols"),
            ("Compounds and mixtures", "Formulas of compounds\nSeparate mixtures"),
            ("Chemical reactions basics", "Reactants and products\nSimple reactions"),
            ("Acids, bases and salts", "Litmus testing\nEveryday examples"),
            ("Water: properties and treatment", "Purify water\nHard water talk"),
            ("Air and combustion", "Components of air\nRusting and burning"),
            ("Metals and non metals", "Properties comparison\nUses in life"),
            ("Force and motion", "Newton basics\nMeasure speed"),
            ("Pressure", "Pressure in liquids and gases\nApplications"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Work, energy and power", "Calculate work\nEnergy conversions"),
            ("Simple machines: mechanics", "Levers and pulleys\nMechanical advantage"),
            ("Heat transfer", "Conduction, convection, radiation\nApplications"),
            ("Light: reflection and refraction", "Plane mirrors\nRefraction demos"),
            ("Sound: waves and hearing", "Pitch and loudness\nEcho basics"),
            ("Electricity: current and circuits", "Ohm basics\nMeasure current"),
            ("Magnetism and electromagnetism", "Fields and coils\nMake an electromagnet"),
            ("Electronics basics", "Semiconductors talk\nSimple components"),
            ("Science project", "Plan and build\nPresent the project"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Basic Technology": {
        1: [
            ("Revision of drawing basics", "Line types and lettering\nQuick construction drill"),
            ("Geometric construction: triangles", "Construct given sides\nAccurate construction"),
            ("Construction: quadrilaterals", "Squares and parallelograms\nConstruct precisely"),
            ("Construction: circles and arcs", "Tangents and arcs\nDraw with instruments"),
            ("Isometric projection", "Isometric circles\nDraw complex blocks"),
            ("Oblique projection", "Cabinet projection\nDraw objects"),
            ("Orthographic projection", "Three view projection\nProject components"),
            ("Dimensioning techniques", "Dimension rules\nDimension my drawing"),
            ("Design process", "Identify and plan\nDesign a product"),
            ("Revision and assessment", "Term work review\nPractical quiz"),
        ],
        2: [
            ("Wood: processing", "Felling to seasoning\nPrepare timber"),
            ("Woodwork: tools and machines", "Planers and lathes\nMachine basics"),
            ("Wood joints: advanced", "Mortise and tenon\nMake the joint"),
            ("Metals: extraction and forms", "Ore to metal\nMetal products"),
            ("Metalwork: processes", "Welding and brazing talk\nJoin metals demo"),
            ("Metalwork: finishing", "Polishing and painting\nFinish my work"),
            ("Plastics: types and processing", "Thermoplastics talk\nForm plastics"),
            ("Ceramics and glass", "Production basics\nIdentify products"),
            ("Electrical projects", "Wire a lamp holder\nSafe wiring practice"),
            ("Revision and assessment", "Term work review\nPractical quiz"),
        ],
        3: [
            ("Building construction: site work", "Setting out\nSite preparation"),
            ("Foundations", "Types of foundations\nStrip foundation talk"),
            ("Walls and blocks", "Block making\nWall construction"),
            ("Doors and windows", "Types and fixing\nFit a frame"),
            ("Roofing basics", "Roof types\nCover and trusses"),
            ("Services: plumbing", "Water systems\nSimple pipe work"),
            ("Services: electricity in buildings", "Circuits at home\nDistribution board talk"),
            ("Bridges and roads", "Types and parts\nCivil engineering talk"),
            ("Project: model building", "Build a model structure\nPresent and test"),
            ("Revision and assessment", "Year work review\nEnd of year practical"),
        ],
    },
    "Business Studies": {
        1: [
            ("Revision of JSS one work", "Office and trade recap\nQuick quiz"),
            ("The market: types", "Perfect and imperfect talk\nMarket features"),
            ("Demand and supply basics", "Law of demand\nLaw of supply"),
            ("Price determination", "Equilibrium idea\nPrice movements"),
            ("Business units: sole proprietorship", "Features and merits\nLocal examples"),
            ("Business units: partnership", "Features and demerits\nCompare with sole trade"),
            ("Documents: debit and credit notes", "When they are used\nFill the documents"),
            ("Bookkeeping: two column cash book", "Record receipts and payments\nBalance the book"),
            ("Bank reconciliation basics", "Cash book vs bank statement\nSimple reconciliation"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Companies: limited liability", "Private and public companies\nFormation talk"),
            ("Cooperative societies", "Types and benefits\nLocal cooperatives"),
            ("Public corporations", "Features and examples\nRoles in economy"),
            ("Stock exchange basics", "Shares and bonds\nHow markets work"),
            ("Insurance: types", "Life and vehicle cover\nClaim basics"),
            ("Transport: documents", "Waybills and bills of lading\nProcess documents"),
            ("Warehousing", "Types and importance\nStore documents"),
            ("Advertising", "Types and media\nDesign an advert"),
            ("Sales promotion", "Discounts and coupons\nPlan a promotion"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Bookkeeping: three column cash book", "Discount columns\nRecord and balance"),
            ("Petty cash book", "Imprest system\nRecord small payments"),
            ("Purchases and sales day books", "Record credit trades\nPost to ledgers"),
            ("Ledger postings", "Post from day books\nBalance accounts"),
            ("Trading profit and loss account", "Prepare simple accounts\nFind net profit"),
            ("Balance sheet basics", "Assets and liabilities\nPrepare a simple one"),
            ("Business ethics", "Honesty in business\nFair trading"),
            ("Consumer rights", "SON and NAFDAC\nProtect consumers"),
            ("Entrepreneurship project", "Write a mini plan\nPresent the venture"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Civic Education": {
        1: [
            ("Revision of JSS one values", "Values recap\nApply the values"),
            ("Integrity", "Meaning and importance\nRole models"),
            ("Contentment", "Avoid greed\nLive contentedly"),
            ("Discipline", "Self control habits\nBenefits of discipline"),
            ("Courage", "Face challenges\nCourageous people"),
            ("Nationalism", "Love of nation\nNationalist heroes"),
            ("The Nigerian constitution: history", "1979, 1999 constitutions\nKey features"),
            ("Constitution: supremacy", "Supreme law talk\nEquality before law"),
            ("Electoral bodies", "INEC roles\nConduct elections"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Democracy: definition and features", "Pillars of democracy\nBenefits and dangers"),
            ("Federalism: meaning", "Sharing of powers\nNigerian federalism"),
            ("Federalism: problems", "Resource control talk\nSolutions offered"),
            ("Citizenship: acquisition", "By birth and registration\nLegal pathways"),
            ("Citizenship: responsibilities", "Civic duties list\nFulfil my duties"),
            ("Rights: fundamental", "Chapter four rights\nKnow and claim"),
            ("Rights: limitations", "Rights are not absolute\nBalance with duties"),
            ("Human rights abuse", "Identify abuses\nReport mechanisms"),
            ("Agencies: legal aid and public complaints", "Who protects me\nAccess help"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Political parties", "Functions of parties\nParty systems"),
            ("Elections: types", "General and by elections\nProcess of voting"),
            ("Electoral malpractice", "Forms of rigging\nPrevent malpractice"),
            ("Voters education", "Who can vote\nVote wisely"),
            ("Civil service", "Roles and structure\nServe the public"),
            ("Public service ethics", "Transparency and accountability\nServe with honour"),
            ("Community service", "Volunteer projects\nServe my community"),
            ("National economy: sectors", "Agriculture, industry, services\nEconomic activities"),
            ("Economic reform basics", "Policies that shape life\nUnderstand reforms"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Cultural and Creative Arts": {
        1: [
            ("Revision of elements", "Elements and principles recap\nAnalyse artworks"),
            ("Drawing: advanced shading", "Tonal values\nDraw still life"),
            ("Colour: harmony schemes", "Complementary and analogous\nPaint in harmony"),
            ("Music: major scales", "Construct scales\nSing in major keys"),
            ("Music: simple harmony", "Triads and cadences\nHarmonise a song"),
            ("Crafts: weaving advanced", "Loom basics\nWeave a mat"),
            ("Ceramics: throwing talk", "Wheel throwing demo\nCentering basics"),
            ("Dance: elements of dance", "Space, time, energy\nCreate movement phrases"),
            ("Drama: voice production", "Projection and articulation\nVoice exercises"),
            ("Revision and assessment", "Term work review\nPractical display"),
        ],
        2: [
            ("Printmaking: relief printing", "Design and carve\nPrint editions"),
            ("Graphics: book cover design", "Layout and typography\nDesign a cover"),
            ("Textile: batik", "Wax resist methods\nProduce batik"),
            ("Music: minority instruments", "Kakaki and algaita\nCultural contexts"),
            ("Music: composing with technology", "Simple digital tools\nCreate a beat"),
            ("Dance: choreography tools", "Motif development\nChoreograph a piece"),
            ("Drama: characterization", "Build a character\nPerform monologues"),
            ("Theatre: stage design", "Sets and props\nDesign a stage"),
            ("Arts management", "Galleries and dealers\nPlan an exhibition"),
            ("Revision and assessment", "Term work review\nPractical display"),
        ],
        3: [
            ("Sculpture: casting talk", "Casting processes\nMake a mould"),
            ("Crafts: jewellery making", "Design and produce\nBead and wire work"),
            ("Photography basics", "Composition rules\nShoot a theme"),
            ("Music: Nigerian art music", "Composers and works\nListen and analyse"),
            ("Music performance: concert", "Plan and rehearse\nPerform a concert"),
            ("Dance: cultural preservation", "Document dances\nArchive my culture"),
            ("Drama: full production", "Produce a play\nFrom page to stage"),
            ("Film: storyboarding", "Plan a short film\nShoot a scene"),
            ("Exhibition and evaluation", "Mount and critique\nFinal exhibition"),
            ("Revision and assessment", "Year work review\nEnd of year display"),
        ],
    },
    "Home Economics": {
        1: [
            ("Revision of JSS one work", "Tools and stitches recap\nQuick practical"),
            ("Family living: roles", "Father, mother, children\nShared responsibilities"),
            ("Family crises", "Common crises\nCoping strategies"),
            ("Food: nutrients deep dive", "Vitamins and minerals\nDeficiency diseases"),
            ("Meal planning for groups", "Plan for the family\nBudget considerations"),
            ("Cooking: methods review", "Moist and dry heat\nChoose methods"),
            ("Baking: cakes", "Ingredients and methods\nBake a cake"),
            ("Pastries: meat pie", "Make pastry dough\nFill and bake"),
            ("Textiles: fabric construction", "Weaving and knitting\nIdentify weaves"),
            ("Revision and assessment", "Term work review\nPractical quiz"),
        ],
        2: [
            ("Clothing: choosing fabrics", "Suitability factors\nChoose wisely"),
            ("Sewing: fullness", "Darts and tucks\nSew fullness"),
            ("Sewing: openings and fastenings", "Buttons and zips\nFix fastenings"),
            ("Making a simple skirt", "Measure and cut\nAssemble the skirt"),
            ("Laundry: stains removal", "Treat stains\nWash correctly"),
            ("Care labels", "Read the labels\nFollow instructions"),
            ("Home management: work simplification", "Plan house work\nSave time and energy"),
            ("Home decoration", "Colour schemes\nArrange a room"),
            ("Flower arrangement", "Fresh and artificial\nArrange flowers"),
            ("Revision and assessment", "Term work review\nPractical quiz"),
        ],
        3: [
            ("Child development", "Stages of growth\nCare for children"),
            ("Child care: feeding and bathing", "Practical care\nSafety for children"),
            ("Family health: infections", "Common infections\nPrevention habits"),
            ("First aid: home accidents", "Common accidents\nEmergency response"),
            ("Food preservation: methods", "Drying, freezing, canning\nPreserve foods"),
            ("Home enterprises: catering", "Start small catering\nCost and price"),
            ("Home enterprises: tailoring", "Sew for sale\nManage orders"),
            ("Consumer protection", "Agencies and laws\nBuy safely"),
            ("Careers in home economics", "Food, textile, childcare\nPlan a career"),
            ("Revision and assessment", "Year work review\nEnd of year practical"),
        ],
    },
    "Information Technology": {
        1: [
            ("Revision of JSS one work", "Hardware and software recap\nPractical refresher"),
            ("Word processing: advanced formatting", "Styles and themes\nFormat reports"),
            ("Mail merge basics", "Letters to many\nMerge documents"),
            ("Spreadsheets: advanced formulas", "IF and count functions\nAnalyse data"),
            ("Spreadsheet: charts and filters", "Visualise data\nFilter records"),
            ("Database basics", "Tables and records\nCreate a database"),
            ("Database queries", "Find and sort\nQuery my data"),
            ("Presentations: master slides", "Design consistency\nBuild a deck"),
            ("Internet: research skills", "Evaluate sources\nCite references"),
            ("Revision and assessment", "Term work review\nPractical quiz"),
        ],
        2: [
            ("Graphic design basics", "Tools and layout\nDesign a flyer"),
            ("Image editing", "Crop and adjust\nEdit photos"),
            ("Audio editing basics", "Record and trim\nMake a podcast"),
            ("Video basics", "Shoot and cut\nMake a short clip"),
            ("Coding: text basics", "HTML introduction\nBuild a simple page"),
            ("HTML: lists and links", "Structure content\nLink pages"),
            ("HTML: images and tables", "Add media\nTabulate data"),
            ("Web safety", "Safe browsing\nProtect information"),
            ("Project: mini website", "Plan and build\nPresent the site"),
            ("Revision and assessment", "Term work review\nPractical quiz"),
        ],
        3: [
            ("Computer networks", "LAN and WAN\nNetwork types"),
            ("The internet infrastructure", "Servers and ISPs\nHow data travels"),
            ("Cloud computing", "Storage and services\nUse cloud tools"),
            ("Digital collaboration", "Share documents\nWork online safely"),
            ("E commerce basics", "Online buying\nSafe transactions"),
            ("E learning tools", "Platforms and apps\nStudy with technology"),
            ("Artificial intelligence talk", "What AI does\nEveryday examples"),
            ("ICT and society", "Digital divide talk\nResponsible use"),
            ("Careers in ICT", "Roles and skills\nPlan my path"),
            ("Revision and assessment", "Year work review\nEnd of year practical"),
        ],
    },
    "Physical and Health Education": {
        1: [
            ("Revision of JSS one skills", "Athletics recap\nFitness drills"),
            ("Athletics: sprints theory and practice", "Technique phases\nSprint drills"),
            ("Athletics: relay rules", "Changeover rules\nRelay practice"),
            ("Football: tactics", "Formation basics\nPlay positional games"),
            ("Volleyball: systems", "Serve receive patterns\nPlay matches"),
            ("Basketball: rules and officiating", "Violations list\nOfficiate mini games"),
            ("Recreation: games of low organisation", "Simple games rules\nOrganise games"),
            ("Health: growth and development", "Adolescence talk\nHealthy habits"),
            ("Health: diseases prevention", "Vector control\nPrevent malaria"),
            ("Revision and assessment", "Term work review\nSkills display"),
        ],
        2: [
            ("Gymnastics: advanced tumbling", "Round off basics\nSequence building"),
            ("Gymnastics: group balances", "Counter balance\nPerform routines"),
            ("Handball: goalkeeping", "Stance and saves\nKeeper drills"),
            ("Table tennis: tactics", "Spin basics\nMatch play"),
            ("Athletics: hurdling", "Stride pattern\nHurdle drills"),
            ("First aid: resuscitation talk", "CPR awareness\nEmergency steps"),
            ("First aid: bites and stings", "Snake and insect bites\nImmediate care"),
            ("Posture: corrective exercises", "Assess posture\nExercise plans"),
            ("Health: substance abuse", "Tobacco and alcohol\nRefusal skills"),
            ("Revision and assessment", "Term work review\nSkills display"),
        ],
        3: [
            ("Sports administration", "Organise competitions\nPlan a sports day"),
            ("Traditional sports: rules mastery", "Ayo and dambe talk\nOfficiate games"),
            ("Swimming: strokes basics", "Freestyle arms\nWater safety drills"),
            ("Athletics: combined events", "Pentathlon basics\nPlan my events"),
            ("Fitness: training principles", "Overload and recovery\nDesign workouts"),
            ("Health: population and health", "Community health\nSanitation projects"),
            ("Health: agency roles", "NCDC and WHO\nHealth campaigns"),
            ("Nutrition for athletes", "Eat for performance\nPlan sports meals"),
            ("Sports injuries", "Common injuries\nPrevention and care"),
            ("Revision and assessment", "Year work review\nEnd of year display"),
        ],
    },
    "Social Studies": {
        1: [
            ("Revision of JSS one work", "Family and culture recap\nQuick quiz"),
            ("Science and technology in community development", "Technology changes life\nAssess impacts"),
            ("Agencies of socialisation: school", "Values from school\nSchool culture"),
            ("Agencies: mass media", "Media influence\nUse media wisely"),
            ("Agencies: religious groups", "Values from faith\nPeaceful worship"),
            ("Social problems: poverty", "Causes of poverty\nAddress poverty"),
            ("Social problems: crime", "Types of crime\nPrevention roles"),
            ("Social problems: cultism", "Dangers of cults\nSay no early"),
            ("Population growth", "Rapid growth effects\nPlan for people"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Nigeria: physical setting", "States and capitals\nMap work"),
            ("Nigeria: peoples and cultures", "Major groups\nCultural displays"),
            ("National economy: agriculture", "Role in economy\nModernise farming"),
            ("National economy: manufacturing", "Industries talk\nMade in Nigeria"),
            ("National economy: services", "Banking and telecom\nService growth"),
            ("Environmental problems: erosion", "Causes of erosion\nControl measures"),
            ("Environmental problems: pollution", "Types of pollution\nReduce pollution"),
            ("World environment: climate", "Climate change talk\nAct locally"),
            ("Project: community mapping", "Map my area\nPresent findings"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Democracy: practice in Nigeria", "Institutions at work\nParticipate civically"),
            ("National integration", "Unity strategies\nLive as one"),
            ("Global issues: terrorism", "Understanding the threat\nPeace education"),
            ("Global issues: human trafficking", "Tactics of traffickers\nProtect yourself"),
            ("Global issues: child labour", "Causes and effects\nChildren deserve school"),
            ("Values: honesty in national life", "Anti corruption talk\nIntegrity practices"),
            ("Leadership: qualities", "Great leaders studied\nLead responsibly"),
            ("Followership: qualities", "Support good causes\nBe a responsible follower"),
            ("Project: action for change", "Plan a community action\nExecute and report"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Agricultural Science": {
        1: [
            ("Revision of JSS one work", "Tools and crops recap\nPractical refresher"),
            ("Soil science: properties", "Physical properties\nTest soil samples"),
            ("Soil science: fertility", "Nutrients for plants\nMaintain fertility"),
            ("Pasture and forage crops", "Types of forage\nIdentify grasses"),
            ("Forest resources", "Trees and products\nForest management talk"),
            ("Wildlife in agriculture", "Conservation basics\nProtect wildlife"),
            ("Crop diseases: identification", "Symptoms on crops\nDiagnose diseases"),
            ("Crop pests: store pests", "Weevils and rodents\nProtect stores"),
            ("Agro chemicals", "Fertilisers and pesticides\nApply safely"),
            ("Revision and assessment", "Term work review\nPractical quiz"),
        ],
        2: [
            ("Anatomy of farm animals", "Body parts of cattle\nLabel and identify"),
            ("Animal physiology: digestion", "Ruminants vs non ruminants\nCompare digestion"),
            ("Animal reproduction", "Gestation basics\nReproductive cycles"),
            ("Animal nutrition", "Feed classes\nRation basics"),
            ("Poultry production: systems", "Intensive and free range\nChoose systems"),
            ("Poultry: egg production", "Layers management\nCollect and grade eggs"),
            ("Fisheries: pond culture", "Stock a pond\nManage water"),
            ("Fisheries: harvest and processing", "Harvest fish\nProcess and store"),
            ("Bee keeping basics", "Hives and honey\nCare for bees"),
            ("Revision and assessment", "Term work review\nPractical quiz"),
        ],
        3: [
            ("Agricultural economics: wants and scarcity", "Basic economic ideas\nApply to farming"),
            ("Farm records", "Types of records\nKeep farm records"),
            ("Farm accounts", "Income and expenses\nSimple accounts"),
            ("Marketing: farm produce", "Price determination\nMarketing channels"),
            ("Agricultural extension services", "Roles of extension\nVisit a farm"),
            ("Farm machinery: engines", "Two stroke and four stroke\nCompare engines"),
            ("Machinery maintenance", "Service schedules\nMaintain machines"),
            ("Mechanised farming", "Benefits and challenges\nModern agriculture talk"),
            ("Project: school farm plan", "Plan the season\nExecute the plan"),
            ("Revision and assessment", "Year work review\nEnd of year practical"),
        ],
    },
}
