#!/usr/bin/env python3
"""Nursery 3 scheme data, part B: Health Habits, Basic Science and Discovery, Creative Arts, Moral Instruction, Handwriting."""

NURSERY_3_B = {
    "Health Habits": {
        1: [
            ("My amazing body", "Bones, muscles, heart, lungs\nBody systems puzzle"),
            ("Nutrition plate", "Go, grow and glow foods\nBuild my healthy plate"),
            ("Food groups", "Carbohydrate, protein, vitamins\nSort my meal"),
            ("Cooking is science", "Watch beans porridge being made\nKitchen safety rules"),
            ("Exercise and heart", "Heart rate after play\nExercise chart"),
            ("Posture and spine", "Sit, stand and lift well\nBack friendly habits"),
            ("Sleep science", "Growth happens in sleep\nBedtime routines"),
            ("Hygiene deep clean", "Full hygiene audit\nChecklist practice"),
            ("First aid basics", "Cuts, burns, nosebleed\nCall for help steps"),
            ("Revision and health fair", "Health stations around class\nHealth fair passport"),
        ],
        2: [
            ("Disease and prevention", "How sickness spreads\nPrevention habits"),
            ("Malaria and nets", "Mosquito life cycle basics\nNet hanging practice"),
            ("Immunisation", "Why we take vaccines\nMy immunisation card"),
            ("Environment and health", "Gutters, bushes and sickness\nClean environment poster"),
            ("Water watch", "Safe drinking water\nWater sources sort"),
            ("Food safety", "Clean hands, covered food\nStreet food wisdom"),
            ("Road safety full", "Crossing, walking, riding\nTraffic light craft"),
            ("Stranger and body safety", "Scream, run, tell\nSafe touches only"),
            ("Fire and burn safety", "Hot things, matches, candles\nStop, drop and roll"),
            ("Revision and safety quiz", "Mixed safety scenarios\nSafety certificate"),
        ],
        3: [
            ("Body changes talk", "Growing up is healthy\nQuestions welcome"),
            ("Personal safety plan", "My safe adults list\nMy phone number memory"),
            ("Emergency numbers", "Who to call for help\nRole play emergencies"),
            ("Sports and teamwork", "Relay and ball games\nPlay fair, stay safe"),
            ("Rest and relaxation", "Quiet time, breathing\nSimple meditation"),
            ("Screen health", "Eye rest, posture, time limits\nFamily media plan"),
            ("Growing food", "Water our school garden\nHarvest and taste"),
            ("Health careers", "Doctor, nurse, pharmacist visit\nAsk our helpers"),
            ("My health promise", "Pick three health habits to keep\nSign my promise"),
            ("Revision and health graduation", "Teach a habit to a friend\nHealth ambassador awards"),
        ],
    },
    "Basic Science and Discovery": {
        1: [
            ("Science is asking why", "Question wall opens\nOur discovery tools"),
            ("Measure it", "Ruler, tape and scale\nMeasure everything hunt"),
            ("Magnets at work", "Attract and repel\nMagnetic maze game"),
            ("Electric basics", "Battery, bulb, wire\nLight the bulb with help"),
            ("Static fun", "Balloon and paper bits\nSparkly static experiments"),
            ("Sink and float deep dive", "Heavy ships float, why\nClay boat challenge"),
            ("Air power", "Straw rockets and parachutes\nAir pushes things"),
            ("Water cycle start", "Evaporation puddles and rain\nWatch and draw"),
            ("Recycling science", "Sort and reuse materials\nBottle bank craft"),
            ("Revision and inventor day", "Show my experiment\nExplain like a scientist"),
        ],
        2: [
            ("Plants we eat", "Roots, stems, leaves we eat\nVegetable sorting"),
            ("Grow our food", "Plant maize and beans\nGarden duty roster"),
            ("Soil types", "Sandy, clay and loam\nFeel and sort soils"),
            ("Small creatures big jobs", "Worms and bees help plants\nWormery observation"),
            ("Bird watch", "Local birds and their nests\nBinocular craft"),
            ("Animal classification", "Farm, wild, water animals\nSort and group"),
            ("Body movement science", "Joints and muscles\nRobot and stretch play"),
            ("Senses experiment", "Taste, smell and touch stations\nBlindfold guessing"),
            ("Simple machines", "Lever, ramp, pulley play\nMove the load"),
            ("Revision and garden harvest", "Present my garden notes\nTaste our harvest"),
        ],
        3: [
            ("Experiment planning", "Question, guess, test, see\nPlan my mini experiment"),
            ("Plant experiment", "Water or no water\nRecord growth chart"),
            ("Weather station", "Rain gauge and wind flag\nDaily weather log"),
            ("Solar oven snack", "Melt chocolate with the sun\nSun energy snack"),
            ("Bridge building", "Build with sticks and tape\nTest the strongest bridge"),
            ("Boat engineering", "Design a load carrying boat\nFloat the cargo"),
            ("Sound experiment", "String telephone\nSound travels"),
            ("Light and colour", "Prism and rainbow making\nColour mixing light"),
            ("Earth care project", "Reuse, reduce, recycle plan\nClass eco poster"),
            ("Revision and science fair", "Full science fair\nParents' tour"),
        ],
    },
    "Creative Arts": {
        1: [
            ("Artist study", "Look at local artists' work\nWhat do I see, feel"),
            ("Sketch books start", "My own sketch book\nDaily little drawings"),
            ("Perspective first step", "Near things big, far things small\nRoad to my house drawing"),
            ("Clay technique", "Pinch, coil and slab methods\nChoose my technique"),
            ("Textile patterns", "Adire, ankara and aso oke\nDesign my cloth"),
            ("Printing mastery", "Stamp, rub and screen play\nPattern repeat design"),
            ("3D craft", "Paper sculpture animals\nFold, roll and paste"),
            ("Portrait mastery", "Draw a grown up I love\nProportion practice"),
            ("Group installation", "Plan and build one big piece\nClass project"),
            ("Exhibition opening", "Curate our gallery\nInvite cards for parents"),
        ],
        2: [
            ("Cultural masks", "Study and make festival masks\nOwn mask design"),
            ("Dance costume craft", "Make raffia and bead pieces\nDress the dancers"),
            ("Musical instruments", "Make shakers, drums and rattles\nDecorate and play"),
            ("Drama props", "Crowns, wands and scenery\nProp painting crew"),
            ("Backdrop painting", "Paint the big stage cloth\nTeam painting day"),
            ("Flyer design", "Design graduation flyers\nBright lettering"),
            ("Photography day", "Take portraits of friends\nFrame my best shot"),
            ("Face painting studio", "Simple safe face designs\nPaint and be painted"),
            ("Rehearsal decor", "Dress the graduation stage\nFinal decor touches"),
            ("Graduation gallery and stage", "Final art walk and stage reveal\nStanding ovation"),
        ],
        3: [
            ("Graduation portfolio", "Choose my best five works\nMount and label"),
            ("Artist statement", "Talk about my art\nWrite my artist line"),
            ("Portfolio walk", "Present to another class\nAnswer their questions"),
            ("Community art gift", "Make art for the school wall\nLegacy mural tile"),
            ("Gift crafts", "Make presents for parents\nWrap with our paper"),
            ("Memory book art", "Draw my nursery memories\nPages of my journey"),
            ("Class flag design", "Design our graduating flag\nVote and sew"),
            ("Stage craft final", "Final stage dressing\nCurtain and flowers"),
            ("Grand rehearsal", "Full dress rehearsal\nEvery crew in place"),
            ("Graduation day art", "Our art on the big day\nProud send off"),
        ],
    },
    "Moral Instruction": {
        1: [
            ("My identity", "I am special and made with care\nMy talents list"),
            ("Integrity jar", "Marbles for honest acts\nClass integrity jar"),
            ("Respect relay", "Respect at home, school, worship\nAct each one"),
            ("Work ethics", "Do my best, not the least\nFinish strong"),
            ("Money and me", "Saving and giving basics\nMoneywise choices"),
            ("Media discernment", "Choose what builds me\nTalk about what we watch"),
            ("Kindness counts", "Kindness tree leaves\nFill the tree"),
            ("Perseverance", "Try, try, try again\nStory of the persistent child"),
            ("Team spirit", "Together we win\nGroup challenges"),
            ("Revision and character crown", "Character review\nCrown ceremony"),
        ],
        2: [
            ("The power of words", "Build or break with words\nSpeak kindly activity"),
            ("Self discipline", "Do what is right, not what is easy\nDiscipline stories"),
            ("Accountability", "Own my actions\nApology and repair"),
            ("Generosity", "Give with joy\nClass giving project"),
            ("Mercy wins", "Choose mercy in little quarrels\nPeace pact activity"),
            ("Courage to stand", "Stand alone for right\nBrave stories"),
            ("Humility", "Great but humble\nServe someone quietly"),
            ("Faithful in little", "Small jobs, big trust\nLittle steward tasks"),
            ("Nation building", "I can build Nigeria\nMy nation promise"),
            ("Revision and values day", "Values showcase\nValues medal awards"),
        ],
        3: [
            ("Graduation gratitude", "Thank God for the journey\nGratitude journal"),
            ("Blessing my school", "Leave it better\nCampus beautify duty"),
            ("Mentoring juniors", "Teach a nursery one class\nBuddy hour"),
            ("My next chapter", "Primary one goals\nWrite my goals letter"),
            ("Courage for change", "New school, new friends\nBrave talk"),
            ("Keeping the values", "My values go with me\nValues passport"),
            ("Blessing my parents", "Honour mummy and daddy\nThank you letters"),
            ("Prayer and blessing", "Pray for our future\nBlessing circle"),
            ("Legacy project final", "Finish our legacy gift\nPresent to head teacher"),
            ("Graduation character send off", "Character awards and blessings\nCaps and smiles"),
        ],
    },
    "Handwriting": {
        1: [
            ("Fluency lines", "Write full lines neatly\nSpeed with control"),
            ("Word families copy", "Copy family word lists\nCheck my joins"),
            ("Sight words writing", "Write sight words from memory\nSpelling and writing together"),
            ("Sentence writing", "Write my own sentences\nCapitals and stops"),
            ("Question sentences", "Write and answer questions\nQuestion marks"),
            ("Little paragraph", "Write three linked sentences\nAbout my family"),
            ("Number words to twenty", "Write number words\nMatch digits and words"),
            ("Dictation 1", "Words and one sentence\nListen and write"),
            ("Dictation 2", "Two sentences this time\nCheck my work"),
            ("Revision and writing show", "Best independent page\nWriting award"),
        ],
        2: [
            ("Composition 1", "My best friend, four sentences\nPlan, write, read"),
            ("Composition 2", "My favourite food, four sentences\nDescribe and explain"),
            ("Composition 3", "A rainy day story\nFirst, then, last"),
            ("Letter writing", "Write to granny\nGreeting and closing"),
            ("List making", "My shopping list, my wishes\nNeat numbered lists"),
            ("Card messages", "Birthday and thank you lines\nInside card writing"),
            ("Label and caption", "Caption my picture\nLabel my diagram"),
            ("Dictation mastery", "Full dictation paragraph\nSelf check habit"),
            ("Free writing", "Write anything I choose\nShare my writing"),
            ("Revision and author chair", "Read my writing aloud\nAuthor certificates"),
        ],
        3: [
            ("Primary one readiness", "Copy longer passages\nStamina building"),
            ("Note taking start", "Write what teacher says in steps\nSimple notes"),
            ("Composition mastery", "My graduation day plan\nFive sentences"),
            ("Story with pictures", "Illustrate my story\nAuthor and illustrator"),
            ("Spelling bee prep", "Word lists and games\nClass spelling bee"),
            ("Handwriting olympics", "Neat, fast and proud\nTimed neat writing"),
            ("Autograph pages", "Write in friends' memory books\nSignature practice"),
            ("Graduation programme copy", "Copy my programme lines\nContribute to the day"),
            ("Final portfolio page", "My proudest writing\nMount for graduation"),
            ("Revision and send off", "Writing journey review\nPrimary one, here I come"),
        ],
    },
}
