#!/usr/bin/env python3
"""Nursery 2 scheme data, part A: Letter Work, Number Work, Rhymes, Social Habits."""

NURSERY_2_A = {
    "Letter Work": {
        1: [
            ("Sounds revision Aa to Ff", "Say each sound with its picture\nCircle the first sound in apple, ball"),
            ("Sounds Gg to Ll", "Goat, hat, ink, jug, kite, leaf\nTrace and say each sound"),
            ("Sounds Mm to Rr", "Moon, nose, orange, pen, queen, rope\nMatch letter to picture"),
            ("Sounds Ss to Zz", "Sun, tap, umbrella, van, water, box\nSay all 26 sounds"),
            ("Vowel sounds a and e", "a as in cat, e as in hen\nSort pictures by vowel"),
            ("Vowel sounds i, o, u", "i as in sit, o as in pot, u as in cup\nPick the middle sound"),
            ("Two letter words", "at, an, am, in, on, up\nBlend and read together"),
            ("Word family an", "ban, can, fan, man, pan\nRead the family ladder"),
            ("Word family at", "bat, cat, fat, hat, mat\nMake new words with letter cards"),
            ("Revision and reading fun", "Read two letter words fast\nRead our word wall"),
        ],
        2: [
            ("Word family ad", "bad, dad, had, mad, pad\nBlend and read"),
            ("Word family ap", "cap, lap, map, nap, tap\nRead and match to pictures"),
            ("Word family ig", "big, dig, pig, wig\nRead the pig story"),
            ("Word family in", "bin, fin, pin, tin, win\nPin the word to the picture"),
            ("Word family og", "dog, fog, log, jog\nRead and clap"),
            ("Word family ot", "cot, dot, hot, pot\nRead and write on the board"),
            ("Word family ug", "bug, jug, mug, rug\nMug the bug game"),
            ("Word family un", "bun, fun, run, sun\nRead and run game"),
            ("Simple sentences", "The cat sat. The dog ran.\nRead with the teacher"),
            ("Revision and word contest", "Word family relay\nRead our class word wall"),
        ],
        3: [
            ("Rhyming words", "cat and hat, sun and fun\nPick the word that rhymes"),
            ("Opposites", "big and small, up and down\nMatch the opposites"),
            ("My body words", "head, hand, eye, ear, leg\nLabel the body picture"),
            ("Family words", "mummy, daddy, sister, brother\nDraw and label my family"),
            ("Classroom words", "desk, chair, book, board\nLabel our classroom"),
            ("Colours and number words", "red, blue, one, two, three\nRead the colour cards"),
            ("Reading short sentences", "I can see a big bus.\nRead together and alone"),
            ("Question words", "what, where, who\nAsk each other little questions"),
            ("Story time words", "Read the class story together\nPoint to words we know"),
            ("Revision and reading celebration", "Read a page on my own\nReading certificate for all"),
        ],
    },
    "Number Work": {
        1: [
            ("Count and write 1 to 10", "Count objects and write the number\nMatch number to objects"),
            ("Count 11 to 20", "Count with bundles of ten\nWrite 11 to 20"),
            ("Count 21 to 30", "Number line jump\nWrite 21 to 30"),
            ("Count 31 to 50", "Fill the missing numbers\nWrite 31 to 50"),
            ("Counting 1 to 50 fast", "Count in turns around the circle\nFill number gaps on the board"),
            ("More and fewer", "Which group has more\nCircle the group with fewer"),
            ("Simple addition with objects", "Two sweets and three sweets\nCount all and write the answer"),
            ("Simple subtraction with objects", "Five balls, take away two\nCount what is left"),
            ("Shapes", "Circle, triangle, square\nFind shapes in the room"),
            ("Revision and number games", "Number bingo to 50\nShape hunt in the playground"),
        ],
        2: [
            ("Count 51 to 70", "Count in tens 50, 60, 70\nWrite 51 to 70"),
            ("Count 71 to 90", "Number line walk\nWrite 71 to 90"),
            ("Count 91 to 100", "We reached 100 party\nWrite 91 to 100"),
            ("Counting 1 to 100", "Count by tens, then all together\nFill the hundred chart"),
            ("Adding with objects", "Add two groups of counters\nWrite the sum"),
            ("Adding small numbers", "2 plus 1, 3 plus 2\nDraw and add"),
            ("Taking away", "Take away with counters\nWrite what is left"),
            ("Number before and after", "What comes before 8, after 8\nFill before and after"),
            ("Comparing numbers", "Bigger and smaller numbers\nUse more than, less than with objects"),
            ("Revision and maths fair", "Add and take away relay\nNumber chart race"),
        ],
        3: [
            ("Number names 1 to 10", "one, two, three to ten\nMatch word cards to numbers"),
            ("Number names 11 to 20", "eleven to twenty\nRead and match"),
            ("Ordinal numbers", "first, second, third\nLine up and say our position"),
            ("Adding to 10", "All the ways to make ten\nWrite the addition sentences"),
            ("Adding to 20 without carrying", "12 plus 5 with counters\nWrite and solve"),
            ("Subtraction from 10", "Take away stories\nWrite the subtraction sentence"),
            ("Doubling", "Double two is four\nDouble the dots game"),
            ("Sharing equally", "Share ten sweets between two friends\nHalf of a whole"),
            ("Money play", "Naira play shopping\nBuy and count change to 20"),
            ("Revision and maths olympics", "Mixed addition and subtraction games\nMaths star awards"),
        ],
    },
    "Rhymes": {
        1: [
            ("Welcome back songs", "Sing our class welcome song\nAdd new claps"),
            ("One two three four five", "Count on fingers as we recite\nCatch the fish action"),
            ("Five little ducks", "Count down with duck puppets\nSing the waddling song"),
            ("The farmer in the dell", "Act the farmer and the cheese\nCircle game"),
            ("Head and shoulders", "Touch each part as we sing\nSpeed round"),
            ("Bingo", "Clap the missing letters\nSpell Bingo together"),
            ("I'm a little teapot", "Recite with teapot actions\nPouring action song"),
            ("Two little dickie birds", "Act Peter and Paul with fingers\nFly the birds away and back"),
            ("Hot cross buns", "Recite and clap the rhythm\nOne a penny, two a penny"),
            ("Rhyme concert", "Groups pick and sing rhymes\nClap for every group"),
        ],
        2: [
            ("Twinkle twinkle new verses", "Sing and add our own star words\nActions in pairs"),
            ("Five little firemen", "Count down and act spraying water\nFire safety talk"),
            ("Ten fat sausages", "Count down by twos\nPop and bang actions"),
            ("Miss Polly had a dolly", "Act the doctor and the dolly\nCaring for the sick"),
            ("Little Boy Blue", "Recite and act the horn\nTalk about farm work"),
            ("Polly put the kettle on", "Recite with tea party actions\nFamily roles play"),
            ("Wind the bobbin up", "Actions with hands and arms\nFollow the moving song"),
            ("One finger, one thumb", "Add a body part each verse\nKeep the beat"),
            ("Clap your hands", "Sing and clap in rhythm\nFast and slow rounds"),
            ("Rhyme festival", "Sing term rhymes on stage\nClap along with parents"),
        ],
        3: [
            ("The grand old Duke of York", "March up and down as we sing\nUp and down actions"),
            ("Here we go round the mulberry bush", "Sing each daily task verse\nThis is the way we wash and brush"),
            ("Sing a song of sixpence", "Count four and twenty blackbirds\nAct the king and the queen"),
            ("Little Jack Horner", "Recite with the pie action\nTalk about good behaviour"),
            ("Georgie Porgie", "Recite and act\nTalk about kind friends"),
            ("Doctor Foster", "Recite and act the rain step\nTalk about weather"),
            ("There was an old woman", "Recite the shoe rhyme\nCount the children"),
            ("Sea shell rhyme", "Recite with shell sounds\nListen to the sea in the shell"),
            ("Our class rhyme", "Write our own short rhyme together\nPerform it with actions"),
            ("Graduation rhyme concert", "All time favourite rhymes\nSolo performances"),
        ],
    },
    "Social Habits": {
        1: [
            ("Back to school manners", "Greet the teacher and friends\nShare holiday stories kindly"),
            ("My feelings", "Happy, sad, angry faces\nSay how I feel with words"),
            ("Calm down steps", "Stop, breathe, count to five\nAsk for help calmly"),
            ("Playing fair", "Follow the game rules\nNo cheating in games"),
            ("My classroom job", "Line leader, plant keeper, book helper\nDo my job daily"),
            ("Respect for property", "Handle books and toys with care\nReturn what I borrow"),
            ("Listening skills", "Eyes on the speaker\nRaise my hand to talk"),
            ("Apology and forgiveness", "Say sorry and mean it\nAccept sorry and move on"),
            ("Different families", "Families come in all sizes\nEvery family is special"),
            ("Revision and manners badge", "Role play all term habits\nGood manners badge ceremony"),
        ],
        2: [
            ("Culture and greetings", "Greet the Nigerian way in our cultures\nYoruba, Hausa, Igbo greetings"),
            ("National anthem and pledge", "Recite the pledge\nSing the anthem with respect"),
            ("Our national colours", "Green, white, green\nColour the flag craft"),
            ("Community helpers 1", "Teacher, doctor, nurse\nSay how they help us"),
            ("Community helpers 2", "Police, soldier, firefighter\nThey keep us safe"),
            ("Market day manners", "Greet the trader\nSay please and thank you when buying"),
            ("Transport manners", "Sit in the car, wear the belt\nDo not wave from the window"),
            ("Visiting manners", "Knock before entering\nGreet the host and sit nicely"),
            ("Helping the community", "Do not litter the street\nKeep our estate and school clean"),
            ("Revision and community day", "Dress as a community helper\nSay what my helper does"),
        ],
        3: [
            ("Leadership in class", "Class monitor duties\nLead the line the right way"),
            ("Following leaders", "Support our class monitor\nTake turns to lead"),
            ("Money talk", "Needs first, wants later\nSave in my piggy bank"),
            ("Honesty with money", "Return extra change\nNever take money that is not mine"),
            ("Good touch, bad touch", "My body is mine\nShout and tell a trusted adult"),
            ("Stranger safety", "Never follow strangers\nSay my name only when safe"),
            ("Emergency basics", "Shout for help\nKnow mummy's phone number"),
            ("Kindness with screens", "Screens need grown up time too\nTell adults what I see"),
            ("Peaceful solving", "Talk it out, walk it out\nAgree the fair way"),
            ("Revision and safety certificate", "Recite my safety rules\nSafety star awards"),
        ],
    },
}
