#!/usr/bin/env python3
"""JSS 3 scheme data: twelve subjects, three terms, ten weeks each (BECE year)."""

JSS_3 = {
    "English Studies": {
        1: [
            ("Revision of jss two work", "Comprehension and grammar warm up\nVocabulary drill"),
            ("Comprehension: the price of honesty", "Read and answer\nSummary of paragraphs"),
            ("Grammar: sequence of tenses", "Reported events\nTense consistency drills"),
            ("Grammar: adverbials", "Time, place, manner\nUse in sentences"),
            ("Vocabulary: registered words", "Formal and informal words\nRegister practice"),
            ("Composition: descriptive essay", "My favourite place\nSensory details"),
            ("Argument essay", "Boarding school is better\nCounter arguments"),
            ("Oral: consonant clusters", "str, spr, spl words\nPronunciation drill"),
            ("Literature: figures of speech", "Simile, metaphor, personification\nFind them in poems"),
            ("Revision and BECE practice", "Past questions\nMark and correct"),
        ],
        2: [
            ("Comprehension: leadership and service", "Read and answer\nInference questions"),
            ("Grammar: question tags", "Form and use\nDialogue practice"),
            ("Grammar: phrasal verbs", "Common phrasal verbs\nFill in drills"),
            ("Vocabulary: prefixes and suffixes", "Build and guess meaning\nWord formation"),
            ("Composition: expository essay", "Drug abuse dangers\nPlan and write"),
            ("Formal letter", "Letter of application\nFormat mastery"),
            ("Oral: vowel contrasts", "Minimal pairs\nListen and repeat"),
            ("Literature: drama analysis", "Theme and character\nAct a scene"),
            ("Summary writing", "Main ideas in own words\nSentence reduction"),
            ("Revision and BECE practice", "Past questions\nMark and correct"),
        ],
        3: [
            ("BECE comprehension marathon", "Two passages per week\nTime management"),
            ("BECE grammar marathon", "Lexis and structure drills\nError spotting"),
            ("BECE essay practice", "Narrative and argument\nWrite under time"),
            ("BECE oral marathon", "All sounds review\nPractice tape"),
            ("BECE literature marathon", "Set texts revision\nCharacter and theme questions"),
            ("Mock examination", "Full paper practice\nMark and review"),
            ("Weakness clinics", "Fix my weak topics\nTargeted drills"),
            ("Speed and accuracy", "Timed mini tests\nImprove my score"),
            ("Final mock", "Full dress exam\nFinal review"),
            ("BECE readiness", "Exam day tips\nSend off and blessings"),
        ],
    },
    "Mathematics": {
        1: [
            ("Revision of jss two work", "Number and algebra warm up\nQuick quiz"),
            ("Simultaneous equations", "Elimination and substitution\nWord problems"),
            ("Quadratic expressions", "Expand and factorise\nDifference of two squares"),
            ("Word problems with equations", "Set up the equation\nSolve and check"),
            ("Geometry: similar and congruent triangles", "Conditions for congruence\nProof basics"),
            ("Trigonometry", "Sine, cosine, tangent ratios\nHeight problems"),
            ("Statistics: grouped data", "Mean, median, mode tables\nClass intervals"),
            ("Measurement: cylinders", "Volume and surface area\nReal objects"),
            ("Bearings", "Directions and bearings\nNavigation problems"),
            ("Revision and BECE practice", "Past questions\nMark and correct"),
        ],
        2: [
            ("Numbers and indices", "Laws of indices\nStandard form"),
            ("Logarithms", "Use log tables\nMultiplication with logs"),
            ("Variation", "Direct and inverse\nJoint problems"),
            ("Probability", "Simple events\nExperimental probability"),
            ("Circle geometry", "Chords and angles\nTheorems practice"),
            ("Constructions", "Bisectors and angles\nConstruct triangles"),
            ("Graphs of quadratic functions", "Plot the parabola\nRead the roots"),
            ("Statistics: pie charts", "Angles from data\nDraw and interpret"),
            ("Everyday arithmetic", "Tax, interest, sharing\nBECE style problems"),
            ("Revision and BECE practice", "Past questions\nMark and correct"),
        ],
        3: [
            ("BECE number marathon", "Number operations drills\nSpeed tests"),
            ("BECE algebra marathon", "Equations and expressions\nMixed practice"),
            ("BECE geometry marathon", "Angles, circles, construction\nDiagram practice"),
            ("BECE statistics marathon", "Data questions\nChart reading"),
            ("BECE trigonometry marathon", "Ratios and bearings\nProblem sets"),
            ("Mock examination", "Full paper practice\nMark and review"),
            ("Weakness clinics", "Fix my weak topics\nTargeted drills"),
            ("Speed and accuracy", "Timed mini tests\nImprove my score"),
            ("Final mock", "Full dress exam\nFinal review"),
            ("BECE readiness", "Exam day tips\nSend off"),
        ],
    },
    "Basic Science": {
        1: [
            ("Revision of jss two work", "Matter and energy review\nQuick quiz"),
            ("Family health: genes and traits", "Dominant and recessive traits\nFamily tree of traits"),
            ("Environmental health", "Waste and disease links\nSchool sanitation audit"),
            ("Micro organisms", "Useful and harmful microbes\nMould observation"),
            ("Diseases and prevention", "Communicable diseases\nImmunisation charts"),
            ("The circulatory system", "Blood components\nPulse and exercise"),
            ("The nervous system", "Reflex actions\nReaction time test"),
            ("Metabolism in the body", "Enzymes at work\nDigestion experiment"),
            ("Drugs and substance abuse", "Effects and refusal skills\nSay no campaigns"),
            ("Revision and BECE practice", "Past questions\nMark and correct"),
        ],
        2: [
            ("Work, energy and power", "Calculations and machines\nEnergy audit"),
            ("Electric charges and current", "Simple circuits\nMeasure current"),
            ("Magnetism review", "Fields and uses\nMake an electromagnet"),
            ("Radioactivity basics", "Uses and dangers\nSafety rules"),
            ("Soap making", "Saponification demo\nMake local soap"),
            ("Metals and alloys", "Properties and uses\nSort metals"),
            ("Ceramics and glass", "Making and uses\nClay experiment"),
            ("Plastics and rubber", "Thermoplastics\nRecycling codes"),
            ("Nano and space technology", "Modern frontiers\nResearch talk"),
            ("Revision and BECE practice", "Past questions\nMark and correct"),
        ],
        3: [
            ("BECE biology marathon", "Systems and health drills\nDiagrams practice"),
            ("BECE chemistry marathon", "Elements and reactions\nEquation practice"),
            ("BECE physics marathon", "Motion and energy\nCalculation drills"),
            ("BECE earth science marathon", "Space and environment\nQuick quizzes"),
            ("Mock examination", "Full paper practice\nMark and review"),
            ("Practical revision", "Simple experiments\nRecord and conclude"),
            ("Weakness clinics", "Fix my weak topics\nTargeted drills"),
            ("Speed and accuracy", "Timed mini tests\nImprove my score"),
            ("Final mock", "Full dress exam\nFinal review"),
            ("BECE readiness", "Exam day tips\nSend off"),
        ],
    },
    "Basic Technology": {
        1: [
            ("Revision of jss two work", "Drawing and tools review\nQuick quiz"),
            ("Technical drawing: orthographic", "First angle projection\nDraw the block"),
            ("Isometric drawing", "Isometric axes\nDraw the box"),
            ("Woodwork: joints", "Common joints\nMake a halving joint"),
            ("Metalwork: marking out", "Tools and techniques\nMark my template"),
            ("Building: foundations", "Types of foundations\nSite visit talk"),
            ("Building: walls and floors", "Materials and bonds\nBrick bond patterns"),
            ("Machines: simple mechanisms", "Gears and pulleys\nModel mechanisms"),
            ("Power transmission", "Belt and chain drives\nModel assembly"),
            ("Revision and BECE practice", "Past questions\nMark and correct"),
        ],
        2: [
            ("Electrical projects", "Simple wiring board\nSafety first"),
            ("Plumbing basics", "Pipes and fittings\nJoint practice"),
            ("Geometric construction", "Polygons and circles\nConstruct precisely"),
            ("Sectioning", "Cut views\nSection my block"),
            ("Fastening methods", "Nails, screws, rivets, welding\nChoose and use"),
            ("Woodwork: finishing", "Planing and sanding\nFinish my project"),
            ("Metalwork: forging basics", "Simple bends\nSafety practice"),
            ("Design process", "Need to solution\nDesign my product"),
            ("Project build", "Make my product\nRecord the steps"),
            ("Revision and BECE practice", "Past questions\nMark and correct"),
        ],
        3: [
            ("BECE drawing marathon", "Orthographic and isometric\nTimed drawings"),
            ("BECE tools marathon", "Tools and machines drills\nIdentification"),
            ("BECE building marathon", "Building components\nLabel practice"),
            ("BECE projects marathon", "Design process questions\nPast questions"),
            ("Mock examination", "Full paper practice\nMark and review"),
            ("Project completion", "Finish my build\nPrepare to show"),
            ("Weakness clinics", "Fix my weak topics\nTargeted drills"),
            ("Speed and accuracy", "Timed mini tests\nImprove my score"),
            ("Final mock", "Full dress exam\nFinal review"),
            ("BECE readiness", "Exam day tips\nSend off"),
        ],
    },
    "Business Studies": {
        1: [
            ("Revision of jss two work", "Office and commerce review\nQuick quiz"),
            ("The office", "Functions of an office\nOffice layout"),
            ("Office equipment", "Machines and uses\nCare of equipment"),
            ("Business documents", "Invoice, receipt, order\nFill the documents"),
            ("Book keeping: double entry", "Ledger accounts\nPost entries"),
            ("Trial balance", "Balance the ledgers\nSpot the errors"),
            ("Trading account", "Gross profit\nPrepare the account"),
            ("Profit and loss account", "Net profit\nPrepare the account"),
            ("Balance sheet basics", "Assets and liabilities\nSimple balance sheet"),
            ("Revision and BECE practice", "Past questions\nMark and correct"),
        ],
        2: [
            ("Production", "Types and factors\nLocal examples"),
            ("Division of labour", "Specialisation benefits\nClass activity"),
            ("Home trade", "Retail and wholesale\nTrade chains"),
            ("Foreign trade", "Import and export\nBalance of trade"),
            ("Transport", "Types and choice\nCost comparison"),
            ("Insurance", "Why insure\nTypes of insurance"),
            ("Banking", "Services of banks\nOpen account steps"),
            ("Savings and investment", "Grow my money\nInvestment options"),
            ("Entrepreneurship", "Start up steps\nMy mini plan"),
            ("Revision and BECE practice", "Past questions\nMark and correct"),
        ],
        3: [
            ("BECE commerce marathon", "Trade and aids to trade\nPast questions"),
            ("BECE book keeping marathon", "Ledger to final accounts\nPractice sets"),
            ("BECE office marathon", "Office practice drills\nPast questions"),
            ("Mock examination", "Full paper practice\nMark and review"),
            ("Typing and data entry", "Speed practice\nAccuracy tests"),
            ("Weakness clinics", "Fix my weak topics\nTargeted drills"),
            ("Business plan project", "Write my plan\nPresent my plan"),
            ("Speed and accuracy", "Timed mini tests\nImprove my score"),
            ("Final mock", "Full dress exam\nFinal review"),
            ("BECE readiness", "Exam day tips\nSend off"),
        ],
    },
    "Social Studies": {
        1: [
            ("Revision of jss two work", "Family and society review\nQuick quiz"),
            ("The structure of society", "Groups and institutions\nMap my society"),
            ("Social change", "Causes and effects\nChange in my community"),
            ("Population", "Census and growth\nNigeria's population"),
            ("Resources utilisation", "Human and natural resources\nUse wisely"),
            ("Conflict and resolution", "Causes of conflicts\nPeace processes"),
            ("National unity", "Unity in diversity\nOur diversity fair"),
            ("Corruption", "Effects on society\nIntegrity campaign"),
            ("Human rights", "The Nigerian constitution\nRights and duties"),
            ("Revision and BECE practice", "Past questions\nMark and correct"),
        ],
        2: [
            ("Democracy", "Principles and practice\nMock election"),
            ("Rule of law", "Equality before the law\nCase discussions"),
            ("Citizenship", "Acquisition and duties\nGood citizen project"),
            ("Public service", "Civil servants and us\nServe with honesty"),
            ("Drug abuse", "Social effects\nPrevention campaign"),
            ("Human trafficking", "Dangers and prevention\nAwareness posters"),
            ("Cultism", "Dangers to youth\nChoose wisely"),
            ("HIV and society", "Facts and care\nNo stigma campaign"),
            ("Environmental problems", "Erosion, flood, pollution\nLocal solutions"),
            ("Revision and BECE practice", "Past questions\nMark and correct"),
        ],
        3: [
            ("BECE social studies marathon", "Family to government topics\nPast questions"),
            ("BECE civic concepts marathon", "Rights, duties, democracy\nDrills"),
            ("BECE environment marathon", "Resources and hazards\nDrills"),
            ("Mock examination", "Full paper practice\nMark and review"),
            ("Project: my community study", "Survey and report\nPresent findings"),
            ("Weakness clinics", "Fix my weak topics\nTargeted drills"),
            ("Speed and accuracy", "Timed mini tests\nImprove my score"),
            ("Current affairs", "Nigeria and the world\nQuiz rounds"),
            ("Final mock", "Full dress exam\nFinal review"),
            ("BECE readiness", "Exam day tips\nSend off"),
        ],
    },
    "Civic Education": {
        1: [
            ("Revision of jss two work", "Rights and duties review\nQuick quiz"),
            ("The constitution", "Meaning and sources\nWhy constitutions matter"),
            ("Features of the Nigerian constitution", "Key sections\nCase talks"),
            ("Democracy and its pillars", "Rule of law, participation\nClass democracy"),
            ("Nationalism", "Our founding fathers\nNationalist profiles"),
            ("Responsible parenthood", "Duties of parents\nFamily values"),
            ("Civil society", "Groups that serve\nJoin a cause"),
            ("Public opinion", "Voice of the people\nClass poll"),
            ("Voting and elections", "Processes and PVC\nMock voting"),
            ("Revision and BECE practice", "Past questions\nMark and correct"),
        ],
        2: [
            ("Electoral bodies", "INEC and its work\nElection simulation"),
            ("Political parties", "Roles and manifestos\nParty posters"),
            ("Public service in democracy", "Accountability\nService standards"),
            ("Citizenship by registration", "Naturalisation\nRequirements"),
            ("Rights of the child", "Child rights act\nRights charters"),
            ("Human trafficking law", "Legal protection\nReport channels"),
            ("Law enforcement", "Police and us\nRespect and rights"),
            ("Drugs and the law", "NDLEA and penalties\nSay no"),
            ("Community service", "Serve my community\nClass project"),
            ("Revision and BECE practice", "Past questions\nMark and correct"),
        ],
        3: [
            ("BECE civic marathon", "Constitution to community\nPast questions"),
            ("BECE current affairs", "National and global\nQuiz rounds"),
            ("National values review", "Patriotism, integrity\nValues pledge"),
            ("Mock examination", "Full paper practice\nMark and review"),
            ("Project: active citizenship", "Plan and act\nReport my impact"),
            ("Weakness clinics", "Fix my weak topics\nTargeted drills"),
            ("Speed and accuracy", "Timed mini tests\nImprove my score"),
            ("Leadership send off", "Lead one last project\nReflections"),
            ("Final mock", "Full dress exam\nFinal review"),
            ("BECE readiness", "Exam day tips\nSend off"),
        ],
    },
    "Agricultural Science": {
        1: [
            ("Revision of jss two work", "Soil and crops review\nQuick quiz"),
            ("Agricultural extension", "Role of extension agents\nExtension visit notes"),
            ("Farm records", "Types of records\nKeep my farm book"),
            ("Crop propagation", "Sexual and asexual\nPropagate by cuttings"),
            ("Nursery practices", "Raise seedlings\nMake a nursery bed"),
            ("Cultural practices", "Tillage to weeding\nField practice"),
            ("Manures and fertilisers", "Organic and inorganic\nApply to beds"),
            ("Pests of crops", "Types and control\nPest scouting"),
            ("Diseases of crops", "Symptoms and control\nField diagnosis"),
            ("Revision and BECE practice", "Past questions\nMark and correct"),
        ],
        2: [
            ("Animal nutrition", "Feed types and rations\nMix a ration"),
            ("Animal health", "Common diseases\nPrevention routines"),
            ("Fish farming", "Pond culture\nCare routines"),
            ("Poultry production", "Broilers and layers\nHousing systems"),
            ("Ruminant production", "Goats and sheep\nManage a flock"),
            ("Agricultural machinery", "Tractors and implements\nSafety lessons"),
            ("Farm surveying", "Chain and compass\nMeasure my plot"),
            ("Farm planning", "Layout my farm\nDraw the plan"),
            ("Agro forestry", "Trees and crops\nPlant a tree"),
            ("Revision and BECE practice", "Past questions\nMark and correct"),
        ],
        3: [
            ("BECE agriculture marathon", "Crops, animals, soil\nPast questions"),
            ("BECE machinery marathon", "Tools and machines\nIdentification drills"),
            ("BECE economics marathon", "Records and marketing\nCalculation drills"),
            ("Mock examination", "Full paper practice\nMark and review"),
            ("Project: school farm handover", "Finish my beds\nRecord yields"),
            ("Weakness clinics", "Fix my weak topics\nTargeted drills"),
            ("Field trip", "Visit a real farm\nWrite my report"),
            ("Speed and accuracy", "Timed mini tests\nImprove my score"),
            ("Final mock", "Full dress exam\nFinal review"),
            ("BECE readiness", "Exam day tips\nSend off"),
        ],
    },
    "Home Economics": {
        1: [
            ("Revision of jss two work", "Food and clothing review\nQuick quiz"),
            ("Family living", "Family needs and resources\nBudget my home"),
            ("Consumer education", "Wise buying skills\nCompare products"),
            ("Food nutrients", "Classes and sources\nPlan balanced meals"),
            ("Meal planning and service", "Plan, cook, serve\nCook a dish"),
            ("Food preservation", "Methods at home\nPreserve a fruit"),
            ("Clothing construction", "Pattern drafting basics\nDraft my block"),
            ("Sewing machine mastery", "Oiling and stitching\nSew a pillowcase"),
            ("Home care", "Cleaning routines\nClean schedule"),
            ("Revision and BECE practice", "Past questions\nMark and correct"),
        ],
        2: [
            ("Child development", "Care of babies\nMake baby food"),
            ("Housing the family", "Types of houses\nVentilation study"),
            ("Interior decoration", "Colour and flower arrangement\nDecorate a corner"),
            ("Laundry work", "Stains and methods\nRemove a stain"),
            ("Textiles", "Fibre types\nTest my fabric"),
            ("Clothing repair", "Mend and alter\nMend my clothes"),
            ("Personal finance", "Pocket money plan\nMy savings book"),
            ("Food hygiene", "Safe cooking habits\nKitchen inspection"),
            ("Entertainment", "Host a small party\nPlan and host"),
            ("Revision and BECE practice", "Past questions\nMark and correct"),
        ],
        3: [
            ("BECE home economics marathon", "Food, clothing, family\nPast questions"),
            ("BECE practical marathon", "Cookery and stitching\nTimed tasks"),
            ("Mock examination", "Full paper practice\nMark and review"),
            ("Project: graduation outfit", "Sew my piece\nShow my work"),
            ("Practical cooking exam", "Cook and serve\nJudged fairly"),
            ("Weakness clinics", "Fix my weak topics\nTargeted drills"),
            ("Home management project", "Manage a day\nReport my plan"),
            ("Speed and accuracy", "Timed mini tests\nImprove my score"),
            ("Final mock", "Full dress exam\nFinal review"),
            ("BECE readiness", "Exam day tips\nSend off"),
        ],
    },
    "Cultural and Creative Arts": {
        1: [
            ("Revision of jss two work", "Art and music review\nQuick quiz"),
            ("Art: colour theory deep", "Colour schemes\nPaint my scheme"),
            ("Art: composition", "Balance and focus\nCompose my scene"),
            ("Music: theory basics", "Keys and scales\nNotation drills"),
            ("Music: Nigerian music history", "From juju to afrobeats\nListen and discuss"),
            ("Art: print and design", "Lino print basics\nPrint my design"),
            ("Drama: theatre history", "Nigerian theatre\nWatch and discuss"),
            ("Art: digital art", "Draw with apps\nMy digital piece"),
            ("Music: production basics", "Beats and mixing\nMake a track"),
            ("Revision and BECE practice", "Past questions\nMark and correct"),
        ],
        2: [
            ("Art: sculpture materials", "Wood, clay, metal\nChoose and make"),
            ("Art: textiles", "Weaving and dyeing\nWeave my piece"),
            ("Music: choral training", "Two part singing\nChoir practice"),
            ("Drama: script writing", "Write my scene\nRead my script"),
            ("Art: exhibition practice", "Mount and label\nCurate a corner"),
            ("Music: instruments family", "Strings, winds, percussion\nPlay one"),
            ("Dance: choreography", "Create my routine\nPerform my routine"),
            ("Art: portraiture", "Proportion mastery\nDraw a portrait"),
            ("Music: performance practice", "Stage craft\nRehearse my piece"),
            ("Revision and BECE practice", "Past questions\nMark and correct"),
        ],
        3: [
            ("BECE arts theory marathon", "Art and music theory\nPast questions"),
            ("BECE arts history marathon", "Artists and traditions\nDrills"),
            ("Mock examination", "Full paper practice\nMark and review"),
            ("Project: graduation arts", "Art for the day\nFinish my piece"),
            ("Performance project", "Prepare my act\nAudition and polish"),
            ("Weakness clinics", "Fix my weak topics\nTargeted drills"),
            ("Portfolio completion", "Collect my best\nMount my show"),
            ("Speed and accuracy", "Timed mini tests\nImprove my score"),
            ("Final mock", "Full dress exam\nFinal review"),
            ("BECE readiness", "Exam day tips\nSend off"),
        ],
    },
    "Physical and Health Education": {
        1: [
            ("Revision of jss two work", "Skills and health review\nQuick quiz"),
            ("Athletics: throws", "Shot and javelin basics\nSafe technique"),
            ("Athletics: jumps", "High jump technique\nPractice sessions"),
            ("Ball games: football", "Skills and tactics\nMatch practice"),
            ("Ball games: basketball", "Shooting drills\nGame play"),
            ("Ball games: volleyball", "Serving and spiking\nGame play"),
            ("Health: mental health", "Stress and coping\nRelaxation practice"),
            ("Health: drugs in sport", "Fair play\nSay no to doping"),
            ("First aid: sports injuries", "Sprain and cramp\nPractical care"),
            ("Revision and BECE practice", "Past questions\nMark and correct"),
        ],
        2: [
            ("Swimming", "Strokes and safety\nPool practice"),
            ("Gymnastics: advanced", "Handstands and vaults\nSpotters first"),
            ("Traditional sports", "Ayo, wrestling\nTournament play"),
            ("Fitness training", "Circuit design\nFollow my plan"),
            ("Health: nutrition", "Diet and performance\nPlan my meals"),
            ("Health: diseases", "Non communicable diseases\nPrevention charts"),
            ("Health: environment", "Sanitation and health\nClean up campaign"),
            ("Recreation", "Games for life\nOrganise a session"),
            ("Sports administration", "Organise a tournament\nFixtures and rules"),
            ("Revision and BECE practice", "Past questions\nMark and correct"),
        ],
        3: [
            ("BECE phe marathon", "Skills, health, games\nPast questions"),
            ("Mock examination", "Full paper practice\nMark and review"),
            ("Practical exam prep", "My best skills\nPractice and polish"),
            ("Inter house sports", "Compete for my house\nRecords and fun"),
            ("Weakness clinics", "Fix my weak topics\nTargeted drills"),
            ("Health project", "Health campaign\nRun my campaign"),
            ("Speed and accuracy", "Timed mini tests\nImprove my score"),
            ("Officiating basics", "Referee a game\nFair whistle practice"),
            ("Final mock", "Full dress exam\nFinal review"),
            ("BECE readiness", "Exam day tips\nSend off"),
        ],
    },
    "Information Technology": {
        1: [
            ("Revision of jss two work", "Hardware and software\nQuick quiz"),
            ("Word processing advanced", "Styles and references\nFormat my report"),
            ("Spreadsheets advanced", "Functions and charts\nAnalyse my data"),
            ("Database design", "Tables and queries\nBuild my database"),
            ("Presentation mastery", "Animate and deliver\nPresent my topic"),
            ("Internet and web", "Search and evaluate\nResearch skills"),
            ("HTML basics", "Tags and structure\nBuild my page"),
            ("CSS styling", "Colours and layout\nStyle my page"),
            ("Block coding advanced", "Functions and events\nBuild my game"),
            ("Revision and BECE practice", "Past questions\nMark and correct"),
        ],
        2: [
            ("Algorithm thinking", "Flowcharts and pseudocode\nWrite my algorithm"),
            ("Python first steps", "Print and variables\nRun my code"),
            ("Python conditions", "If and else\nSolve my problems"),
            ("Python loops", "For and while\nAutomate my tasks"),
            ("Digital graphics", "Edit and design\nDesign my poster"),
            ("Audio and video", "Edit my clip\nPublish my clip"),
            ("Cyber security", "Threats and protection\nSecure my accounts"),
            ("Digital ethics", "Copyright and fair use\nRespect creators"),
            ("ICT and society", "Digital divide\nBridge the gap ideas"),
            ("Revision and BECE practice", "Past questions\nMark and correct"),
        ],
        3: [
            ("BECE ict marathon", "Theory and practical\nPast questions"),
            ("Mock examination", "Full paper practice\nMark and review"),
            ("Project: my web page", "Build and publish\nDemo my page"),
            ("Practical exam prep", "Timed tasks\nPractice drills"),
            ("Weakness clinics", "Fix my weak topics\nTargeted drills"),
            ("Typing mastery", "Speed and accuracy\nBeat my record"),
            ("Coding mini project", "Plan and code\nShow my project"),
            ("Speed and accuracy", "Timed mini tests\nImprove my score"),
            ("Final mock", "Full dress exam\nFinal review"),
            ("BECE readiness", "Exam day tips\nSend off"),
        ],
    },
}
