#!/usr/bin/env python3
"""Nursery 1 scheme data, part B: Health Habits, Basic Science and Discovery, Creative Arts, Moral Instruction, Handwriting."""

NURSERY_1_B = {
    "Health Habits": {
        1: [
            ("Washing my hands", "When to wash hands\nSteps of hand washing with soap"),
            ("Bathing every day", "Bath in the morning and before bed\nUse soap and sponge"),
            ("Clean clothes", "Wear a clean uniform\nDirty clothes go in the basket"),
            ("Brushing my teeth", "Brush morning and night\nBrush up and down"),
            ("Eating good food", "Fruits and vegetables help us grow\nName healthy foods"),
            ("Drinking clean water", "Water keeps the body fresh\nDrink from my own cup"),
            ("Sleep and rest", "Sleep early to grow well\nRest after play"),
            ("Using the toilet well", "Flush after use\nWash hands after the toilet"),
            ("Covering coughs", "Cough into my elbow\nTurn away from friends"),
            ("Revision and hand wash practice", "Practise hand washing together\nSort healthy and unhealthy foods"),
        ],
        2: [
            ("Care of the nose and ears", "Do not push things into nose or ears\nUse a clean handkerchief"),
            ("Care of the hair", "Comb my hair every day\nKeep hair clean and short or tied"),
            ("Care of nails", "Cut nails short\nDirt under nails carries germs"),
            ("Germs are not for me", "Germs are tiny and make us sick\nWash germs away"),
            ("Safe play", "Play away from the road\nDo not throw sand or stones"),
            ("Food safety", "Wash fruits before eating\nDo not pick food from the floor"),
            ("Exercise time", "Run, jump and stretch every day\nExercise makes the body strong"),
            ("Going to the clinic", "Tell the teacher when I feel sick\nThe nurse helps us get well"),
            ("Medicine is not sweets", "Never take medicine alone\nOnly adults give medicine"),
            ("Revision and health march", "Health habits song\nPractise safe play rules"),
        ],
        3: [
            ("My growth chart", "Measure how tall I am\nFood and sleep help me grow"),
            ("Balanced plate", "Half the plate fruits and vegetables\nGo, grow and glow foods"),
            ("Care of the eyes", "Do not read in the dark\nRest the eyes after screen time"),
            ("Care of the teeth", "Avoid too many sweets\nVisit the dentist with mummy"),
            ("Road safety basics", "Stop, look and cross with an adult\nWalk on the inside of the road"),
            ("Sharp objects are dangerous", "Do not play with knives or blades\nTell an adult when I see one"),
            ("Fire and hot things", "Do not touch pots or fire\nShout for help when there is smoke"),
            ("Mosquito and malaria", "Sleep under the treated net\nClear stagnant water"),
            ("Clean environment", "Sweep and pick litter\nBushes and gutters breed sickness"),
            ("Revision and health quiz", "Health habits quiz game\nMake a healthy plate craft"),
        ],
    },
    "Basic Science and Discovery": {
        1: [
            ("Me and my body", "Point to head, tummy, hands and feet\nMy body can see, hear and touch"),
            ("My five senses", "Eyes see, ears hear, nose smells\nTongue tastes, skin feels"),
            ("Colours around us", "Name red, blue, yellow and green\nFind colours in class"),
            ("Water play", "Water flows and fills\nWet and dry sand"),
            ("Big and little animals", "Name a big animal and a small one\nAnimal sounds"),
            ("Pets", "Name the dog, cat and bird\nAnimals we keep at home"),
            ("Plants are alive", "A seed grows when we water it\nWater the class plant"),
            ("The sun and the sky", "The sun gives light in the day\nThe moon and stars come at night"),
            ("Hot and cold", "Touch warm water and cool water\nThe sun is hot, ice is cold"),
            ("Revision and nature walk", "Walk and name what we see\nCollect leaves and stones"),
        ],
        2: [
            ("Living and non living", "A dog grows, a stone does not\nSort picture cards"),
            ("Parts of a plant", "Root, stem, leaf and flower\nShow each part on a real plant"),
            ("Animals and their homes", "Dog in the kennel, bird in the nest\nMatch animal to home"),
            ("Animal babies", "Cow and calf, hen and chick\nMatch the mother to the baby"),
            ("Float and sink", "Drop objects in water\nGuess, float or sink"),
            ("Air is everywhere", "Blow bubbles and balloons\nFeel the wind on my face"),
            ("Day and night sky", "Sun in the day, moon at night\nDraw the night sky"),
            ("Rainy and sunny days", "What we wear when it rains\nUmbrellas and rain boots"),
            ("Sound around us", "Loud and soft sounds\nMake sound with bottles and drums"),
            ("Revision and discovery fair", "Show and tell my favourite discovery\nSort living and non living"),
        ],
        3: [
            ("Growing plants experiment", "Plant beans in cotton and water them\nWatch roots and shoots grow"),
            ("What plants need", "Water, air, sunlight and soil\nOne pot in the dark, one in the sun"),
            ("Insects small and busy", "Ants, bees and butterflies\nWatch ants march in a line"),
            ("Water in our life", "Uses of water at home and school\nDo not waste water"),
            ("Magnet magic", "Pick up pins with a magnet\nSort magnetic and non magnetic things"),
            ("Push and pull", "Push the door, pull the drawer\nPlay push and pull games"),
            ("Light and shadow", "Make hand shadows with the torch\nShadows follow the light"),
            ("Floating boat craft", "Build a boat that floats\nWhich load sinks my boat"),
            ("Weather chart", "Sunny, cloudy, rainy days\nMark the weather every morning"),
            ("Revision and young scientists day", "Show my plant or boat\nTalk about what I discovered"),
        ],
    },
    "Creative Arts": {
        1: [
            ("Free scribbling", "Hold the crayon and make marks\nBig strokes on big paper"),
            ("Colouring a ball", "Colour inside the circle\nChoose my favourite colour"),
            ("Tearing and pasting", "Tear coloured paper\nPaste inside a big shape"),
            ("Finger painting", "Paint with my fingers\nMake prints on paper"),
            ("Moulding with clay", "Squeeze and roll clay\nMake a little ball and snake"),
            ("Printing with shapes", "Dip blocks in paint\nStamp patterns on paper"),
            ("Colouring fruits", "Colour the orange and the banana\nSay each fruit colour"),
            ("Sponge painting", "Dab the sponge in paint\nFill a big outline"),
            ("Paper ball craft", "Crush paper into balls\nPaste to make a bunch"),
            ("Art exhibition", "Display all my works\nTell mummy about my art"),
        ],
        2: [
            ("Colour mixing 1", "Yellow and red make orange\nMix paints with a brush"),
            ("Colour mixing 2", "Blue and yellow make green\nPaint a green tree"),
            ("Drawing myself", "Draw my head, hands and legs\nAdd my eyes and smile"),
            ("Drawing my family", "Draw big people and small people\nName who is who"),
            ("Leaf printing", "Print with real leaves\nSee the lines on the leaf"),
            ("Clay fruits", "Mould an orange and a banana\nPaint them when dry"),
            ("Cutting with help", "Cut along a straight line with scissors\nPaste my cut strips"),
            ("String painting", "Drag paint with a string\nMake wavy designs"),
            ("Masks and faces", "Decorate a paper face\nAdd eyes, nose and mouth"),
            ("Art gallery walk", "Walk and see everyone's art\nClap for each artist"),
        ],
        3: [
            ("Drawing my school", "Draw the classroom and the flag\nColour neatly"),
            ("Weaving paper mats", "Fold and weave strips\nMake a little mat"),
            ("Cotton wool pictures", "Paste cotton for clouds and sheep\nAdd a sun with paint"),
            ("Bead threading", "Thread big beads on a lace\nMake a necklace or bracelet"),
            ("Clay pots", "Mould a small pot the local way\nSmooth the sides with water"),
            ("Painting the weather", "Paint a rainy day or a sunny day\nAdd umbrellas or clouds"),
            ("Origami boat and fan", "Fold a paper boat\nFold a paper fan"),
            ("Group mural", "Paint one big class picture\nEveryone paints a part"),
            ("Cultural art day", "Draw patterns from our culture\nLook at adire and ankara patterns"),
            ("Graduation art show", "Mount my best works\nPresent my favourite piece"),
        ],
    },
    "Moral Instruction": {
        1: [
            ("God made me special", "Every child is special\nSay one thing I can do"),
            ("Saying thank you", "When someone gives me something\nSay thank you with a smile"),
            ("Saying please", "Ask kindly for what I need\nPractise please in role play"),
            ("Truthful words", "Say what really happened\nThe truth is always best"),
            ("Gentle hands", "Touch friends gently\nHands are for helping"),
            ("Obedience", "Listen to mummy, daddy and teacher\nDo it the first time"),
            ("Cleanliness", "Keep my body and class clean\nClean habits are good habits"),
            ("Loving my friends", "Be kind to everyone\nInvite a new friend to play"),
            ("Forgiving", "Say I forgive you\nPlay again together"),
            ("Revision and story day", "Story of the good boy or girl\nSing our moral songs"),
        ],
        2: [
            ("Honesty", "Return the toy I borrowed\nDo not take what is not mine"),
            ("Respect for elders", "Greet elders politely\nSpeak politely"),
            ("Patience", "Wait for my turn quietly\nGood things come to those who wait"),
            ("Helpfulness", "Help a friend who fell\nCarry for someone smaller"),
            ("Self control", "Count to ten when I am angry\nUse words, not hands"),
            ("Gratitude", "Thank God and my parents\nSay thank you without being told"),
            ("Sharing joy", "Share my sweets and toys\nGiving makes everyone happy"),
            ("Keeping promises", "Do what I said I would do\nBe a child of my word"),
            ("Courage to say sorry", "Apologise even when it is hard\nSorry fixes friendship"),
            ("Revision and drama", "Act honest, patient and kind\nTalk about our best moment"),
        ],
        3: [
            ("Love your neighbour", "Treat friends the way I love to be treated\nKindness to all children"),
            ("Respect for God", "Pray before we eat\nBehave well in church or mosque"),
            ("Hard work", "Finish my little tasks\nWork before play"),
            ("Contentment", "Be happy with what I have\nDo not cry for everything"),
            ("Honesty pays", "The story of the honest child\nTruth brings trust"),
            ("Unity", "We are one class, one Nigeria\nPlay with every child"),
            ("Service", "Help without being asked\nLook around for little jobs"),
            ("Forgiveness", "Let go of small hurts\nMake peace before home time"),
            ("Being a good example", "Younger children copy me\nBehave well always"),
            ("Revision and character day", "Recite our moral rules\nAward the kindest friend"),
        ],
    },
    "Handwriting": {
        1: [
            ("Pre-writing strokes", "Sleeping lines, standing lines\nSlanting lines left to right"),
            ("Curves and circles", "Draw big and small circles\nTrace half circles"),
            ("Patterns", "Trace zigzag and wave patterns\nColour my pattern"),
            ("Writing 1 and 2", "Trace number 1 and 2\nWrite on my own"),
            ("Writing 3 and 4", "Trace number 3 and 4\nWrite neatly in the lines"),
            ("Writing 5", "Trace number 5\nCount five and write five"),
            ("Tracing Aa to Ee", "Trace the letters of the week\nSay each sound"),
            ("Tracing Ff to Jj", "Trace the letters of the week\nWrite on my own"),
            ("My name", "Trace my name\nWrite the first letter of my name"),
            ("Revision and handwriting race", "Write our best letters\nShow neat writing on the wall"),
        ],
        2: [
            ("Letters Aa to Hh", "Write capital and small letters\nMatch capital to small"),
            ("Letters Ii to Pp", "Write capital and small letters\nCopy three letter rows"),
            ("Letters Qq to Zz", "Write the last letters neatly\nSay the whole alphabet"),
            ("Numbers 1 to 10", "Write numbers 1 to 10 in order\nCount as we write"),
            ("Numbers 11 to 20", "Write teen numbers\nTrace the tens"),
            ("Two letter words", "Write at, in, on, up\nRead what we write"),
            ("Three letter words", "Write cat, dog, sun, cup\nSay the sounds as we write"),
            ("My name and my class", "Write my full name by copying\nWrite my class"),
            ("Neat pages", "Write on the line, sit well\nHold the pencil right"),
            ("Revision and writing show", "Best handwriting on the wall\nWrite the alphabet from A to Z"),
        ],
        3: [
            ("Words from Aa to Zz", "Write one word for many letters\nant, ball, cup, dog"),
            ("Simple sentences", "I can run. The sun is up.\nCopy with finger spaces"),
            ("Sentences about me", "I am a boy or girl. I am five.\nWrite about myself"),
            ("Numbers 1 to 50", "Write numbers in rows of ten\nFill missing numbers"),
            ("Days of the week", "Copy the seven days\nSay them in order"),
            ("Months of the year", "Copy the twelve months\nFind my birthday month"),
            ("My address", "Copy my house address with help\nKnow why address matters"),
            ("Sentence writing", "Write one sentence about my friend\nCapital letter and full stop"),
            ("Copy from the board", "Copy two lines without mistakes\nCheck my work"),
            ("Revision and handwriting certificate", "Write our best page\nEvery child gets a writing star"),
        ],
    },
}
