#!/usr/bin/env python3
"""Primary 3 scheme data: nine subjects, three terms, ten weeks each."""

PRIMARY_3 = {
    "English Studies": {
        1: [
            ("Revision of primary two work", "Phonics and sight words warm up\nSimple sentence reading"),
            ("Phonics: blends bl, cr, fl", "blue, crayon, flower\nBlend and read words"),
            ("Comprehension: my family", "Read the family passage\nAnswer oral questions"),
            ("Grammar: naming words", "Person, animal, place, thing\nCircle the nouns"),
            ("Grammar: action words", "Verbs in sentences\nAct the verbs"),
            ("Vocabulary: new words", "Meanings and sentence making\nMy word bank"),
            ("Composition: myself", "Write four sentences about me\nRead aloud"),
            ("Handwriting and dictation", "Copy a paragraph neatly\nFive word dictation"),
            ("Reading fluency", "Punctuation pause practice\nRead in pairs"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Phonics: digraphs sh and ch", "ship, shop, chat, chip\nWord sort"),
            ("Comprehension: the market", "Read the market passage\nAnswer questions"),
            ("Grammar: describing words", "Adjectives for size and colour\nDescribe objects"),
            ("Grammar: is, am, are", "Be verbs with subjects\nFill the gaps"),
            ("Vocabulary: opposites", "Big and small pairs\nMatch and use in sentences"),
            ("Composition: my best friend", "Describe my friend in four lines\nEdit and read"),
            ("Story time and retelling", "Read the class story\nRetell in my own words"),
            ("Handwriting and dictation", "Joined writing practice\nSentence dictation"),
            ("Punctuation", "Capital letters and full stops\nQuestion marks"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Phonics: long vowels", "cake, kite, home, tube\nMagic e words"),
            ("Comprehension: the farm", "Read the farm passage\nAnswer questions"),
            ("Grammar: prepositions", "in, on, under, between\nPlace the objects"),
            ("Grammar: tenses", "Today, yesterday, tomorrow\nChange the tense"),
            ("Vocabulary: word building", "Add s, ed and ing\nBuild new words"),
            ("Composition: a rainy day", "Four sentence story\nFirst, then, last"),
            ("Letter writing", "Write to a friend\nGreeting and closing"),
            ("Handwriting and dictation", "Paragraph copy\nFull dictation"),
            ("Spelling drill", "Look, cover, write, check\nClass spelling bee"),
            ("Revision and assessment", "Term work review\nEnd of year quiz"),
        ],
    },
    "Mathematics": {
        1: [
            ("Counting to 100", "Count and fill gaps\nNumber chart work"),
            ("Place value", "Tens and ones with sticks\nWrite the values"),
            ("Addition without carrying", "Two digit plus one digit\nSolve and check"),
            ("Addition with carrying", "Carry the ten\nVertical sums"),
            ("Subtraction without borrowing", "Take away ones and tens\nSolve and check"),
            ("Subtraction with borrowing", "Borrow a ten\nVertical sums"),
            ("Multiplication as repeated addition", "Groups and rows\n2 and 3 times tables"),
            ("Fractions: half and quarter", "Fold and shade\nHalf of objects"),
            ("Money", "Naira addition and change\nShopping problems"),
            ("Revision and assessment", "Mixed problems quiz\nMental maths relay"),
        ],
        2: [
            ("Numbers to 500", "Count, read and write\nCompare with more than, less than"),
            ("Place value to 500", "Hundreds, tens and ones\nExpand the numbers"),
            ("Addition of three numbers", "Add in columns\nWord problems"),
            ("Subtraction of three digit numbers", "Borrow across tens\nWord problems"),
            ("Multiplication tables", "2, 3, 4, 5 tables\nMissing factor game"),
            ("Division as sharing", "Share equally\nDivision from multiplication"),
            ("Length and weight", "Measure in metres and kilograms\nEstimate then measure"),
            ("Time", "O'clock and half past\nCalendar work"),
            ("Shapes and symmetry", "2D and 3D shapes\nSymmetry lines"),
            ("Revision and assessment", "Mixed problems quiz\nMental maths relay"),
        ],
        3: [
            ("Numbers to 1000", "Count, read and write\nOrder numbers"),
            ("Place value to 1000", "Expand three digit numbers\nNumber names"),
            ("Addition of money", "Add prices\nShopping lists"),
            ("Subtraction of money", "Change from a purchase\nWord problems"),
            ("Multiplication by 6 to 10", "Tables practice\nWord problems"),
            ("Division with remainders", "Share and find the left over\nReal life sharing"),
            ("Capacity and time", "Litres and minutes\nMeasure and compare"),
            ("Data handling", "Tally marks and pictograph\nRead the chart"),
            ("Everyday arithmetic", "Combine operations\nMulti step problems"),
            ("Revision and assessment", "End of year quiz\nProblem solving fair"),
        ],
    },
    "Basic Science and Technology": {
        1: [
            ("Living and non living things", "Features of living things\nSort and group"),
            ("Parts of the body", "External body parts\nFunctions of each part"),
            ("The senses", "Five senses and sense organs\nSense stations"),
            ("Plants around us", "Parts of a plant\nUses of plants"),
            ("Animals around us", "Farm and wild animals\nAnimal groups"),
            ("Water", "Uses and sources of water\nWater safety"),
            ("Air", "Air around us\nMoving air activities"),
            ("Soil", "Types of soil\nBest soil for planting"),
            ("Simple machines", "Levers around us\nMake work easy"),
            ("Revision and project", "Term review\nShow my project"),
        ],
        2: [
            ("Health and hygiene", "Personal cleanliness routine\nGerm prevention"),
            ("Food and nutrition", "Classes of food\nBalanced meal plate"),
            ("The environment", "Keeping the environment clean\nWaste and bins"),
            ("Weather", "Weather symbols\nOur weather chart"),
            ("Energy: sun, heat and light", "Sources of heat and light\nSun safety"),
            ("Sound energy", "How sound is made\nLoud and soft"),
            ("Movement and force", "Push and pull\nForces around us"),
            ("Materials", "Wood, metal, plastic, fabric\nSort materials"),
            ("Technology: tools", "Safe use of simple tools\nMake a craft"),
            ("Revision and project", "Term review\nShow my project"),
        ],
        3: [
            ("Plant growth", "Conditions for growth\nGrow a bean experiment"),
            ("Animal care", "Care for pets and farm animals\nFeeding and shelter"),
            ("The human skeleton", "Bones and posture\nJoint movement"),
            ("Teeth and digestion", "Types of teeth\nCare of teeth"),
            ("Electricity basics", "Safe use of electricity\nBattery and bulb circuit"),
            ("Magnetism", "Magnetic materials\nMagnet games"),
            ("Water cycle", "Evaporation and rain\nDraw the cycle"),
            ("Pollution", "Types of pollution\nKeep our air and water clean"),
            ("Simple technology projects", "Build a model\nPlan and make"),
            ("Revision and science fair", "Year review\nPresent my project"),
        ],
    },
    "National Values Education": {
        1: [
            ("Civic: my community", "Members of my community\nHow we live together"),
            ("Civic: rights of a child", "Food, shelter, education, play\nRights poster"),
            ("Social: family types", "Nuclear and extended family\nMy family tree"),
            ("Social: culture", "Nigerian foods and dresses\nCulture day"),
            ("Security: home safety", "Dangerous objects at home\nSafety rules"),
            ("Security: stranger danger", "Do not follow strangers\nShout and tell"),
            ("Civic: national symbols", "Flag and anthem\nRespect for symbols"),
            ("Social: helping others", "Community helpers\nBe a helper"),
            ("Security: safety on the road", "Crossing the road\nTraffic signs"),
            ("Revision and project", "Values quiz\nMy values chart"),
        ],
        2: [
            ("Civic: obedience", "Why we obey rules\nRules at home and school"),
            ("Civic: honesty", "Telling the truth\nHonest child stories"),
            ("Social: cooperation", "Working together\nGroup tasks"),
            ("Social: religion in our community", "Respect for worship places\nPeaceful worship"),
            ("Security: first aid", "Simple first aid steps\nCall for help"),
            ("Security: fire safety", "Fire prevention\nStop, drop and roll"),
            ("Civic: leadership", "Class monitor and prefects\nGood leaders serve"),
            ("Social: festivals", "Nigerian festivals\nOur festival fair"),
            ("Security: emergency numbers", "Who to call\nRole play emergencies"),
            ("Revision and project", "Values quiz\nMy values chart"),
        ],
        3: [
            ("Civic: patriotism", "Love for Nigeria\nThe national pledge"),
            ("Civic: national consciousness", "States and capital cities\nOur map work"),
            ("Social: division of labour", "Jobs in the community\nRespect all work"),
            ("Social: corruption is bad", "Say no to cheating\nHonesty pays"),
            ("Security: personal hygiene and health", "Healthy habits prevent sickness\nHealth checklist"),
            ("Security: neighbourhood safety", "Strangers and suspicious acts\nReport to adults"),
            ("Civic: democracy for kids", "Voting and choosing\nClass election"),
            ("Social: national assets", "School and public property\nCare for public things"),
            ("Security: internet safety", "Safe screen habits\nTell an adult"),
            ("Revision and project", "End of year values quiz\nValues portfolio"),
        ],
    },
    "Pre-Vocational Studies": {
        1: [
            ("Agriculture: why farming matters", "Food from the farm\nFarm tools naming"),
            ("Agriculture: plant a seed", "Plant maize in cups\nCare routine"),
            ("Home economics: my body", "Bathing and grooming routine\nClean habits"),
            ("Home economics: the kitchen", "Kitchen tools\nSafe kitchen habits"),
            ("Agriculture: farm animals", "Names and homes of farm animals\nAnimal sounds"),
            ("Home economics: food groups", "Simple food groups\nHealthy plate"),
            ("Agriculture: watering and weeding", "Tend our class garden\nGarden tools"),
            ("Home economics: washing", "Wash handkerchiefs\nDrying and folding"),
            ("Entrepreneurship: helping hands", "Little jobs for little pay ideas\nClass job chart"),
            ("Revision and exhibition", "Show my garden cup\nDisplay my work"),
        ],
        2: [
            ("Agriculture: soil and planting", "Prepare a seed bed\nSow seeds"),
            ("Agriculture: crops we eat", "Root, leaf and fruit crops\nCrop sorting"),
            ("Home economics: the home", "Rooms in the home\nHome care duties"),
            ("Home economics: sewing basics", "Threading a needle\nSimple stitches"),
            ("Agriculture: insects friends and foes", "Bees help, locusts destroy\nInsect hunt"),
            ("Home economics: table manners", "Lay the table\nEat politely"),
            ("Agriculture: harvest", "Harvest our crops\nStore the harvest"),
            ("Home economics: mending", "Sew on a button\nPatch practice"),
            ("Entrepreneurship: class shop", "Buy and sell play\nCounting money"),
            ("Revision and exhibition", "Show my stitches\nMarket day"),
        ],
        3: [
            ("Agriculture: fish and poultry", "Caring for chickens\nFish farming basics"),
            ("Agriculture: preservation", "Drying and storing crops\nWhy we preserve"),
            ("Home economics: clothing care", "Wash and iron basics\nFold the wardrobe"),
            ("Home economics: simple meals", "Prepare a fruit salad\nKitchen safety"),
            ("Agriculture: trees and money", "Tree crops like cocoa and palm\nCash crops list"),
            ("Home economics: the family budget", "Needs and wants\nSpend wisely"),
            ("Entrepreneurship: making crafts", "Beads and cards to sell\nPrice my craft"),
            ("Entrepreneurship: savings", "My savings plan\nPiggy bank check"),
            ("Agriculture: farm visit", "Walk the school farm\nRecord what I see"),
            ("Revision and exhibition", "Year review\nShow and sell"),
        ],
    },
    "Cultural and Creative Arts": {
        1: [
            ("Art: drawing with shapes", "House and car from shapes\nColour my drawing"),
            ("Art: patterns", "Stripes, dots, zigzag\nDecorate a shirt"),
            ("Music: rhythm clapping", "Clap simple beats\nEcho clapping"),
            ("Art: colour wheel", "Primary and secondary colours\nMix my colours"),
            ("Music: school songs", "Learn two school songs\nSing in parts"),
            ("Art: clay work", "Mould a pot\nSmooth and paint"),
            ("Drama: role play", "Act community helpers\nStage manners"),
            ("Art: collage", "Paper collage of Nigeria\nGreen and white"),
            ("Music: local instruments", "Drum, shekere, flute\nPlay the beat"),
            ("Revision and exhibition", "Show my works\nClass concert"),
        ],
        2: [
            ("Art: landscape drawing", "Sky, trees, river, house\nLayer the scene"),
            ("Art: tie and dye", "Band patterns on cloth\nDye and reveal"),
            ("Music: notation basics", "Beat and rhythm marks\nClap the notation"),
            ("Art: bead work", "Thread a bracelet\nColour patterns"),
            ("Music: call and response songs", "Leader and chorus\nTake turns"),
            ("Art: papier mache", "Layer and paste\nPaint my bowl"),
            ("Drama: folk story play", "Act the tortoise story\nProps and masks"),
            ("Art: mask making", "Festival masks\nDecorate mine"),
            ("Music: dance steps", "Local dance steps\nDance in groups"),
            ("Revision and exhibition", "Show my works\nClass concert"),
        ],
        3: [
            ("Art: portrait", "Draw a friend\nProportions of the face"),
            ("Art: weaving", "Weave a mat\nTwo colour patterns"),
            ("Music: solfa basics", "d r m f s\nSing the scale"),
            ("Art: print making", "Stamp printing\nRepeat patterns"),
            ("Music: choir practice", "Sing in two groups\nHarmony try out"),
            ("Art: sculpture", "Clay animal sculpture\nDisplay on stands"),
            ("Drama: short play", "Plan, act and stage\nCostumes"),
            ("Art: cultural designs", "Uli and adire patterns\nDesign my cloth"),
            ("Music: concert practice", "Choose our songs\nRehearse the show"),
            ("Revision and exhibition", "Year showcase\nArts festival"),
        ],
    },
    "Physical and Health Education": {
        1: [
            ("Movement skills", "Run, jump, hop, skip\nRelay practice"),
            ("Ball skills", "Throw, catch, bounce\nCircle games"),
            ("Fitness basics", "Warm up and stretch\nExercise safety"),
            ("Personal health", "Bathing, brushing, clean clothes\nHealth habits chart"),
            ("Food and health", "Healthy foods\nJunk food watch"),
            ("Safety at home", "Sharp objects and fire\nHome safety rules"),
            ("Games: tag and dodge", "Play fair\nFollow the rules"),
            ("Athletics: short races", "50 metre dash practice\nStarts and finishes"),
            ("First aid basics", "Small cuts and bruises\nTell an adult"),
            ("Revision and sports day", "Class mini sports\nCertificates"),
        ],
        2: [
            ("Athletics: baton relay", "Pass the baton\nTeam relay race"),
            ("Ball games: football", "Dribbling and passing\nMini match"),
            ("Gymnastics", "Rolling and balancing\nSafe landing"),
            ("Posture and body care", "Sit, stand, walk well\nBack care"),
            ("Disease prevention", "Clean habits stop sickness\nMalaria prevention"),
            ("Safety in school", "Playground rules\nNo pushing at stairs"),
            ("Swimming and water safety", "Pool rules\nNever swim alone"),
            ("Traditional games", "Local children games\nTeach and play"),
            ("First aid", "Simple bandaging\nThe first aid box"),
            ("Revision and sports day", "Class mini sports\nCertificates"),
        ],
        3: [
            ("Athletics: long jump", "Jump and land\nMeasure my jump"),
            ("Ball games: handball", "Passing and shooting\nMini match"),
            ("Fitness circuits", "Stations training\nTrack my progress"),
            ("Nutrition and exercise", "Food for energy\nMy exercise plan"),
            ("Community health", "Clean environment\nCommunal labour"),
            ("Safety on the road", "Road crossing drill\nZebra crossing"),
            ("Martial play", "Safe wrestling basics\nRespect the rules"),
            ("Rhythmic activities", "March and move to beats\nDisplay practice"),
            ("First aid and rescue", "Call for help\nBasic rescue shouts"),
            ("Revision and sports festival", "Inter house mini sports\nCertificates"),
        ],
    },
    "Christian Religious Studies": {
        1: [
            ("God creates the world", "The creation story\nCare for creation"),
            ("God made me", "I am special to God\nMy talents"),
            ("The fall of man", "Adam and Eve\nObeying God"),
            ("Noah obeys God", "The ark story\nTrust and obey"),
            ("Abraham's faith", "God calls Abraham\nListening to God"),
            ("Joseph forgives", "Joseph and his brothers\nForgiveness"),
            ("Moses leads", "God helps Moses\nGod is with us"),
            ("The ten commandments", "God's rules for living\nObedience"),
            ("Jesus is born", "The Christmas story\nGod's gift of love"),
            ("Revision and memory verses", "Recite our verses\nSongs of praise"),
        ],
        2: [
            ("Jesus loves children", "Let the children come\nI matter to Jesus"),
            ("Jesus heals", "The sick are made well\nCaring for the sick"),
            ("Jesus teaches kindness", "The good Samaritan\nBe a neighbour"),
            ("The lost sheep", "God looks for us\nNever give up on anyone"),
            ("The generous boy", "Five loaves and two fish\nSharing with others"),
            ("Jesus and prayer", "The Lord's prayer\nMy prayer habits"),
            ("Giving thanks", "The ten lepers\nSay thank you"),
            ("Honesty pleases God", "Do not steal or lie\nTruthful living"),
            ("The prodigal son", "Sorry and forgiveness\nGod welcomes back"),
            ("Revision and memory verses", "Recite our verses\nSongs of praise"),
        ],
        3: [
            ("The early church shares", "The believers together\nSharing in my class"),
            ("Peter and John help", "Healing in the name of Jesus\nHelping in His name"),
            ("Stephen stands firm", "Brave faith\nStand for right"),
            ("Philip tells the good news", "Sharing Jesus\nTell my friends"),
            ("Saul becomes Paul", "Change of heart\nGod can change anyone"),
            ("Paul's journeys", "Travelling to teach\nNever tire of good"),
            ("Love is patient", "1 Corinthians 13\nLove in action"),
            ("The fruit of the Spirit", "Nine good fruits\nGrow the fruit"),
            ("Heaven our home", "Jesus prepares a place\nLiving for God"),
            ("Revision and memory verses", "Year verses review\nPraise concert"),
        ],
    },
    "Islamic Religious Studies": {
        1: [
            ("Allah the Creator", "Allah creates everything\nCare for creation"),
            ("The five pillars", "An introduction\nShahadah and salah"),
            ("Wudu", "Cleanliness before prayer\nSteps of wudu"),
            ("Salah", "Praying five times\nPrayer manners"),
            ("Surah Al-Fatihah", "Recite and meaning\nThe opening chapter"),
            ("The Prophet Muhammad", "His kind life\nFollow his example"),
            ("Honesty in Islam", "Speak the truth\nTruth pleases Allah"),
            ("Kindness to parents", "Obey mother and father\nServing parents"),
            ("Zakat and sharing", "Helping the poor\nGive with joy"),
            ("Revision and recitation", "Recite our surahs\nSongs of praise"),
        ],
        2: [
            ("Surah Al-Ikhlas", "Recite and meaning\nAllah is one"),
            ("Surah Al-Falaq and An-Nas", "Recite and meaning\nSeeking protection"),
            ("Salah in congregation", "Praying together\nLines and manners"),
            ("Fasting in Ramadan", "Why we fast\nPatience and self control"),
            ("The Prophet's honesty", "Al-Amin the trustworthy\nBe trustworthy"),
            ("Cleanliness is faith", "Taharah\nClean habits"),
            ("Good manners", "Greeting with salam\nSalam practice"),
            ("Respect for elders", "Adab with parents and teachers\nPolite speech"),
            ("Brotherhood in Islam", "All Muslims are brothers\nPeace with all"),
            ("Revision and recitation", "Recite our surahs\nSongs of praise"),
        ],
        3: [
            ("Surah Al-Asr", "Recite and meaning\nTime and good deeds"),
            ("Surah Al-Kawthar", "Recite and meaning\nGratitude to Allah"),
            ("Salat al-Jama'ah practice", "Lead and follow\nImam manners"),
            ("Hajj", "The fifth pillar\nUnity of pilgrims"),
            ("Stories of the prophets", "Adam, Nuh, Ibrahim\nLessons for me"),
            ("The Prophet's family", "Khadijah and Fatimah\nFamily virtues"),
            ("Truthfulness", "Hadith on truth\nHonest choices"),
            ("Charity", "Sadaqah habits\nThe giving hand"),
            ("Peace and forgiveness", "Pardon others\nMake peace"),
            ("Revision and recitation", "Year surahs review\nPraise concert"),
        ],
    },
}
