#!/usr/bin/env python3
"""Primary 2 scheme data: nine subjects, three terms, ten weeks each."""

PRIMARY_2 = {
    "English Studies": {
        1: [
            ("Revision of primary one work", "Sounds and letters warm up\nSimple word reading"),
            ("Three letter words: a words", "cat, map, bag, hat\nBuild and read words"),
            ("Three letter words: e and i words", "hen, pen, pig, lid\nBuild and read words"),
            ("Three letter words: o and u words", "dog, box, cup, sun\nBuild and read words"),
            ("Simple sentences", "The cat sat on the mat.\nRead aloud in groups"),
            ("Comprehension: my class", "Read the class passage\nAnswer oral questions"),
            ("Grammar: naming words", "Person, animal, place, thing\nCircle the nouns"),
            ("Grammar: action words", "Run, jump, read, write\nAct the verbs"),
            ("Writing: words and simple sentences", "Copy short sentences neatly\nDictation of three letter words"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Four letter words", "hand, road, milk, fish\nBuild and read words"),
            ("Word families: an and ap words", "fan, man, pan, cap, map\nSort the words"),
            ("Word families: ig and op words", "big, dig, pig, top, mop\nSort the words"),
            ("Comprehension: the market", "Read the market passage\nAnswer questions"),
            ("Grammar: one and many", "One book, two books\nChange the words"),
            ("Grammar: is, am, are", "I am, you are, he is\nFill the gaps"),
            ("Vocabulary: opposites", "Big and small, tall and short\nMatch and use"),
            ("Composition: my school", "Write three sentences\nRead to the class"),
            ("Handwriting and dictation", "Copy a short paragraph\nWord dictation"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Long vowel words", "cake, kite, rope, tube\nMagic e practice"),
            ("Two letter blends", "bl, cr, st, fl words\nBlend and read"),
            ("Comprehension: the farm", "Read the farm passage\nAnswer questions"),
            ("Grammar: describing words", "A red car, a tall boy\nDescribe objects"),
            ("Grammar: has and have", "He has, we have\nFill the gaps"),
            ("Vocabulary: word building", "Add s and ing\nBuild new words"),
            ("Composition: my friend", "Three sentence description\nRead aloud"),
            ("Letter writing: greeting a friend", "Greeting and closing\nSimple friendly letter"),
            ("Spelling and dictation", "Look, cover, write, check\nClass spelling bee"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Mathematics": {
        1: [
            ("Revision of numbers 1 to 50", "Count and order numbers\nFill the gaps"),
            ("Numbers 51 to 60", "Count and write\nTens and ones"),
            ("Numbers 61 to 70", "Count and write\nTens and ones"),
            ("Numbers 71 to 80", "Count and write\nFill the gaps"),
            ("Numbers 81 to 90", "Count and write\nTens and ones"),
            ("Numbers 91 to 100", "Count to 100\nHundred chart work"),
            ("Addition to 20 with carrying", "Carry the ten\nVertical sums"),
            ("Subtraction from 20", "Take away with borrowing talk\nVertical sums"),
            ("Shapes: rectangle, square, circle", "Name and draw shapes\nCount sides"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Addition of two digit numbers", "Add tens and ones\nVertical sums"),
            ("Addition of three numbers", "Add step by step\nWord problems"),
            ("Subtraction of two digit numbers", "Take away tens and ones\nVertical sums"),
            ("Open sentences", "Box sums: 5 + [] = 8\nFind the missing number"),
            ("Multiplication as repeated addition", "Two taken five times\nMake equal groups"),
            ("Multiplication tables 2 and 3", "Recite the tables\nSimple products"),
            ("Division as sharing", "Share between friends\nEqual groups"),
            ("Fractions: half and quarter", "Fold and colour\nHalf of shapes"),
            ("Money: shopping to 100 naira", "Coins and notes\nSimple change"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Numbers to 200", "Count, read and write\nPlace value practice"),
            ("Numbers to 500", "Count, read and write\nOrder the numbers"),
            ("Addition to 100 without carrying", "Add tens and ones\nQuick sums"),
            ("Addition to 100 with carrying", "Carry the ten\nWord problems"),
            ("Subtraction from 100", "Take away tens and ones\nCheck by adding"),
            ("Length: metres and centimetres", "Measure with a ruler\nEstimate then measure"),
            ("Capacity: litres", "Fill and compare\nMeasure with litres"),
            ("Weight: kilograms", "Weigh with a scale\nHeavier and lighter"),
            ("Time and the calendar", "Days of the week\nMonths of the year"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Basic Science and Technology": {
        1: [
            ("Revision of senses", "Five senses game\nSort by sense"),
            ("The human body: bones", "Bones hold the body\nSimple body map"),
            ("Muscles and movement", "Muscles help us move\nBend and stretch"),
            ("Food groups", "Energy and body building foods\nSort the foods"),
            ("Why we eat", "Energy to play and grow\nGood eating habits"),
            ("Common plants", "Trees, grasses, flowers\nLeaf walk"),
            ("Parts of a plant", "Root, stem, leaf, flower\nLabel the plant"),
            ("Common animals", "Farm and home animals\nGroup the animals"),
            ("Animal body parts", "Wings, legs, tails\nMatch parts to animals"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        2: [
            ("Living and non living things", "Things that grow\nSort and explain"),
            ("Features of living things", "They feed and grow\nMovement and breathing"),
            ("The habitat of animals", "Where animals live\nWater and land homes"),
            ("Plant habitats", "Plants by the river\nPlants in the bush"),
            ("The sun and its energy", "Light and heat from the sun\nDry things in the sun"),
            ("Forms of energy: light", "Light helps us see\nSources of light"),
            ("Forms of energy: heat", "Hot and cold objects\nHandle with care"),
            ("Simple machines", "Lever: seesaw and spoon\nMake work easy"),
            ("Moving things: push and pull", "Push the door, pull the rope\nEveryday examples"),
            ("Revision and assessment", "Term work review\nClass quiz"),
        ],
        3: [
            ("Water in our environment", "Sources of water\nClean and dirty water"),
            ("Uses of water", "Drinking and washing\nSave water habits"),
            ("Air in our environment", "Air everywhere\nMoving air does work"),
            ("The weather instruments", "Rain gauge and wind vane\nObserve the weather"),
            ("The water cycle", "Rain and rivers\nSimple cycle drawing"),
            ("Soil types", "Sand, loam, clay\nFeel and compare"),
            ("Things made from soil", "Pots and bricks\nMould and dry"),
            ("Reproduction in plants", "Seeds grow to plants\nBean sprouting"),
            ("Reproduction in animals", "Animals have babies\nMatch parent to young"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "National Values Education": {
        1: [
            ("The school community", "Pupils, teachers, head teacher\nRoles in school"),
            ("Rules in the community", "School rules and home rules\nWhy rules help"),
            ("Honesty always", "The honest pupil story\nTelling the truth"),
            ("Cooperation", "Working together\nGroup cleaning game"),
            ("Self reliance", "Do it myself\nSimple self work"),
            ("Care of my books", "Cover and keep books neat\nBook care rules"),
            ("Respect for the flag and anthem", "Stand at attention\nRecite the pledge"),
            ("National colours", "Green white green\nFlag drawing"),
            ("Peoples of my area", "My tribe and others\nLive in peace"),
            ("Revision and assessment", "Term work review\nOral quiz"),
        ],
        2: [
            ("The family as a community", "Members of the family\nDuties of members"),
            ("Rights in the family", "Food, clothes, school\nSay my rights"),
            ("Duties in the family", "Run errands, tidy up\nDo my duty"),
            ("Discipline", "Do the right thing\nSelf control stories"),
            ("Patience", "Wait for my turn\nPatience stories"),
            ("Contentment", "Happy with what I have\nNo stealing talk"),
            ("Community helpers", "Nurse, police, teacher\nThank the helpers"),
            ("Traffic rules", "Stop and look\nCross safely"),
            ("Peaceful living", "No fighting words\nSettle quarrels well"),
            ("Revision and assessment", "Term work review\nOral quiz"),
        ],
        3: [
            ("Our country Nigeria", "States and peoples\nOne Nigeria talk"),
            ("National heroes", "Nnamdi Azikiwe and others\nHero stories"),
            ("Respect for national things", "The flag, anthem, pledge\nStand with respect"),
            ("Money and work", "Money comes from work\nNo laziness"),
            ("Saving for tomorrow", "Piggy bank habits\nWhy we save"),
            ("Choosing friends", "Good and bad friends\nChoose well"),
            ("Good touch, bad touch", "My body is mine\nTell an adult"),
            ("Safety at home", "Gas, fire, chemicals\nSafe habits"),
            ("Helping the community", "Community clean up\nMy contribution"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Cultural and Creative Arts": {
        1: [
            ("Revision of singing", "Warm up songs\nSing in tune"),
            ("Drawing: things in the home", "Draw a chair and cup\nColour the drawing"),
            ("Designing patterns", "Repeat patterns\nMake a border design"),
            ("Rhythm: clapping patterns", "Echo clapping\nKeep the beat"),
            ("Traditional songs of my area", "Learn local songs\nSing in groups"),
            ("Craft: papier mache basics", "Tear, soak, paste\nMould simple bowls"),
            ("Clay work: animals", "Mould a goat or bird\nDisplay the works"),
            ("Drama: classroom scenes", "Act teacher and pupil\nSimple class play"),
            ("Movement to music", "March and gallop\nExpress the music"),
            ("Revision and assessment", "Term work review\nDisplay my work"),
        ],
        2: [
            ("Nigerian musical instruments", "Drum, flute, shekere\nName and sort"),
            ("Instrument families", "Shakers and drums\nMake simple sounds"),
            ("Drawing: festivals", "Draw a festival scene\nColour with meaning"),
            ("Weaving with paper and raffia", "Over and under\nMake small mats"),
            ("Cultural dances", "Bata and atilogwu talks\nLearn simple steps"),
            ("Mask and masquerade talk", "Masks in festivals\nMake paper masks"),
            ("Bead work", "String and colour\nMake simple beads"),
            ("Drama: folk stories", "Act the hare story\nSimple costumes"),
            ("Making greeting cards", "Card for a friend\nNeat lettering"),
            ("Revision and assessment", "Term work review\nDisplay my work"),
        ],
        3: [
            ("Songs for national events", "Independence songs\nSing with pride"),
            ("Music notation: simple notes", "Do re mi\nSing the scale"),
            ("Drawing: my community", "Market and church or mosque\nColour the scene"),
            ("Pottery: coiling method", "Roll and coil clay\nMake a small bowl"),
            ("Tie and dye basics", "Tie and dip cloth\nSimple patterns"),
            ("Dance drama", "Dance with a story\nGroup performance"),
            ("Collage making", "Cut and paste pictures\nTell a story in collage"),
            ("Poster design", "Keep the school clean poster\nLetters and pictures"),
            ("Class exhibition", "Arrange my works\nExplain my art"),
            ("Revision and assessment", "Year work review\nEnd of year display"),
        ],
    },
    "Pre-Vocational Studies": {
        1: [
            ("Home making: tidying my room", "Fold and arrange\nDaily tidy habits"),
            ("Washing simple items", "Handkerchief and cups\nWash and dry"),
            ("The tailor's work", "Sewing tools\nWatch simple stitching"),
            ("The carpenter's work", "Saw, hammer, nails\nName and uses"),
            ("Planting flower seeds", "Prepare the pot\nPlant and water"),
            ("Caring for flowers", "Water and weed\nWatch them grow"),
            ("Rearing fowls", "Housing and feeding\nDaily care"),
            ("Food preparation: fruits", "Wash and peel\nServe fruit plates"),
            ("Stitching basics", "Thread a needle\nRun simple stitches"),
            ("Revision and assessment", "Term work review\nPractical display"),
        ],
        2: [
            ("Kitchen safety", "Fire and hot water\nSafe kitchen habits"),
            ("Simple meals: boiling", "Boil yam and eggs\nWatch and help"),
            ("Table setting", "Plate, cup, spoon\nSet the table well"),
            ("Sewing: buttons", "Sew a button\nFix loose buttons"),
            ("Gardening: transplanting", "Lift the seedling\nPlant in the bed"),
            ("Pests in the garden", "Insects eat leaves\nSimple control"),
            ("Harvesting vegetables", "Pick and pack\nSell or use at home"),
            ("Animal care: rabbits", "Housing and feeding\nHandle with care"),
            ("Simple repairs", "Tighten loose screws\nGlue broken items"),
            ("Revision and assessment", "Term work review\nPractical display"),
        ],
        3: [
            ("Food preservation: drying", "Dry pepper and fish\nStore dry foods"),
            ("Food preservation: refrigeration", "Cold keeps food\nFridge safety"),
            ("Baking basics", "Cakes and meat pies\nWatch the mixing"),
            ("Knitting and crocheting basics", "Hold the wool\nSimple chains"),
            ("Composting", "Plant waste to manure\nMake a compost heap"),
            ("Fish pond basics", "Small pond care\nFeed the fish"),
            ("Selling produce", "Price and sell\nCount the money"),
            ("First aid box", "Items in the box\nSimple uses"),
            ("Career talks", "Farmer, tailor, cook\nTalk about careers"),
            ("Revision and assessment", "Year work review\nEnd of year practical"),
        ],
    },
    "Physical and Health Education": {
        1: [
            ("Revision of movement skills", "Run, jump, throw drills\nWarm up rules"),
            ("Athletics: starts and finishes", "Standing start\nRun through the line"),
            ("Middle distance running", "Pace the race\nBreathe well"),
            ("Ball games: football basics", "Dribble and pass\nSimple match rules"),
            ("Ball games: volleyball basics", "Serve and catch\nSimple rally"),
            ("Table tennis basics", "Hold the bat\nSimple serves"),
            ("Posture and body carriage", "Stand and walk tall\nCorrect posture"),
            ("Personal health: bathing", "Bath daily habits\nClean clothes"),
            ("Communicable diseases basics", "Cover the mouth\nWash hands often"),
            ("Revision and assessment", "Term work review\nSkills display"),
        ],
        2: [
            ("Athletics: high jump basics", "Approach and take off\nScissors jump"),
            ("Athletics: relay races", "Pass the baton well\nTeam practice"),
            ("Football: shooting", "Aim and shoot\nGoal keeping basics"),
            ("Volleyball: passing", "Under arm pass\nTwo hand pass"),
            ("Handball basics", "Dribble and throw\nSimple rules"),
            ("Safety in sports", "Warm up first\nPlay without pushing"),
            ("Food and exercise", "Eat then play\nEnergy for games"),
            ("Care of the skin", "Clean skin habits\nAvoid skin infections"),
            ("Rest and relaxation", "Sleep well hours\nRest after school"),
            ("Revision and assessment", "Term work review\nSkills display"),
        ],
        3: [
            ("Gymnastics: floor moves", "Forward roll with help\nBalance poses"),
            ("Gymnastics: balance beam basics", "Walk the low beam\nArms out balance"),
            ("Athletics: long jump", "Run, jump, land\nMeasure the jump"),
            ("Ball games: basketball basics", "Dribble the ball\nSimple shoot"),
            ("Traditional games", "Ten ten and suwe\nPlay by the rules"),
            ("Health: malaria prevention", "Sleep under nets\nClear stagnant water"),
            ("First aid: burns", "Cool with water\nTell an adult fast"),
            ("Environmental health", "Clean compound rules\nNo littering"),
            ("Physical fitness tests", "Simple fitness drills\nRecord my scores"),
            ("Revision and assessment", "Year work review\nEnd of year display"),
        ],
    },
    "Christian Religious Studies": {
        1: [
            ("The Bible: God's word", "Old and new testament\nCare for my Bible"),
            ("Creation: days one to three", "Light, sky, land\nThank God for creation"),
            ("Creation: days four to six", "Sun, moon, animals, man\nGod saw it was good"),
            ("God made man in His image", "God made me special\nCare for my body"),
            ("The first family", "Adam and Eve\nMy family matters"),
            ("Obedience to God", "Noah obeyed God\nBlessing of obedience"),
            ("Talking to God always", "Pray at all times\nSimple prayer habits"),
            ("Praising God", "Praise songs and dance\nPraise like David"),
            ("God is everywhere", "God sees me always\nLive well always"),
            ("Revision and assessment", "Term work review\nStories and songs"),
        ],
        2: [
            ("Abraham trusted God", "The call of Abraham\nTrust and obey"),
            ("God keeps His promises", "Isaac the promised child\nGod keeps promises"),
            ("Jacob and his family", "Jacob's twelve sons\nGod's big family"),
            ("Joseph the dreamer", "Joseph's coat\nDreams from God"),
            ("Joseph forgave his brothers", "Forgiveness in Egypt\nI can forgive"),
            ("Moses: God calls the humble", "The burning bush\nGod can use me"),
            ("God cares for His people", "Manna in the desert\nGod provides daily"),
            ("The ten commandments: love God", "First commandments\nLove God only"),
            ("The ten commandments: love others", "Honour and respect\nLove my neighbour"),
            ("Revision and assessment", "Term work review\nStories and songs"),
        ],
        3: [
            ("The birth of Jesus", "The Bethlehem story\nJesus the Saviour"),
            ("Jesus grew in wisdom", "The boy Jesus in church\nGrow like Jesus"),
            ("Jesus calls his friends", "The twelve disciples\nJesus calls me too"),
            ("Jesus teaches love", "Love your neighbour\nThe good neighbour story"),
            ("Jesus prays", "Jesus prayed often\nMy prayer life"),
            ("Jesus the helper", "Healing and helping\nI can help others"),
            ("The last supper", "Jesus with his friends\nRemember Jesus"),
            ("Jesus rises again", "The empty tomb\nThe joy of Easter"),
            ("The church is born", "The friends of Jesus gather\nLove the church"),
            ("Revision and assessment", "Year work review\nEnd of year quiz"),
        ],
    },
    "Islamic Religious Studies": {
        1: [
            ("Revision of Surah Al-Fatihah", "Recite together\nMeaning in short"),
            ("Surah Al-Fil", "The elephant story\nAllah protects His house"),
            ("Surah Al-Quraysh", "Trade journeys\nAllah provides"),
            ("The Prophet's birth", "Makkah and the Prophet\nLove the Prophet (SAW)"),
            ("The Prophet's honesty", "Al-Amin the truthful\nBe truthful always"),
            ("Salat: the positions", "Ruku and sujud\nPray with care"),
            ("Du'a for knowledge", "Lord increase my knowledge\nPray before study"),
            ("Allah the Creator", "Signs in nature\nSay Subhanallah"),
            ("Kindness to neighbours", "The Prophet's teaching\nBe a good neighbour"),
            ("Revision and assessment", "Term work review\nRecitations"),
        ],
        2: [
            ("Surah Al-Asr", "Recite and memorise\nTime and good deeds"),
            ("Surah Al-Lahab", "Recite together\nSimple lesson"),
            ("Surah Al-Kafirun", "Recite and memorise\nWorship Allah alone"),
            ("The Prophet's childhood", "Halima the nurse\nSimple life stories"),
            ("Kalimahs: meaning and recitation", "First kalimah\nRecite with meaning"),
            ("Salat: times and rak'ah", "Fajr to Isha\nCount the rak'ah"),
            ("Honesty in trade", "The Prophet as a trader\nNo cheating"),
            ("Zakat: caring with wealth", "Help the poor\nGive with joy"),
            ("Angels of Allah", "Angels record deeds\nDo good always"),
            ("Revision and assessment", "Term work review\nRecitations"),
        ],
        3: [
            ("Surah Al-Ma'un", "Recite together\nCare for the needy"),
            ("Surah Al-Kawthar", "Recite and memorise\nAllah's blessings"),
            ("Surah Al-Nasr", "Recite together\nVictory from Allah"),
            ("The Prophet's marriage", "Khadijah the believer\nFamily in Islam"),
            ("The Hijrah", "Journey to Madinah\nNew calendar talk"),
            ("Hajj basics", "The fifth pillar\nSimple Hajj stories"),
            ("Brotherhood in Islam", "The Ansar and Muhajirun\nLive in peace"),
            ("Du'a for parents", "Pray for mum and dad\nHonour parents"),
            ("Jannah for the good", "Paradise talk\nWork for Jannah"),
            ("Revision and assessment", "Year work review\nEnd of year recitations"),
        ],
    },
}
